### ISSUE TITLE
Can not import numpy or matplotlib.pyplot on pyodide-cdn2.iodide.io/v0.17.0a2/full/console.html

### ISSUE THREAD

**Issue by politinsa** [pyodide/pyodide#1418]
I just wanted to try pyodide out and went to https://pyodide-cdn2.iodide.io/v0.17.0a2/full/console.html (I clicked on a link from the readme).
I got `[Command] memory access out of bounds`.

Full log from https://pyodide-cdn2.iodide.io/v0.17.0a2/full/console.html:
```python
Welcome to the Pyodide terminal emulator 🐍
Python 3.8.2 (default, Mar 21 2021 18:08:58) on WebAssembly VM
Type "help", "copyright", "credits" or "license" for more information.
>>> a = 1
>>> a
1
>>> import numpy as np
[Command] memory access out of bounds
>>> np
>>> a
>>> a = 1
>>> a
>>> print(a)
>>> 
```
In console:
```
Python initialization complete
pyodide.js:123 Loading numpy
pyodide.js:171 Loading numpy from https://cdn.jsdelivr.net/pyodide/v0.17.0a2/full/numpy.js
pyodide.js:227 Loaded numpy
pyodide.js:404 Pyodide has suffered a fatal error, refresh the page. Please report this to the Pyodide maintainers.
globalThis.languagePluginLoader.Module.fatal_error @ pyodide.js:404
pyodide.js:405 The cause of the fatal error was:
 RuntimeError: memory access out of bounds
    at PyArray_IntpFromIndexSequence (<anonymous>:wasm-function[991]:0x737a1)
    at PyArray_IntpConverter (<anonymous>:wasm-function[990]:0x73702)
    at byn$fpcast-emu$PyArray_IntpConverter (<anonymous>:wasm-function[3415]:0x15bfeb)
    at https://cdn.jsdelivr.net/pyodide/v0.17.0a2/full/pyodide.asm.wasm:wasm-function[2980]:0x2d8970
    at https://cdn.jsdelivr.net/pyodide/v0.17.0a2/full/pyodide.asm.wasm:wasm-function[2987]:0x2d9a7a
    at _PyArg_ParseTupleAndKeywords_SizeT (https://cdn.jsdelivr.net/pyodide/v0.17.0a2/full/pyodide.asm.wasm:wasm-function[2989]:0x2da982)
    at obj.<computed> (https://cdn.jsdelivr.net/pyodide/v0.17.0a2/full/pyodide.asm.js:9:218346)
    at __static_1541 (<anonymous>:wasm-function[2335]:0xf8012)
    at byn$fpcast-emu$__static_1541 (<anonymous>:wasm-function[5842]:0x1688cc)
    at https://cdn.jsdelivr.net/pyodide/v0.17.0a2/full/pyodide.asm.wasm:wasm-function[771]:0x1cd8be
globalThis.languagePluginLoader.Module.fatal_error @ pyodide.js:405
00675876:0x737a1 Uncaught (in promise) RuntimeError: memory access out of bounds
    at PyArray_IntpFromIndexSequence (<anonymous>:wasm-function[991]:0x737a1)
    at PyArray_IntpConverter (<anonymous>:wasm-function[990]:0x73702)
    at byn$fpcast-emu$PyArray_IntpConverter (<anonymous>:wasm-function[3415]:0x15bfeb)
    at https://cdn.jsdelivr.net/pyodide/v0.17.0a2/full/pyodide.asm.wasm:wasm-function[2980]:0x2d8970
    at https://cdn.jsdelivr.net/pyodide/v0.17.0a2/full/pyodide.asm.wasm:wasm-function[2987]:0x2d9a7a
    at _PyArg_ParseTupleAndKeywords_SizeT (https://cdn.jsdelivr.net/pyodide/v0.17.0a2/full/pyodide.asm.wasm:wasm-function[2989]:0x2da982)
    at obj.<computed> (https://cdn.jsdelivr.net/pyodide/v0.17.0a2/full/pyodide.asm.js:9:218346)
    at __static_1541 (<anonymous>:wasm-function[2335]:0xf8012)
    at byn$fpcast-emu$__static_1541 (<anonymous>:wasm-function[5842]:0x1688cc)
    at https://cdn.jsdelivr.net/pyodide/v0.17.0a2/full/pyodide.asm.wasm:wasm-function[771]:0x1cd8be
```

Same thing happened when trying to import matplotlib.pyplot.

Browser: Google Chrome Version 89.0.4389.114 (Official Build) (64-bit), Windows 10

EDIT: it works only when **chrome dev tool are open**. It seems a similar issue than #1384

**Comment by rth** [comment]
Thanks for the report and the additional information! Yes, it's very likely an instance of #1384 so I'm going to close this issue in favor of that one.

Could you please comment on that issue if you can reproduce it consistently?
