### ISSUE TITLE
pyodide.js:112 Skipping unknown package 'numpy'

### ISSUE THREAD

**Issue by daoxian** [pyodide/pyodide#1437]
I'm running the sample code with the newly built pyodide from the Master branch.  It says that numpy cannot be found, but I'm sure that numpy.js & numpy.data exist. The code is:
```
<html>
  <head>
      <script>
      languagePluginUrl = 'https://<MY-SERVER>/wasm.master/';
      </script>
      <script src="https://<MY-SERVER>/wasm.master/pyodide.js"></script>
  </head>
  <body>
    Pyodide test page <br>
    Open your browser console to see Pyodide output
    <script type="text/javascript">
    	languagePluginUrl = 'https://<MY-SERVER>/wasm.master/';
      async function main(){
      	await window.languagePluginLoader;
      	//await loadPyodide({indexURL:languagePluginUrl});   // this line would throw an exception: pyodide is already loading...
      	await pyodide.loadPackage(['numpy', 'micropip']);
    		pyodide.runPython(`
	            import numpy as np
	            import sys, micropip, pyodide, js
	            print(sys.version)
	            a = np.arange(10).reshape(2,5)
	            print(a)
        	`);
      }
      main();
    </script>
  </body>
</html>
```

and the exception as the following:

```
pyodide.asm.js:9 Uncaught (in promise) PythonError: Traceback (most recent call last):
  File "/lib/python3.8/site-packages/pyodide/_base.py", line 344, in eval_code
    return CodeRunner(
  File "/lib/python3.8/site-packages/pyodide/_base.py", line 238, in run
    exec(mod, self.globals, self.locals)
  File "<exec>", line 2, in <module>
ModuleNotFoundError: No module named 'numpy'
```

**Comment by hoodmane** [comment]
Check your `packages.json` file, there should be an entry there under `import_name_to_package_name.numpy` which is what `loadPackage` is looking for.
