### ISSUE TITLE
`AttributeError: 'Task' object has no attribute 'then'` when running the examples in the documentation

### ISSUE THREAD

**Issue by ProgVal** [pyodide/pyodide#1466]
Hello,

I just tried the examples in the documentation: https://pyodide.org/en/0.17.0a2/usage/serving-pyodide-packages.html and https://pyodide.org/en/0.17.0a2/usage/serving-pyodide-packages.html , and I get this in the console:

```
pyodide.asm.js:9 Python initialization complete
pyodide.js:123 Loading micropip, distlib
pyodide.js:171 Loading micropip from https://cdn.jsdelivr.net/pyodide/v0.17.0a2/full/micropip.js
pyodide.js:171 Loading distlib from https://cdn.jsdelivr.net/pyodide/v0.17.0a2/full/distlib.js
pyodide.js:227 Loaded micropip,distlib
pyodide.asm.js:9 Python exception:
Traceback (most recent call last):
  File "/lib/python3.8/site-packages/pyodide/_base.py", line 344, in eval_code
    return CodeRunner(
  File "/lib/python3.8/site-packages/pyodide/_base.py", line 242, in run
    return eval(last_expr, self.globals, self.locals)
  File "<exec>", line 8, in <module>
AttributeError: 'Task' object has no attribute 'then'
```

Tested both with Firefox 78.9.0esr and Chromium 89.0.4389.114.

Here is the content of my local files (should be exactly as in the examples):

```
$ cat test.py 
import sys
import socketserver
from http.server import SimpleHTTPRequestHandler


class Handler(SimpleHTTPRequestHandler):

    def end_headers(self):
        # Enable Cross-Origin Resource Sharing (CORS)
        self.send_header('Access-Control-Allow-Origin', '*')
        super().end_headers()


if sys.version_info < (3, 7, 5):
    # Fix for WASM MIME type for older Python versions
    Handler.extensions_map['.wasm'] = 'application/wasm'


if __name__ == '__main__':
    port = 8000
    with socketserver.TCPServer(("", port), Handler) as httpd:
        print("Serving at: http://127.0.0.1:{}".format(port))
        httpd.serve_forever()


$ cat test.html
<html>
<head>
  <meta charset="utf-8">
</head>
<body>
  <script type="text/javascript">
      // set the Pyodide files URL (packages.json, pyodide.asm.data etc)
      window.languagePluginUrl = 'https://cdn.jsdelivr.net/pyodide/v0.17.0a2/full/';
  </script>
  <script type="text/javascript" src="https://cdn.jsdelivr.net/pyodide/v0.17.0a2/full/pyodide.js"></script>
  <script type="text/javascript">
    pythonCode = `
      def do_work(*args):
          import snowballstemmer
          stemmer = snowballstemmer.stemmer('english')
          print(stemmer.stemWords('go goes going gone'.split()))

      import micropip
      micropip.install('snowballstemmer').then(do_work)
    `

    languagePluginLoader.then(() => {
      return pyodide.loadPackage(['micropip'])
    }).then(() => {
      pyodide.runPython(pythonCode);
    })
  </script>
</body>
</html>
```

Am I missing something?

Thanks for your help!

**Comment by hoodmane** [comment]
Hi @ProgVal, thanks for your question. The docs are indeed incorrect in 0.17.0a2, but the [master version of the docs](https://pyodide.org/en/latest/usage/loading-packages.html) has correct info (at least I hope it does, I've been trying to get them up to date for the upcoming release).

In particular, think it should work if you use the following:
```py
await pyodide.runPythonAsync(`
  import micropip # runPythonAsync will load micropip automatically
  await micropip.install('snowballstemmer')
  import snowballstemmer
  stemmer = snowballstemmer.stemmer('english')
  print(stemmer.stemWords('go goes going gone'.split()))
`);
```

**Comment by ProgVal** [comment]
Thanks for the quick reply. I just tried this example: https://pyodide.org/en/latest/usage/loading-packages.html#example , which gives me this error: `Uncaught (in promise) ReferenceError: loadPyodide is not defined`, followed by `Python initialization complete` two seconds later.

**Comment by hoodmane** [comment]
Right, so for the examples on master you should not use
cdn.jsdelivr.net/pyodide/**v0.17.0a2**/full/
(which is unfortunately what it says in the docs)
instead use: cdn.jsdelivr.net/pyodide/**dev**/full/
If you detect inconsistencies between the behavior of the master version of pyodide at cdn.jsdelivr.net/pyodide/dev/full/ and the master docs, please let me know so we can fix it.

**Comment by ProgVal** [comment]
Thanks, it works! Feel free to close the issue
