### ISSUE TITLE
`TypeError: exceptions must derive from BaseException` when micropip can't access PyPI

### ISSUE THREAD

**Issue by progval** [pyodide/pyodide#1468]
Hi,

I used the example here: https://pyodide.org/en/latest/usage/loading-packages.html#example with `dev` instead of `v0.17.0a2`.

My browser has a content blocker (uMatrix) that blocked the request to pypi.org (and/or files.pythonhosted.org) by changing the CORS policy.
This causes this error:

```
 Uncaught (in promise) PythonError: Traceback (most recent call last):
  File "/lib/python3.8/asyncio/futures.py", line 178, in result
    raise self._exception
  File "/lib/python3.8/asyncio/tasks.py", line 282, in __step
    result = coro.throw(exc)
  File "/lib/python3.8/site-packages/pyodide/_base.py", line 419, in eval_code_async
    return await CodeRunner(
  File "/lib/python3.8/site-packages/pyodide/_base.py", line 272, in run_async
    await coro
  File "<exec>", line 3, in <module>
  File "/lib/python3.8/asyncio/futures.py", line 260, in __await__
    yield self  # This tells Task to wait for completion.
  File "/lib/python3.8/asyncio/tasks.py", line 349, in __wakeup
    future.result()
  File "/lib/python3.8/asyncio/futures.py", line 178, in result
    raise self._exception
  File "/lib/python3.8/asyncio/tasks.py", line 282, in __step
    result = coro.throw(exc)
  File "/lib/python3.8/site-packages/micropip.py", line 157, in install
    await gather(*requirement_promises)
  File "/lib/python3.8/asyncio/futures.py", line 260, in __await__
    yield self  # This tells Task to wait for completion.
  File "/lib/python3.8/asyncio/tasks.py", line 349, in __wakeup
    future.result()
  File "/lib/python3.8/asyncio/futures.py", line 178, in result
    raise self._exception
  File "/lib/python3.8/asyncio/tasks.py", line 282, in __step
    result = coro.throw(exc)
  File "/lib/python3.8/site-packages/micropip.py", line 209, in add_requirement
    metadata = await _get_pypi_json(req.name)
  File "/lib/python3.8/site-packages/micropip.py", line 70, in _get_pypi_json
    fd = await _get_url(url)
  File "/lib/python3.8/site-packages/micropip.py", line 30, in _get_url
    resp = await fetch(url)
  File "/lib/python3.8/asyncio/futures.py", line 260, in __await__
    yield self  # This tells Task to wait for completion.
  File "/lib/python3.8/asyncio/tasks.py", line 349, in __wakeup
    future.result()
  File "/lib/python3.8/asyncio/futures.py", line 178, in result
    raise self._exception
TypeError: exceptions must derive from BaseException
    PythonError https://cdn.jsdelivr.net/pyodide/dev/full/pyodide.asm.js:9
    new_error https://cdn.jsdelivr.net/pyodide/dev/full/pyodide.asm.js:9
    callPyObject https://cdn.jsdelivr.net/pyodide/dev/full/pyodide.asm.js:9
    wrapper https://cdn.jsdelivr.net/pyodide/dev/full/pyodide.asm.js:9
```

(of course I don't expect micropip to work if requests are blocked; but it should probably raise a better exception)

Thanks!

**Comment by hoodmane** [comment]
Thanks for the report!

**Comment by ryanking13** [comment]
I don't think this happens anymore
