### ISSUE TITLE
Issue in using micropip to install pakcage with extra_requires

### ISSUE THREAD

**Issue by oeway** [pyodide/pyodide#1481]
With the pyodide v0.17.0a2, I have some issues in using loading `werkzeug`. It's wired that it tries to load `pytest` which is not the default runtime dependency (see [setup.py](https://github.com/pallets/werkzeug/blob/master/setup.py)). 

`pytest` should be only activated when we do `pip install wekzeug[dev]`.

You can reproduce this with the console: https://pyodide-cdn2.iodide.io/v0.17.0a2/full/console.html
```python
import micropip
micropip.install('werkzeug')
```

In the console it complains `Skipping unknown package ['pytest']`.

**Comment by hoodmane** [comment]
Thanks for the report! I think this bug was fixed in #1457 or #1463. Indeed the problem doesn't occur in `dev/full/console.html`.

**Comment by oeway** [comment]
Great! I tried with dev console and indeed it works now. Thanks you @hoodmane !

**Comment by oeway** [comment]
Hi, I noticed that I cannot get the actual package to work if, see below:

With the dev console at https://pyodide-cdn2.iodide.io/dev/full/console.html

If I start to add `await` before `micropip.install` I got an error:
```python
>>> import micropip
>>> await micropip.install(["werkzeug", "imjoy-rpc"])
Traceback (most recent call last):
​  File "/lib/python3.8/site-packages/pyodide/console.py", line 233, i
n load_packages_and_run
    result = await eval_code_async(source, self.locals)
​  File "/lib/python3.8/site-packages/pyodide/_base.py", line 419, in 
eval_code_async
    return await CodeRunner(
​  File "/lib/python3.8/site-packages/pyodide/_base.py", line 278, in 
run_async
    res = await res
​  File "<exec>", line 1, in <module>
​  File "/lib/python3.8/asyncio/futures.py", line 260, in __await__
    yield self  # This tells Task to wait for completion.
​  File "/lib/python3.8/asyncio/tasks.py", line 349, in __wakeup
    future.result()
​  File "/lib/python3.8/asyncio/futures.py", line 178, in result
    raise self._exception
​  File "/lib/python3.8/asyncio/tasks.py", line 282, in __step
    result = coro.throw(exc)
​  File "/lib/python3.8/site-packages/micropip.py", line 151, in insta
ll
    await gather(*requirement_promises)
​  File "/lib/python3.8/asyncio/futures.py", line 260, in __await__
    yield self  # This tells Task to wait for completion.
​  File "/lib/python3.8/asyncio/tasks.py", line 349, in __wakeup
    future.result()
​  File "/lib/python3.8/asyncio/futures.py", line 178, in result
    raise self._exception
​  File "/lib/python3.8/asyncio/tasks.py", line 280, in __step
    result = coro.send(None)
​  File "/lib/python3.8/site-packages/micropip.py", line 222, in add_r
equirement
    await self.add_requirement(recurs_req, ctx, transaction)
​  File "/lib/python3.8/site-packages/micropip.py", line 202, in add_r
equirement
    if not req.marker.evaluate(ctx):
​  File "/lib/python3.8/site-packages/packaging/markers.py", line 328,
 in evaluate
    return _evaluate_markers(self._markers, current_environment)
​  File "/lib/python3.8/site-packages/packaging/markers.py", line 244,
 in _evaluate_markers
    lhs_value = _get_env(environment, lhs.value)
​  File "/lib/python3.8/site-packages/packaging/markers.py", line 224,
 in _get_env
    raise UndefinedEnvironmentName(
​packaging.markers.UndefinedEnvironmentName: 'extra' does not exist in
 evaluation environment.
```

**Comment by hoodmane** [comment]
I think this is a quick fix.

**Comment by hoodmane** [comment]
You will probably be happy to see that I added the imjoy-rpc dependencies as a test case.

**Comment by hoodmane** [comment]
You can try out the fixed version here:
https://2085-322074228-gh.circle-artifacts.com/0/root/repo/build/console.html
