### ISSUE TITLE
BLD error: can't create or remove files in install directory

### ISSUE THREAD

**Issue by rth** [pyodide/pyodide#1482]
We seem to be getting this error occasionally lately in CI,
```
error: can't create or remove files in install directory

The following error occurred while trying to add or remove files in the
installation directory:

    [Errno 17] File exists: '/root/repo/packages/.artifacts/lib/python'

The installation directory you specified (via --install-dir, --prefix, or
the distutils default setting) was:

    /root/repo/packages/.artifacts/lib/python/

Perhaps your account does not have write access to this directory?  If the
installation directory is a system-owned directory, you may need to sign in
as the administrator or "root" account.  If you do not have administrative
access to this machine, you may wish to choose a different installation
directory, preferably one that is listed in your PYTHONPATH environment
variable.

For information on other options, you may wish to consult the
documentation at:

  https://setuptools.readthedocs.io/en/latest/easy_install.html

Please make the appropriate changes for your system and try again.

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.8/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/root/repo/pyodide_build/__main__.py", line 50, in <module>
    main()
  File "/root/repo/pyodide_build/__main__.py", line 44, in main
    args.func(args)
  File "/root/repo/pyodide_build/buildpkg.py", line 352, in main
    build_package(path, args)
  File "/root/repo/pyodide_build/buildpkg.py", line 287, in build_package
    compile(path, srcpath, pkg, args)
  File "/root/repo/pyodide_build/buildpkg.py", line 147, in compile
    subprocess.run(
  File "/usr/local/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError
```

For instance https://app.circleci.com/pipelines/github/pyodide/pyodide/2680/workflows/27e98ae8-38d8-4052-9273-b4ef91367141/jobs/27813

~~Maybe something to do with https://github.com/pyodide/pyodide/pull/1429 but if it was the issue I don't see why it would only happen occasionally.~~ Nevermind

**Comment by rth** [comment]
Similarly, this hasn't happened for some time. Closing.
