### ISSUE TITLE
pandas load_largish_file segfault chrome 89

### ISSUE THREAD

**Issue by hoodmane** [pyodide/pyodide#1495]
Strangely, no fatal error is signaled by `callPyObject` even though the traceback reports that the error came from inside the try block:
```js
Module.callPyObject = function(ptrobj, ...jsargs) {
  let idargs = Module.hiwire.new_value(jsargs);
  let idresult;
  try {
    idresult = __pyproxy_apply(ptrobj, idargs); // function fails inside of __pyproxy_apply
  } catch (e) { // But the exception doesn't get caught for some reason ???
    Module.fatal_error(e);
  }
```
I have been unable to reproduce this error in browser. The data is random, so that could cause it to be intermittent:
```py
    # Note: we don't fix the random seed here, but the actual values
    # shouldn't matter
```
but it seems pretty consistent on CI. Here's the stack trace:
```
conftest.JavascriptException: RuntimeError: memory access out of bounds
    at __static_1 (<anonymous>:wasm-function[174]:0x17748)
    at byn$fpcast-emu$__static_1 (<anonymous>:wasm-function[506]:0x87748)
    at __static_2 (<anonymous>:wasm-function[175]:0x17eca)
    at __static_199 (<anonymous>:wasm-function[339]:0x538d5)
    at byn$fpcast-emu$__static_199 (<anonymous>:wasm-function[704]:0x881f7)
    at __static_254 (http://127.0.0.1:45597/pyodide.asm.wasm:wasm-function[901]:0x1d3efc)
    at byn$fpcast-emu$__static_254 (http://127.0.0.1:45597/pyodide.asm.wasm:wasm-function[21696]:0x7bc708)
    at _PyObject_GenericGetAttrWithDict (http://127.0.0.1:45597/pyodide.asm.wasm:wasm-function[1713]:0x218614)
    at PyObject_GenericGetAttr (http://127.0.0.1:45597/pyodide.asm.wasm:wasm-function[1712]:0x2183c9)
    at byn$fpcast-emu$PyObject_GenericGetAttr (http://127.0.0.1:45597/pyodide.asm.wasm:wasm-function[14359]:0x7a2290)
    at PyObject_GetAttr (http://127.0.0.1:45597/pyodide.asm.wasm:wasm-function[1701]:0x217362)
    at _PyEval_EvalFrameDefault (http://127.0.0.1:45597/pyodide.asm.wasm:wasm-function[2758]:0x2a8076)
                
    <... many many skipped frames ...>

    at PyObject_Call (http://127.0.0.1:45597/pyodide.asm.wasm:wasm-function[764]:0x1cb0b8)
    at _pyproxy_apply (http://127.0.0.1:45597/pyodide.asm.wasm:wasm-function[373]:0x1aa705)
    at Object.Module.callPyObject (http://127.0.0.1:45597/pyodide.asm.js:9:177440)
    at Module.PyProxyClass.apply (http://127.0.0.1:45597/pyodide.asm.js:9:178431)
    at Object.apply (http://127.0.0.1:45597/pyodide.asm.js:9:183826)
    at Object.Module.runPython (http://127.0.0.1:45597/pyodide.js:581:30)
    at run (eval at executeAsyncScript (:556:26), <anonymous>:6:22)
    at eval (eval at executeAsyncScript (:556:26), <anonymous>:19:40)
    at eval (eval at executeAsyncScript (:556:26), <anonymous>:37:15)
    at eval (eval at executeAsyncScript (:556:26), <anonymous>:39:4)
    at executeAsyncScript (<anonymous>:556:47)
    at <anonymous>:571:29
    at callFunction (<anonymous>:450:22)
    at <anonymous>:464:23
    at <anonymous>:465:3
```

**Comment by hoodmane** [comment]
Closed in favor of #1507 where @dmondev has an improved reproduction.
