### ISSUE TITLE
SSL Error when trying to use requests library to send a GET request

### ISSUE THREAD

**Issue by apugoneappu** [pyodide/pyodide#1585]
I am trying to send a GET request from my Python code within pyodide, but I am getting the following error:

```
Python exception:
Traceback (most recent call last):
  File "/lib/python3.8/site-packages/urllib3/connectionpool.py", line 688, in urlopen
    conn = self._get_conn(timeout=pool_timeout)
  File "/lib/python3.8/site-packages/urllib3/connectionpool.py", line 280, in _get_conn
    return conn or self._new_conn()
  File "/lib/python3.8/site-packages/urllib3/connectionpool.py", line 979, in _new_conn
    raise SSLError(
urllib3.exceptions.SSLError: Can't connect to HTTPS URL because the SSL module is not available.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/lib/python3.8/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/lib/python3.8/site-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='<MASKED_HOST_HERE>', port=443): Max retries exceeded with url: /someAPI (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available."))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/lib/python3.8/site-packages/pyodide/_base.py", line 344, in eval_code
    return CodeRunner(
  File "/lib/python3.8/site-packages/pyodide/_base.py", line 238, in run
    exec(mod, self.globals, self.locals)
  File "<exec>", line 7, in <module>
  File "<exec>", line 51, in send_otp
  File "/lib/python3.8/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/lib/python3.8/site-packages/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='<MASKED_HOST_HERE>', port=443): Max retries exceeded with url: /someAPI (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available."))
```

Any pointer on how to solve this would be hugely helpful!

**Comment by apugoneappu** [comment]
Hey @rth,
Thanks for the quick response!

I should have mentioned that I want to send POST requests as well. So `pyodide.open_url` won't work.
In the requests that I send, I have to change headers like `User-Agent` that `fetch` won't allow. 

But the last option should work! To confirm, is this the process that should be used to use that:  
1. Build wheel from the setup.py
2. Upload the wheel on pypi
3. Use [installing wheels from arbitrary urls](https://pyodide.org/en/stable/usage/loading-packages.html#installing-wheels-from-arbitrary-urls) to install

**Comment by rth** [comment]
> In the requests that I send, I have to change headers like User-Agent that fetch won't allow.

It should work in Firefox https://stackoverflow.com/a/42815264/1791279

> Upload the wheel on pypi [for the pyodide fork of requests]

It's better to leave @casatir do that who is the author of that code. You can upload the the wheel anywhere (e.g. Github pages) and load it from an arbitary URL indeed.

**Comment by apugoneappu** [comment]
Thanks @rth. You're right, the authors/maintainers should upload to PyPi. 
I have uploaded the wheel in a [Github repository](https://github.com/apugoneappu/requests-pyodide) with the link to the original repository. Is this an acceptable thing to do?

**Comment by rth** [comment]
Sure, that works. Thanks!

**Comment by apugoneappu** [comment]
@hoodmane Yes, I got the same error because of the `XMLHttpRequest ` :(
Unfortunately, I cannot route my requests through a proxy server since the final server has geo-location restrictions as well as a limit on the number of requests from a particular IP address (all users' accesses will be counted against the proxy server's IP address).
