### ISSUE TITLE
Importing ThreadPool fails with "No module named '_multiprocessing'"

### ISSUE THREAD

**Issue by karthiknadig** [pyodide/pyodide#1603]
```
>>> from multiprocessing.pool import ThreadPool
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/lib/python3.8/multiprocessing/pool.py", line 30, in <module>
    from .connection import wait
  File "/lib/python3.8/multiprocessing/connection.py", line 21, in <module>
    import _multiprocessing
ModuleNotFoundError: No module named '_multiprocessing'
```

**Comment by rth** [comment]
Thanks for the report! Well multiprocessing won't work in Pyodide because one cannot create processes (and threads for now). However the import shouldn't have failed. I'm not sure why the `_multiprocessing` module is not present. It should have been added [here](https://github.com/python/cpython/blob/4844abdd700120120fc76c29d911bcb547700baf/setup.py#L1656). Someone would need to investigate in more detail.

**Comment by karthiknadig** [comment]
@rth I ran into it when I tried to `import pygls` after installing it with `micropip`. To ensure it wasn't any weirdness with importing I tested that out in the console. It shows up if you try to import `black` as well:
![image](https://user-images.githubusercontent.com/3840081/120061221-0b360a00-c011-11eb-8e0b-4b5a1d56ba68.png)

**Comment by rth** [comment]
A workaround is to monkypatch the `_multiprocessing` module:
```py
>>> import sys
>>> sys.modules['_multiprocessing'] = object
>>> from multiprocessing.pool import ThreadPool
```

Of course if you actually try to use this ThreadPool you will get errors as expected. The error message is fairly self explanatory,
```py
>>> ThreadPool()
Traceback (most recent call last):
  File "/lib/python3.8/multiprocessing/synchronize.py", line 28, in <module>
    from _multiprocessing import SemLock, sem_unlink
ImportError: cannot import name 'SemLock' from 'object' (unknown location)
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  [...]
  File "/lib/python3.8/multiprocessing/context.py", line 67, in Lock
    from .synchronize import Lock
  File "/lib/python3.8/multiprocessing/synchronize.py", line 30, in <module>
    raise ImportError("This platform lacks a functioning sem_open" +
ImportError: This platform lacks a functioning sem_open implementation, therefore,
 the required synchronization primitives needed will not function, see issue 3770.
```

**Comment by dberardo-com** [comment]
what if pyodide is running on a backend environment like nodejs, can these packages work there ?

**Comment by ryanking13** [comment]
It might be possible, but I believe it would take a huge amount of effort by someone with a passion, and it would require a lot of patches to CPython.

**Comment by dberardo-com** [comment]
and i also believe that https communication is not available within pyodide ? 

i get an error similar to this one: https://github.com/microsoft/debugpy/issues/935

"Failed to establish a new connection: [Errno 50] Protocol not available"

i have loaded the package "ssl" in the pyodide environment but .... welll --- it seems to fail

**Comment by ryanking13** [comment]
> any workarounds to use requests.get() ????

You can use [pyodide-http](https://github.com/koenvo/pyodide-http), which patches `requests.get` or other famous HTTP APIs with Web APIs.
