### ISSUE TITLE
Cannot build MarkupSafe locally or in Docker

### ISSUE THREAD

**Issue by radu-matei** [pyodide/pyodide#1621]
I've been unsuccessfully trying to build MarkupSafe both locally and in a container, both unsuccessful - here are the logs from running in a container:
(I also tried most of the things in #884)

```
Error building MarkupSafe. Printing build logs.
running install
running bdist_egg
running egg_info
writing src/MarkupSafe.egg-info/PKG-INFO
writing dependency_links to src/MarkupSafe.egg-info/dependency_links.txt
writing top-level names to src/MarkupSafe.egg-info/top_level.txt
reading manifest file 'src/MarkupSafe.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
no previously-included directories found matching 'docs/_build'
warning: no previously-included files matching '*.py[co]' found anywhere in distribution
writing manifest file 'src/MarkupSafe.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build
creating build/lib.linux-x86_64-3.8
creating build/lib.linux-x86_64-3.8/markupsafe
copying src/markupsafe/_constants.py -> build/lib.linux-x86_64-3.8/markupsafe
copying src/markupsafe/_compat.py -> build/lib.linux-x86_64-3.8/markupsafe
copying src/markupsafe/__init__.py -> build/lib.linux-x86_64-3.8/markupsafe
copying src/markupsafe/_native.py -> build/lib.linux-x86_64-3.8/markupsafe
copying src/markupsafe/_speedups.c -> build/lib.linux-x86_64-3.8/markupsafe
running build_ext
building 'markupsafe._speedups' extension
creating build/temp.linux-x86_64-3.8
creating build/temp.linux-x86_64-3.8/src
creating build/temp.linux-x86_64-3.8/src/markupsafe
cc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -I/usr/local/include/python3.8 -c src/markupsafe/_speedups.c -o build/temp.linux-x86_64-3.8/src/markupsafe/_speedups.o
gcc -pthread -shared build/temp.linux-x86_64-3.8/src/markupsafe/_speedups.o -L/usr/local/lib -o build/lib.linux-x86_64-3.8/markupsafe/_speedups.cpython-38-x86_64-linux-gnu.so
creating build/bdist.linux-x86_64
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/markupsafe
copying build/lib.linux-x86_64-3.8/markupsafe/_speedups.cpython-38-x86_64-linux-gnu.so -> build/bdist.linux-x86_64/egg/markupsafe
copying build/lib.linux-x86_64-3.8/markupsafe/_speedups.c -> build/bdist.linux-x86_64/egg/markupsafe
copying build/lib.linux-x86_64-3.8/markupsafe/_constants.py -> build/bdist.linux-x86_64/egg/markupsafe
copying build/lib.linux-x86_64-3.8/markupsafe/_compat.py -> build/bdist.linux-x86_64/egg/markupsafe
copying build/lib.linux-x86_64-3.8/markupsafe/__init__.py -> build/bdist.linux-x86_64/egg/markupsafe
copying build/lib.linux-x86_64-3.8/markupsafe/_native.py -> build/bdist.linux-x86_64/egg/markupsafe
byte-compiling build/bdist.linux-x86_64/egg/markupsafe/_constants.py to _constants.cpython-38.pyc
byte-compiling build/bdist.linux-x86_64/egg/markupsafe/_compat.py to _compat.cpython-38.pyc
byte-compiling build/bdist.linux-x86_64/egg/markupsafe/__init__.py to __init__.cpython-38.pyc
byte-compiling build/bdist.linux-x86_64/egg/markupsafe/_native.py to _native.cpython-38.pyc
creating stub loader for markupsafe/_speedups.cpython-38-x86_64-linux-gnu.so
byte-compiling build/bdist.linux-x86_64/egg/markupsafe/_speedups.py to _speedups.cpython-38.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying src/MarkupSafe.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying src/MarkupSafe.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying src/MarkupSafe.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying src/MarkupSafe.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
writing build/bdist.linux-x86_64/egg/EGG-INFO/native_libs.txt
zip_safe flag not set; analyzing archive contents...
markupsafe.__pycache__._speedups.cpython-38: module references __file__
creating dist
creating 'dist/MarkupSafe-1.1.1-py3.8-linux-x86_64.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing MarkupSafe-1.1.1-py3.8-linux-x86_64.egg
removing '/src/packages/.artifacts/lib/python/MarkupSafe-1.1.1-py3.8-linux-x86_64.egg' (and everything under it)
creating /src/packages/.artifacts/lib/python/MarkupSafe-1.1.1-py3.8-linux-x86_64.egg
Extracting MarkupSafe-1.1.1-py3.8-linux-x86_64.egg to /src/packages/.artifacts/lib/python
MarkupSafe 1.1.1 is already the active version in easy-install.pth

Installed /src/packages/.artifacts/lib/python/MarkupSafe-1.1.1-py3.8-linux-x86_64.egg
Processing dependencies for MarkupSafe==1.1.1
Finished processing dependencies for MarkupSafe==1.1.1
cache:INFO: generating system asset: generated_struct_info.json... (this will be cached in "/src/emsdk/emsdk/upstream/emscripten/cache/generated_struct_info.json" for subsequent builds)
/src/emsdk/emsdk/upstream/bin/wasm-opt: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /src/emsdk/emsdk/upstream/bin/wasm-opt)
/src/emsdk/emsdk/upstream/bin/wasm-opt: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /src/emsdk/emsdk/upstream/bin/wasm-opt)
emcc: error: error running binaryen executable (/src/emsdk/emsdk/upstream/bin/wasm-opt). Please check your binaryen installation
FAIL: Compilation failed!: ['/src/emsdk/emsdk/upstream/emscripten/emcc', '-D_GNU_SOURCE', '-o', '/tmp/tmpgt8h23oz.js', '/tmp/tmpm9_3york.c', '-O0', '-Werror', '-Wno-format', '-nostdlib', '/src/emsdk/emsdk/upstream/emscripten/cache/sysroot/lib/wasm32-emscripten/pic/libcompiler_rt.a', '-s', 'BOOTSTRAPPING_STRUCT_INFO=1', '-s', 'STRICT', '-s', 'SINGLE_FILE', '-Wno-error=version-check', '-Wno-deprecated']
emcc -O2 -g -fPIC -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -Wall -fPIC -I/src/cpython/installs/python-3.8.2/include/python3.8 -c src/markupsafe/_speedups.c -o build/temp.linux-x86_64-3.8/src/markupsafe/_speedups.o
emcc -s BINARYEN_EXTRA_PASSES="--pass-arg=max-func-params@61" -O2 -s MODULARIZE=1 -s EMULATE_FUNCTION_POINTER_CASTS=1 -s LINKABLE=1 -s EXPORT_ALL=1 -s WASM=1 -std=c++14 -s LZ4=1 -s SIDE_MODULE=1 build/temp.linux-x86_64-3.8/src/markupsafe/_speedups.o -o build/lib.linux-x86_64-3.8/markupsafe/_speedups.cpython-38-x86_64-linux-gnu.so
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.8/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/src/pyodide-build/pyodide_build/__main__.py", line 50, in <module>
    main()
  File "/src/pyodide-build/pyodide_build/__main__.py", line 44, in main
    args.func(args)
  File "/src/pyodide-build/pyodide_build/buildpkg.py", line 344, in main
    build_package(path, args)
  File "/src/pyodide-build/pyodide_build/buildpkg.py", line 279, in build_package
    compile(path, srcpath, pkg, args)
  File "/src/pyodide-build/pyodide_build/buildpkg.py", line 147, in compile
    subprocess.run(
  File "/usr/local/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/usr/local/bin/python3', '-m', 'pyodide_build', 'pywasmcross', '--cflags', '-O2 -g -fPIC ', '--cxxflags', ' ', '--ldflags', '-s BINARYEN_EXTRA_PASSES="--pass-arg=max-func-params@61" -O2 -s MODULARIZE=1 -s EMULATE_FUNCTION_POINTER_CASTS=1 -s LINKABLE=1 -s EXPORT_ALL=1 -s WASM=1 -std=c++14 -s LZ4=1  -s SIDE_MODULE=1 ', '--target', '/src/cpython/installs/python-3.8.2', '--install-dir', '/src/packages/.artifacts', '--replace-libs', '']' returned non-zero exit status 1.
[2021-06-03 23:40:38] Building package MarkupSafe...
[2021-06-03 23:40:47] done building package MarkupSafe in 9.1 s.
Traceback (most recent call last):
  File "/src/packages/.artifacts/bin/pyodide-build", line 33, in <module>
    sys.exit(load_entry_point('pyodide-build', 'console_scripts', 'pyodide-build')())
  File "/src/pyodide-build/pyodide_build/__main__.py", line 44, in main
    args.func(args)
  File "/src/pyodide-build/pyodide_build/buildall.py", line 360, in main
    build_packages(packages_dir, outputdir, args)
  File "/src/pyodide-build/pyodide_build/buildall.py", line 248, in build_packages
    build_from_graph(pkg_map, outputdir, args)
  File "/src/pyodide-build/pyodide_build/buildall.py", line 234, in build_from_graph
    raise pkg
  File "/src/pyodide-build/pyodide_build/buildall.py", line 217, in builder
    pkg.build(outputdir, args)
  File "/src/pyodide-build/pyodide_build/buildall.py", line 109, in build
    p.check_returncode()
  File "/usr/local/lib/python3.8/subprocess.py", line 444, in check_returncode
    raise CalledProcessError(self.returncode, self.args, self.stdout,
subprocess.CalledProcessError: Command '['/usr/local/bin/python3', '-m', 'pyodide_build', 'buildpkg', '/src/packages/MarkupSafe/meta.yaml', '--cflags', '-O2 -g -fPIC', '--cxxflags', '', '--ldflags', '-s BINARYEN_EXTRA_PASSES="--pass-arg=max-func-params@61" -O2 -s MODULARIZE=1 -s EMULATE_FUNCTION_POINTER_CASTS=1 -s LINKABLE=1 -s EXPORT_ALL=1 -s WASM=1 -std=c++14 -s LZ4=1  -s SIDE_MODULE=1', '--target', '/src/cpython/installs/python-3.8.2', '--install-dir', '/src/packages/.artifacts']' returned non-zero exit status 1.
make: *** [Makefile:11: all] Error 1
make: Leaving directory '/src/packages'
```

**Comment by rth** [comment]
Does building other packages work?  For instance,
```
PYODIDE_PACKAGES="regex" make
```

It feels more like an issue with the environment rather than with MarkupSafe. Could you please share a bit more information about your OS (Linux Distribution version if any) and environment?

**Comment by radu-matei** [comment]
Sure.
I skipped building MarkupSafe, and continued trying to build the packages inside a container - at least 25% of all packages failed to build - however, the rest compiled successfully.

I'm running a container based on the `run_docker` script on top of Ubuntu 20.04.

I will try to cleanup everything and try a new environment, but for now, here are the logs trying to build `regex`:


```
$ PYODIDE_PACKAGES="regex" make
Error building regex. Printing build logs.
running install
running bdist_egg
running egg_info
writing regex.egg-info/PKG-INFO
writing dependency_links to regex.egg-info/dependency_links.txt
writing top-level names to regex.egg-info/top_level.txt
reading manifest file 'regex.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'regex.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build
creating build/lib.linux-x86_64-3.8
creating build/lib.linux-x86_64-3.8/regex
copying regex_3/__init__.py -> build/lib.linux-x86_64-3.8/regex
copying regex_3/regex.py -> build/lib.linux-x86_64-3.8/regex
copying regex_3/_regex_core.py -> build/lib.linux-x86_64-3.8/regex
copying regex_3/test_regex.py -> build/lib.linux-x86_64-3.8/regex
running build_ext
building 'regex._regex' extension
creating build/temp.linux-x86_64-3.8
creating build/temp.linux-x86_64-3.8/regex_3
cc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -I/usr/local/include/python3.8 -c regex_3/_regex.c -o build/temp.linux-x86_64-3.8/regex_3/_regex.o
cc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -I/usr/local/include/python3.8 -c regex_3/_regex_unicode.c -o build/temp.linux-x86_64-3.8/regex_3/_regex_unicode.o
gcc -pthread -shared build/temp.linux-x86_64-3.8/regex_3/_regex.o build/temp.linux-x86_64-3.8/regex_3/_regex_unicode.o -L/usr/local/lib -o build/lib.linux-x86_64-3.8/regex/_regex.cpython-38-x86_64-linux-gnu.so
creating build/bdist.linux-x86_64
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/regex
copying build/lib.linux-x86_64-3.8/regex/_regex_core.py -> build/bdist.linux-x86_64/egg/regex
copying build/lib.linux-x86_64-3.8/regex/test_regex.py -> build/bdist.linux-x86_64/egg/regex
copying build/lib.linux-x86_64-3.8/regex/regex.py -> build/bdist.linux-x86_64/egg/regex
copying build/lib.linux-x86_64-3.8/regex/_regex.cpython-38-x86_64-linux-gnu.so -> build/bdist.linux-x86_64/egg/regex
copying build/lib.linux-x86_64-3.8/regex/__init__.py -> build/bdist.linux-x86_64/egg/regex
byte-compiling build/bdist.linux-x86_64/egg/regex/_regex_core.py to _regex_core.cpython-38.pyc
byte-compiling build/bdist.linux-x86_64/egg/regex/test_regex.py to test_regex.cpython-38.pyc
byte-compiling build/bdist.linux-x86_64/egg/regex/regex.py to regex.cpython-38.pyc
byte-compiling build/bdist.linux-x86_64/egg/regex/__init__.py to __init__.cpython-38.pyc
creating stub loader for regex/_regex.cpython-38-x86_64-linux-gnu.so
byte-compiling build/bdist.linux-x86_64/egg/regex/_regex.py to _regex.cpython-38.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying regex.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying regex.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying regex.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying regex.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
writing build/bdist.linux-x86_64/egg/EGG-INFO/native_libs.txt
zip_safe flag not set; analyzing archive contents...
regex.__pycache__._regex.cpython-38: module references __file__
creating dist
creating 'dist/regex-2021.4.4-py3.8-linux-x86_64.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing regex-2021.4.4-py3.8-linux-x86_64.egg
removing '/src/packages/.artifacts/lib/python/regex-2021.4.4-py3.8-linux-x86_64.egg' (and everything under it)
creating /src/packages/.artifacts/lib/python/regex-2021.4.4-py3.8-linux-x86_64.egg
Extracting regex-2021.4.4-py3.8-linux-x86_64.egg to /src/packages/.artifacts/lib/python
regex 2021.4.4 is already the active version in easy-install.pth

Installed /src/packages/.artifacts/lib/python/regex-2021.4.4-py3.8-linux-x86_64.egg
Processing dependencies for regex==2021.4.4
Finished processing dependencies for regex==2021.4.4
regex_3/_regex.c:24886:23: warning: unused function 'contains_repeat' [-Wunused-function]
Py_LOCAL_INLINE(BOOL) contains_repeat(RE_CODE* code, RE_CODE* end_code) {
                      ^
1 warning generated.
cache:INFO: generating system asset: generated_struct_info.json... (this will be cached in "/src/emsdk/emsdk/upstream/emscripten/cache/generated_struct_info.json" for subsequent builds)
/src/emsdk/emsdk/upstream/bin/wasm-opt: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /src/emsdk/emsdk/upstream/bin/wasm-opt)
/src/emsdk/emsdk/upstream/bin/wasm-opt: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /src/emsdk/emsdk/upstream/bin/wasm-opt)
emcc: error: error running binaryen executable (/src/emsdk/emsdk/upstream/bin/wasm-opt). Please check your binaryen installation
FAIL: Compilation failed!: ['/src/emsdk/emsdk/upstream/emscripten/emcc', '-D_GNU_SOURCE', '-o', '/tmp/tmp8ug3shtd.js', '/tmp/tmprik_n2p9.c', '-O0', '-Werror', '-Wno-format', '-nostdlib', '/src/emsdk/emsdk/upstream/emscripten/cache/sysroot/lib/wasm32-emscripten/pic/libcompiler_rt.a', '-s', 'BOOTSTRAPPING_STRUCT_INFO=1', '-s', 'STRICT', '-s', 'SINGLE_FILE', '-Wno-error=version-check', '-Wno-deprecated']
emcc -O2 -g -fPIC -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -Wall -fPIC -I/src/cpython/installs/python-3.8.2/include/python3.8 -c regex_3/_regex.c -o build/temp.linux-x86_64-3.8/regex_3/_regex.o
emcc -O2 -g -fPIC -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -Wall -fPIC -I/src/cpython/installs/python-3.8.2/include/python3.8 -c regex_3/_regex_unicode.c -o build/temp.linux-x86_64-3.8/regex_3/_regex_unicode.o
emcc -s BINARYEN_EXTRA_PASSES="--pass-arg=max-func-params@61" -O2 -s MODULARIZE=1 -s EMULATE_FUNCTION_POINTER_CASTS=1 -s LINKABLE=1 -s EXPORT_ALL=1 -s WASM=1 -std=c++14 -s LZ4=1 -s SIDE_MODULE=1 build/temp.linux-x86_64-3.8/regex_3/_regex.o build/temp.linux-x86_64-3.8/regex_3/_regex_unicode.o -o build/lib.linux-x86_64-3.8/regex/_regex.cpython-38-x86_64-linux-gnu.so
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.8/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/src/pyodide-build/pyodide_build/__main__.py", line 50, in <module>
    main()
  File "/src/pyodide-build/pyodide_build/__main__.py", line 44, in main
    args.func(args)
  File "/src/pyodide-build/pyodide_build/buildpkg.py", line 344, in main
    build_package(path, args)
  File "/src/pyodide-build/pyodide_build/buildpkg.py", line 279, in build_package
    compile(path, srcpath, pkg, args)
  File "/src/pyodide-build/pyodide_build/buildpkg.py", line 147, in compile
    subprocess.run(
  File "/usr/local/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/usr/local/bin/python3', '-m', 'pyodide_build', 'pywasmcross', '--cflags', '-O2 -g -fPIC ', '--cxxflags', ' ', '--ldflags', '-s BINARYEN_EXTRA_PASSES="--pass-arg=max-func-params@61" -O2 -s MODULARIZE=1 -s EMULATE_FUNCTION_POINTER_CASTS=1 -s LINKABLE=1 -s EXPORT_ALL=1 -s WASM=1 -std=c++14 -s LZ4=1  -s SIDE_MODULE=1 ', '--target', '/src/cpython/installs/python-3.8.2', '--install-dir', '/src/packages/.artifacts', '--replace-libs', '']' returned non-zero exit status 1.
[2021-06-04 18:34:47] Building package regex...
[2021-06-04 18:35:07] done building package regex in 20.2 s.
Traceback (most recent call last):
  File "/src/packages/.artifacts/bin/pyodide-build", line 33, in <module>
    sys.exit(load_entry_point('pyodide-build', 'console_scripts', 'pyodide-build')())
  File "/src/pyodide-build/pyodide_build/__main__.py", line 44, in main
    args.func(args)
  File "/src/pyodide-build/pyodide_build/buildall.py", line 360, in main
    build_packages(packages_dir, outputdir, args)
  File "/src/pyodide-build/pyodide_build/buildall.py", line 248, in build_packages
    build_from_graph(pkg_map, outputdir, args)
  File "/src/pyodide-build/pyodide_build/buildall.py", line 234, in build_from_graph
    raise pkg
  File "/src/pyodide-build/pyodide_build/buildall.py", line 217, in builder
    pkg.build(outputdir, args)
  File "/src/pyodide-build/pyodide_build/buildall.py", line 109, in build
    p.check_returncode()
  File "/usr/local/lib/python3.8/subprocess.py", line 444, in check_returncode
    raise CalledProcessError(self.returncode, self.args, self.stdout,
subprocess.CalledProcessError: Command '['/usr/local/bin/python3', '-m', 'pyodide_build', 'buildpkg', '/src/packages/regex/meta.yaml', '--cflags', '-O2 -g -fPIC', '--cxxflags', '', '--ldflags', '-s BINARYEN_EXTRA_PASSES="--pass-arg=max-func-params@61" -O2 -s MODULARIZE=1 -s EMULATE_FUNCTION_POINTER_CASTS=1 -s LINKABLE=1 -s EXPORT_ALL=1 -s WASM=1 -std=c++14 -s LZ4=1  -s SIDE_MODULE=1', '--target', '/src/cpython/installs/python-3.8.2', '--install-dir', '/src/packages/.artifacts']' returned non-zero exit status 1.
make[1]: *** [Makefile:11: all] Error 1
```

**Comment by sylvain-ri** [comment]
i also run into this issue when building MarkupSafe `emcc: error: elf_x86_64`
WSL2 on Windows 10.

```
creating dist
creating 'dist/MarkupSafe-2.0.1-py3.9-linux-x86_64.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing MarkupSafe-2.0.1-py3.9-linux-x86_64.egg
creating /home/sylvain/sylvain-pyodide/packages/.artifacts/lib/python/MarkupSafe-2.0.1-py3.9-linux-x86_64.egg
Extracting MarkupSafe-2.0.1-py3.9-linux-x86_64.egg to /home/sylvain/sylvain-pyodide/packages/.artifacts/lib/python
Adding MarkupSafe 2.0.1 to easy-install.pth file

Installed /home/sylvain/sylvain-pyodide/packages/.artifacts/lib/python/MarkupSafe-2.0.1-py3.9-linux-x86_64.egg
Processing dependencies for MarkupSafe==2.0.1
Finished processing dependencies for MarkupSafe==2.0.1
emcc: error: elf_x86_64: No such file or directory ("elf_x86_64" was expected to be an input file, based on the commandline arguments provided)
emcc -O2 -g -fPIC -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/home/sylvain/sylvain-pyodide/cpython/installs/python-3.9.5/include/python3.9 -c src/markupsafe/_speedups.c -o build/temp.linux-x86_64-3.9/src/markupsafe/_speedups.o
emcc -s BINARYEN_EXTRA_PASSES="--pass-arg=max-func-params@61" -O2 -s MODULARIZE=1 -s EMULATE_FUNCTION_POINTER_CASTS=1 -s LINKABLE=1 -s EXPORT_ALL=1 -s WASM=1 -std=c++14 -s LZ4=1 -L /installs/python-3.9.5/lib/ -s SIDE_MODULE=1 -plugin /usr/lib/gcc/x86_64-linux-gnu/9/liblto_plugin.so -plugin-opt=/usr/lib/gcc/x86_64-linux-gnu/9/lto-wrapper -plugin-opt=-fresolution=/tmp/cc26Tkcv.res -plugin-opt=-pass-through=-lgcc -plugin-opt=-pass-through=-lgcc_s -plugin-opt=-pass-through=-lpthread -plugin-opt=-pass-through=-lc -plugin-opt=-pass-through=-lgcc -plugin-opt=-pass-through=-lgcc_s --build-id --eh-frame-hdr -m elf_x86_64 --hash-style=gnu --as-needed -z relro -o build/lib.linux-x86_64-3.9/markupsafe/_speedups.cpython-39-x86_64-linux-gnu.so /usr/lib/gcc/x86_64-linux-gnu/9/../../../x86_64-linux-gnu/crti.o /usr/lib/gcc/x86_64-linux-gnu/9/crtbeginS.o -L/lib/x86_64-linux-gnu -L/lib/../lib -z relro -z relro build/temp.linux-x86_64-3.9/src/markupsafe/_speedups.o -lgcc --push-state --as-needed -lgcc_s --pop-state -lpthread -lc --push-state --as-needed --pop-state /usr/lib/gcc/x86_64-linux-gnu/9/crtendS.o /usr/lib/gcc/x86_64-linux-gnu/9/../../../x86_64-linux-gnu/crtn.o
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/sylvain/sylvain-pyodide/pyodide-build/pyodide_build/__main__.py", line 50, in <module>
    main()
  File "/home/sylvain/sylvain-pyodide/pyodide-build/pyodide_build/__main__.py", line 44, in main
    args.func(args)
  File "/home/sylvain/sylvain-pyodide/pyodide-build/pyodide_build/buildpkg.py", line 397, in main
    build_package(path, args)
  File "/home/sylvain/sylvain-pyodide/pyodide-build/pyodide_build/buildpkg.py", line 331, in build_package
    compile(path, srcpath, pkg, args, bash_runner)
  File "/home/sylvain/sylvain-pyodide/pyodide-build/pyodide_build/buildpkg.py", line 187, in compile
    subprocess.run(
  File "/usr/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/usr/bin/python3', '-m', 'pyodide_build', 'pywasmcross', '--cflags', '-O2 -g -fPIC ', '--cxxflags', ' ', '--ldflags', '-s BINARYEN_EXTRA_PASSES="--pass-arg=max-func-params@61" -O2 -s MODULARIZE=1 -s EMULATE_FUNCTION_POINTER_CASTS=1 -s LINKABLE=1 -s EXPORT_ALL=1 -s WASM=1 -std=c++14 -s LZ4=1 -L /installs/python-3.9.5/lib/  -s SIDE_MODULE=1 ', '--target', '/home/sylvain/sylvain-pyodide/cpython/installs/python-3.9.5', '--install-dir', '/home/sylvain/sylvain-pyodide/packages/.artifacts', '--replace-libs', '']' returned non-zero exit status 1.
[2021-09-22 08:38:48] Building package MarkupSafe...
[2021-09-22 08:38:54] done building package MarkupSafe in 6.0 s.
Traceback (most recent call last):
  File "/usr/local/bin/pyodide-build", line 33, in <module>
    sys.exit(load_entry_point('pyodide-build', 'console_scripts', 'pyodide-build')())
  File "/home/sylvain/sylvain-pyodide/pyodide-build/pyodide_build/__main__.py", line 44, in main
    args.func(args)
  File "/home/sylvain/sylvain-pyodide/pyodide-build/pyodide_build/buildall.py", line 428, in main
    build_packages(packages_dir, outputdir, args)
  File "/home/sylvain/sylvain-pyodide/pyodide-build/pyodide_build/buildall.py", line 325, in build_packages
    build_from_graph(pkg_map, outputdir, args)
  File "/home/sylvain/sylvain-pyodide/pyodide-build/pyodide_build/buildall.py", line 265, in build_from_graph
    raise pkg
  File "/home/sylvain/sylvain-pyodide/pyodide-build/pyodide_build/buildall.py", line 245, in builder
    pkg.build(outputdir, args)
  File "/home/sylvain/sylvain-pyodide/pyodide-build/pyodide_build/buildall.py", line 130, in build
    p.check_returncode()
  File "/usr/lib/python3.9/subprocess.py", line 460, in check_returncode
    raise CalledProcessError(self.returncode, self.args, self.stdout,
subprocess.CalledProcessError: Command '['/usr/bin/python3', '-m', 'pyodide_build', 'buildpkg', '/home/sylvain/sylvain-pyodide/packages/MarkupSafe/meta.yaml', '--cflags', '-O2 -g -fPIC', '--cxxflags', '', '--ldflags', '-s BINARYEN_EXTRA_PASSES="--pass-arg=max-func-params@61" -O2 -s MODULARIZE=1 -s EMULATE_FUNCTION_POINTER_CASTS=1 -s LINKABLE=1 -s EXPORT_ALL=1 -s WASM=1 -std=c++14 -s LZ4=1 -L /installs/python-3.9.5/lib/  -s SIDE_MODULE=1', '--target', '/home/sylvain/sylvain-pyodide/cpython/installs/python-3.9.5', '--install-dir', '/home/sylvain/sylvain-pyodide/packages/.artifacts']' returned non-zero exit status 1.
make[1]: *** [Makefile:16: all] Error 1
make[1]: Leaving directory '/home/sylvain/sylvain-pyodide/packages'
make: *** [Makefile:212: build/packages.json] Error 2
```

**Comment by ryanking13** [comment]
I believe this is resolved now.
