### ISSUE TITLE
http.client.HTTPSConnection is missing from the standard library

### ISSUE THREAD

**Issue by jpivarski** [pyodide/pyodide#1714]
This looks like a fantastic project, and I want to try using it with [Uproot](https://github.com/scikit-hep/uproot4), a Python package that only (strictly) depends on NumPy and the Python standard library.

I started by creating an `index.html` in the way described in [Quickstart > Complete example](https://pyodide.org/en/stable/usage/quickstart.html#complete-example), which loads Pyodide from `"https://cdn.jsdelivr.net/pyodide/v0.17.0/full/pyodide.js"`.

In the Javascript console (Chrome 91 on Linux), I ran

```javascript
pyodide.loadPackage('micropip')
pyodide.runPython("import micropip")
pyodide.runPython("micropip.install('uproot')")
```

which successfully installed the Uproot package (either from the [universal wheel or source tarball](https://pypi.org/project/uproot/#files), I don't know which). Then

```javascript
pyodide.runPython("import uproot")
```

failed with an import that I narrowed down to

```javascript
pyodide.runPython("from http.client import HTTPSConnection")
```

```
pyodide.asm.js:9
Python exception:
Traceback (most recent call last):
  File "/lib/python3.8/site-packages/pyodide/_base.py", line 344, in eval_code
    return CodeRunner(
  File "/lib/python3.8/site-packages/pyodide/_base.py", line 238, in run
    exec(mod, self.globals, self.locals)
  File "<exec>", line 1, in <module>
ImportError: cannot import name 'HTTPSConnection' from 'http.client' (/lib/python3.8/http/client.py)
```

Interestingly, it can find the `HTTPConnection` object, but not the `HTTPSConnection` object.

This might be related to https://github.com/pyodide/pyodide/issues/1545, but I don't see how.

To see if there would be any other import failures after this one, I grepped the Uproot library's imports (including non-strict ones) and found nothing except for

```javascript
pyodide.runPython("import lzma")
```

```
pyodide.asm.js:9
Python exception:
Traceback (most recent call last):
  File "/lib/python3.8/site-packages/pyodide/_base.py", line 344, in eval_code
    return CodeRunner(
  File "/lib/python3.8/site-packages/pyodide/_base.py", line 238, in run
    exec(mod, self.globals, self.locals)
  File "<exec>", line 1, in <module>
  File "/lib/python3.8/lzma.py", line 27, in <module>
    from _lzma import *
ModuleNotFoundError: No module named '_lzma'
```

which seems to be known: https://github.com/pyodide/pyodide/issues/877#issuecomment-763010175

It would be fun to stress-test Pyodide using Uproot, which I suppose I'll have to do through building custom wheels locally (e.g. with HTTPSConnection commented out). Since the argument to `micropip.install` needs to be a URL, I'll need to find a way to sidestep CORS in the `python -m http.server 8888` that I'm using to make the local files into URLs. (I'm unfamiliar with web technologies, if there's an easier way to make local files available to micropip so that I can test Uproot in Pyodide, I'd like to know. Thanks!)

**Comment by hoodmane** [comment]
Yeah I've run into this too. It's because the `ssl` import fails here:
```
try:
    import ssl
except ImportError:
    pass
else:
    class HTTPSConnection(HTTPConnection):
```
https://github.com/python/cpython/blob/2b47af63982e4ccc09ae14c7c66ba115804bbbf6/Lib/http/client.py#L1387

Kind of interesting that the socket import succeeds though because `socket` is also completely broken.

> need to find a way to sidestep CORS in the python -m http.server 8888

Don't CORS restrictions not apply to files served from localhost? Or are you loading your main page from a remote URL and only the one package from localhost?

**Comment by jpivarski** [comment]
Pyodide is in a file:// and the wheel is being served from http://localhost:8888. That's probably the problem.

Meanwhile, I found out that JupyterLite works for me (same error message in Uproot, but more convenient for development because it can be in the same directory that is hosted to provide JupyterLite). That's likely what I'll use for further testing, so I'll be able to adjust the Uproot code more dynamically.

**Comment by hoodmane** [comment]
> Pyodide is in a file://

Right, `file://` messes up CORS. Put the wheel and Pyodide in the same folder, serve that folder to localhost then load both Pyodide and the wheel over http. You should have no problem. Though it sounds like you already have a solution.

**Comment by hoodmane** [comment]
Probably the easiest fix for this is actually:
```py
from http import client
class HTTPSConnection: pass
client.HTTPSConnection = HTTPSConnection
```

**Comment by jpivarski** [comment]
You mean there's no difference between HTTPConnection and HTTPSConnection? (In Pyodide, not CPython, maybe because of the security already imposed by the browser?)

Is there a way to tell if I'm running under Pyodide, so that I can only apply this in the Pyodide case?

**Comment by hoodmane** [comment]
There are ways to feature detect Pyodide. I think the best is `"pyodide" in sys.modules`.

There is no functional difference between `HTTPConnection` and `HTTPSConnection`: both currently break when you try to use them. They try to open sockets but it isn't possible to open a socket out of the browser. That would be fine we can shim it using `fetch` but `fetch` is an asynchronous API and `HTTPConnection` is a synchronous API so to get it to work we need to dispatch the request to the main thread and use `Atomics.wait` to block for the result, or some other blocking strategy or stack rewinding #1503.

But yeah when we do get this stuff working, `HTTPConnection` and `HTTPSConnection` will have almost the same implementation because browsers already do most of the stuff for us and in any case won't let us directly touch tcp connections.
