### ISSUE TITLE
Error when executing pyodide via WebWorker

### ISSUE THREAD

**Issue by jdpigeon** [pyodide/pyodide#1771]
In the (Brainwaves)[https://github.com/makebrainwaves/BrainWaves/releases] project, we've recently run into an error executing python via pyodide in both version 17 and 18.

We get this message after any call to worker.postMessage using a WebWorker implementation (almost identical to the example code in the documentation).

```
Pyodide: 
Traceback (most recent call last): 
File "/lib/python3.9/asyncio/futures.py", line 201, in result raise self._exception 
File "/lib/python3.9/asyncio/tasks.py", line 256, in __step result = coro.send(None) 
File "/lib/python3.9/site-packages/_pyodide/_base.py", line 494, in eval_code_async await CodeRunner( 
File "/lib/python3.9/site-packages/_pyodide/_base.py", line 237, in __init__ self.ast = next(self._gen) 
File "/lib/python3.9/site-packages/_pyodide/_base.py", line 139, in _parse_and_compile_gen source = dedent(source) 
File "/lib/python3.9/textwrap.py", line 430, in dedent text = _whitespace_only_re.sub('', text) 
TypeError: expected string or bytes-like object
```

Any ideas what this might be? It looks like there's some problem with asyncio?

**Comment by hoodmane** [comment]
It looks to me like you called `runPythonAsync` with an argument that wasn't a string.

**Comment by teonbrooks** [comment]
I think I found our error. we were posting the message in our webworker with the field `data` but the webworker example we based it off of it set the field name to `python`. when `python` was trying to be access on the onMessage, it errored because the `python` value was undefined.

this issue can be closed, thanks!

**Comment by hoodmane** [comment]
We might consider typechecking the input to `runPython`.
