### ISSUE TITLE
How should I test my own package?

### ISSUE THREAD

**Issue by isaiahshiner** [pyodide/pyodide#1791]
Is there any official pattern for testing a 3rd party package on Pyodide, that does not intend to have their package become part of Pyodide?

I'm trying to run my own package, [dit_cli](https://github.com/ditabase/dit-cli), in Pyodide. This was actually quite easy to set up, you can see a very rough demo [here](https://dev.ditabase.io/demo.html). This is a 100% pure Python package, I'm not using the science stack, I just want to run Python/WASM efficiently in the browser.

Now I would like to set up testing, following the Pyodide pattern using Selenium. I've got the basics working, but a lot of what `conftest.py` does is very unclear, and apparently not intended for testing 3rd party packages.

- Should I package Pyodide with my project, just for testing?
- Should I just copy `conftest.py` and the rest of the testing system? What else do I need to know if I do that?

**Comment by rth** [comment]
You can actually run pytest on your package in Pyodide. The steps would be,
 1. add your tests under `<package_import_name>/tests`, so that locally you can run them using,
    ```
    pytest --pyargs <package_import_name>
    ```
    cf https://docs.pytest.org/en/6.2.x/example/pythoncollection.html#interpreting-cmdline-arguments-as-python-packages . Likely you would also need to add your conftest.py in the same folder.
 2. Install it with micropip, and run `pytest.main(['--pyargs', '<package_import_name>'])`. The steps are detailed in https://github.com/pyodide/pyodide/issues/1792 It looks like we have a regression when running a pytest in the REPL. It likely will work outside it (though I haven't tried it). Otherwise you can run it in the [0.17.0 REPL](https://pyodide.org/en/0.17.0/console.html). Currently it finds no test in your package, but I think that's because step 1 needs to be done.

The only donwiside of this is that it would increase the download size slightly.

**Comment by isaiahshiner** [comment]
Ah, okay. This took me a bit to follow, but you're saying I should drop Selenium, package the tests with the `.whl`, and then just run the tests in a real browser? This is definitely easier in some ways.

I've done a version of this on my demo page:
```JavaScript
async function startPyodide() {
  await loadPyodide({
    indexURL: "https://cdn.jsdelivr.net/pyodide/v0.17.0/full/",
    fullStdLib: false,
  });
  await pyodide.runPythonAsync(`
    import pytest
    import micropip
    await micropip.install('setuptools')
    await micropip.install('${window.location.origin}/js/dit_cli-0.5.1-py3-none-any.whl')
    pytest.main(['--pyargs', 'dit_cli'])
  `);
}
```
However, I get an error with pytest, it seems like some things are not imported. I tried running the tests for `matplotlib` and got a very similar error message.
<details>
  <summary>Error log</summary>
  
  ```
============================= test session starts ==============================
platform emscripten -- Python 3.8.2, pytest-3.6.3, py-1.9.0, pluggy-0.13.1
rootdir: /, inifile:

collecting 0 items / 1 errors                                                  
collected 0 items / 1 errors                                                   

==================================== ERRORS ====================================
______________________________ ERROR collecting  _______________________________
lib/python3.8/site-packages/_pytest/config/__init__.py:372: in _getconftestmodules
    return self._path2confmods[path]
E   KeyError: local('/lib/python3.8/site-packages/dit_cli/tests')

During handling of the above exception, another exception occurred:
lib/python3.8/site-packages/_pytest/config/__init__.py:403: in _importconftest
    return self._conftestpath2mod[conftestpath]
E   KeyError: local('/lib/python3.8/site-packages/dit_cli/tests/conftest.py')

During handling of the above exception, another exception occurred:
lib/python3.8/site-packages/_pytest/config/__init__.py:409: in _importconftest
    mod = conftestpath.pyimport()
lib/python3.8/site-packages/py/_path/local.py:704: in pyimport
    __import__(modname)
lib/python3.8/site-packages/_pytest/assertion/rewrite.py:226: in load_module
    py.builtin.exec_(co, mod.__dict__)
lib/python3.8/site-packages/dit_cli/tests/conftest.py:3: in <module>
    from _pytest.reports import TestReport
E   ModuleNotFoundError: No module named '_pytest.reports'

During handling of the above exception, another exception occurred:
lib/python3.8/site-packages/py/_path/common.py:383: in visit
    for x in Visitor(fil, rec, ignore, bf, sort).gen(self):
lib/python3.8/site-packages/py/_path/common.py:424: in gen
    dirs = self.optsort([p for p in entries
lib/python3.8/site-packages/py/_path/common.py:425: in <listcomp>
    if p.check(dir=1) and (rec is None or rec(p))])
lib/python3.8/site-packages/_pytest/main.py:511: in _recurse
    ihook = self.gethookproxy(path)
lib/python3.8/site-packages/_pytest/main.py:413: in gethookproxy
    my_conftestmodules = pm._getconftestmodules(fspath)
lib/python3.8/site-packages/_pytest/config/__init__.py:386: in _getconftestmodules
    mod = self._importconftest(conftestpath)
lib/python3.8/site-packages/_pytest/config/__init__.py:417: in _importconftest
    raise ConftestImportFailure(conftestpath, sys.exc_info())
E   _pytest.config.ConftestImportFailure: ModuleNotFoundError("No module named '_pytest.reports'")
E     File "/lib/python3.8/site-packages/_pytest/assertion/rewrite.py", line 226, in load_module
E       py.builtin.exec_(co, mod.__dict__)
E     File "/lib/python3.8/site-packages/dit_cli/tests/conftest.py", line 3, in <module>
E       from _pytest.reports import TestReport
!!!!!!!!!!!!!!!!!!! Interrupted: 1 errors during collection !!!!!!!!!!!!!!!!!!!!
=========================== 1 error in 1.04 seconds ============================
  ```
  
</details>

**Comment by isaiahshiner** [comment]
Ah, no wait. I was on v17. I updated to v18, and I get a different error. Very similar error with numpy this time.

```
INTERNALERROR>   File "/lib/python3.9/site-packages/_pytest/capture.py", line 459, in resume
INTERNALERROR>     os.dup2(self.tmpfile.fileno(), self.targetfd)
INTERNALERROR> PermissionError: [Errno 2] Permission denied
```

<details>
  <summary>Full Error Log</summary>
  
```
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/lib/python3.9/site-packages/_pytest/main.py", line 634, in perform_collect
INTERNALERROR>     self.items.extend(self.genitems(node))
INTERNALERROR>   File "/lib/python3.9/site-packages/_pytest/main.py", line 808, in genitems
INTERNALERROR>     rep = collect_one_node(node)
INTERNALERROR>   File "/lib/python3.9/site-packages/_pytest/runner.py", line 458, in collect_one_node
INTERNALERROR>     rep: CollectReport = ihook.pytest_make_collect_report(collector=collector)
INTERNALERROR>   File "/lib/python3.9/site-packages/pluggy/hooks.py", line 286, in __call__
INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "/lib/python3.9/site-packages/pluggy/manager.py", line 93, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/lib/python3.9/site-packages/pluggy/manager.py", line 84, in <lambda>
INTERNALERROR>     self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
INTERNALERROR>   File "/lib/python3.9/site-packages/pluggy/callers.py", line 208, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/lib/python3.9/site-packages/pluggy/callers.py", line 80, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/lib/python3.9/site-packages/pluggy/callers.py", line 182, in _multicall
INTERNALERROR>     next(gen)  # first yield
INTERNALERROR>   File "/lib/python3.9/site-packages/_pytest/capture.py", line 793, in pytest_make_collect_report
INTERNALERROR>     self.resume_global_capture()
INTERNALERROR>   File "/lib/python3.9/site-packages/_pytest/capture.py", line 701, in resume_global_capture
INTERNALERROR>     self._global_capturing.resume_capturing()
INTERNALERROR>   File "/lib/python3.9/site-packages/_pytest/capture.py", line 593, in resume_capturing
INTERNALERROR>     self.out.resume()
INTERNALERROR>   File "/lib/python3.9/site-packages/_pytest/capture.py", line 459, in resume
INTERNALERROR>     os.dup2(self.tmpfile.fileno(), self.targetfd)
INTERNALERROR> PermissionError: [Errno 2] Permission denied
INTERNALERROR> 
INTERNALERROR> During handling of the above exception, another exception occurred:
INTERNALERROR> 
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/lib/python3.9/site-packages/_pytest/main.py", line 269, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>   File "/lib/python3.9/site-packages/_pytest/main.py", line 322, in _main
INTERNALERROR>     config.hook.pytest_collection(session=session)
INTERNALERROR>   File "/lib/python3.9/site-packages/pluggy/hooks.py", line 286, in __call__
INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "/lib/python3.9/site-packages/pluggy/manager.py", line 93, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/lib/python3.9/site-packages/pluggy/manager.py", line 84, in <lambda>
INTERNALERROR>     self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
INTERNALERROR>   File "/lib/python3.9/site-packages/pluggy/callers.py", line 208, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/lib/python3.9/site-packages/pluggy/callers.py", line 80, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/lib/python3.9/site-packages/pluggy/callers.py", line 187, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/lib/python3.9/site-packages/_pytest/main.py", line 333, in pytest_collection
INTERNALERROR>     session.perform_collect()
INTERNALERROR>   File "/lib/python3.9/site-packages/_pytest/main.py", line 641, in perform_collect
INTERNALERROR>     hook.pytest_collection_finish(session=self)
INTERNALERROR>   File "/lib/python3.9/site-packages/pluggy/hooks.py", line 286, in __call__
INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "/lib/python3.9/site-packages/pluggy/manager.py", line 93, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/lib/python3.9/site-packages/pluggy/manager.py", line 84, in <lambda>
INTERNALERROR>     self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
INTERNALERROR>   File "/lib/python3.9/site-packages/pluggy/callers.py", line 208, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/lib/python3.9/site-packages/pluggy/callers.py", line 80, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/lib/python3.9/site-packages/pluggy/callers.py", line 187, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/lib/python3.9/site-packages/_pytest/terminal.py", line 745, in pytest_collection_finish
INTERNALERROR>     self.report_collect(True)
INTERNALERROR>   File "/lib/python3.9/site-packages/_pytest/terminal.py", line 682, in report_collect
INTERNALERROR>     self.rewrite(line, bold=True, erase=True)
INTERNALERROR>   File "/lib/python3.9/site-packages/_pytest/terminal.py", line 448, in rewrite
INTERNALERROR>     self._tw.write("\r" + line + fill, **markup)
INTERNALERROR>   File "/lib/python3.9/site-packages/_pytest/_io/terminalwriter.py", line 155, in write
INTERNALERROR>     self._file.write(msg)
INTERNALERROR> OSError: [Errno 8] Bad file descriptor

============================ no tests ran in 0.75s =============================
```
</details>

**Comment by hoodmane** [comment]
I opened an issue about these `TemporaryFile` errors here:
https://github.com/emscripten-core/emscripten/issues/15012

**Comment by isaiahshiner** [comment]
![image](https://user-images.githubusercontent.com/7571411/133312245-f2986482-5c4a-4865-a4d2-a23b1cb86a6d.png)
My tests are running! Thank you so much! This is so valuable. The tests for the `regex` package are also running now, where they weren't before.

Sorry I wasn't able to fix it myself. I spent some time just trying to learn the emscripten architecture and then got busy with other things. I'd still love to work on Pyodide, but maybe something a little easier to start with.

**Comment by hoodmane** [comment]
> Sorry I wasn't able to fix it myself.

No worries, this was indeed not a great first issue. If you are willing to open a PR adding an FAQ entry with "How should I test my own package?" that would be welcome.
