### ISSUE TITLE
Pandas line with exception prints stacktrace incorrectly

### ISSUE THREAD

**Issue by leopsidom** [pyodide/pyodide#1809]
Found an interesting case where the exception does not seem to be handled correctly

Reproduce step, type the following in REPL: https://pyodide.org/en/stable/console.html

```
import pandas as pd
df = pd.DataFrame({"customer_code": ['1234','3411','9303'],
                   "main_purchases": [3,10,5],
                   "main_revenue": [103.5,401.5,99.0],
                   "secondary_purchases": [1,2,4],
                   "secondary_revenue": [43.1,77.5,104.6]
                  })

df.set_index('customer_code').rename(columns=lambda x: x.split('_'))
```

This will result in:
> [Command] fut.formatted_error is undefined

If we run the above code in a native python terminal, we get the following stack trace:

> Traceback (most recent call last):
  File "pandas/_libs/hashtable_class_helper.pxi", line 5231, in pandas._libs.hashtable.PyObjectHashTable.map_locations
TypeError: unhashable type: 'list'
Exception ignored in: 'pandas._libs.index.IndexEngine._call_map_locations'
Traceback (most recent call last):
  File "pandas/_libs/hashtable_class_helper.pxi", line 5231, in pandas._libs.hashtable.PyObjectHashTable.map_locations
TypeError: unhashable type: 'list'
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/yaxiaoy/AWSResourcesAnalysis/lib/python3.8/site-packages/pandas/core/frame.py", line 995, in __repr__
    self.to_string(
  File "/Users/yaxiaoy/AWSResourcesAnalysis/lib/python3.8/site-packages/pandas/core/frame.py", line 1131, in to_string
    return fmt.DataFrameRenderer(formatter).to_string(
  File "/Users/yaxiaoy/AWSResourcesAnalysis/lib/python3.8/site-packages/pandas/io/formats/format.py", line 1053, in to_string
    string = string_formatter.to_string()
  File "/Users/yaxiaoy/AWSResourcesAnalysis/lib/python3.8/site-packages/pandas/io/formats/string.py", line 25, in to_string
    text = self._get_string_representation()
  File "/Users/yaxiaoy/AWSResourcesAnalysis/lib/python3.8/site-packages/pandas/io/formats/string.py", line 40, in _get_string_representation
    strcols = self._get_strcols()
  File "/Users/yaxiaoy/AWSResourcesAnalysis/lib/python3.8/site-packages/pandas/io/formats/string.py", line 31, in _get_strcols
    strcols = self.fmt.get_strcols()
  File "/Users/yaxiaoy/AWSResourcesAnalysis/lib/python3.8/site-packages/pandas/io/formats/format.py", line 540, in get_strcols
    strcols = self._get_strcols_without_index()
  File "/Users/yaxiaoy/AWSResourcesAnalysis/lib/python3.8/site-packages/pandas/io/formats/format.py", line 793, in _get_strcols_without_index
    str_columns = self._get_formatted_column_labels(self.tr_frame)
  File "/Users/yaxiaoy/AWSResourcesAnalysis/lib/python3.8/site-packages/pandas/io/formats/format.py", line 874, in _get_formatted_column_labels
    str_columns = [
  File "/Users/yaxiaoy/AWSResourcesAnalysis/lib/python3.8/site-packages/pandas/io/formats/format.py", line 875, in <listcomp>
    [" " + x if not self._get_formatter(i) and need_leadsp[x] else x]
  File "/Users/yaxiaoy/AWSResourcesAnalysis/lib/python3.8/site-packages/pandas/io/formats/format.py", line 838, in _get_formatter
    return self.formatters.get(i, None)
TypeError: unhashable type: 'list'

Seems to have something to do with `repr`, but can't confirm yet.

**Comment by hoodmane** [comment]
Thanks for this report! There is a simpler reproduction with:
```
>>> class Test:
...    def __repr__(self):
...       raise TypeError("hi")
... 
>>> Test()
[Command] fut.formatted_error is undefined
```

**Comment by alexmojaki** [comment]
Both these examples now print `[Command] fut.formatted_error is undefined`, and more importantly the console stops working entirely afterwards.
