### ISSUE TITLE
ImportError: cannot import name 'shgo' from 'scipy.optimize' (/lib/python3.9/site-packages/scipy/optimize/__init__.py)

### ISSUE THREAD

**Issue by SebastianJHM** [pyodide/pyodide#1815]
I´m trying this code but I hava an error ImportError

```js
pyodide.runPython(`
    from scipy.optimize import rosen, shgo
    bounds = [(0,2), (0, 2), (0, 2), (0, 2), (0, 2)]
    result = shgo(rosen, bounds)
    result.x, result.fun
    str(list(result.x))
`)
```

 =======================================================
```
Uncaught (in promise) PythonError: Traceback (most recent call last):
  File "/lib/python3.9/site-packages/_pyodide/_base.py", line 415, in eval_code
    CodeRunner(
  File "/lib/python3.9/site-packages/_pyodide/_base.py", line 296, in run
    coroutine = eval(self.code, globals, locals)
  File "<exec>", line 2, in <module>
ImportError: cannot import name 'shgo' from 'scipy.optimize' (/lib/python3.9/site-packages/scipy/optimize/__init__.py)

    at new_error (pyodide.asm.js:14)
    at pyodide.asm.wasm:0x1b2e8b
    at pyodide.asm.wasm:0x1b2f82
    at Object.Module._pythonexc2js (pyodide.asm.js:14)
    at Object.Module.callPyObjectKwargs (pyodide.js:1)
    at Object.Module.callPyObject (pyodide.js:1)
    at PyProxyClass.apply (pyodide.js:1)
    at Object.apply (pyodide.js:1)
    at Object.runPython (pyodide.js:1)
    at evaluatePython (6index.html:20)
```

**Comment by rth** [comment]
SHGO was added to scipy in 1.2 while we still include only scipy 0.17.1 Closing in favor of https://github.com/pyodide/pyodide/issues/549. Don't hesitate to comment there.
