### ISSUE TITLE
The calendar module may use the wrong locale

### ISSUE THREAD

**Issue by 0x6369616e** [pyodide/pyodide#1831]
Hey, 
I tried to use the calendar with the locale both got some issues. 

Whenever I set the locale through the locale.setlocale function the module variable 'month_name' in the calendar module returns the wrong month names. The 'month_name' always returns the english names of all months. If it would use the current locale, the attribute returns all names in the appropriate language. 

To show more details here's a simple example how it should work:

Tested OS: Windows x64 
Python Version: 3.9.5

![log_win](https://user-images.githubusercontent.com/76896905/133104064-0f25b365-fdc9-4b1b-a4c9-fa6c199a24c3.PNG)

And here is another image how it works in the online pydiode console: 

![log_pyodide_online_console](https://user-images.githubusercontent.com/76896905/133104359-db29d453-b5ce-41db-8ddd-3d7ffd5fb51e.PNG)

Tested on: Pyodide Online Repl Console
Python Version: 3.9.5

Best Regards
0x6369616e

**Comment by rth** [comment]
Thanks for the report! I think what is likely happening is that `locale.setlocale` should have failed because the `de_DE.UTF-8` locale is not included in Pyodide. For instance locally on system Python I get,
```py
>>> locale.setlocale(locale.LC_ALL, "de_DE.UTF-8")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.9/locale.py", line 610, in setlocale
    return _setlocale(category, locale)
locale.Error: unsupported locale setting
```
However it sounds like emscripten silently ignored that call -- there is a precedent in https://github.com/emscripten-core/emscripten/issues/2636. So what would be necessary is to search trough Emscripten code to figure out why this is happening and how one can add locales to the environment. 

The minimal reproducible example is,
```py
>>> import datetime
>>> locale.set_locale(locale.LC_ALL, "de_DE.UTF-8")
>>> datetime.date(2001, 1, 1).strftime("%B")
```
since the calendar module uses `strftime` internally.

**Comment by rth** [comment]
BTW, we are currently [skipping all locale tests](https://github.com/pyodide/pyodide/blob/main/src/tests/python_tests.txt#L27) in CPython.
