### ISSUE TITLE
new package: preshed, cymem

### ISSUE THREAD

**Issue by sylvain-ri** [pyodide/pyodide#1858]
Creating new packages for cymem and preshed (dependencies of SpaCy). 
I created the meta.yaml with `pyodide-build mkpkg`, added dependencies in the `requirements/run` section. Using Docker image on Windows 10 pro.

Cymem seems to built fine, but when i try to build preshed, it doesn't find cymem. Then chain reaction, were it doesn't find murmurhash and issues with the gil, but i think that's side effects.

Some directions I should follow ? Thank you in advance

Log:
```
# PYODIDE_PACKAGES="preshed" make
./tools/dependency-check.sh
cp src/templates/console.html build/console.html
sed -i -e 's#{{ PYODIDE_BASE_URL }}#./#g' build/console.html
date +"[%F %T] Building packages..."
[2021-09-24 08:57:52] Building packages...
make -C packages
make[1]: Entering directory '/src/sylvain-pyodide/packages'
mkdir -p build-logs
PYTHONPATH="/src/sylvain-pyodide/packages/.artifacts/lib/python:/src/sylvain-pyodide/pyodide-build/" pyodide-build buildall . ../build \
        --target=/src/sylvain-pyodide/cpython/installs/python-3.9.5 --only "preshed" --install-dir /src/sylvain-pyodide/packages/.artifacts --n-jobs ${PYODIDE_JOBS:-4} \
        --log-dir=build-logs
Building the following packages: cymem, distutils, micropip, murmurhash, packaging, preshed, pyparsing
[1/7] (thread 1) building pyparsing
[2/7] (thread 2) building cymem
[3/7] (thread 3) building murmurhash
[4/7] (thread 4) building distutils
[4/7] (thread 4) built distutils in 0.0 s
[3/7] (thread 3) built murmurhash in 0.7 s
[2/7] (thread 2) built cymem in 0.7 s
[5/7] (thread 4) building preshed
[1/7] (thread 1) built pyparsing in 0.7 s
[6/7] (thread 3) building packaging
[6/7] (thread 3) built packaging in 0.6 s
[7/7] (thread 2) building micropip
[7/7] (thread 2) built micropip in 0.6 s
Error building preshed. Printing build logs.

Error compiling Cython file:
------------------------------------------------------------
...
from libc.stdint cimport uint64_t, uint32_t
from cymem.cymem cimport Pool
^
------------------------------------------------------------

preshed/bloom.pxd:2:0: 'cymem/cymem.pxd' not found

Error compiling Cython file:
------------------------------------------------------------
...
from libc.stdint cimport uint64_t, uint32_t
from cymem.cymem cimport Pool
^
------------------------------------------------------------

preshed/bloom.pxd:2:0: 'cymem/cymem/Pool.pxd' not found
```
skipping some lines
```
preshed/bloom.pyx:4:0: 'murmurhash/mrmr.pxd' not found

Error compiling Cython file:
------------------------------------------------------------
...
# cython: infer_types=True
# cython: cdivision=True
#
from murmurhash.mrmr cimport hash128_x86
^
------------------------------------------------------------

preshed/bloom.pyx:4:0: 'murmurhash/mrmr/hash128_x86.pxd' not found
```
Skipping more 
```
preshed/bloom.pyx:90:21: Storing unsafe C derivative of temporary Python reference

Error compiling Cython file:
------------------------------------------------------------
...

cdef void bloom_add(BloomStruct* bloom, key_t item) nogil:
    cdef key_t hv
    cdef key_t[2] keys
    cdef key_t one = 1 # We want this explicitly typed, because bits
    hash128_x86(&item, sizeof(key_t), 0, &keys)
   ^
------------------------------------------------------------

preshed/bloom.pyx:110:4: 'hash128_x86' is not a constant, variable or function identifier
```
Skipping more lines
```
preshed/bloom.pyx:120:23: Converting to Python object not allowed without gil

Error compiling Cython file:
------------------------------------------------------------
...

cdef bint bloom_contains(const BloomStruct* bloom, key_t item) nogil:
    cdef key_t hv
    cdef key_t[2] keys
    cdef key_t one = 1 # We want this explicitly typed, because bits
    hash128_x86(&item, sizeof(key_t), 0, &keys)
                                        ^
------------------------------------------------------------

preshed/bloom.pyx:120:41: Converting to Python object not allowed without gil
Compiling preshed/maps.pyx because it changed.
Compiling preshed/counter.pyx because it changed.
Compiling preshed/bloom.pyx because it changed.
[1/3] Cythonizing preshed/bloom.pyx
Traceback (most recent call last):
  File "/src/sylvain-pyodide/packages/preshed/build/preshed-3.0.5/setup.py", line 134, in <module>
    setup_package()
  File "/src/sylvain-pyodide/packages/preshed/build/preshed-3.0.5/setup.py", line 109, in setup_package
    ext_modules=cythonize(ext_modules, language_level=2),
  File "/usr/local/lib/python3.9/site-packages/Cython/Build/Dependencies.py", line 1102, in cythonize
    cythonize_one(*args)
  File "/usr/local/lib/python3.9/site-packages/Cython/Build/Dependencies.py", line 1225, in cythonize_one
    raise CompileError(None, pyx_file)
Cython.Compiler.Errors.CompileError: preshed/bloom.pyx
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/src/sylvain-pyodide/pyodide-build/pyodide_build/__main__.py", line 50, in <module>
    main()
  File "/src/sylvain-pyodide/pyodide-build/pyodide_build/__main__.py", line 44, in main
    args.func(args)
  File "/src/sylvain-pyodide/pyodide-build/pyodide_build/buildpkg.py", line 496, in main
    build_package(path, args)
  File "/src/sylvain-pyodide/pyodide-build/pyodide_build/buildpkg.py", line 430, in build_package
    compile(path, srcpath, pkg, args, bash_runner)
  File "/src/sylvain-pyodide/pyodide-build/pyodide_build/buildpkg.py", line 188, in compile
    subprocess.run(
  File "/usr/local/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/usr/local/bin/python', '-m', 'pyodide_build', 'pywasmcross', '--cflags', '-O2 -g -fPIC ', '--cxxflags', ' ', '--ldflags', '-s BINARYEN_EXTRA_PASSES="--pass-arg=max-func-params@61" -O2 -s MODULARIZE=1 -s EMULATE_FUNCTION_POINTER_CASTS=1 -s LINKABLE=1 -s EXPORT_ALL=1 -s WASM=1 -std=c++14 -s LZ4=1 -L /installs/python-3.9.5/lib/  -s SIDE_MODULE=1 ', '--target', '/src/sylvain-pyodide/cpython/installs/python-3.9.5', '--install-dir', '/src/sylvain-pyodide/packages/.artifacts', '--replace-libs', '']' returned non-zero exit status 1.
[2021-09-24 08:57:55] Building package preshed...
[2021-09-24 08:57:56] done building package preshed in 1.1 s.
Traceback (most recent call last):
  File "/usr/local/bin/pyodide-build", line 33, in <module>
    sys.exit(load_entry_point('pyodide-build', 'console_scripts', 'pyodide-build')())
  File "/src/sylvain-pyodide/pyodide-build/pyodide_build/__main__.py", line 44, in main
    args.func(args)
  File "/src/sylvain-pyodide/pyodide-build/pyodide_build/buildall.py", line 454, in main
    build_packages(packages_dir, outputdir, args)
  File "/src/sylvain-pyodide/pyodide-build/pyodide_build/buildall.py", line 351, in build_packages
    build_from_graph(pkg_map, outputdir, args)
  File "/src/sylvain-pyodide/pyodide-build/pyodide_build/buildall.py", line 275, in build_from_graph
    raise pkg
  File "/src/sylvain-pyodide/pyodide-build/pyodide_build/buildall.py", line 255, in builder
    pkg.build(outputdir, args)
  File "/src/sylvain-pyodide/pyodide-build/pyodide_build/buildall.py", line 131, in build
    p.check_returncode()
  File "/usr/local/lib/python3.9/subprocess.py", line 460, in check_returncode
    raise CalledProcessError(self.returncode, self.args, self.stdout,
subprocess.CalledProcessError: Command '['/usr/local/bin/python', '-m', 'pyodide_build', 'buildpkg', '/src/sylvain-pyodide/packages/preshed/meta.yaml', '--cflags', '-O2 -g -fPIC', '--cxxflags', '', '--ldflags', '-s BINARYEN_EXTRA_PASSES="--pass-arg=max-func-params@61" -O2 -s MODULARIZE=1 -s EMULATE_FUNCTION_POINTER_CASTS=1 -s LINKABLE=1 -s EXPORT_ALL=1 -s WASM=1 -std=c++14 -s LZ4=1 -L /installs/python-3.9.5/lib/  -s SIDE_MODULE=1', '--target', '/src/sylvain-pyodide/cpython/installs/python-3.9.5', '--install-dir', '/src/sylvain-pyodide/packages/.artifacts']' returned non-zero exit status 1.
make[1]: *** [Makefile:16: all] Error 1
make[1]: Leaving directory '/src/sylvain-pyodide/packages'
make: *** [Makefile:217: build/packages.json] Error 2
```

**Comment by ryanking13** [comment]
Can you show us how meta.yaml file of cymem and preshed look like?
And also it would be nice if you provide the build log of those packages.
