### ISSUE TITLE
CI ImportError: cannot import name 'fetch' from 'js'

### ISSUE THREAD

**Issue by rth** [pyodide/pyodide#1890]
We seem to get more and more CI failures on main. While some are probably difficult to avoid, the following ones I find suspicious,

Node.js
```
test_idbfs_persist_code[node] - src.tests.test_filesystem
[...]
conftest.JavascriptException: PythonError: Traceback (most recent call last):
  File "<string>", line 8, in temp

  File "/lib/python3.9/site-packages/pyodide/__init__.py", line 31, in <module>

    from .http import open_url

  File "/lib/python3.9/site-packages/pyodide/http.py", line 14, in <module>

    from js import fetch as _jsfetch, Object

ImportError: cannot import name 'fetch' from 'js' (unknown location)
```

test-js
```
1) "before all" hook in "{root}":
     PythonError: Traceback (most recent call last):
  File "<string>", line 8, in temp
  File "/lib/python3.9/site-packages/pyodide/__init__.py", line 31, in <module>
    from .http import open_url
  File "/lib/python3.9/site-packages/pyodide/http.py", line 14, in <module>
    from js import fetch as _jsfetch, Object
ImportError: cannot import name 'fetch' from 'js' (unknown location)
```

They started to happen after https://github.com/pyodide/pyodide/pull/1865

**Comment by hoodmane** [comment]
What's weird though is that I didn't think this import error was consistent. It only happens some of the time. Or maybe the reason I thought it was inconsistent was because I was comparing across different branches, only some of which had the problematic code....

**Comment by rth** [comment]
Also looking into this now, and it is indeed strange. In particular, why it happens for only 1 Node test, there are plenty that would use pyfetch..

**Comment by hoodmane** [comment]
Right, everything that imports micropip ought to be affected...

**Comment by hoodmane** [comment]
Well we have two distinct node test runners, test_js is the more "primitive" one. It's possible we only set up the fetch shim in the pytest node runner?

**Comment by w213034025** [comment]
Also getting issue in PyCharm

**Comment by ryanking13** [comment]
> (C:\Anaconda\lib\site-packages\js__init__.py)

Could you show us the content of that file? I think that file is not part of Pyodide and is probably shadowing the namespace js.
