### ISSUE TITLE
Unable to import `matplotlib` in 0.18.1

### ISSUE THREAD

**Issue by vrthra** [pyodide/pyodide#1945]
## 🐛 Bug

I am unable to import matplotlib in 0.18.1 pyodide release.

### To Reproduce

```shell
$ bzcat ../pyodide-build-0.18.1.tar.bz2| tar -xvpf -
```

```html
<!DOCTYPE html>
<html>
  <head>
     <meta charset="utf-8"/>
      <script src="/pyodide/pyodide.js"></script>
  </head>
  <body>
    Pyodide test page <br>
    Open your browser console to see Pyodide output
    <script type="text/javascript">
      async function main(){
        let pyodide = await loadPyodide({
          indexURL : "/pyodide/"
        });
        pyodide.loadPackage("matplotlib");
        // pyodide.loadPackage("/pyodide/matplotlib.js");
        console.log(pyodide.runPython(`
            import sys
            import matplotlib
            print(sys.version)
        `));

      }
      main();
    </script>
  </body>
</html>
```

This produces

```
-----
pyodide.asm.js:14 wasm streaming compile failed: TypeError: Failed to execute 'compile' on 'WebAssembly': Incorrect response MIME type. Expected 'application/wasm'.
(anonymous) @ pyodide.asm.js:14
-----
pyodide.asm.js:14 falling back to ArrayBuffer instantiation
(anonymous) @ pyodide.asm.js:14
pyodide.asm.js:14 Python initialization complete
load-pyodide.js:172 Loading distutils
load-pyodide.js:198 Loading distutils from /pyodide/distutils.js
load-pyodide.js:252 Loaded distutils
-----
pyodide.asm.js:14 Python exception:
Traceback (most recent call last):
  File "/lib/python3.9/site-packages/_pyodide/_base.py", line 415, in eval_code
    CodeRunner(
  File "/lib/python3.9/site-packages/_pyodide/_base.py", line 296, in run
    coroutine = eval(self.code, globals, locals)
  File "<exec>", line 3, in <module>
ModuleNotFoundError: No module named 'matplotlib'
-----
log_python_error @ pyodide.asm.js:14
load-pyodide.js:172 Loading matplotlib, distutils, cycler, six, kiwisolver, numpy, pillow, pyparsing, python-dateutil, pytz
load-pyodide.js:198 Loading matplotlib from /pyodide/matplotlib.js
load-pyodide.js:185 distutils already loaded from default channel
load-pyodide.js:198 Loading cycler from /pyodide/cycler.js
load-pyodide.js:198 Loading six from /pyodide/six.js
load-pyodide.js:198 Loading kiwisolver from /pyodide/kiwisolver.js
load-pyodide.js:198 Loading numpy from /pyodide/numpy.js
load-pyodide.js:198 Loading pillow from /pyodide/pillow.js
load-pyodide.js:198 Loading pyparsing from /pyodide/pyparsing.js
load-pyodide.js:198 Loading python-dateutil from /pyodide/python-dateutil.js
load-pyodide.js:198 Loading pytz from /pyodide/pytz.js
load-pyodide.js:252 Loaded matplotlib, distutils, cycler, six, kiwisolver, numpy, pillow, pyparsing, python-dateutil, pytz
```
I confirmed that `matplotlib` is indeed present in the filesystem.

```shell
$ ls pyodide/matplotlib.*
pyodide/matplotlib.data
pyodide/matplotlib.js
```

### Expected behavior

It was expected that I should see the `sys.version` in the console log.

### Environment

- Pyodide Version 0.18.1
- Browser version Chrome Version 95.0.4638.54 (Official Build) (x86_64),  Firefox 94.0.1

**Comment by ryanking13** [comment]
Can you try

```
await pyodide.loadPackage("matplotlib");
```

instead of

```
pyodide.loadPackage("matplotlib");
```

**Comment by vrthra** [comment]
Ah I see, yes, that worked. Thank you!
