### ISSUE TITLE
How to indicate in requirements that a package requires Pyodide to run

### ISSUE THREAD

**Issue by rth** [pyodide/pyodide#1985]
From a Python perspective if a package requires Pyodide to run in WASM VM (e.g. because it uses the `pyodide` or `js` modules) it should be reflected in the requirements. For instance, [aitk.keras](https://github.com/ArtificialIntelligenceToolkit/aitk.keras)

 Following the discussion in https://github.com/pyodide/pyodide/issues/1984, I think we can do this with,
```py
setup(
    ...,
    install_requires=[
        "pyodide; platform_system=='Emscripten'",
    ],
)
```
In this case,
 - pip will already drop the requirement since `platform.system` will not much
 - micropip should also drop the requirement for this to work, I think, to avoid installing a package that is already there.

**Comment by rth** [comment]
Related to this, I just uploaded https://pypi.org/project/pyodide/ to register the name on PyPi. When installed with pip it would error,
```
$ pip install pyodide
  Downloading pyodide-0.0.2.tar.gz (19 kB)
    ERROR: Command errored out with exit status 1:
[...]
    ValueError: Pyodide is a Python distribution that runs in the browser or Node.js. It cannot be installed from PyPi.
                See https://github.com/pyodide/pyodide for how to use Pyodide.
ERROR: Could not find a version that satisfies the requirement pyodide (from versions: 0.0.2)
ERROR: No matching distribution found for pyodide
```

Source is [here](https://github.com/rth/sandbox/tree/master/pyodide-pypi-package) since the package is not intended to be updated.

**Comment by ryanking13** [comment]
https://github.com/rth/sandbox/tree/master/pyodide-pypi-package returns 404 error

**Comment by rth** [comment]
@ryanking13 It should work now. I forgot that the repo was private.

**Comment by RenzoGamero** [comment]
I get this error

pip install pyodide
Collecting pyodide
  Using cached pyodide-0.0.2.tar.gz (19 kB)
    ERROR: Command errored out with exit status 1:
     command: /opt/anaconda3/envs/py39/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/t1/79lnp4j53190yljd0_nvvb5m0000gp/T/pip-install-jugnf9ga/pyodide_cf1129029d6a44649ea2c74f256c1766/setup.py'"'"'; __file__='"'"'/private/var/folders/t1/79lnp4j53190yljd0_nvvb5m0000gp/T/pip-install-jugnf9ga/pyodide_cf1129029d6a44649ea2c74f256c1766/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/t1/79lnp4j53190yljd0_nvvb5m0000gp/T/pip-pip-egg-info-6p4pxp_0
         cwd: /private/var/folders/t1/79lnp4j53190yljd0_nvvb5m0000gp/T/pip-install-jugnf9ga/pyodide_cf1129029d6a44649ea2c74f256c1766/
    Complete output (6 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/t1/79lnp4j53190yljd0_nvvb5m0000gp/T/pip-install-jugnf9ga/pyodide_cf1129029d6a44649ea2c74f256c1766/setup.py", line 7, in <module>
        raise ValueError(
    ValueError: Pyodide is a Python distribution that runs in the browser or Node.js. It cannot be installed from PyPi.
                See https://github.com/pyodide/pyodide for how to use Pyodide.
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/87/f6/a828d76fbb3fab2c114f2c5f6cd045b574e7c52d2f192c112cc97c23c0f4/pyodide-0.0.2.tar.gz#sha256=ca79db85c1ce8ebfde2f6b44d294e9dc9ccbb89b59304a68f26e75da7ddfb673 (from https://pypi.org/simple/pyodide/) (requires-python:>=3.9). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement pyodide (from versions: 0.0.2, 0.19.0a1)
ERROR: No matching distribution found for pyodide

**Comment by hoodmane** [comment]
See error message:

> Pyodide is a Python distribution that runs in the browser or Node.js. **It cannot be installed from PyPi.**
> See [pyodide/pyodide](https://github.com/pyodide/pyodide) for how to use Pyodide.

**Comment by Baghdadimouad** [comment]
Hi hope you're doing well, pleas how can I install pyodide package on vs code to use it on a data analysis project

**Comment by Baghdadimouad** [comment]
I have this problem while running pip install pyodide :
Collecting pyodide
  Using cached pyodide-0.0.2.tar.gz (19 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [7 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\Mouad\AppData\Local\Temp\pip-install-hytn_jkn\pyodide_d2f2163c84794780a8a92f7a373c9c76\setup.py", line 7, in <module>
          raise ValueError(
      ValueError: Pyodide is a Python distribution that runs in the browser or Node.js. It cannot be installed from PyPi.
                  See https://github.com/pyodide/pyodide for how to use Pyodide.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by ryanking13** [comment]
@Baghdadimouad You can't install Pyodide with pip. The error is intended to prevent people from trying to install pyodide with pip  (see the error message).

If you want to use pyodide from VSCode, I think the current best way is to use https://github.com/joyceerhl/vscode-pyolite extension which is a Jupyterlite + Pyodide extension for VSCode. There is also a experimental commandline runner for Pyodide, but it is not documented (https://github.com/pyodide/pyodide/pull/3044) yet.
