### ISSUE TITLE
runPythonAsync never returns when interrupted during await.

### ISSUE THREAD

**Issue by brendan0powers** [pyodide/pyodide#2141]
## 🐛 Bug

If an interrupt buffer is used to interrupt pyodide while pthon is awaiting some function, an exception is thrown in the internals of WebLoop, and the awaiting code never returns. If runPythonAsync was used to run the python code, the promise it returns never resolves.

### To Reproduce

A more complete, runnable reproduction can be found here: https://jsfiddle.net/jhb4d8s1/50/

```js
let interruptBuffer = new Uint8Array(new SharedArrayBuffer(1));
pyodide.setInterruptBuffer(interruptBuffer);

// Run some async python code
const result = pyodide.runPythonAsync(`
  import asyncio
  
  # If an interrupt happens here, `result` never resolves.
  asyncio.sleep(10)
`);

//wait some amount of time, then call
interruptBuffer[0] = 2

await result;
console.log("This line is never run");
```

### Expected behavior

```python
asyncio.sleep(10)
```
Should throw a KeyboardInterrupt exception.

### Environment

- Pyodide Version: 0.19.0
- Browser version: 97.0.4692.99

### Additional context

Calling `checkInterrupt()` from JS periodically does not resolve the issue. It does throw the exception much earlier, but the result is the same.

The exception that is thrown is different though.

With `checkInterrupt()`:
```
Uncaught PythonError: Traceback (most recent call last):
  File \&quot;/lib/python3.9/site-packages/_pyodide/_base.py\&quot;, line 352, in eval_code
    def eval_code(
KeyboardInterrupt
```

Without `checkInterrupt()`:
```
pyodide.asm.js:14 Uncaught PythonError: Traceback (most recent call last):
  File "/lib/python3.9/site-packages/pyodide/webloop.py", line 148, in run_handle
    if h.cancelled():
  File "/lib/python3.9/asyncio/events.py", line 75, in cancelled
    def cancelled(self):
KeyboardInterrupt

    at new_error (pyodide.asm.js:14:247183)
    at pyodide.asm.wasm:0xe6eb0
    at pyodide.asm.wasm:0xe6fae
    at Object.Module._pythonexc2js (pyodide.asm.js:14:944230)
    at Object.Module.callPyObjectKwargs (pyproxy.gen.js:391:12)
    at Object.Module.callPyObject (pyproxy.gen.js:397:17)
    at wrapper (pyodide.asm.js:14:215278)
```

**Comment by hoodmane** [comment]
Thanks for the report! The jsfiddle doesn't work to reproduce this error because of `Uncaught ReferenceError: SharedArrayBuffer is not defined`. The security headers make it slightly annoying to do quick demos with `SharedArrayBuffer`. I think though you can get a working reproduction with no worker or `SharedArrayBuffer`:
```js
interruptBuffer = new Uint8Array(new ArrayBuffer(1));
pyodide.setInterruptBuffer(interruptBuffer);
// Run some async python code
result = pyodide.runPythonAsync(`
  import asyncio
  asyncio.sleep(5)
`).catch((e) => console.log("hi?"));

function sleep(s){
	return new Promise(res => setTimeout(res, s))
}
await sleep(50);

//wait some amount of time, then call
interruptBuffer[0] = 2;
```
The problem is that our event loop needs to be made keyboard interrupt aware: basically all that `asyncio.sleep` does is call:
```
    h = loop.call_later(delay,
                        futures._set_result_unless_cancelled,
                        future, result)
```
so it should be the event loop's responsibility to notice and cancel stuff if a keyboard interrupt occurs. I'm not really sure what this code should look like -- the logic to handle it in normal Python is quite different because somewhere there must be a blocking call to `loop.run_until_complete()` or something, and the `KeyboardInterrupt` can be caught there. Here, what happens is that nobody is looking for the keyboard interrupt, so the error flag is left set for the whole 10 seconds that you are sleeping for and then whatever next command is executed notices the error and raises it.

I think what needs to happen is this:
1. If a `KeyboardInterrupt` interrupts synchronous execution, record a second event loop interrupt flag
2. The event loop should keep track of a list of ongoing tasks. It also checks error flag for a `KeyboardInterrupt` in a loop and event loop interrupt flag in a async loop, and if it finds either of these set, then it cancels all ongoing tasks, then clears both flags.

**Comment by brendan0powers** [comment]
Ah, I forgot I had Chrome running with the enable SharedArrayBuffer's flag. I think I get what you mean by #⁠2, but I'm not sure what you mean by #⁠1.

**Comment by hoodmane** [comment]
> I had Chrome running with the enable SharedArrayBuffer's flag

I don't see that flag on chrome 96. Sounds convenient. It isn't *that* hard to set up a server to add the appropriate headers, but it is an extra step.

**Comment by hoodmane** [comment]
> I'm not sure what you mean by #⁠1.

Well the interaction between blocking and nonblocking calls is a bit complicated. 
Consider what should happen in the following cases:

### Case 1
```js
pyodide.runPythonAsync(`
	await asyncio.sleep(3);
	print("a")
`);
```
With a keyboard interrupt after 2 seconds, it should print nothing.

### Case 2
```js
pyodide.runPythonAsync(`
	await asyncio.sleep(1);
	print("a")
`);
pyodide.runPython(`
	time.sleep(3);
	print("b")
`);
```
With a keyboard interrupt after 2 seconds it should print nothing?

### Case 3
```js
pyodide.runPythonAsync(`
	await asyncio.sleep(1);
	print("a")
`);
pyodide.runPython(`
	time.sleep(3);
	print("b")
`);
pyodide.runPython(`
	time.sleep(3);
	print("c")
`);
```
With a keyboard interrupt after 2 seconds, it should print just "c"?

**Comment by hoodmane** [comment]
Another question is what about asynchronous background tasks that we don't want interrupted ever. Perhaps we could add a `noInterrupt` flag to `runPythonAsync` that marks an async task as uninterruptible.

**Comment by brendan0powers** [comment]
I was able to test #2142, and it seems to work for my use case (Implementing the stop button in JupyterLite).

**Comment by hoodmane** [comment]
Thanks for testing it @brendan0powers! What do you think the interface for a task to opt in/out of interruption should look like?

Problem is that #2142 has a memory leak that I am having trouble hunting down -- the promise `onFulfilled` and `onRejected` handles are not freed correctly.

**Comment by hoodmane** [comment]
Okay I think I fixed the memory leak:
[https://github.com/pyodide/pyodide/pull/2142/commits/27efc9c3bd1eda284db78efb8818a92d0fc6cef0](https://github.com/pyodide/pyodide/pull/2142/commits/27efc9c3bd1eda284db78efb8818a92d0fc6cef0)

I'm a bit confused though because `run_handle` is getting deallocated -- I am logging that it has refcount 1 just before a decref -- so I would think that its local variables would get cleaned up too, so I don't understand why clearing the local variable `h` fixes the leak. But it works so *shrug*.

**Comment by brendan0powers** [comment]
> Thanks for testing it @brendan0powers! What do you think the interface for a task to opt-in/out of interruption should look like?

Good question. I suspect the primary use case for this would be in a REPL (or notebook). I don't think it's reasonable for the user of that REPL to opt-in, since they probably won't understand the details. So, perhaps a global enable flag, and some way to gracefully handle interrupts in "background" tasks?

For example, in my use case, I have a jupyter notebook, where a user may run an async function. I need the cell execution to end when a keyboard interrupt happens. I also have a background async task that polls some I/O for input, and I need to make sure that keeps running. I control the task though, so I could modify it to handle cancelations.

For example, if the awaiting function threw a keyboard exception, I could catch it, and re-run the polling loop. It gets tricky when you don't own the background thread. It might be in some 3rd party library.

**Comment by hoodmane** [comment]
Luckily I think most of the problems you are discussing are already solved pretty well by [context variables](https://www.python.org/dev/peps/pep-0567/).
In particular, context variables are hereditary and local to a task. So if you just said:
```py
with interrupts_enabled():
	await run_user_code()
```
then the user code itself and all tasks it spawns would run with interrupts enabled (unless they disable interrupts). Similarly, if for some reason you had globally enabled interrupts you could do:
```py
with interrupts_disabled():
	await run_background_task()
```
and then you don't need any cooperation from the background task, any other tasks that it spawns automatically run with interrupts disabled (unless they enable interrupts).

>  if the awaiting function threw a keyboard exception, I could catch it, and re-run the polling loop

Part of the reason I wrote it this way is that a lot of logic can't be safely aborted at some unknown step and rerun (say it made a network request -- not really desirable to double up on the request because we accidentally cancelled it in the middle). It's much better not to allow the logic to be interrupted in the first place.

**Comment by brendan0powers** [comment]
Both of those sounds like they'd work. In my case, I'd probably set a global enable flag (is this an option?), and then explicitly opt-out when launching the background task. We could wrap cell execution in an opt-in,  but in my case, the background task is launched from a cell, so the context would be inherited by the task.

**Comment by hoodmane** [comment]
> a global enable flag (is this an option?)

Yeah that will be possible
