### ISSUE TITLE
`make benchmark` fails

### ISSUE THREAD

**Issue by madhur-tandon** [pyodide/pyodide#2150]
## 🐛 Bug

Run `make benchmark` inside docker container on Intel Mac

The error received is:
```
Traceback (most recent call last):
  File "/src/benchmark/benchmark.py", line 178, in <module>
    results = main(Path(sys.argv[-2]).resolve())
  File "/src/benchmark/benchmark.py", line 148, in main
    selenium_backends[name] = cls(port)
  File "/src/conftest.py", line 123, in __init__
    self.load_pyodide()
  File "/src/conftest.py", line 150, in load_pyodide
    self.run_js(
  File "/src/conftest.py", line 250, in run_js
    return self.run_js_inner(code, check_code)
  File "/src/conftest.py", line 270, in run_js_inner
    raise JavascriptException(retval[1], retval[2])
conftest.JavascriptException: ReferenceError: assignment to undeclared variable newFn

updateGOT@http://127.0.0.1:39493/pyodide.asm.js:14:273680
relocateExports@http://127.0.0.1:39493/pyodide.asm.js:14:274113
receiveInstance@http://127.0.0.1:39493/pyodide.asm.js:14:203925
receiveInstantiatedSource@http://127.0.0.1:39493/pyodide.asm.js:14:204112
```

### Expected behavior

Benchmarks should appear.

### Additional context

Was calculating benchmarks for the blog that we have here: https://github.com/pyodide/pyodide-blog/pull/12 but it fails to run. I can push the code for the benchmarks that I have written in another PR

cc: @rth

**Comment by rth** [comment]
Can you check that running the benchmarks on main works for you (without the added code)? Yes maybe the easiest is to open a draft PR and see if they would be run in CI.

**Comment by madhur-tandon** [comment]
I face the same issue on `main` as well.
I ran `make` and `PYODIDE_PACKAGES="matplotlib" make` before running `make benchmark`
Draft PR here: https://github.com/pyodide/pyodide/pull/2151

**Comment by madhur-tandon** [comment]
Is there any update on this? I am running it inside the docker container. Idk why it fails :/

**Comment by madhur-tandon** [comment]
I ran `make clean` overall and inside `emsdk` and `cpython` too.
After which I ran `make` and `PYODIDE_PACKAGES="matplotlib" make`
Running `make benchmark` now gives me

```
Spawning webserver at http://127.0.0.1:47955 (see logs in /tmp/tmp9jwu67di/http-server.log)
Traceback (most recent call last):
  File "/src/benchmark/benchmark.py", line 151, in <module>
    results = main(Path(sys.argv[-2]).resolve())
  File "/src/benchmark/benchmark.py", line 124, in main
    selenium_backends[name].load_package("numpy")
  File "/src/conftest.py", line 331, in load_package
    self.run_js("await pyodide.loadPackage({!r})".format(packages))
  File "/src/conftest.py", line 250, in run_js
    return self.run_js_inner(code, check_code)
  File "/src/conftest.py", line 270, in run_js_inner
    raise JavascriptException(retval[1], retval[2])
conftest.JavascriptException: Error: No known package with name 'numpy'
```
