### ISSUE TITLE
`statsmodels` fails to build from source inside provided Docker container

### ISSUE THREAD

**Issue by ibdafna** [pyodide/pyodide#2157]
## 🐛 Bug

`statsmodels` fails to build in Docker container

### To Reproduce

Inside the pyodide directory, run:

```bash
./docker_run
PYODIDE_PACKAGES='statsmodels'
make
```

### Expected behavior

The package should build, but there is a checksum validation error:

```bash
Building the following packages: statsmodels
[1/1] (thread 1) building statsmodels
Error building statsmodels. Printing build logs.
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/src/pyodide-build/pyodide_build/__main__.py", line 62, in <module>
    main()
  File "/src/pyodide-build/pyodide_build/__main__.py", line 56, in main
    args.func(args)
  File "/src/pyodide-build/pyodide_build/buildpkg.py", line 862, in main
    build_package(
  File "/src/pyodide-build/pyodide_build/buildpkg.py", line 678, in build_package
    prepare_source(pkg_root, build_dir, srcpath, source_metadata)
  File "/src/pyodide-build/pyodide_build/buildpkg.py", line 254, in prepare_source
    download_and_extract(buildpath, srcpath, src_metadata)
  File "/src/pyodide-build/pyodide_build/buildpkg.py", line 206, in download_and_extract
    check_checksum(tarballpath, src_metadata)
  File "/src/pyodide-build/pyodide_build/buildpkg.py", line 155, in check_checksum
    raise ValueError("Invalid {} checksum".format(checksum_algorithm))
ValueError: Invalid sha256 checksum
[2022-02-08 02:59:02] Building package statsmodels...
[2022-02-08 02:59:15] Failed building package statsmodels in 12.9 seconds.
[1/1] (thread 1) failed statsmodels in 14.37 s
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/src/pyodide-build/pyodide_build/__main__.py", line 62, in <module>
    main()
  File "/src/pyodide-build/pyodide_build/__main__.py", line 56, in main
    args.func(args)
  File "/src/pyodide-build/pyodide_build/buildall.py", line 585, in main
    build_packages(packages_dir, outputdir, args)
  File "/src/pyodide-build/pyodide_build/buildall.py", line 478, in build_packages
    build_from_graph(pkg_map, outputdir, args)
  File "/src/pyodide-build/pyodide_build/buildall.py", line 397, in build_from_graph
    raise pkg
  File "/src/pyodide-build/pyodide_build/buildall.py", line 373, in builder
    pkg.build(outputdir, args)
  File "/src/pyodide-build/pyodide_build/buildall.py", line 141, in build
    p.check_returncode()
  File "/usr/local/lib/python3.9/subprocess.py", line 460, in check_returncode
    raise CalledProcessError(self.returncode, self.args, self.stdout,
subprocess.CalledProcessError: Command '['/usr/local/bin/python', '-m', 'pyodide_build', 'buildpkg', '/src/packages/statsmodels/meta.yaml', '--cflags', '-O2 -g0 -fPIC', '--cxxflags', '', '--ldflags', '-O2 -g0 -s MODULARIZE=1 -s LINKABLE=1 -s EXPORT_ALL=1 -s WASM=1 -std=c++14 -s LZ4=1 -L /src/cpython/installs/python-3.9.5/lib/  -s SIDE_MODULE=1', '--target-install-dir', '/src/cpython/installs/python-3.9.5', '--host-install-dir', '/src/packages/.artifacts', '--force-rebuild']' returned non-zero exit status 1.
make[1]: *** [Makefile:12: all] Error 1
make[1]: Leaving directory '/src/packages'
make: *** [Makefile:197: build/packages.json] Error 2
```

### Environment

I am building Pyodide from source, using commit `276d396fffd9bc9fa1453ce48d32ad42c5381756` using the default image provided by the `./run_docker` command.

### Additional context

I am upgrading [WebDash](https://github.com/ibdafna/webdash) to use the latest Pyodide and Plotly Dash versions for an upcoming release.

Many thanks!

**Comment by ibdafna** [comment]
Initial investigation:

The current SHA256 in the meta.yaml file for `statsmodels` is: https://github.com/pyodide/pyodide/blob/2005c9d231454493b9c140d926ab81e6fa35d018/packages/statsmodels/meta.yaml#L7

Running  `bash curl https://github.com/statsmodels/statsmodels/archive/refs/tags/v0.13.1.tar.gz | sha256sum` yields:

7e656205250cedec7f4638deef6267c3da6b998358b8fc94774a7ac11b32519e

So there is already a mismatch there. However, the checksum expected by `pyodide-build` in: https://github.com/pyodide/pyodide/blob/2005c9d231454493b9c140d926ab81e6fa35d018/pyodide-build/pyodide_build/buildpkg.py#L146

is 428a60ade157172dc53a9987b134acc721dc15dcdf26ffd93af128157c0f8055, which is neither of the two hashes above.

**Comment by ryanking13** [comment]
Thanks for the report, we had recently updated statsmodels' URL due to that issue (#2153).

**Comment by ibdafna** [comment]
Ah, silly me. I should have checked more thoroughly! Many thanks for the reply. I will close this now :)
