### ISSUE TITLE
Release 0.19.1

### ISSUE THREAD

**Issue by rth** [pyodide/pyodide#2163]
It's been 1 month since the release with a few bug fixes, I think it could be a good moment to make the 0.19.1 patch release with those.

I can look into it. Any particular commits you would like included there that are not already on the `stable` branch?

**Comment by hoodmane** [comment]
I think we got most of them but there might be one or two more, I'll double check. We should also fix the API docs tables.

**Comment by hoodmane** [comment]
Should also backport #2137 and possibly #2146 and #2153. We could also include #2165.

**Comment by rth** [comment]
Yes, also we would need all the docker CI fixes including https://github.com/pyodide/pyodide/pull/2168 (once it's merged).

**Comment by rth** [comment]
> Yes, also we would need all the docker CI fixes including https://github.com/pyodide/pyodide/pull/2168 (once it's merged).

No never mind, it's tried to Dockefile + browser version updates, and that's probably too big a change to include in a patch release.

**Comment by rth** [comment]
The release was done yesterday, however, there was an issue when deploying the pre-built docker image to GH packages (deployment to docker hub succeded) https://github.com/pyodide/pyodide/actions/runs/1882453624/attempts/1.
When re-run both failed. 

It's not clear what exactly failed in build,
```
2022-02-22T15:46:53.4320037Z #5 843.6 You should consider upgrading via the '/usr/local/bin/python3.9 -m pip install --upgrade pip' command.
2022-02-22T17:05:23.1975188Z #5 5553.3 Traceback (most recent call last):
2022-02-22T17:05:23.1975583Z #5 5553.3   File "/usr/local/lib/python3.9/runpy.py", line 197, in _run_module_as_main
2022-02-22T17:05:23.1975926Z #5 5553.3     return _run_code(code, main_globals, None,
2022-02-22T17:05:23.1976238Z #5 5553.3   File "/usr/local/lib/python3.9/runpy.py", line 87, in _run_code
2022-02-22T17:05:23.1976522Z #5 5553.3     exec(code, run_globals)
2022-02-22T17:05:23.1977213Z #5 5553.3   File "/src/pyodide/pyodide-build/pyodide_build/__main__.py", line 62, in <module>
2022-02-22T17:05:23.1977510Z #5 5553.3     main()
2022-02-22T17:05:23.1977924Z #5 5553.3   File "/src/pyodide/pyodide-build/pyodide_build/__main__.py", line 56, in main
2022-02-22T17:05:23.1978216Z #5 5553.3     args.func(args)
2022-02-22T17:05:23.1978670Z #5 5553.3   File "/src/pyodide/pyodide-build/pyodide_build/buildall.py", line 585, in main
2022-02-22T17:05:23.1979028Z #5 5553.3     build_packages(packages_dir, outputdir, args)
2022-02-22T17:05:23.1979523Z #5 5553.3   File "/src/pyodide/pyodide-build/pyodide_build/buildall.py", line 478, in build_packages
2022-02-22T17:05:23.1979892Z #5 5553.3     build_from_graph(pkg_map, outputdir, args)
2022-02-22T17:05:23.1980384Z #5 5553.3   File "/src/pyodide/pyodide-build/pyodide_build/buildall.py", line 397, in build_from_graph
2022-02-22T17:05:23.1980699Z #5 5553.3     raise pkg
2022-02-22T17:05:23.1981124Z #5 5553.3   File "/src/pyodide/pyodide-build/pyodide_build/buildall.py", line 373, in builder
2022-02-22T17:05:23.1981445Z #5 5553.3     pkg.build(outputdir, args)
2022-02-22T17:05:23.1981890Z #5 5553.3   File "/src/pyodide/pyodide-build/pyodide_build/buildall.py", line 141, in build
2022-02-22T17:05:23.1982202Z #5 5553.3     p.check_returncode()
2022-02-22T17:05:23.1982518Z #5 5553.3   File "/usr/local/lib/python3.9/subprocess.py", line 460, in check_returncode
2022-02-22T17:05:23.1982907Z #5 5553.3     raise CalledProcessError(self.returncode, self.args, self.stdout,
2022-02-22T17:05:23.1984423Z #5 5553.3 subprocess.CalledProcessError: Command '['/usr/local/bin/python', '-m', 'pyodide_build', 'buildpkg', '/src/pyodide/packages/matplotlib/meta.yaml', '--cflags', '-O2 -g0 -fPIC', '--cxxflags', '', '--ldflags', '-O2 -g0 -s MODULARIZE=1 -s LINKABLE=1 -s EXPORT_ALL=1 -s WASM=1 -std=c++14 -s LZ4=1 -L /src/pyodide/cpython/installs/python-3.9.5/lib/  -s SIDE_MODULE=1', '--target-install-dir', '/src/pyodide/cpython/installs/python-3.9.5', '--host-install-dir', '/src/pyodide/packages/.artifacts', '--force-rebuild']' returned non-zero exit status 1.
2022-02-22T17:05:23.2017311Z #5 5553.3 make[1]: *** [Makefile:12: all] Error 1
2022-02-22T17:05:23.2017612Z #5 5553.3 make: *** [Makefile:197: build/packages.json] Error 2
2022-02-22T17:05:23.7640719Z #5 ERROR: executor failed running [/bin/sh -c cd pyodide && PYODIDE_PACKAGES='*' make && rm -r ./build]: exit code: 2
2022-02-22T17:05:23.7641554Z ------
2022-02-22T17:05:23.7642100Z  > [3/3] RUN cd pyodide && PYODIDE_PACKAGES='*' make && rm -r ./build:
2022-02-22T17:05:23.7642402Z #5 5553.3     raise pkg
2022-02-22T17:05:23.7642877Z #5 5553.3   File "/src/pyodide/pyodide-build/pyodide_build/buildall.py", line 373, in builder
2022-02-22T17:05:23.7643267Z #5 5553.3     pkg.build(outputdir, args)
2022-02-22T17:05:23.7643792Z #5 5553.3   File "/src/pyodide/pyodide-build/pyodide_build/buildall.py", line 141, in build
2022-02-22T17:05:23.7644171Z #5 5553.3     p.check_returncode()
2022-02-22T17:05:23.7644530Z #5 5553.3   File "/usr/local/lib/python3.9/subprocess.py", line 460, in check_returncode
2022-02-22T17:05:23.7644954Z #5 5553.3     raise CalledProcessError(self.returncode, self.args, self.stdout,
2022-02-22T17:05:23.7646838Z #5 5553.3 subprocess.CalledProcessError: Command '['/usr/local/bin/python', '-m', 'pyodide_build', 'buildpkg', '/src/pyodide/packages/matplotlib/meta.yaml', '--cflags', '-O2 -g0 -fPIC', '--cxxflags', '', '--ldflags', '-O2 -g0 -s MODULARIZE=1 -s LINKABLE=1 -s EXPORT_ALL=1 -s WASM=1 -std=c++14 -s LZ4=1 -L /src/pyodide/cpython/installs/python-3.9.5/lib/  -s SIDE_MODULE=1', '--target-install-dir', '/src/pyodide/cpython/installs/python-3.9.5', '--host-install-dir', '/src/pyodide/packages/.artifacts', '--force-rebuild']' returned non-zero exit status 1.
```
I'm not sure why we are not seeing the traceback from `pyodide_build buildpkg`, maybe there is an issue with stderr redirection?

Note that this used Docker images, before latest browser related updates by @ryanking13

**Comment by ryanking13** [comment]
> I'm not sure why we are not seeing the traceback from `pyodide_build buildpkg`, maybe there is an issue with stderr redirection?

Maybe the log is clipped due to the docker buildkit log size limit? [I see the message "[output clipped, log limit 1MiB reached]"](https://github.com/pyodide/pyodide/runs/5290549880?check_suite_focus=true#step:5:10163)

**Comment by rth** [comment]
Yes, there is also some rendering issue in the UI. You can click on the wheel on the right to see raw logs 
![image](https://user-images.githubusercontent.com/630936/155311430-941f0ff2-c7b9-4d33-84c0-fa75e406f95a.png)
