### ISSUE TITLE
No way to run asynchronous tests in pytest 

### ISSUE THREAD

**Issue by Kodiologist** [pyodide/pyodide#2221]
## 🐛 Bug

If a pytest test uses `async` stuff, there's no apparent way to run the test properly. If the test function is defined to be synchronous and calls `asyncio.run()` internally, it raises `RuntimeError: asyncio.run() cannot be called from a running event loop`. On the other hand, if the test function is defined with `async def` and you use the PyPI package `pytest-async`, an error is raised by an unimplemented `close` method in Pyodide. Either of these approaches works in native CPython.

### To Reproduce

This shell script sets up an example with `pytest-async`. It's about as minimal as I can get it. If there's a shorter way to do this kind of thing, let me know.

<details><summary>example.sh</summary>

```
#!/bin/bash

mkdir -p project
mkdir -p project/tests

echo >project/pyproject.toml \
'[tool.pytest.ini_options]
asyncio_mode = "auto"'

echo >project/tests/test_foo.py \
'def test_sync(): assert 1 == 1
async def test_async(): assert 2 == 2'

rm -f project.tar
tar cf project.tar project

echo >page.html \
'<!DOCTYPE html>
<meta charset="utf-8"/>
<script src="https://cdn.jsdelivr.net/pyodide/v0.19.1/full/pyodide.js"></script>
<title>x</title>
<script>
async function main()
   {let pyodide = await loadPyodide(
       {indexURL: "https://cdn.jsdelivr.net/pyodide/v0.19.1/full/"})
    await pyodide.loadPackage("micropip")
    await pyodide.runPythonAsync(`
        import micropip
        await micropip.install("toml")
        await micropip.install("pytest-asyncio")
        from pyodide.http import pyfetch
        await (await pyfetch("http://0.0.0.0:8000/project.tar")).unpack_archive()`)
    console.log(pyodide.runPython(`
        import os
        os.rename("project/tests", "tests")
        os.rename("project/pyproject.toml", "pyproject.toml")
        import pytest
        pytest.main(["--verbose", "--color=no"])`))}
main()
</script>'
```

</details>

Then say `python3 -m http.server --bind 127.0.0.1 --dir "$(pwd)"` and `"$BROWSER" http://0.0.0.0:8000/page.html`. The output in the browser console is:

<details><summary>Output</summary>

```
GEThttp://0.0.0.0:8000/favicon.ico
[HTTP/1.0 404 File not found 0ms]

Loading distutils load-pyodide.js:213:20
Loading distutils from https://cdn.jsdelivr.net/pyodide/v0.19.1/full/distutils.js load-pyodide.js:239:20
Loaded distutils load-pyodide.js:273:2
Python initialization complete pyodide.asm.js:14:295959
Loading micropip, pyparsing, packaging, distutils load-pyodide.js:213:20
Loading micropip from https://cdn.jsdelivr.net/pyodide/v0.19.1/full/micropip.js load-pyodide.js:239:20
Loading pyparsing from https://cdn.jsdelivr.net/pyodide/v0.19.1/full/pyparsing.js load-pyodide.js:239:20
Loading packaging from https://cdn.jsdelivr.net/pyodide/v0.19.1/full/packaging.js load-pyodide.js:239:20
distutils already loaded from default channel load-pyodide.js:226:24
Loaded micropip, pyparsing, packaging, distutils load-pyodide.js:273:2
Loading pytest, atomicwrites, attrs, six, more-itertools, pluggy, py, setuptools, distutils, pyparsing, iniconfig load-pyodide.js:213:20
Loading pytest from https://cdn.jsdelivr.net/pyodide/v0.19.1/full/pytest.js load-pyodide.js:239:20
Loading atomicwrites from https://cdn.jsdelivr.net/pyodide/v0.19.1/full/atomicwrites.js load-pyodide.js:239:20
Loading attrs from https://cdn.jsdelivr.net/pyodide/v0.19.1/full/attrs.js load-pyodide.js:239:20
Loading six from https://cdn.jsdelivr.net/pyodide/v0.19.1/full/six.js load-pyodide.js:239:20
Loading more-itertools from https://cdn.jsdelivr.net/pyodide/v0.19.1/full/more-itertools.js load-pyodide.js:239:20
Loading pluggy from https://cdn.jsdelivr.net/pyodide/v0.19.1/full/pluggy.js load-pyodide.js:239:20
Loading py from https://cdn.jsdelivr.net/pyodide/v0.19.1/full/py.js load-pyodide.js:239:20
Loading setuptools from https://cdn.jsdelivr.net/pyodide/v0.19.1/full/setuptools.js load-pyodide.js:239:20
distutils already loaded from default channel load-pyodide.js:226:24
pyparsing already loaded from default channel load-pyodide.js:226:24
Loading iniconfig from https://cdn.jsdelivr.net/pyodide/v0.19.1/full/iniconfig.js load-pyodide.js:239:20
Loaded pytest, atomicwrites, attrs, six, more-itertools, pluggy, py, setuptools, distutils, pyparsing, iniconfig load-pyodide.js:273:2
============================= test session starts ============================== pyodide.asm.js:14:295959
platform emscripten -- Python 3.9.5, pytest-6.2.5, py-1.9.0, pluggy-1.0.0 -- pyodide.asm.js:14:295959
cachedir: .pytest_cache pyodide.asm.js:14:295959
rootdir: /home/pyodide, configfile: pyproject.toml pyodide.asm.js:14:295959
plugins: asyncio-0.18.1 pyodide.asm.js:14:295959
asyncio: mode=auto pyodide.asm.js:14:295959
collecting ... pyodide.asm.js:14:296104

collected 2 items                                                              pyodide.asm.js:14:295959
<empty string> pyodide.asm.js:14:295959
tests/test_foo.py::test_sync pyodide.asm.js:14:296104
PASSED                                      [ 50%] pyodide.asm.js:14:296104
<empty string> pyodide.asm.js:14:295959
tests/test_foo.py::test_async pyodide.asm.js:14:296104
PASSED                                     [100%] pyodide.asm.js:14:296104
<empty string> pyodide.asm.js:14:295959
tests/test_foo.py::test_async ERROR                                      [100%] pyodide.asm.js:14:295959
<empty string> pyodide.asm.js:14:295959
==================================== ERRORS ==================================== pyodide.asm.js:14:295959
_______________________ ERROR at teardown of test_async ________________________ pyodide.asm.js:14:295959
<empty string> pyodide.asm.js:14:295959
self = <FixtureDef argname='event_loop' scope='function' baseid=''> pyodide.asm.js:14:295959
request = <SubRequest 'event_loop' for <Function test_async>> pyodide.asm.js:14:295959
<empty string> pyodide.asm.js:14:295959
    def finish(self, request: SubRequest) -> None: pyodide.asm.js:14:295959
        exc = None pyodide.asm.js:14:295959
        try: pyodide.asm.js:14:295959
            while self._finalizers: pyodide.asm.js:14:295959
                try: pyodide.asm.js:14:295959
                    func = self._finalizers.pop() pyodide.asm.js:14:295959
                    func() pyodide.asm.js:14:295959
                except BaseException as e: pyodide.asm.js:14:295959
                    # XXX Only first exception will be seen by user, pyodide.asm.js:14:295959
                    #     ideally all should be reported. pyodide.asm.js:14:295959
                    if exc is None: pyodide.asm.js:14:295959
                        exc = e pyodide.asm.js:14:295959
            if exc: pyodide.asm.js:14:295959
>               raise exc pyodide.asm.js:14:295959
<empty string> pyodide.asm.js:14:295959
/lib/python3.9/site-packages/_pytest/fixtures.py:1034: pyodide.asm.js:14:295959
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ pyodide.asm.js:14:295959
<empty string> pyodide.asm.js:14:295959
self = <FixtureDef argname='event_loop' scope='function' baseid=''> pyodide.asm.js:14:295959
request = <SubRequest 'event_loop' for <Function test_async>> pyodide.asm.js:14:295959
<empty string> pyodide.asm.js:14:295959
    def finish(self, request: SubRequest) -> None: pyodide.asm.js:14:295959
        exc = None pyodide.asm.js:14:295959
        try: pyodide.asm.js:14:295959
            while self._finalizers: pyodide.asm.js:14:295959
                try: pyodide.asm.js:14:295959
                    func = self._finalizers.pop() pyodide.asm.js:14:295959
>                   func() pyodide.asm.js:14:295959
<empty string> pyodide.asm.js:14:295959
/lib/python3.9/site-packages/_pytest/fixtures.py:1027: pyodide.asm.js:14:295959
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ pyodide.asm.js:14:295959
<empty string> pyodide.asm.js:14:295959
fixturefunc = <function event_loop at 0x14c74b0> pyodide.asm.js:14:295959
it = <generator object event_loop at 0x1539ce8> pyodide.asm.js:14:295959
<empty string> pyodide.asm.js:14:295959
    def _teardown_yield_fixture(fixturefunc, it) -> None: pyodide.asm.js:14:295959
        """Execute the teardown of a fixture function by advancing the iterator pyodide.asm.js:14:295959
        after the yield and ensure the iteration ends (if not it means there is pyodide.asm.js:14:295959
        more than one yield in the function).""" pyodide.asm.js:14:295959
        try: pyodide.asm.js:14:295959
>           next(it) pyodide.asm.js:14:295959
<empty string> pyodide.asm.js:14:295959
/lib/python3.9/site-packages/_pytest/fixtures.py:941: pyodide.asm.js:14:295959
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ pyodide.asm.js:14:295959
<empty string> pyodide.asm.js:14:295959
request = <SubRequest 'event_loop' for <Function test_async>> pyodide.asm.js:14:295959
<empty string> pyodide.asm.js:14:295959
    @pytest.fixture pyodide.asm.js:14:295959
    def event_loop(request: "pytest.FixtureRequest") -> Iterator[asyncio.AbstractEventLoop]: pyodide.asm.js:14:295959
        """Create an instance of the default event loop for each test case.""" pyodide.asm.js:14:295959
        loop = asyncio.get_event_loop_policy().new_event_loop() pyodide.asm.js:14:295959
        yield loop pyodide.asm.js:14:295959
>       loop.close() pyodide.asm.js:14:295959
<empty string> pyodide.asm.js:14:295959
/lib/python3.9/site-packages/pytest_asyncio/plugin.py:484: pyodide.asm.js:14:295959
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ pyodide.asm.js:14:295959
<empty string> pyodide.asm.js:14:295959
self = <pyodide.webloop.WebLoop object at 0xfdbab8> pyodide.asm.js:14:295959
<empty string> pyodide.asm.js:14:295959
    def close(self): pyodide.asm.js:14:295959
        """Close the loop. pyodide.asm.js:14:295959
    pyodide.asm.js:14:295959
        The loop should not be running. pyodide.asm.js:14:295959
    pyodide.asm.js:14:295959
        This is idempotent and irreversible. pyodide.asm.js:14:295959
    pyodide.asm.js:14:295959
        No other methods should be called after this one. pyodide.asm.js:14:295959
        """ pyodide.asm.js:14:295959
>       raise NotImplementedError pyodide.asm.js:14:295959
E       NotImplementedError pyodide.asm.js:14:295959
<empty string> pyodide.asm.js:14:295959
/lib/python3.9/asyncio/events.py:245: NotImplementedError pyodide.asm.js:14:295959
<empty string> pyodide.asm.js:14:295959
During handling of the above exception, another exception occurred: pyodide.asm.js:14:295959
<empty string> pyodide.asm.js:14:295959
fixturedef = <FixtureDef argname='event_loop' scope='function' baseid=''> pyodide.asm.js:14:295959
request = <SubRequest 'event_loop' for <Function test_async>> pyodide.asm.js:14:295959
<empty string> pyodide.asm.js:14:295959
    @pytest.hookimpl(trylast=True) pyodide.asm.js:14:295959
    def pytest_fixture_post_finalizer(fixturedef: FixtureDef, request: SubRequest) -> None: pyodide.asm.js:14:295959
        """Called after fixture teardown""" pyodide.asm.js:14:295959
        if fixturedef.argname == "event_loop": pyodide.asm.js:14:295959
            policy = asyncio.get_event_loop_policy() pyodide.asm.js:14:295959
            try: pyodide.asm.js:14:295959
                loop = policy.get_event_loop() pyodide.asm.js:14:295959
            except RuntimeError: pyodide.asm.js:14:295959
                loop = None pyodide.asm.js:14:295959
            if loop is not None: pyodide.asm.js:14:295959
                # Clean up existing loop to avoid ResourceWarnings pyodide.asm.js:14:295959
>               loop.close() pyodide.asm.js:14:295959
<empty string> pyodide.asm.js:14:295959
/lib/python3.9/site-packages/pytest_asyncio/plugin.py:357: pyodide.asm.js:14:295959
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ pyodide.asm.js:14:295959
<empty string> pyodide.asm.js:14:295959
self = <pyodide.webloop.WebLoop object at 0xfdbab8> pyodide.asm.js:14:295959
<empty string> pyodide.asm.js:14:295959
    def close(self): pyodide.asm.js:14:295959
        """Close the loop. pyodide.asm.js:14:295959
    pyodide.asm.js:14:295959
        The loop should not be running. pyodide.asm.js:14:295959
    pyodide.asm.js:14:295959
        This is idempotent and irreversible. pyodide.asm.js:14:295959
    pyodide.asm.js:14:295959
        No other methods should be called after this one. pyodide.asm.js:14:295959
        """ pyodide.asm.js:14:295959
>       raise NotImplementedError pyodide.asm.js:14:295959
E       NotImplementedError pyodide.asm.js:14:295959
<empty string> pyodide.asm.js:14:295959
/lib/python3.9/asyncio/events.py:245: NotImplementedError pyodide.asm.js:14:295959
=========================== short test summary info ============================ pyodide.asm.js:14:295959
ERROR tests/test_foo.py::test_async - NotImplementedError pyodide.asm.js:14:295959
========================== 2 passed, 1 error in 0.87s ========================== pyodide.asm.js:14:295959
1 page.html:15:13
```

</details>

### Environment

- Pyodide 0.19.1
- Firefox 97

**Comment by hoodmane** [comment]
Thanks for the report! What happens if you monkey patch the `close` function into a no op?

**Comment by Kodiologist** [comment]
Good question. That makes my example appear to work, although I haven't tried it with less trivial examples.

**Comment by hoodmane** [comment]
Well this seems like it could be a simple fix. It doesn't really make sense to create a new event loop or to close an event loop or anything because each browser thread comes with an event loop and we can schedule tasks on it but we have no power to close it without e.g. killing the webworker it is running in. I somewhat arbitrarily decided whether these methods would raise not implemented errors or do nothing, if more code can work with a close method that does nothing then probably we should change it. The question is whether there is any code that silently would do something weird in this case.

**Comment by simonegiacomelli** [comment]
An updated with Pyodide v0.26.2; 
The close error is gone and it looks like the async tests are run **but they always succeed**. 
I updated the shell script of @Kodiologist to reproduces the behaviour.
The async test has a `assert 1 == 2` that should fail

```
#!/bin/bash

mkdir -p project
mkdir -p project/tests

echo >project/pyproject.toml \
'[tool.pytest.ini_options]
asyncio_mode = "auto"'

echo >project/tests/test_foo.py \
'import pytest

def test_sync(): assert 2 == 2
@pytest.mark.asyncio
async def test_async(): assert 1 == 2'

rm -f project.tar
tar cf project.tar project

echo >page.html \
'<!DOCTYPE html>
<meta charset="utf-8"/>
<script src="https://cdn.jsdelivr.net/pyodide/v0.26.2/full/pyodide.js"></script>
<title>x</title>
<script>
async function main()
   {let pyodide = await loadPyodide(
       {indexURL: "https://cdn.jsdelivr.net/pyodide/v0.26.2/full/"})
    await pyodide.loadPackage("micropip")
    await pyodide.runPythonAsync(`
        import micropip
        await micropip.install("toml")
        await micropip.install("pytest-asyncio")
        from pyodide.http import pyfetch
        await (await pyfetch("http://0.0.0.0:8000/project.tar")).unpack_archive()`)
    console.log(pyodide.runPython(`
        import os
        os.rename("project/tests", "tests")
        os.rename("project/pyproject.toml", "pyproject.toml")
        import pytest
        pytest.main(["--verbose", "--color=no"])`))}
main()
</script>'
```

Output:
```
Loading micropip, packaging
pyodide.asm.js:10 Loaded micropip, packaging
pyodide.asm.js:10 Loading atomicwrites, attrs, exceptiongroup, iniconfig, more-itertools, pluggy, py, pyparsing, pytest, pytest-asyncio, setuptools, six
pyodide.asm.js:10 Loaded atomicwrites, attrs, exceptiongroup, iniconfig, more-itertools, pluggy, py, pyparsing, pytest, pytest-asyncio, setuptools, six
pyodide.asm.js:10 ============================= test session starts ==============================
pyodide.asm.js:10 platform emscripten -- Python 3.12.1, pytest-8.1.1, pluggy-1.5.0 -- /home/pyodide/this.program
pyodide.asm.js:10 cachedir: .pytest_cache
pyodide.asm.js:10 rootdir: /home/pyodide
pyodide.asm.js:10 configfile: pyproject.toml
pyodide.asm.js:10 plugins: asyncio-0.23.7
pyodide.asm.js:10 asyncio: mode=Mode.AUTO
pyodide.asm.js:10 collecting ... 
pyodide.asm.js:10 collected 2 items
pyodide.asm.js:10 
pyodide.asm.js:10 tests/test_foo.py::test_sync 
pyodide.asm.js:10 PASSED                                      [ 50%]
pyodide.asm.js:10 
pyodide.asm.js:10 tests/test_foo.py::test_async 
pyodide.asm.js:10 PASSED                                     [100%]
pyodide.asm.js:10 
pyodide.asm.js:10 
pyodide.asm.js:10 =============================== warnings summary ===============================
pyodide.asm.js:10 tests/test_foo.py::test_async
pyodide.asm.js:10   /lib/python3.12/site-packages/pytest_asyncio/plugin.py:814: DeprecationWarning: pytest-asyncio detected an unclosed event loop when tearing down the event_loop
pyodide.asm.js:10   fixture: <pyodide.webloop.WebLoop object at 0x1952c30>
pyodide.asm.js:10   pytest-asyncio will close the event loop for you, but future versions of the
pyodide.asm.js:10   library will no longer do so. In order to ensure compatibility with future
pyodide.asm.js:10   versions, please make sure that:
pyodide.asm.js:10       1. Any custom "event_loop" fixture properly closes the loop after yielding it
pyodide.asm.js:10       2. The scopes of your custom "event_loop" fixtures do not overlap
pyodide.asm.js:10       3. Your code does not modify the event loop in async fixtures or tests
pyodide.asm.js:10   
pyodide.asm.js:10     warnings.warn(
pyodide.asm.js:10 
pyodide.asm.js:10 -- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
pyodide.asm.js:10 ========================= 2 passed, 1 warning in 0.04s =========================
page.html:16 0
```

**Comment by hoodmane** [comment]
If you use the following it works:
```sh
#!/bin/bash

mkdir -p project
mkdir -p project/tests

echo >project/pyproject.toml \
'[tool.pytest.ini_options]
asyncio_mode = "auto"'

echo >project/tests/test_foo.py \
'import pytest

def test_sync():
    assert 2 == 2

@pytest.mark.asyncio
async def test_async():
    assert 1 == 2'

rm -f project.tar
tar cf project.tar project

npm i pyodide

echo >test.mjs \
'import { loadPyodide } from "pyodide";
import { readFileSync } from "fs";

let pyodide = await loadPyodide({ enableRunUntilComplete: true });
await pyodide.loadPackage("micropip");
const res = readFileSync("project.tar");
pyodide.FS.writeFile("/project.tar", res);
pyodide.runPython(`
  import shutil
  from js.process import stdout
  import os
  def get_terminal_size(fallback=(80, 24)):
    columns = getattr(stdout, "columns", None)
    rows = getattr(stdout, "rows", None)
    if columns is None:
      columns = fallback[0]
    if rows is None:
      rows = fallback[1]
    return os.terminal_size((columns, rows))
  shutil.get_terminal_size = get_terminal_size
`);

await pyodide.runPythonAsync(`
  import micropip
  await micropip.install(["pytest-asyncio"])
  import shutil
  shutil.unpack_archive("/project.tar")
`);
pyodide.runPythonAsync(`
  import pytest
  pytest.main(["--verbose", "project/"])
`);'

node --experimental-wasm-stack-switching test.mjs
```

Output:

![image](https://github.com/user-attachments/assets/8c3a6f49-3aa0-4ccb-ae28-2752e60ca149)

**Comment by simonegiacomelli** [comment]
After reading your comment I landed on this post authored by you https://blog.pyodide.org/posts/0.26-release/#improvements-to-stack-switching-support
Can't wait to see stack switching generally available! 😍

**Comment by hoodmane** [comment]
> Can't wait to see stack switching generally available! 😍

Yeah me too.

**Comment by hoodmane** [comment]
It should soon be possible to use requests / urllib3 to do this too:
https://github.com/urllib3/urllib3/pull/3427

**Comment by agriyakhetarpal** [comment]
I guess this is done now, following #5681, so we can close it.

**Comment by juntyr** [comment]
I'm still experiencing the same issue with Pyodide 0.29.0 when trying to run tests with pytest-asyncio in CI using pyodide venv. Even though my test function is `async` and marked with `@pytest.mark.asyncio`, I end up with

```
_____________________________ test_zarr_pointwise ______________________________

self = <Coroutine test_zarr_pointwise>

    def runtest(self) -> None:
        runner_fixture_id = f"_{self._loop_scope}_scoped_runner"
        runner = self._request.getfixturevalue(runner_fixture_id)
        context = contextvars.copy_context()
        synchronized_obj = _synchronize_coroutine(
            getattr(*self._synchronization_target_attr), runner, context
        )
        with MonkeyPatch.context() as c:
            c.setattr(*self._synchronization_target_attr, synchronized_obj)
>           super().runtest()

.venv-pyodide/lib/python3.13/site-packages/pytest_asyncio/plugin.py:469: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
.venv-pyodide/lib/python3.13/site-packages/pytest_asyncio/plugin.py:716: in inner
    runner.run(coro, context=context)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <asyncio.runners.Runner object at 0x6fb3670>
coro = <coroutine object test_zarr_pointwise at 0x65136b8>

    def run(self, coro, *, context=None):
        """Run a coroutine inside the embedded event loop."""
        if not coroutines.iscoroutine(coro):
            raise ValueError("a coroutine was expected, got {!r}".format(coro))
    
        if events._get_running_loop() is not None:
            # fail fast with short traceback
>           raise RuntimeError(
                "Runner.run() cannot be called from a running event loop")
E           RuntimeError: Runner.run() cannot be called from a running event loop

/lib/python313.zip/asyncio/runners.py:93: RuntimeError
```

**Comment by ryanking13** [comment]
@juntyr Could you please share us the minimal code for the reproduction?

**Comment by juntyr** [comment]
The issue persists with Pyodide 0.29.2.

My test is here

https://github.com/juntyr/compression-safeguards/blob/99591596bcae6547d2ca349c8128ae277329b228/tests/test_accidental_chunking.py#L92-L121

Though, since we're failing just with creating an asynchronous test, I think that anything would fail, e.g.

```python
import pytest

async def foo():
    print("hi")

@pytest.mark.asyncio
async def test_async():
    await foo()
```

In CI, I'm setting up Pyodide as follows:

https://github.com/juntyr/compression-safeguards/blob/99591596bcae6547d2ca349c8128ae277329b228/.github/workflows/ci.yml#L436-L445

https://github.com/juntyr/compression-safeguards/blob/99591596bcae6547d2ca349c8128ae277329b228/.github/workflows/ci.yml#L459-L469

(you can ignore the install from dist, I just also need to build some custom Pyodide wheels in CI and install them in the Pyodide venv)

Importantly, my `test` dependency group contains

https://github.com/juntyr/compression-safeguards/blob/99591596bcae6547d2ca349c8128ae277329b228/pyproject.toml#L94-L95

Finally, I run the tests with

https://github.com/juntyr/compression-safeguards/blob/99591596bcae6547d2ca349c8128ae277329b228/.github/workflows/ci.yml#L471-L474
