### ISSUE TITLE
Cannot import AMD modules after loading pyodide

### ISSUE THREAD

**Issue by yuccai** [pyodide/pyodide#2282]
## 🐛 Bug
After loading `pyodide`, AMD modules cannot be loaded with `requirejs`.

### To Reproduce
Create 3 files according to this layout (or unzip attached archives)
```
- demo/
   - moduleA.js
   - moduleB.js
   - index.html
```

  - Define two basic similar AMD modules :
    - `moduleA.js` :
        ```javascript
      define(() => function moduleA() {
          console.log("Module A execution");
      });
        ```
     - `moduleB.js`   
          ```javascript
        define(() => function moduleB() {
            console.log("Module B execution");
        });
          ```
  - Create simple `index.html` that load `pyodide` then `requirejs` scripts. Then we load `moduleA` (works fine), load `pyodide` (works fine) and finally load `moduleB` (error) :
  ```html
  <!DOCTYPE html>
  <html>
    <head>
      <script src="https://cdn.jsdelivr.net/pyodide/v0.19.1/full/pyodide.js"></script>
      <script src="https://requirejs.org/docs/release/2.3.6/minified/require.js"></script>
    </head>
    <body>
      <script type="text/javascript">
  
        async function loadAMDModule(url) {
          return new Promise(resolve => {
            requirejs([url], module => resolve(module));
          });
        }
  
        async function main(){
          const moduleA = await loadAMDModule("./moduleA");
          moduleA();
  
          const pyodide = await loadPyodide({
            indexURL : "https://cdn.jsdelivr.net/pyodide/v0.19.1/full/"
          });
  
          const moduleB = await loadAMDModule("./moduleB");
          moduleB();
        }
        main();
      </script>
    </body>
  </html>
```
Then run `python -m http.server -d demo`

Here is the error :
```
require.js:5 Uncaught (in promise) Error: Mismatched anonymous define() module: function() { return _createPyodideModule; }
https://requirejs.org/docs/errors.html#mismatch
    at makeError (require.js:5:1795)
    at T (require.js:5:8677)
    at Object.s [as require] (require.js:5:15042)
    at requirejs (require.js:5:2335)
    at index.html:12:11
    at new Promise (<anonymous>)
    at loadAMDModule (index.html:11:16)
    at main (index.html:24:31)
```
If we dont' execute the `loadPyodide` function, `moduleA` and `moduleB` are correctly loaded.

Furthermore, we cannot load `requirejs` before `pyodide` : 
doing this :
```html
   <head>
      <script src="https://requirejs.org/docs/release/2.3.6/minified/require.js"></script>
      <script src="https://cdn.jsdelivr.net/pyodide/v0.19.1/full/pyodide.js"></script>
  </head>
```
instead of this :
```html
   <head>
      <script src="https://cdn.jsdelivr.net/pyodide/v0.19.1/full/pyodide.js"></script>
      <script src="https://requirejs.org/docs/release/2.3.6/minified/require.js"></script>
  </head>
```
Here is the error :
```
Uncaught (in promise) Error: Mismatched anonymous define() module: function(exports){"use strict";let Module={};function setStandardStreams(stdin,stdout,stderr){stdout&&(Module.print=stdout),stderr&&(Module.printErr=stderr),stdin&&Module.preRun.push((function(){Module.FS.init(function(stdin){const encoder=new TextEncoder;let input=new Uint8Array(0),inputIndex=-1;function stdinWrapper(){try{if(-1===inputIndex){let text=stdin();if(null==text)return null;if("string"!=typeof text)throw new TypeError(`Expected stdin to return string, null, or undefined, got type ${typeof text}.`);text.endsWith("\n")||(text+="\n"),input=encoder.encode(text),inputIndex=0}if(inputIndex<input.length){let character=input[inputIndex];return inputIndex++,character}return inputIndex=-1,null}catch(e){throw console.error("Error thrown in stdin:"),console.error(e),e}}return stdinWrapper}(stdin),null,null)}))}Module.noImageDecoding=!0,Module.noAudioDecoding=!0,Module.noWasmDecoding=!1,Module.preloadedWasm={},Module.preRun=[];const IN_NODE="undefined"!=typeof process&&process.release&&"node"===process.release.name&&void 0===process.browser;let baseURL;const package_uri_regexp=/^.*?([^\/]*)\.js$/;function _uri_to_package_name(package_uri){let match=package_uri_regexp.exec(package_uri);if(match)return match[1].toLowerCase()}let loadScript;if(globalThis.document)loadScript=async url=>await import(url);else if(globalThis.importScripts)loadScript=async url=>{globalThis.importScripts(url)};else{if(!IN_NODE)throw new Error("Cannot determine runtime environment");{const pathPromise=import("path").then((M=>M.default)),fetchPromise=import("node-fetch").then((M=>M.default)),vmPromise=import("vm").then((M=>M.default));loadScript=async url=>{if(url.includes("://")){const fetch=await fetchPromise;(await vmPromise).runInThisContext(await(await fetch(url)).text())}else{const path=await pathPromise;await import(path.resolve(url))}}}}function addPackageToLoad(name,toLoad){if(name=name.toLowerCase(),!toLoad.has(name)&&(toLoad.set(name,"default channel"),void 0===loadedPackages[name]))for(let dep_name of Module.packages[name].depends)addPackageToLoad(dep_name,toLoad)}function recursiveDependencies(names,_messageCallback,errorCallback,sharedLibsOnly){const toLoad=new Map;for(let name of names){const pkgname=_uri_to_package_name(name);toLoad.has(pkgname)&&toLoad.get(pkgname)!==name?errorCallback(`Loading same package ${pkgname} from ${name} and ${toLoad.get(pkgname)}`):void 0===pkgname?(name=name.toLowerCase(),name in Module.packages?addPackageToLoad(name,toLoad):errorCallback(`Skipping unknown package '${name}'`)):toLoad.set(pkgname,name)}if(sharedLibsOnly){let onlySharedLibs=new Map;for(let c of toLoad){let name=c[0];Module.packages[name].shared_library&&onlySharedLibs.set(name,toLoad.get(name))}return onlySharedLibs}return toLoad}function waitRunDependency(){const promise=new Promise((r=>{Module.monitorRunDependencies=n=>{0===n&&r()}}));return Module.addRunDependency("dummy"),Module.removeRunDependency("dummy"),promise}async function _loadPackage(names,messageCallback,errorCallback){let toLoad=recursiveDependencies(names,0,errorCallback);if(Module.locateFile_packagesToLoad=toLoad,0===toLoad.size)return Promise.resolve("No new packages to load");messageCallback(`Loading ${Array.from(toLoad.keys()).join(", ")}`);let scriptPromises=[];for(let[pkg,uri]of toLoad){let loaded=loadedPackages[pkg];if(void 0!==loaded){if(loaded===uri||"default channel"===uri){messageCallback(`${pkg} already loaded from ${loaded}`);continue}errorCallback(`URI mismatch, attempting to load package ${pkg} from ${uri} while it is already loaded from ${loaded}. To override a dependency, load the custom package first.`);continue}let pkgname=Module.packages[pkg]&&Module.packages[pkg].name||pkg,scriptSrc="default channel"===uri?`${baseURL}${pkgname}.js`:uri;messageCallback(`Loading ${pkg} from ${scriptSrc}`),scriptPromises.push(loadScript(scriptSrc).catch((e=>{errorCallback(`Couldn't load package from URL ${scriptSrc}`,e),toLoad.delete(pkg)})))}try{await Promise.all(scriptPromises).then(waitRunDependency)}finally{delete Module.monitorRunDependencies}let resolveMsg,packageList=[];for(let[pkg,uri]of toLoad)loadedPackages[pkg]=uri,packageList.push(pkg);if(packageList.length>0){resolveMsg=`Loaded ${packageList.join(", ")}`}else resolveMsg="No packages loaded";Module.reportUndefinedSymbols(),messageCallback(resolveMsg),Module.importlib.invalidate_caches()}Module.locateFile=function(path){let pkg=path.replace(/\.data$/,"");const toLoad=Module.locateFile_packagesToLoad;if(toLoad&&toLoad.has(pkg)){let package_uri=toLoad.get(pkg);if("default channel"!=package_uri)return package_uri.replace(/\.js$/,".data")}return baseURL+path};let _package_lock=Promise.resolve();let sharedLibraryWasmPlugin,origWasmPlugin,wasmPluginIndex,loadedPackages={};function useSharedLibraryWasmPlugin(){sharedLibraryWasmPlugin||function(){for(let p in Module.preloadPlugins)if(Module.preloadPlugins[p].canHandle("test.so")){origWasmPlugin=Module.preloadPluhttps://requirejs.org/docs/errors.html#mismatch
    at makeError (require.js:5:1795)
    at T (require.js:5:8677)
    at Object.s [as require] (require.js:5:15042)
    at requirejs (require.js:5:2335)
    at index.html:12:11
    at new Promise (<anonymous>)
    at loadAMDModule (index.html:11:16)
    at main (index.html:17:31)
    at index.html:27:7
makeError @ require.js:5
T @ require.js:5
s @ require.js:5
requirejs @ require.js:5
(anonymous) @ index.html:12
loadAMDModule @ index.html:11
main @ index.html:17
(anonymous) @ index.html:27
await in (anonymous) (async)
(anonymous) @ index.html:27
```

### Expected behavior
Loading pyodide should not impact requirejs behaviour at all.

### Environment

- Pyodide Version: from `v0.17.2` to `v0.19.1`
- Browser version : Brave [Version 1.36.112 Chromium: 99.0.4844.51 (Official Build) (64-bit)])

[demo.zip](https://github.com/pyodide/pyodide/files/8284742/demo.zip)

**Comment by hoodmane** [comment]
Thanks for the report!

> v0.17.2

You mean v0.17.0a2? I think may well be an upstream bug, 0.17.0a2 mainly included an update to a much more modern emscripten. It would be worth looking into what happens when you require pyodide.asm.js directly. 

I will investigate, but I would definitely appreciate if anyone else could look into it as well.
