### ISSUE TITLE
Testing `yt` package is failing in CI

### ISSUE THREAD

**Issue by ryanking13** [pyodide/pyodide#2315]
## 🐛 Bug

Maybe related to #2307?

```
conftest.JavascriptException: PythonError: Traceback (most recent call last):
  File "/lib/python3.10/asyncio/futures.py", line 201, in result
    raise self._exception
  File "/lib/python3.10/asyncio/tasks.py", line 232, in __step
    result = coro.send(None)
  File "/lib/python3.10/site-packages/_pyodide/_base.py", line 494, in eval_code_async
    await CodeRunner(
  File "/lib/python3.10/site-packages/_pyodide/_base.py", line 345, in run_async
    coroutine = eval(self.code, globals, locals)
  File "<exec>", line 1, in <module>
  File "/lib/python3.10/site-packages/yt/__init__.py", line 13, in <module>
    import yt.utilities.physical_constants as physical_constants
  File "/lib/python3.10/site-packages/yt/utilities/physical_constants.py", line 3, in <module>
    from yt.units.yt_array import YTQuantity
  File "/lib/python3.10/site-packages/yt/units/yt_array.py", line 3, in <module>
    from yt.funcs import array_like_field  # NOQA: F401
  File "/lib/python3.10/site-packages/yt/funcs.py", line 33, in <module>
    from yt.utilities.logger import ytLogger as mylog
  File "/lib/python3.10/site-packages/yt/utilities/logger.py", line 4, in <module>
    from yt.config import ytcfg
  File "/lib/python3.10/site-packages/yt/config.py", line 9, in <module>
    from yt._maintenance.deprecation import issue_deprecation_warning
ModuleNotFoundError: No module named 'yt._maintenance'
```

**Comment by rth** [comment]
It doesn't look like it's happening for last commits on main anymore?

**Comment by ryanking13** [comment]
> It doesn't look like it's happening for last commits on main anymore?

We didn't fix something, so I'm not sure what the reason was. I'll close it for now and reopen if it occurs again.
