### ISSUE TITLE
micropip didn't resolve package versions correctly

### ISSUE THREAD

**Issue by oeway** [pyodide/pyodide#2487]
## 🐛 Bug

Hi, I am using micropip to installs two pure python packages, but got the error message complaining:
```
ValueError: Requested 'imjoy-rpc>=0.5.7', but imjoy-rpc==0.5.10a2 is already installed
```

### To Reproduce

```
Welcome to the Pyodide terminal emulator 🐍
Python 3.10.2 (main, May  4 2022 10:50:05) on WebAssembly VM
Type "help", "copyright", "credits" or "license" for more information.
>>> import micropip
>>> await micropip.install("imjoy-rpc==0.5.10a2")
>>> await micropip.install("imjoy-rpc>=0.5.7")
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/lib/python3.10/asyncio/futures.py", line 284, in __await__
    yield self  # This tells Task to wait for completion.
  File "/lib/python3.10/asyncio/tasks.py", line 304, in __wakeup
    future.result()
  File "/lib/python3.10/asyncio/futures.py", line 201, in result
    raise self._exception
  File "/lib/python3.10/asyncio/tasks.py", line 234, in __step
    result = coro.throw(exc)
  File "/lib/python3.10/site-packages/micropip/_micropip.py", line 192, in install
    transaction = await self.gather_requirements(
  File "/lib/python3.10/site-packages/micropip/_micropip.py", line 174, in gather_requirements
    await gather(*requirement_promises)
  File "/lib/python3.10/asyncio/futures.py", line 284, in __await__
    yield self  # This tells Task to wait for completion.
  File "/lib/python3.10/asyncio/tasks.py", line 304, in __wakeup
    future.result()
  File "/lib/python3.10/asyncio/futures.py", line 201, in result
    raise self._exception
  File "/lib/python3.10/asyncio/tasks.py", line 232, in __step
    result = coro.send(None)
  File "/lib/python3.10/site-packages/micropip/_micropip.py", line 302, in add_requirement
    raise ValueError(
ValueError: Requested 'imjoy-rpc>=0.5.7', but imjoy-rpc==0.5.10a2 is already installed
```

### Expected behavior

When I run the second install command, it should know that the version is already satisfied and do nothing instead of generating an error.

### Environment

Latest version at https://pyodide-cdn2.iodide.io/dev/full/console.html

**Comment by hoodmane** [comment]
Probably it did something like `'0.5.10' >= '0.5.7'` and got `False`.

**Comment by oeway** [comment]
> Thanks for the report! Probably it did something like `'0.5.10' >= '0.5.7'` and got `False`.

FYI: also failed if we install the later one without specifying the version, it appears that it only matches the exact string.

**Comment by ryanking13** [comment]
https://github.com/pypa/packaging/blob/ba124324e866e518ebfe0378a25b6ba4816e5880/packaging/specifiers.py#L185-L189

Setting `req.prereleases = True` will work I guess.

**Comment by marcbernot** [comment]
oh this is already solved, well done! 
Anyway, if you are in a hurry, here is a hack for the install to go through. You first install the alpha version, then change the viewed from micropip version name, then install the other packages.
```python
await  micropip.install('imjoy-rpc==0.5.10a2')
from micropip import _micropip
_micropip.PACKAGE_MANAGER.installed_packages['imjoy-rpc'].version = '0.5.10'
await  micropip.install('imjoy-rpc>=0.5.7')
```

**Comment by oeway** [comment]
Thank you! Feel free to close the issue then!

**Comment by Pancham97** [comment]
I recently got this issue again.

Pyodide version: 0.2.0
JupyterLite version: 0.2.3

```python
import micropip
await micropip.install("pandas==2.2.2", deps=False, keep_going=True, pre=True)
```

<details>
<summary>
Click to view stacktrace
</summary>

```python
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[187], line 2
      1 import micropip
----> 2 await micropip.install("pandas==2.2.2", deps=False, keep_going=True, pre=True)
      3 micropip.list()

File /lib/python3.11/site-packages/micropip/_commands/install.py:142, in install(requirements, keep_going, deps, credentials, pre, index_urls, verbose)
    130     index_urls = package_index.INDEX_URLS[:]
    132 transaction = Transaction(
    133     ctx=ctx,
    134     ctx_extras=[],
   (...)
    140     index_urls=index_urls,
    141 )
--> 142 await transaction.gather_requirements(requirements)
    144 if transaction.failed:
    145     failed_requirements = ", ".join([f"'{req}'" for req in transaction.failed])

File /lib/python3.11/site-packages/micropip/transaction.py:204, in Transaction.gather_requirements(self, requirements)
    201 for requirement in requirements:
    202     requirement_promises.append(self.add_requirement(requirement))
--> 204 await asyncio.gather(*requirement_promises)

File /lib/python3.11/site-packages/micropip/transaction.py:211, in Transaction.add_requirement(self, req)
    208     return await self.add_requirement_inner(req)
    210 if not urlparse(req).path.endswith(".whl"):
--> 211     return await self.add_requirement_inner(Requirement(req))
    213 # custom download location
    214 wheel = WheelInfo.from_url(req)

File /lib/python3.11/site-packages/micropip/transaction.py:290, in Transaction.add_requirement_inner(self, req)
    287 # Is some version of this package is already installed?
    288 req.name = canonicalize_name(req.name)
--> 290 satisfied, ver = self.check_version_satisfied(req)
    291 if satisfied:
    292     logger.info(f"Requirement already satisfied: {req} ({ver})")

File /lib/python3.11/site-packages/micropip/transaction.py:235, in Transaction.check_version_satisfied(self, req)
    231 if req.specifier.contains(ver, prereleases=True):
    232     # installed version matches, nothing to do
    233     return True, ver
--> 235 raise ValueError(
    236     f"Requested '{req}', " f"but {req.name}=={ver} is already installed"
    237 )

ValueError: Requested 'pandas==2.2.2', but pandas==1.5.3 is already installed
```
</details>
