### ISSUE TITLE
platform.freedesktop_os_release() raises a JsException/PythonError

### ISSUE THREAD

**Issue by cclauss** [pyodide/pyodide#2495]
## 🐛 Bug

`platform.freedesktop_os_release()` raises a JsException/PythonError

### To Reproduce

```python
import platform
platform.freedesktop_os_release()
```
### --> 
```
JsException(PythonError:
    Traceback (most recent call last):
        File "/lib/python3.10/site-packages/_pyodide/_base.py", line 429, in eval_code .run(globals, locals)
        File "/lib/python3.10/site-packages/_pyodide/_base.py", line 300, in run coroutine = eval(self.code, globals, locals)
        File "", line 22, in File "/lib/python3.10/platform.py", line 1297, in freedesktop_os_release
            raise OSError( FileNotFoundError: [Errno 44] Unable to read files /etc/os-release, /usr/lib/os-release )
```

### Expected behavior

A version number string is returned.

### Environment

- Pyodide Version: `main` branch
- Browser version: FireFox
- Any other relevant information:

**Comment by rth** [comment]
Thanks for the report! This is the expected behavior though,

https://docs.python.org/3/library/platform.html#platform.freedesktop_os_release

> Raises [OSError](https://docs.python.org/3/library/exceptions.html#OSError) or subclass when neither /etc/os-release nor /usr/lib/os-release can be read.

**Comment by rth** [comment]
If the concern is that it raised a JsException instead of an OSError, could you please give more context what you did to obtain it? Because running the code to reproduce in the REPL for instance does produce the expected exception,
```py
>>> import platform
>>> platform.freedesktop_os_release()
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/lib/python3.10/platform.py", line 1297, in freedesktop_os_release
    raise OSError(
FileNotFoundError: [Errno 44] Unable to read files /etc/os-release, /usr/lib/os-release
```

**Comment by cclauss** [comment]
Merci, Roman.  I think works-as-designed is good enough for me.  Closing.
