### ISSUE TITLE
matplotlib build fails due to setuptools update

### ISSUE THREAD

**Issue by ryanking13** [pyodide/pyodide#2567]
## 🐛 Bug

See:

- https://github.com/pypa/setuptools/issues/3320
- https://github.com/pypa/setuptools/pull/3262

**Comment by hoodmane** [comment]
Thanks for investigating @ryanking13. I guess we need to require `setuptools<62.3.0` then. We should really get #2132 finished so we would have a place to put this constraint...

**Comment by ryanking13** [comment]
The setuptools merged the patch very quickly (https://github.com/pypa/setuptools/pull/3321), so let's wait for the patch release (v62.3.1)

**Comment by abravalheri** [comment]
Sorry for the disruption. Soon the new setuptools version will be available with the fix for the unexpected error (it should only be a warning).Thank you @ryanking13 .

Please let me know if it does not work

**Comment by dominicdev** [comment]
is this gonna get fix? I tought it was something with my machine..it was very frustrating

```
Uncaught (in promise) PythonError: Traceback (most recent call last):
  File "/lib/python3.10/site-packages/packaging/requirements.py", line 102, in __init__
    req = REQUIREMENT.parseString(requirement_string)
  File "/lib/python3.10/site-packages/pyparsing/core.py", line 1134, in parse_string
    raise exc.with_traceback(None)
pyparsing.exceptions.ParseException: Expected W:(0-9A-Za-z), found '.'  (at char 0), (line:1, col:1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/lib/python3.10/asyncio/futures.py", line 201, in result
    raise self._exception
  File "/lib/python3.10/asyncio/tasks.py", line 234, in __step
    result = coro.throw(exc)
  File "/lib/python3.10/site-packages/micropip/_micropip.py", line 183, in install
    transaction = await self.gather_requirements(requirements, ctx, keep_going)
  File "/lib/python3.10/site-packages/micropip/_micropip.py", line 173, in gather_requirements
    await gather(*requirement_promises)
  File "/lib/python3.10/asyncio/futures.py", line 284, in __await__
    yield self  # This tells Task to wait for completion.
  File "/lib/python3.10/asyncio/tasks.py", line 304, in __wakeup
    future.result()
  File "/lib/python3.10/asyncio/futures.py", line 201, in result
    raise self._exception
  File "/lib/python3.10/asyncio/tasks.py", line 232, in __step
    result = coro.send(None)
  File "/lib/python3.10/site-packages/micropip/_micropip.py", line 248, in add_requirement
    req = Requirement(requirement)
  File "/lib/python3.10/site-packages/packaging/requirements.py", line 104, in __init__
    raise InvalidRequirement(
packaging.requirements.InvalidRequirement: Parse error at "'./reques'": Expected W:(0-9A-Za-z)
```

**Comment by ryanking13** [comment]
@dominicdev I think your issue is unrelated to this one? Please open a new issue for it.

**Comment by ryanking13** [comment]
I can confirm that we are not facing this error now. Thank you for your prompt response @abravalheri!

**Comment by hoodmane** [comment]
Thanks for the quick fix @abravalheri!
