### ISSUE TITLE
ModuleNotFoundError: No module named 'selenium'

### ISSUE THREAD

**Issue by khl4git** [pyodide/pyodide#2585]
Hi,

Any visibility concerning the integration of the Selenium package  ?
```
JsException(PythonError: Traceback (most recent call last): File "/lib/python3.10/asyncio/futures.py", line 201, in result raise self._exception File "/lib/python3.10/asyncio/tasks.py", line 232, in __step result = coro.send(None) File "/lib/python3.10/site-packages/_pyodide/_base.py", line 500, in eval_code_async await CodeRunner( File "/lib/python3.10/site-packages/_pyodide/_base.py", line 351, in run_async coroutine = eval(self.code, globals, locals) File "", line 4, in ModuleNotFoundError: No module named 'selenium' )
```

**Comment by ryanking13** [comment]
Since selenium is a pure python package, you can install it with `micropip`.

```py
>>> import micropip
>>> await micropip.install("selenium")
>>> import selenium
>>> selenium
<module 'selenium' from '/lib/python3.10/site-packages/selenium/__init__.py'>
>>> selenium.__version__
'4.1.5'
```

However, it won't be useful because you can't instantiate web driver in the browser.

**Comment by khl4git** [comment]
Very nice tip, very useful, thank you !
