### ISSUE TITLE
Micropip does not resolve development versions correctly

### ISSUE THREAD

**Issue by philippjfr** [pyodide/pyodide#2634]
## 🐛 Bug

When installing a development version from PyPI using an explicit pin and another package expresses a version requirement micropip does not correctly compare these two requirements and errors.
 
### To Reproduce

As a minimal example here I pin holoviews 1.15.1a2 and also install hvplot. 

```python
import micropip
await micropip.install(['holoviews==1.15.1a2', 'hvplot'])
```
Since hvplot requires HoloViews 1.10.0 micropip fails to resolve that `1.15.1a2 >= 1.10.0` and errors:

```
Uncaught (in promise) PythonError: Traceback (most recent call last):
  File "/lib/python3.10/asyncio/futures.py", line 201, in result
    raise self._exception
  File "/lib/python3.10/asyncio/tasks.py", line 234, in __step
    result = coro.throw(exc)
  File "/lib/python3.10/site-packages/micropip/_micropip.py", line 183, in install
    transaction = await self.gather_requirements(requirements, ctx, keep_going)
  File "/lib/python3.10/site-packages/micropip/_micropip.py", line 173, in gather_requirements
    await gather(*requirement_promises)
  File "/lib/python3.10/asyncio/futures.py", line 284, in __await__
    yield self  # This tells Task to wait for completion.
  File "/lib/python3.10/asyncio/tasks.py", line 304, in __wakeup
    future.result()
  File "/lib/python3.10/asyncio/futures.py", line 201, in result
    raise self._exception
  File "/lib/python3.10/asyncio/tasks.py", line 232, in __step
    result = coro.send(None)
  File "/lib/python3.10/site-packages/micropip/_micropip.py", line 291, in add_requirement
    await self.add_wheel(
  File "/lib/python3.10/site-packages/micropip/_micropip.py", line 316, in add_wheel
    await self.add_requirement(recurs_req, ctx, transaction)
  File "/lib/python3.10/site-packages/micropip/_micropip.py", line 276, in add_requirement
    raise ValueError(
ValueError: Requested 'holoviews>=1.11.0', but holoviews==1.15.0a2 is already installed
```

### Expected behavior

I would expect it to correctly compare development versions and resolve this version spec.

### Environment

- Pyodide Version: 0.20.0

**Comment by philippjfr** [comment]
Apologies, duplicate of https://github.com/pyodide/pyodide/issues/2487. Closing.
