### ISSUE TITLE
Accessing files does not work on Pyodide

### ISSUE THREAD

**Issue by andreaslam** [pyodide/pyodide#2669]
## 🐛 Bug

I used an external python file as my python code source file. Inside the python code file, I access files locally given a directory in the code. The code itself works separately but when used externally on Pyodide it doesn't work. I made sure my files are on the same level to access the files 

### To Reproduce

test.html
```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="https://pyscript.net/alpha/pyscript.css" />
    <script defer src="https://pyscript.net/alpha/pyscript.js"></script>
</head>
<body>
    <py-script src="source.py">
</body>
</html>
```

source.py
```
from os import listdir
from os.path import isfile, join
from tempfile import TemporaryDirectory

for x in listdir("./temporary"):
    print(x)
```

### Expected behavior

I expect it to print all items in a file but got an error instead.

JsException(PythonError: Traceback (most recent call last): File "/lib/python3.10/site-packages/_pyodide/_base.py", line 429, in eval_code .run(globals, locals) File "/lib/python3.10/site-packages/_pyodide/_base.py", line 300, in run coroutine = eval(self.code, globals, locals) File "", line 5, in FileNotFoundError: [Errno 44] No such file or directory: './temporary' )

### Environment
```
  <link rel="stylesheet" href="https://pyscript.net/alpha/pyscript.css" />
    <script defer src="https://pyscript.net/alpha/pyscript.js"></script>
```
- I use VSCode and I use Brave Browser to test it

**Comment by andreaslam** [comment]
How should I do it? I read the link you sent to me and I don't get how this piece of code works/where should I put it in etc. 

```await pyodide.runPythonAsync(`
  from pyodide.http import pyfetch
  response = await pyfetch("https://some_url/...")
  if response.status == 200:
      with open("<output_file>", "wb") as f:
          f.write(await response.bytes())
`)
```

Also, I am just testing my code, as in this version is merely a test of my actual code. For the actual code, instead of hard coding the file directory, the user needs to upload their own file, something like 
```<input type="file">``` for HTML and saving it to a server. Is this possible as well?

**Comment by ryanking13** [comment]
> How should I do it?

You can put the python code parts inside `<py-script>` tag.

```py
<py-script>
async def _fetch():
from pyodide.http import pyfetch
resp = await pyfetch("...")
...
pyscript.run_until_complete(_fetch())
</py-script>
```

> `<input type="file">` for HTML and saving it to a server. Is this possible as well?

Yes, why not. Though you'll have to download those files from the server to the virtual file system anyway.

**Comment by andreaslam** [comment]
I have tried it, however it led me to new problems. I have other modules, such as PIL and now it says that the module is not found.

Full error:

```
JsException(PythonError: Traceback (most recent call last): File "/lib/python3.10/site-packages/_pyodide/_base.py", line 429, in eval_code .run(globals, locals) File "/lib/python3.10/site-packages/_pyodide/_base.py", line 300, in run coroutine = eval(self.code, globals, locals) File "", line 1, in ModuleNotFoundError: No module named 'PIL' )
```

My Code in full: 

```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://pyscript.net/alpha/pyscript.css" />
    <script defer src="https://pyscript.net/alpha/pyscript.js"></script>
    <title>Document</title>
    <py-env>
        - Pillow
        - paths:
            - ./trait-layers/Backgrounds
            - ./trait-layers/mouth
            - './trait-layers/PurposelessPorpoise
    </py-env>
</head>
<body>
    <main class="container h-screen flex flex-col items-center justify-center">
    <py-script src="generate.py">
        <py-script>
            await pyodide.runPythonAsync(`
            from pyodide.http import pyfetch
            response = await pyfetch("file:///Users/andreas/Desktop/Code/NFT/Code_files_from_GitHub/Modded_Version_of_NFT_Generator")
            if response.status == 200:
                with open("<output_file>", "wb") as f:
                    f.write(await response.bytes())
          `)
    </py-script>
</body>
</html>
```

**Comment by hoodmane** [comment]
Remove `await pyodide.runPythonAsync(`. py-script tag expects Python, pyodide.runPythonAsync is JavaScript.

**Comment by andreaslam** [comment]
OK I have done that. Nothing happens and still has the same error.

**Comment by ryanking13** [comment]
> - './trait-layers/PurposelessPorpoise

Please fix this typo (single quote) and recheck?

**Comment by andreaslam** [comment]
Nope, the error persists

**Comment by ryanking13** [comment]
> Nope, the error persists.

Please open the browser dev console and see what it says. Apparently, something you wrote inside `<py-env> tag` is wrong but we cannot reproduce it as we don't have the Python scripts that you are trying to import. I think it is more like a pyscript issue, so probably for a fast response, you should ask pyscript devs.

> By the way, is it the right way to download file of pyodide virtual file system?

Yes, it is our recommended way of downloading a single file inside Pyodide. If you prefer JavaScript, you can directly use `fetch` and [save it to a virtual file system using Emscripten file system API.](https://pyodide.org/en/latest/usage/file-system.html)

**Comment by andreaslam** [comment]
Below is everything in my console
```
Live reload enabled.
stores.ts:32 adding initializer async ƒ mountElements() {
        console.log('Collecting nodes to be mounted into python namespace...');
        const pyodide = await pyodideReadyPromise$1;
        const matches = document.querySelectorAl…
stores.ts:34 adding initializer async ƒ mountElements() {
        console.log('Collecting nodes to be mounted into python namespace...');
        const pyodide = await pyodideReadyPromise$1;
        const matches = document.querySelectorAl…
stores.ts:40 adding post initializer async ƒ initHandlers() {
        console.log('Collecting nodes...');
        const pyodide = await pyodideReadyPromise$1;
        for (const pysAttribute of pysAttributeToEvent.keys()) {
            await cr…
stores.ts:42 adding post initializer async ƒ initHandlers() {
        console.log('Collecting nodes...');
        const pyodide = await pyodideReadyPromise$1;
        for (const pysAttribute of pysAttributeToEvent.keys()) {
            await cr…
pyenv.ts:10 RUNTIME READY
pyconfig.ts:17 config set!
pyconfig.ts:22 initializers set
pyconfig.ts:27 post initializers set
pyconfig.ts:32 post initializers set
pyconfig.ts:37 post initializers set
pyconfig.ts:32 post initializers set
pyscript.ts:66 connected
stores.ts:32 adding initializer async ƒ loadEnv() {
                await loadPackage(env);
                console.log('environment loaded');
            }
pyconfig.ts:22 initializers set
stores.ts:34 adding initializer async ƒ loadEnv() {
                await loadPackage(env);
                console.log('environment loaded');
            }
stores.ts:32 adding initializer async ƒ loadPaths() {
                for (const singleFile of paths) {
                    console.log(`loading ${singleFile}`);
                    try {
                        await loadFromFile(singleFi…
pyconfig.ts:22 initializers set
stores.ts:34 adding initializer async ƒ loadPaths() {
                for (const singleFile of paths) {
                    console.log(`loading ${singleFile}`);
                    try {
                        await loadFromFile(singleFi…
pyenv.ts:60 environment loading... Array(1)
pyconfig.ts:17 config set!
pyconfig.ts:112 config set Object
pyconfig.ts:124 Initializing runtimes...
interpreter.ts:5 creating pyodide runtime
pyodide.asm.js:14 Python initialization complete
interpreter.ts:15 loading micropip
load-package.ts:329 Loading micropip, pyparsing, packaging, distutils
load-package.ts:389 Loaded micropip, pyparsing, packaging, distutils
interpreter.ts:17 loading pyscript...
interpreter.ts:30 done setting up environment
pyenv.ts:10 RUNTIME READY
pyscript.ts:148 Collecting nodes to be mounted into python namespace...
load-package.ts:329 Loading pillow
load-package.ts:389 Loaded pillow
pyenv.ts:43 environment loaded
pyenv.ts:47 loading ./trait-layers/Backgrounds
pyenv.ts:47 loading ./trait-layers/mouth
pyenv.ts:47 loading ./trait-layers/PurposelessPorpoise
pyenv.ts:56 paths loaded
base.ts:76 evaluate
pyconfig.ts:32 post initializers set
pyconfig.ts:83 ------ loader closed ------
2pyodide.asm.js:14 ----> changed out to py-97b55539-74c5-742a-2249-4d646e76d2ad true
pyodide.asm.js:14 Python exception:
Traceback (most recent call last):
  File "/lib/python3.10/site-packages/_pyodide/_base.py", line 429, in eval_code
    .run(globals, locals)
  File "/lib/python3.10/site-packages/_pyodide/_base.py", line 300, in run
    coroutine = eval(self.code, globals, locals)
  File "<exec>", line 2, in <module>
ModuleNotFoundError: No module named 'IPython'


log_python_error @ pyodide.asm.js:14
pyodide.asm.js:14 Element.write: PythonError: Traceback (most recent call last):
  File "/lib/python3.10/site-packages/_pyodide/_base.py", line 429, in eval_code
    .run(globals, locals)
  File "/lib/python3.10/site-packages/_pyodide/_base.py", line 300, in run
    coroutine = eval(self.code, globals, locals)
  File "<exec>", line 2, in <module>
ModuleNotFoundError: No module named 'IPython'
 --> True
pyodide.asm.js:14 APPENDING: True ==> py-97b55539-74c5-742a-2249-4d646e76d2ad --> PythonError: Traceback (most recent call last):
  File "/lib/python3.10/site-packages/_pyodide/_base.py", line 429, in eval_code
    .run(globals, locals)
  File "/lib/python3.10/site-packages/_pyodide/_base.py", line 300, in run
    coroutine = eval(self.code, globals, locals)
  File "<exec>", line 2, in <module>
ModuleNotFoundError: No module named 'IPython'

base.ts:128 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'setAttribute')
    at PyScript.evaluate (base.ts:128:79)
pyscript.ts:111 Collecting nodes...
```
I will follow up with this issue with Pyscript but at the same time I would also appreciate it if we can sort some problems related to importing modules here :)

**Comment by ryanking13** [comment]
> ModuleNotFoundError: No module named 'IPython'

We don't have IPython in Pyodide so probably that would be the reason for the error? I'm not sure pyscript has its own implementation of IPython.

**Comment by andreaslam** [comment]
Thanks! The error is gone now but for some reason the file upload doesn't work. Got the previous error just like in the beginning 

```
JsException(PythonError: Traceback (most recent call last): File "/lib/python3.10/site-packages/_pyodide/_base.py", line 429, in eval_code .run(globals, locals) File "/lib/python3.10/site-packages/_pyodide/_base.py", line 300, in run coroutine = eval(self.code, globals, locals) File "", line 21, in FileNotFoundError: [Errno 44] No such file or directory: './trait-layers' )
```

Still, I have added the code already for downloading to the virtual file system

index.html

```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://pyscript.net/alpha/pyscript.css" />
    <script defer src="https://pyscript.net/alpha/pyscript.js"></script>
    <title>Document</title>
    <py-env>
        - Pillow
        - paths:
            - ./trait-layers/Backgrounds
            - ./trait-layers/mouth
            - ./trait-layers/PurposelessPorpoise
            - ./images
            - ./temporary
    </py-env>
</head>
<body>
    <main class="container h-screen flex flex-col items-center justify-center">
    <py-script src="generate.py">
        <py-script>
            from pyodide.http import pyfetch
            response = await pyfetch("file:///Users/andreas/Desktop/Code/NFT/Code_files_from_GitHub/Modded_Version_of_NFT_Generator")
            if response.status == 200:
                with open("<output_file>", "wb") as f:
                    f.write(await response.bytes())
    </py-script>
</body>
</html>
```

**Comment by andreaslam** [comment]
![image](https://user-images.githubusercontent.com/81166794/173339531-2d0c202a-2afc-417d-8969-4e13ebfd064f.png)
As you can see, I have all my items in the same folder and I don't know how to upload this folder to the virtual file system.

**Comment by ryanking13** [comment]
For security reasons, browsers do not allow fetching a file in your local file system. You should serve those files with a file server: https://stackoverflow.com/questions/50007055/fetch-request-to-local-file-not-working

**Comment by andreaslam** [comment]
I have already tried one of the solutions on the stackoverflow link already, which is to install Chrome Web Server. This is my first time doing a project like this. Do you think that it will work with Pyodide? I think I am doing this incorrectly since it doesn't work. Do I need additional code to make it work?

**Comment by ryanking13** [comment]
> Do you think that it will work with Pyodide?

I think it will work. Probably you can also see how [jupyterlite](https://github.com/jupyterlite/jupyterlite) team is dealing with local files and file upload. I think they are quite good at this.

> Do I need additional code to make it work?

Yes, currently Pyodide doesn't have any helper functions to deal with local files. So you will have to do some work.

**Comment by andreaslam** [comment]
Thank for your reply. Just curious, when will helper functions be introduced to Pyodide? I'll still work on the additional code to upload the files onto the virtual file system.

**Comment by ryanking13** [comment]
> Thank for your reply. Just curious, when will helper functions be introduced to Pyodide? I'll still work on the additional code to upload the files onto the virtual file system.

Since Firefox doesn't support File System API yet and Pyodide maintainers currently have more work to do on Pyodide than we have time, so there is no concrete plan to introduce file system APIs for Pyodide in the near future. But since it is a feature that many people want, feel free to open an issue or a PR to start a discussion/ I think Jupyterlite or PyScript devs can help us design the API.

**Comment by pranav7712** [comment]
Was looking for this same features. Here's what I found. (Correct if wrong)

There is a File System Access API from HTML5 onwards which allows accessing the local files. That is available in JavaScript. 
So, can we do something like accessing the local file using this API as a JS object and translating into a equivalent Python datatype (like a dataframe in case of an excel file)

Any thoughts, please?

**Comment by andreaslam** [comment]
I opened an issue in Pyscript telling them that I would like to have a feature of the sort already. I see that you have also mentioned about the File System Access API. I have Googled about it but I still don't quite understand. Is this what you were mentioning about? I see that the code is in JS but just curious, is there a Python version of it? 

https://developer.mozilla.org/en-US/docs/Web/API/File_System_Access_API 

Also, for your reference, here's a more detailed version of my request for new feature in Pyscript:

https://github.com/pyscript/pyscript/issues/558

**Comment by ryanking13** [comment]
> There is a File System Access API from HTML5 onwards which allows accessing the local files. That is available in JavaScript.
> So, can we do something like accessing the local file using this API as a JS object and translating into a equivalent Python datatype (like a dataframe in case of an excel file)

Yes you can try File System Access API. Note that it is only supported in Chromium based browsers (Chrome and newer Edge) and Recent (>=15.2) version of Safari.

**Comment by andreaslam** [comment]
Hello ryanking13,

I have experimented with some ways to try and "upload" the file but to no avail.

I tried the following: creating an html input to upload the folder entirely like this:

<input type="file" id="ctrl" webkitdirectory directory multiple/>

I tried this and it didn't work.
<img width="466" alt="Screenshot 2022-07-15 at 9 24 43 AM" src="https://user
<img width="1440" alt="Screenshot 2022-07-15 at 9 24 53 AM" src="https://user-images.githubusercontent.com/81166794/179184314-f9439f81-7fda-474f-91ba-c45abddfd644.png">
-images.githubusercontent.com/81166794/179184293-1538f6b2-cc5e-428a-82a3-51b3a57acf89.png">

I also tried to upload the folder to workspace but nothing 
<img width="227" alt="Screenshot 2022-07-15 at 9 25 04 AM" src="https://user-images.githubusercontent.com/81166794/179184378-c9d571e8-4205-44cb-9092-5cd2715475ae.png">
changed:

I also re-tried all my previous ways and nothing works. I already contacted the developers of Pyscript for a request for a centralised Google Drive-like app to manage uploads.

**Comment by andreaslam** [comment]
Update: I found a website https://www.jhanley.com/pyscript-files-and-file-systems-part-1/ that sorta explains it but it doesn't quite work i think like it has an input but idk why it doesn't have virtual file system memory?
<img width="1431" alt="Screenshot 2022-07-17 at 4 16 22 PM" src="https://user-images.githubusercontent.com/81166794/179405274-d3cdde5d-35ec-468c-85fd-b8ad42bdde11.png">
Nothing still works until now

**Comment by dberardo-com** [comment]
can one access file on a backend application using pyodide in nodejs? i am trying to make relative imports to local packages (folder/__init__.py) but does not quite work

**Comment by ryanking13** [comment]
@dberardo-com You can mount the local file system to make it visible in Pyodide. See https://pyodide.org/en/stable/usage/faq.html#how-can-i-load-external-files-in-pyodide.

**Comment by hoodmane** [comment]
It should work fine to mount directories anywhere. For instance, our cli test runner uses this pretty heavily.
