### ISSUE TITLE
loadPyodide fails inside a WebWorker

### ISSUE THREAD

**Issue by vanyle** [pyodide/pyodide#2814]
## 🐛 Bug

When starting a web worker that loads pyodide, the following is displayed:

```
Loading distutils
Loaded distutils
pyodide.asm.js:14 Uncaught (in promise) PythonError: Traceback (most recent call last):
  File "/lib/python3.10/site-packages/_pyodide/_base.py", line 429, in eval_code
    .run(globals, locals)
  File "/lib/python3.10/site-packages/_pyodide/_base.py", line 300, in run
    coroutine = eval(self.code, globals, locals)
  File "<exec>", line 1, in <module>
OSError: [Errno 29] I/O error

    at new_error (pyodide.asm.js:14:238191)
    at pyodide.asm.wasm:0xedbcb
    at pyodide.asm.wasm:0xedccc
    .... Omitted ....
```

### To Reproduce

```js
// webworker.js
importScripts("https://cdn.jsdelivr.net/pyodide/v0.20.0/full/pyodide.js");
self.pyodide = null;
async function startPyodide() {
    console.log("Loading pyodide!");
    self.pyodide = await loadPyodide();
    console.log("Loaded!");
}
startPyodide();
```

```js
// main file
import PyodideWorker from 'web-worker:./PyodideWorker';
let worker = new PyodideWorker();
```

I'm using rollup to bundle my code, but this should not matter as the web-worker is stored in a separate file.
After inspecting the code generated by rollup, I have:
```js
function createURLWorkerFactory(url) {
        return function WorkerFactory(options) {
            return new Worker(url, options);
        };
}
var WorkerFactory = createURLWorkerFactory('build/web-worker-0.js');
let worker = new WorkerFactory();
```

### Expected behavior

Pyodide loads properly without throwing any error.

### Environment

- Pyodide Version: 0.20.0
- Browser version: 1.40.109 Chromium: 103.0.5060.66 (Build officiel) (64 bits)

**Comment by vanyle** [comment]
This is caused by an error inside the `stdout` callback when loading.
The error message is a bit cryptic though.
