### ISSUE TITLE
Exception creating string representation of javascript Object if constructor is undefined

### ISSUE THREAD

**Issue by mandersogit** [pyodide/pyodide#2901]
## 🐛 Bug

I've been trying to prove out building a simple VueJS app with PyScript and running into strange errors of the form:

`JsException(TypeError: Cannot read properties of undefined (reading 'name')) TypeError: Cannot read properties of undefined (reading 'name')`

After much debugging, I see at least one of the errors is happing when pyodide attempts to create a string representation of a javascript object when the object has an undefined constructor. Using an object like this seems to be common in Vue (the 'publicThis' variable used for method binding is of this form).

### To Reproduce

`debug.html`
```html
<!DOCTYPE html>
<html>
  <head>
    <script defer src="https://pyscript.net/alpha/pyscript.js"></script>
  </head>
  <body>
<script>
  obj = Object();
  obj.constructor = undefined;
</script>
    <py-script src="./debug.py"></py-script>
    <py-repl></py-repl>
  </body>
</html>
```
`debug.py`
```python
import pyodide
import js

try:
    str(js.obj)
except Exception as err:
    console.log(f"{err!r}", err)
```

`javascript console`
```javascript
pyodide.asm.js:14 JsException(TypeError: Cannot read properties of undefined (reading 'name')) TypeError: Cannot read properties of undefined (reading 'name')
    at hiwire_is_typedarray (pyodide.asm.js:14:227151)
    at pyodide.asm.wasm:0xee398
    at pyodide.asm.wasm:0xeea6e
    at js2python (pyodide.asm.js:14:230955)
    at pyodide.asm.wasm:0xefd61
    at pyodide.asm.wasm:0x178583
    at pyodide.asm.wasm:0x2005f9
    at pyodide.asm.wasm:0x1f98b5
    at pyodide.asm.wasm:0x1f97a0
    at pyodide.asm.wasm:0x1f6ad9
```

### Expected behavior

To produce a string representation with no exceptions thrown.

### Environment

- Pyodide Version: 0.20.0
- Browser version: Brave 1.40.113 Chromium 103.0.5060.114 (macOS 12.4 Monterey)
- Any other relevant information: 

### Related Issue

Somewhat unrelated; the `pyodide.create_proxy()` object does not have a javascript `.bind()` method, and otherwise does not conform to the javascript function api that VueJS is expecting. I had to wrap my pyodide proxy objects in a javascript function to get it to work at all.

This may be fixed (https://github.com/pyodide/pyodide/pull/2769), although a bind that is a no-op would not provide any access to the bound javascript 'this' object if the python function needs access to that to perform its job (and I think that a Vue component method does need such access to function).

```python
jsfn_wrap = js.Function("proxy_fn", """\
function wrapper() {
   // wrap this in an Object to avoid pyodide string-ification bug
   return proxy_fn.apply({this: this}, arguments);
}
return wrapper;
""")

def function_proxy(py_func):
    proxy = pyodide.create_proxy(py_func)
    jsfn = jsfn_wrap(proxy)
    return jsfn

```

**Comment by hoodmane** [comment]
Thanks for the report @mandersogit. Can you check all these things against the development version of Pyodide? We've fixed the problem with undefined constructors. As far as the `this` issue goes, the issue is that it's not clear how a Python function would access the JavaScript `this`. We can't really pass it as the first argument. Perhaps `create_proxy` could take a parameter or something. We would first need a more detailed discussion of the use case.

**Comment by mandersogit** [comment]
Thanks @hoodmane. I haven't yet used pyodide directly without pyscript, nor do I currently know how to tell pyscript how to use the development version instead of the default v0.20.0. Can you point me a recipe for that or do I need to track down the how if it on my own?

What I was attempting to do in my VueJS experiment when I realized I needed access to the bound `this` was to insert the `this` that the function wrapper could access as the first argument to the proxied python function:

```python
jsmethod_wrap = js.Function("proxy_method", """\
function wrapper() {
    var args = Array.from(arguments);
    args.splice(0, 0, {this: this})
    return proxy_method.apply({this: this}, args);
}
return wrapper;
""")

def method_proxy(py_method):
    proxy = pyodide.create_proxy(py_method)
    jsfn = jsmethod_wrap(proxy)
    return jsfn

def update(that, e):
    that.this.editing = False
    c, r = that.this.c, that.this.r
    js.cells[c][r] = e.target.value.trim()

where.it.goes = method_proxy(update)
```

I think it was more or less working, except for the undefined constructors causing problems elsewhere. If there was a more integrated approach in pyodide to support this kind of programming model, that would be great for folks looking to integrate with javascript libraries that operate this way.

This was trying to replicate the [cells example](https://vuejs.org/examples/#cells) from the Vue documentation.

**Comment by hoodmane** [comment]
> nor do I currently know how to tell pyscript how to use the development version instead of the default v0.20.0. Can you point me a recipe for that or do I need to track down the how if it on my own?

Well to be honest, I don't know how to do it either. I am not sure if it's possible at this point... @fpliger What I would recommend is just include `https://pyodide-cdn2.iodide.io/dev/full/pyodide.js` in the script tag instead, and then do
```
<script>
pyodide.runPython(`
# copy contents of debug.py here
`);
</script>
```
Though also I don't think it's super necessary in this case since I think I understand what you are talking about.

It seems that what you've done is indeed the right thing for accessing `this`. For starters we could just add an faq to the docs showing how to do this. But maybe it would be reasonable to add a boolean keyword only argument to `create_proxy` and `create_once_callable` to request `this` to be passed as the first argument to the Python function.

**Comment by mandersogit** [comment]
There are several references to using the `<py-config>` tag to specify a "runtime", and I'm not sure what that means, apart from pyodide is a runtime (are there other runtimes?).
- https://github.com/pyscript/pyscript/blob/main/docs/tutorials/getting-started.md
- https://realpython.com/pyscript-python-in-browser/

Revising my html to this:
```html
<!DOCTYPE html>
<html>
  <head>
    <script defer src="https://pyscript.net/alpha/pyscript.js"></script>
    <py-config>
      - autoclose_loader: true
      - runtimes:
         -
            src: "https://pyodide-cdn2.iodide.io/dev/full/pyodide.js"
            name: pyodide-dev
            lang: python
  </py-config>
  </head>
  <body>
<script>
  obj = Object();
  obj.constructor = undefined;
</script>
   <py-script src="./debug.py"></py-script>
    <py-repl></py-repl>
  </body>
</html>
```
does load cause pyodide v0.21.0a3 to be loaded instead, and resolves the undefined constructor string-ification error in my test case.

The applicable fix was the one referenced in #2520?

Thanks!

**Comment by fpliger** [comment]
Sorry that I'm late to the party (been a rough couple of weeks and I missed this). 

@mandersogit your revised HTML is the correct way of specifying other versions of pyodide (at least for now. Honestly we need to coordinate better for the future in case there are API changes). 

In the docs, we use "runtime" and not "a Pyodide Runtime" because we'd like to support more than just pyodide and are currently starting to explore that route. Maybe it's better to actually just say Pyodide until we actually add support for other, to avoid confusion. Thank for your feedback! 

@hoodmane @mandersogit , I'm not sure I understand though, is the issue fixed?

**Comment by hoodmane** [comment]
I believe the primary issue reported here is fixed on master:
```py
>>> from pyodide.code import run_js
>>> o = run_js("Object.create(null)")
>>> str(o)
Traceback (most recent call last):
  File "<console>", line 1, in <module>
TypeError: Pyodide cannot generate a repr for this Javascript object because it has no 'toString' method
```
I think this is the best we can do because `o.toString()` itself throws an error.

**Comment by mandersogit** [comment]
I think it would be an improvement if exceptions involved in creating a repr of anything from the javascript land would be suppressed by default, for example `<JsProxy id=1234 repr_error="repr failed with TypeError">`, so you would always get some string back.

Have a way to turn off the exception suppression so it can be debugged. Opt-in to it being possible for `repr()` to fail.

I didn't want to use the repr for anything apart from visualizing what was happening in the code (and the error was mostly happening during repr's created internally that I didn't even ask for).

On a side note, there seem to be a lot of JsProxy'd things that produce an empty string when you ask for a `str()` or a `repr()`, and I found this extremely unintuitive as I was trying to explore initially. `print(thing)` sometimes doesn't print anything, `print(type(thing))` sometimes doesn't print anything. I think I had to resort to like `print(type(thing).__name__)` to get any text.

I think it would also be an improvement if every repr() produced some string output even if it was only `<TheType(id=1234)>`.

Should I be the one to close the ticket?

**Comment by hoodmane** [comment]
It would be good to close this issue and create two new ones:
1. improve the repr for JsProxy
2. what to do about `bind` and `this`?
