### ISSUE TITLE
Package download is failing, problem with CDN

### ISSUE THREAD

**Issue by samuelcolvin** [pyodide/pyodide#2916]
See [this](https://github.com/samuelcolvin/pydantic-core/runs/7537317180?check_suite_focus=true) CI build.

It looks like downloading core packages like `pytest-7.1.2-py3-none-any.whl` is failing.

excerpt of output:

```
Didn't find package pytest-7.1.2-py3-none-any.whl, attempting to load from https://cdn.jsdelivr.net/pyodide/v0.21.0a3/full/
```

### Full CI Output:

<details>

```
> pydantic-core@1.0.0 test
> node tests/emscripten_runner.js

Loading distutils
Loaded distutils
Python initialization complete
distutils already loaded from default channel
Loading micropip, pyparsing, packaging, pytest, atomicwrites, attrs, six, more-itertools, pluggy, py, setuptools, iniconfig, pytz
Didn't find package micropip-0.1-py3-none-any.whl, attempting to load from https://cdn.jsdelivr.net/pyodide/v0.21.0a3/full/
(node:2126) ExperimentalWarning: The Fetch API is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
Didn't find package pyparsing-3.0.9-py3-none-any.whl, attempting to load from https://cdn.jsdelivr.net/pyodide/v0.21.0a3/full/
Didn't find package packaging-21.3-py3-none-any.whl, attempting to load from https://cdn.jsdelivr.net/pyodide/v0.21.0a3/full/
Didn't find package pytest-7.1.2-py3-none-any.whl, attempting to load from https://cdn.jsdelivr.net/pyodide/v0.21.0a3/full/
Didn't find package atomicwrites-1.4.0-py2.py3-none-any.whl, attempting to load from https://cdn.jsdelivr.net/pyodide/v0.21.0a3/full/
Didn't find package attrs-21.4.0-py2.py3-none-any.whl, attempting to load from https://cdn.jsdelivr.net/pyodide/v0.21.0a3/full/
Didn't find package six-1.16.0-py2.py3-none-any.whl, attempting to load from https://cdn.jsdelivr.net/pyodide/v0.21.0a3/full/
Didn't find package more_itertools-8.13.0-py3-none-any.whl, attempting to load from https://cdn.jsdelivr.net/pyodide/v0.21.0a3/full/
Didn't find package pluggy-1.0.0-py2.py3-none-any.whl, attempting to load from https://cdn.jsdelivr.net/pyodide/v0.21.0a3/full/
Didn't find package py-1.11.0-py2.py3-none-any.whl, attempting to load from https://cdn.jsdelivr.net/pyodide/v0.21.0a3/full/
Didn't find package setuptools-62.6.0-py3-none-any.whl, attempting to load from https://cdn.jsdelivr.net/pyodide/v0.21.0a3/full/
Didn't find package iniconfig-1.1.1-py2.py3-none-any.whl, attempting to load from https://cdn.jsdelivr.net/pyodide/v0.21.0a3/full/
Didn't find package pytz-2022.1-py2.py3-none-any.whl, attempting to load from https://cdn.jsdelivr.net/pyodide/v0.21.0a3/full/
Package attrs-21.4.0-py2.py3-none-any.whl loaded from https://cdn.jsdelivr.net/pyodide/v0.21.0a3/full/, caching the wheel in node_modules for future use.
Package pluggy-1.0.0-py2.py3-none-any.whl loaded from https://cdn.jsdelivr.net/pyodide/v0.21.0a3/full/, caching the wheel in node_modules for future use.
Package atomicwrites-1.4.0-py2.py3-none-any.whl loaded from https://cdn.jsdelivr.net/pyodide/v0.21.0a3/full/, caching the wheel in node_modules for future use.
Package more_itertools-8.13.0-py3-none-any.whl loaded from https://cdn.jsdelivr.net/pyodide/v0.21.0a3/full/, caching the wheel in node_modules for future use.
Package micropip-0.1-py3-none-any.whl loaded from https://cdn.jsdelivr.net/pyodide/v0.21.0a3/full/, caching the wheel in node_modules for future use.
Package iniconfig-1.1.1-py2.py3-none-any.whl loaded from https://cdn.jsdelivr.net/pyodide/v0.21.0a3/full/, caching the wheel in node_modules for future use.
Package pyparsing-3.0.9-py3-none-any.whl loaded from https://cdn.jsdelivr.net/pyodide/v0.21.0a3/full/, caching the wheel in node_modules for future use.
Package packaging-21.3-py3-none-any.whl loaded from https://cdn.jsdelivr.net/pyodide/v0.21.0a3/full/, caching the wheel in node_modules for future use.
Package py-1.11.0-py2.py3-none-any.whl loaded from https://cdn.jsdelivr.net/pyodide/v0.21.0a3/full/, caching the wheel in node_modules for future use.
Package six-1.16.0-py2.py3-none-any.whl loaded from https://cdn.jsdelivr.net/pyodide/v0.21.0a3/full/, caching the wheel in node_modules for future use.
Package setuptools-62.6.0-py3-none-any.whl loaded from https://cdn.jsdelivr.net/pyodide/v0.21.0a3/full/, caching the wheel in node_modules for future use.
Package pytest-7.1.2-py3-none-any.whl loaded from https://cdn.jsdelivr.net/pyodide/v0.21.0a3/full/, caching the wheel in node_modules for future use.
Package pytz-2022.1-py2.py3-none-any.whl loaded from https://cdn.jsdelivr.net/pyodide/v0.21.0a3/full/, caching the wheel in node_modules for future use.
Loaded attrs, pluggy, atomicwrites, more-itertools, micropip, iniconfig, pyparsing, packaging, py, six, pytest, setuptools, pytz
Loading typing-extensions, pygments
Didn't find package typing_extensions-4.2.0-py3-none-any.whl, attempting to load from https://cdn.jsdelivr.net/pyodide/v0.21.0a3/full/
Didn't find package Pygments-2.12.0-py3-none-any.whl, attempting to load from https://cdn.jsdelivr.net/pyodide/v0.21.0a3/full/
Package typing_extensions-4.2.0-py3-none-any.whl loaded from https://cdn.jsdelivr.net/pyodide/v0.21.0a3/full/, caching the wheel in node_modules for future use.
Package Pygments-2.12.0-py3-none-any.whl loaded from https://cdn.jsdelivr.net/pyodide/v0.21.0a3/full/, caching the wheel in node_modules for future use.
PythonError: Traceback (most recent call last):
  File "/lib/python3.10/asyncio/futures.py", line 201, in result
    raise self._exception
  File "/lib/python3.10/asyncio/tasks.py", line 234, in __step
    result = coro.throw(exc)
  File "/lib/python3.10/site-packages/_pyodide/_base.py", line 505, in eval_code_async
    await CodeRunner(
  File "/lib/python3.10/site-packages/_pyodide/_base.py", line 358, in run_async
    await coroutine
  File "<exec>", line 9, in <module>
  File "/lib/python3.10/site-packages/micropip/_micropip.py", line 576, in install
    await gather(*wheel_promises)
  File "/lib/python3.10/asyncio/futures.py", line 284, in __await__
    yield self  # This tells Task to wait for completion.
  File "/lib/python3.10/asyncio/tasks.py", line 304, in __wakeup
    future.result()
  File "/lib/python3.10/asyncio/futures.py", line 201, in result
    raise self._exception
pyodide.JsException: Error: bad export type for `_emscripten_get_now`: undefined

    at new_error (/home/runner/work/pydantic-core/pydantic-core/node_modules/pyodide/pyodide.asm.js:10:215112)
    at wasm://wasm/02[19](https://github.com/samuelcolvin/pydantic-core/runs/7537317180?check_suite_focus=true#step:13:20)efae:wasm-function[271]:0xdec35
    at wasm://wasm/0[21](https://github.com/samuelcolvin/pydantic-core/runs/7537317180?check_suite_focus=true#step:13:22)9efae:wasm-function[370]:0xe2e36
    at method_call_trampoline (/home/runner/work/pydantic-core/pydantic-core/node_modules/pyodide/pyodide.asm.js:10:215026)
    at wasm://wasm/0219efae:wasm-function[934]:0x1[25](https://github.com/samuelcolvin/pydantic-core/runs/7537317180?check_suite_focus=true#step:13:26)99b
    at wasm://wasm/0219efae:wasm-function[3184]:0x1f65b2
    at wasm://wasm/0219efae:wasm-function[1847]:0x1610b6
    at wasm://wasm/0219efae:wasm-function[939]:0x125eab
    at wasm://wasm/0219efae:wasm-function[940]:0x125fa5
    at wasm://wasm/0219efae:wasm-function[941]:0x1[26](https://github.com/samuelcolvin/pydantic-core/runs/7537317180?check_suite_focus=true#step:13:27)048
    at wasm://wasm/0219efae:wasm-function[3010]:0x1dfd1b
    at wasm://wasm/0219efae:wasm-function[3007]:0x1d9d[29](https://github.com/samuelcolvin/pydantic-core/runs/7537317180?check_suite_focus=true#step:13:30)
    at wasm://wasm/0219efae:wasm-function[942]:0x12608b
    at wasm://wasm/0219efae:wasm-function[[30](https://github.com/samuelcolvin/pydantic-core/runs/7537317180?check_suite_focus=true#step:13:31)19]:0x1e1b10
    at wasm://wasm/0219efae:wasm-function[3010]:0x1df75d
    at wasm://wasm/0219efae:wasm-function[3007]:0x1d9d29
    at wasm://wasm/0219efae:wasm-function[942]:0x12608b
    at wasm://wasm/0219efae:wasm-function[365]:0xe2b02
    at Module.callPyObjectKwargs (/home/runner/work/pydantic-core/pydantic-core/node_modules/pyodide/pyodide.asm.js:10:117602)
    at Module.callPyObject (/home/runner/work/pydantic-core/pydantic-core/node_modules/pyodide/pyodide.asm.js:10:117983)
    at Timeout.wrapper [as _onTimeout] (/home/runner/work/pydantic-core/pydantic-core/node_modules/pyodide/pyodide.asm.js:10:180736)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7) {
  __error_address: 173390[32](https://github.com/samuelcolvin/pydantic-core/runs/7537317180?check_suite_focus=true#step:13:33)
}
```
</details>

**Comment by samuelcolvin** [comment]
The CDN problems seems to have fixed itself, but while we're here, I would suggest that 

```
pyodide.JsException: Error: bad export type for `_emscripten_get_now`: undefined
```

Suggests there's an error processing the error? Otherwise feel free to close.

**Comment by samuelcolvin** [comment]
Error is intermittent, I'm getting it [again](https://github.com/samuelcolvin/pydantic-core/runs/7538465701?check_suite_focus=true) :disappointed:.

**Comment by hoodmane** [comment]
This isn't a CDN problem at all but instead an issue with the `instant` library required by parking_lot v0.11. PyO3 requires [parking_lot >= 0.11, <0.13](https://github.com/PyO3/pyo3/blob/v0.16.5/Cargo.toml#L19). [You should lock parking_lot v0.12.1 instead of v0.11](https://github.com/samuelcolvin/pydantic-core/blob/dd3ceaa8a553d837ca7f579259b0061fcb900a64/Cargo.lock#L172). I think this should fix the problem.

**Comment by hoodmane** [comment]
Not sure why the error is intermittent. Maybe it sometimes uses parking_lot v0.12 and sometimes v0.11? Or are we properly respecting the lock file when building?

**Comment by hoodmane** [comment]
Is it possible to force a fresh build (rust-cache miss)? I think this would provide some useful extra context.

**Comment by samuelcolvin** [comment]
Doesn't seem to be a way to prompt rebuild skipping the cache.
