### ISSUE TITLE
Scipy build failing with Cython error

### ISSUE THREAD

**Issue by ryanking13** [pyodide/pyodide#2918]
## 🐛 Bug

Scipy build is failing in [main](https://app.circleci.com/pipelines/github/ryanking13/pyodide/705/workflows/f75c57c6-95c0-4437-85ca-47889051954d/jobs/11444?invite=true#step-105-1365). I guess it is related to the new Cython release.

```
_stats.pyx:173:0: Referring to a memoryview typed argument directly in a nested closure function is not supported in Cython 0.x. Either upgrade to Cython 3, or assign the argument to a local variable and use that in the nested function.
Traceback (most recent call last):
  File "/root/repo/packages/scipy/build/scipy-1.8.1/tools/cythonize.py", line 317, in <module>
    main()
  File "/root/repo/packages/scipy/build/scipy-1.8.1/tools/cythonize.py", line 313, in main
    find_process_files(root_dir)
  File "/root/repo/packages/scipy/build/scipy-1.8.1/tools/cythonize.py", line 302, in find_process_files
    for result in pool.imap_unordered(lambda args: process(*args), jobs):
  File "/usr/local/lib/python3.10/multiprocessing/pool.py", line 870, in next
    raise value
  File "/usr/local/lib/python3.10/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/root/repo/packages/scipy/build/scipy-1.8.1/tools/cythonize.py", line 302, in <lambda>
    for result in pool.imap_unordered(lambda args: process(*args), jobs):
  File "/root/repo/packages/scipy/build/scipy-1.8.1/tools/cythonize.py", line 236, in process
    processor_function(fromfile, tofile, cwd=path)
  File "/root/repo/packages/scipy/build/scipy-1.8.1/tools/cythonize.py", line 102, in process_pyx
    raise Exception('Cython failed')
Exception: Cython failed
```

**Comment by ryanking13** [comment]
Upstream (scipy) issue tracking this bug: https://github.com/scipy/scipy/issues/16718

**Comment by rth** [comment]
We should pin the cython version used, as it's likely to be forward incompatible, particularly once the long-awaited 3.0 version is released.

**Comment by ryanking13** [comment]
Or we can think of adding a new patch for scipy until they release 1.9.0.

**Comment by rth** [comment]
As you prefer. But it's really upstream job to fix these things, we are just building the latest version that is known to work. So there is no real advantage for us to run the latest Cython in this particular case.
