### ISSUE TITLE
pyodide build gives PermissionError: [Errno 13] Permission denied: 'C:\\Users\\xxx\\AppData\\Local\\Temp\\tmpkfa0byvg.tar'

### ISSUE THREAD

**Issue by viblo** [pyodide/pyodide#3025]
## 🐛 Bug

Im trying to build the pymunk package. However, when I run `pyodide build` from its folder I get either a permission error, or a 404 error depending on if I try with pyodide-build 0.21.0 or 0.22.0.dev0.

### To Reproduce

1. pip install pyodide-build
2. Checkout pymunk from source https://github.com/viblo/pymunk.git
3. go the pymunk folder, and run pyodide build

Error from 0.21.0
```
(base) C:\code\gh\viblo\pymunk>pyodide build
Traceback (most recent call last):
  File "C:\Users\xxx\miniforge3\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\xxx\miniforge3\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\xxx\miniforge3\Scripts\pyodide.exe\__main__.py", line 7, in <module>
  File "C:\Users\xxx\miniforge3\lib\site-packages\pyodide_build\out_of_tree\__main__.py", line 29, in main
    ensure_env_installed(env)
  File "C:\Users\xxx\miniforge3\lib\site-packages\pyodide_build\out_of_tree\__main__.py", line 14, in ensure_env_installed
    download_xbuild_env(__version__, env)
  File "C:\Users\xxx\miniforge3\lib\site-packages\pyodide_build\install_xbuildenv.py", line 30, in download_xbuild_env
    urlretrieve(
  File "C:\Users\xxx\miniforge3\lib\urllib\request.py", line 251, in urlretrieve
    tfp = open(filename, 'wb')
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\xxx\\AppData\\Local\\Temp\\tmpkfa0byvg.tar'
```
Error from 0.22.0.dev0
```
(base) C:\code\gh\viblo\pymunk>pyodide build
Traceback (most recent call last):
  File "C:\Users\xxx\miniforge3\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\xxx\miniforge3\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\xxx\miniforge3\Scripts\pyodide.exe\__main__.py", line 7, in <module>
  File "C:\Users\xxx\miniforge3\lib\site-packages\pyodide_build\out_of_tree\__main__.py", line 29, in main
    ensure_env_installed(env)
  File "C:\Users\xxx\miniforge3\lib\site-packages\pyodide_build\out_of_tree\__main__.py", line 14, in ensure_env_installed
    download_xbuild_env(__version__, env)
  File "C:\Users\xxx\miniforge3\lib\site-packages\pyodide_build\install_xbuildenv.py", line 30, in download_xbuild_env
    urlretrieve(
  File "C:\Users\xxx\miniforge3\lib\urllib\request.py", line 241, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "C:\Users\xxx\miniforge3\lib\urllib\request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Users\xxx\miniforge3\lib\urllib\request.py", line 525, in open
    response = meth(req, response)
  File "C:\Users\xxx\miniforge3\lib\urllib\request.py", line 634, in http_response
    response = self.parent.error(
  File "C:\Users\xxx\miniforge3\lib\urllib\request.py", line 563, in error
    return self._call_chain(*args)
  File "C:\Users\xxx\miniforge3\lib\urllib\request.py", line 496, in _call_chain
    result = func(*args)
  File "C:\Users\xxx\miniforge3\lib\urllib\request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
```
### Expected behavior

No error and package built. :) 

### Environment

- pyodide-build 0.21.0 or 0.22.0.dev0
- Python 3.10 64bit, through conda (miniforge)
- Windows 11

**Comment by ryanking13** [comment]
Thanks for the report! Probably we should not use `urlretrieve` which saves the file in an arbitrary directory.

**Comment by viblo** [comment]
I did some small debugging myself, and the reason why 0.22.0.dev0 reports 404 is because https://github.com/pyodide/pyodide/releases/download/0.22.0.dev0/xbuildenv-0.22.0.dev0.tar.bz2 does not exists.

**Comment by viblo** [comment]
And some more debugging: the permission error is because pyodide build doesnt support Windows (or at least I think it doesnt). The error comes because it uses a NamedTemporaryFile, but on windows you can not open it again, which you can on Linux. I fixed it locally, but then got other errors about make missing. Since it looks like more than a small issue I assume Windows is out of scope. 

Maybe this could be made clearer in the documentation, and / or also marked on the package in pypi (now classified as os independent)? 

I see that in the instructions for building pyodide itself its clearly written it works best on Linux (but MacOS might work). However, if Im only interested in building a package and not pyodide itself I will skip directly to the Creating a pyodide package instruction, which doesnt mention anything.

**Comment by ryanking13** [comment]
> I did some small debugging myself, and the reason why 0.22.0.dev0 reports 404 is because https://github.com/pyodide/pyodide/releases/download/0.22.0.dev0/xbuildenv-0.22.0.dev0.tar.bz2 does not exists. It seems like dev-builds are not released on github.

Yes, we release xbuildenv on each release so you can't use it in dev version. It would be nice to add a proper error message when people try to use xbuildenv in dev versions.

> Maybe this could be made clearer in the documentation, and / or also marked on the package in pypi (now classified as os independent)?

Sorry for your inconvenience. out-of-tree build is still in a very experimental stage so it is not well documented and prone to break. Currently, pyodide build system uses Make and some shell scripts, so I think I guess it would not work well in Windows.

**Comment by ryanking13** [comment]
I don't think this happens anymore. Also, pyodide-build has no plans to support Windows. I'll close this as not-planned, but please don't hesitate to comment more if you have any other thoughts.
