### ISSUE TITLE
Cannot install `ruamel.yaml`: `Can't find a pure Python 3 wheel for ruamel-yaml-clib>=0.2.6`

### ISSUE THREAD

**Issue by astrojuanlu** [pyodide/pyodide#3034]
## 🐛 Bug

I cannot install `ruamel.yaml` on Pyodide.

### To Reproduce

```
>>> await micropip.install('ruamel.yaml', keep_going=True)
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/lib/python3.10/site-packages/micropip/_micropip.py", line 552, in install
    raise ValueError(
ValueError: Can't find a pure Python 3 wheel for: 'ruamel-yaml-clib>=0.2.6; platform_python_implementation == "CPython" and python_version < "3.11"'
See: https://pyodide.org/en/stable/usage/faq.html#micropip-can-t-find-a-pure-python-wheel
```

I see that this dependency should only be installed for CPython, but apparently `micropip` is trying to pull it anyways?

### Expected behavior

Installing `ruamel.yaml` works.

### Environment

- Pyodide Version: _How can I know? I'm on https://pyodide.org/en/latest/console.html_ 
- Browser version: Firefox 104.0

**Comment by astrojuanlu** [comment]
(Note that `ruamel.yaml` itself seems to be available, see https://github.com/pyodide/pyodide/issues/2771)

**Comment by hoodmane** [comment]
Thanks for the report.

> I see that this dependency should only be installed for CPython

Well technically that's the correct behavior. Pyodide is CPython. But we would need to have a version of the binary extension built for our `wasm32_emscripten` platform.

> Pyodide Version: How can I know? 

`import pyodide; print(pyodide.__version__)`. We should update our issue template I guess.

**Comment by ryanking13** [comment]
`ruamel.yaml` works without `ruamel.yaml.clib` (it might be slow, but works). The issue is that we are using the incorrect package name for `ruamel.yaml` in Pyodide: `ruamel`. I think I fixed this in #2637. I'll split out a PR from it that fixes this issue first.

**Comment by hoodmane** [comment]
Seems like #2637 isn't the correct PR.

**Comment by ryanking13** [comment]
> Seems like #2637 isn't the correct PR.

Right, it is #3006. 👀

**Comment by astrojuanlu** [comment]
Now that gh-3006 has been merged, what would be the fastest way of trying it apart from compiling `main` from source? I see that https://pyodide.org/en/latest/console.html is using `https://cdn.jsdelivr.net/pyodide/dev/full/pyodide.js`, and that

```
>>> import pyodide; print(pyodide.__version__)
0.22.0.dev0
```

However, the version string does not say which commit is it running, and I'm not sure if there's some other process that needs to complete.

(Sorry if I sound like the pain in the neck, I have no idea about web frontend but I'd like to understand more about the Pyodide/PyScript to be more effective at reporting and triaging bugs)

**Comment by ryanking13** [comment]
> Now that [gh-3006](https://github.com/pyodide/pyodide/pull/3006) has been merged, what would be the fastest way of trying it apart from compiling `main` from source? I see that https://pyodide.org/en/latest/console.html is using `https://cdn.jsdelivr.net/pyodide/dev/full/pyodide.js`, and that

The latest commit in the main branch will be deployed to https://pyodide.org/en/latest/console.html. But it will take some time until the CI pass and CDN providers cache it (around few hours).

If you don't want to wait, you can download the build artifact (`pyodide.tar.gz`) from `build-packages` CI job (https://app.circleci.com/pipelines/github/pyodide) then [serve them locally](https://pyodide.org/en/stable/usage/downloading-and-deploying.html?highlight=http.server#serving-locally).

**Comment by hoodmane** [comment]
> it is a bug in micropip which is happening because it canonicalize the requested package name.

I don't think this is correct. I did the following:
```
pyodide.loadPackage("micropip");
pyodide.runPythonAsyinc(`import micropip; await micropip.install("ruamel.yaml", deps=False)`);
pyodide.runPython(`
import sys
from ruamel.yaml import YAML
yaml = YAML()
d = dict(a=dict(b=2),c=[3, 4])
yaml.dump(d, sys.stdout)
`);
```
and it printed:
```
a:
  b: 2
c:
- 3
- 4
```
So I think it works fine. If you try without `deps=False`, then you get an error about `ruamel-yaml-clib`, which we aren't building. The solution would be to build `ruamel-yaml-clib` as well.

**Comment by rth** [comment]
Hmm, but isn't the point that we are now distributing that package [as part of the Pyodide distribution](https://github.com/pyodide/pyodide/blob/main/packages/ruamel.yaml/meta.yaml) now and `ruamel-yaml-clib` is not in the Pyodide dependency tree. Or are we also parsing wheel dependencies even for packages that we ship? If so that sounds like a bug.

**Comment by hoodmane** [comment]
Perhaps as @ryanking13 says it is the name normalization: the name gets normalized to `ruamel-yaml`, we check if we have it but we don't have it so we download it from PyPI.

**Comment by ryanking13** [comment]
Yes, as rth mentioned, we have ruamel.yaml in our distribution so `micropip.install` should not search it from PyPI.

It seems like the bug is [happening here](https://github.com/pyodide/pyodide/blob/555f7828f4339b056f2d32b821e6a752784f4729/packages/micropip/src/micropip/_micropip.py#L389-L402). `req.name in REPODATA_PACKAGES` returns False, as the canonicalized name of `ruamel.yaml` is `ruamel-yaml` while the key in REPODATA_PACAKGES is `ruamel.yaml`.

**Comment by hoodmane** [comment]
So instead of:
```py
REPODATA_PACKAGES = pyodide_js._api.repodata_packages.to_py()
```
we should do:
```py
REPODATA_PACKAGES = {canonicalize_name(k) : v for k,v in repodata_packages.object_entries()}
```

**Comment by ryanking13** [comment]
Yes, I think that would work.

I hope `micropip.list()` and `micropip.freeze()` will show correct package names with that change. I think it will as we now load package names using importlib.metadata thanks to your fix in #2572.

**Comment by techtonik** [comment]
So not fixed yet? https://pyodide.org/en/latest/console.html

```python
>>> import pyodide; print(pyodide.__version__)
0.22.0.dev0
>>> await micropip.install('ruamel.yaml', keep_going=True)
Traceback (most recent call last):
  File "<console>", line 1, in <module>
NameError: name 'micropip' is not defined
>>> import micropip
>>> await micropip.install('ruamel.yaml', keep_going=True)
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/lib/python3.10/site-packages/micropip/_micropip.py", line 551, in install
    raise ValueError(
ValueError: Can't find a pure Python 3 wheel for: 'ruamel-yaml-clib>=0.2.6; platform_python_implementation == "CPython" and python_version < "3.11"'
See: https://pyodide.org/en/stable/usage/faq.html#micropip-can-t-find-a-pure-python-wheel
```

**Comment by ryanking13** [comment]
@techtonik No, it is not fixed yet. Dealing with package names often caused some trouble so we need to check if the suggested change would result in an unexpected error. I'll try to fix this when I have time, but it is not my top-1 priority, so if you have interest in fixing this, don't hesitate to open a PR in micropip/pyodide.

**Comment by ryanking13** [comment]
I don't remember exactly when, but this was fixed a while ago.
