### ISSUE TITLE
pyodide-xbuildenv : ensure_env_installed should only run when using xbuildenv

### ISSUE THREAD

**Issue by rth** [pyodide/pyodide#3063]
Currently,
```bash
pyodide --help
```
tries to run `ensure_env_installed` and fetches the corresponding archive. 
```bash
pyodide --help  # followed by Control+C
Traceback (most recent call last):
  File "/home/rth/.miniforge/envs/pyodide-env/bin/pyodide", line 8, in <module>
    sys.exit(main())
  File "/home/rth/src/pyodide/pyodide-build/pyodide_build/out_of_tree/__main__.py", line 29, in main
    ensure_env_installed(env)
  File "/home/rth/src/pyodide/pyodide-build/pyodide_build/out_of_tree/__main__.py", line 14, in ensure_env_installed
    download_xbuild_env(__version__, env)
  File "/home/rth/src/pyodide/pyodide-build/pyodide_build/install_xbuildenv.py", line 30, in download_xbuild_env
    urlretrieve(
  File "/home/rth/.miniforge/envs/pyodide-env/lib/python3.10/urllib/request.py", line 241, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/home/rth/.miniforge/envs/pyodide-env/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/home/rth/.miniforge/envs/pyodide-env/lib/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/home/rth/.miniforge/envs/pyodide-env/lib/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/home/rth/.miniforge/envs/pyodide-env/lib/python3.10/urllib/request.py", line 563, in error
    return self._call_chain(*args)
  File "/home/rth/.miniforge/envs/pyodide-env/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/home/rth/.miniforge/envs/pyodide-env/lib/python3.10/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
```

This should not happen. It would probably be fixed as we migrate to using `pyodide-cli`, but something to keep in mind.

**Comment by ryanking13** [comment]
This issue seems outdated. We don't experience it anymore. Closing.
