### ISSUE TITLE
Loading packages when importing other python files

### ISSUE THREAD

**Issue by kolibril13** [pyodide/pyodide#3155]
## 🚀 Feature

As discussed in #3126, it would be amazing to automatically import modules into pyodide that are present in other imported python files. 
Currently, these modules imports have to be made seperately.
Here is a demo [Pyodide terminal](https://pyodide.org/en/stable/console.html) what is meant by this:

```
Welcome to the Pyodide terminal emulator 🐍
Python 3.10.2 (main, Sep 15 2022 23:28:12) on WebAssembly/Emscripten
Type "help", "copyright", "credits" or "license" for more information.
>>> filename = "numpytest.py"
code = """
print("Hello Numpy")
import numpy
print(f"{numpy.euler_gamma = }")
"""
with open(filename, "w") as f:
    f.write(code)
... 
68
>>> from numpytest import *
Hello Numpy
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/home/pyodide/numpytest.py", line 3, in <module>
    import numpy
ModuleNotFoundError: No module named 'numpy'
>>> import numpy
>>> from numpytest import *
Hello Numpy
numpy.euler_gamma = 0.5772156649015329
 ```
Basically, it would be nice to not have the `ModuleNotFoundError`.
 
I am not a Pyodide expert, but here are two naive implementation ideas to load these modules:
1. One could write Exceptions for the `ModuleNotFoundError` error that import the missing modules.
2. One could go with regex over the python file, look for the package import lines, and then inject `pyodide.loadPackage` for the wanted packages before importing the python file.

### Motivation

Why is this feature useful? This would enable Jupyter notebook collections to run in JupyterLite without code adjustemens, and this would e.g. lower the barrier to teach science with JupyterLite.

**Comment by hoodmane** [comment]
I think this is not feasible without [stack switching] (https://github.com/WebAssembly/stack-switching) currently feature gated in chrome and unavailable in other browser engines.

The problem:
1. Python imports are synchronous
2. Python imports are dynamic: there is no way to know what a program imports without running it
3. Loading a package is asynchronous

So the only option that works generally is to run the code till it fails, quit out and load a package then rerun the code from the beginning. There is no way to know whether rerunning has side effects though.

Another option is to greadily assume all imports happen but this will both install unneeded things and fail to install some needed things. Perhaps it's worth trying this strategy and seeing if it works in a satisfactory manor.

With stack switching we could just pause the wasm stack, asynchronously load the package, and then resume wasm execution.

**Comment by ryanking13** [comment]
> 1. One could write Exceptions for the `ModuleNotFoundError` error that import the missing modules.

As Hood mentioned, I think this is impossible for now without stack switching.

> 2\. One could go with regex over the python file, look for the package import lines, and then inject `pyodide.loadPackage` for the wanted packages before importing the python file.

This is similar to what we are doing in our console now. We inject `pyodide.loadPackagesFromImports` before running every code passed to Pyodide console. So what we can try is adding a new function that extends `pyodide.loadPackagesFromImports` to work recursively in files.

Maybe some core devs of Pyodide would be interested in implementing this, but I don't have bandwidths to look into this for now. Since this is about parsing codes and dealing with Python import system, I believe it won't require knowledge about Pyodide internals. So it would be really nice if @kolibril13 or someone else try implementing this feature and open a PR.

You can find a code that parses import statements from Python code string [here](https://github.com/pyodide/pyodide/blob/9af9bee60b1ce860bb53e98fdda83f924fa7f720/src/py/_pyodide/_base.py#L543).

**Comment by jobovy** [comment]
My unsolicited two cents on this is that I think that the premise is invalid. @kolibril13 says 

> This would enable Jupyter notebook collections to run in JupyterLite without code adjustemens, and this would e.g. lower the barrier to teach science with JupyterLite.

but I think requiring JupyterLab notebooks to just run in JupyterLite/pyodide is a false equivalency. Jupyter notebooks don't just run in Jupyterlab either, you first have to install all necessary requirements. The example given doesn't work in a pure standard-library Python installation either, you would first have to install ``numpy`` from ``pip`` or ``conda`` or whatever. 

I don't see how a pyodide-hosted solution could possibly work in general and in the long run. In the long term, pyodide users might be ``micropip``-installing packages from multiple indices or locally created wheels and they may use things like @emscripten-forge, much like people mix conda and pip in regular Python work these days. So how would an automatic installer know where to look for packages? 

In the end, I think the onus is on a website creator to install the necessary packages and for tools like JupyterLite to make that easy to hide from inexperienced end users (I do agree that this is important when, e.g., teaching). For example, with something like https://github.com/jupyterlite/jupyterlite/pull/811 in, creators of JupyterLite sites can hide the installation from their users. I've advocated for allowing more general code to be pre-run and hidden from users (https://github.com/jupyterlite/jupyterlite/issues/508), but the JupyterLite devs have not been welcoming of this approach. A binder-like service for JupyterLite could also support this, maybe more easily mixing packages from different sources. And users who know about ``micropip.install`` can install more packages during their session, much like users who know about it can use ``%pip`` and other magic commands to install packages in JupyterLab now.

**Comment by rth** [comment]
Thanks for the discussion! Overall I'm also -1 for hacking the import system to make this work even if it was technically possible (which isn't currently). Installing things based on import is rather dangerous and brittle. It's OK for a pre-validated list in `repodata.json` but it's hard to explain to users the difference between those and packages installed from PyPI, and difficult to extend to a case where there isn't a `repodata.json` we fully control.

Having a variation of `pyodide.code.find_imports` that works recursively on a dir (or on a notebook), could be useful for us for a variety of reasons (e.g. to check that a package correctly defines dependencies). BTW, maybe it would be better to use https://docs.python.org/3/library/modulefinder.html instead of doing the manual AST parsing in the current use case? 
If anyone wants to then use this more complex import detection mechanism to install packages, it's their choice, but IMO this is out of scope for Pyodide. 

> In the end, I think the onus is on a website creator to install the necessary packages and for tools like JupyterLite to make that easy to hide from inexperienced end users 

+1. For Pyodide I think we should provide a simple API that works reliably. Parsing imports to determine packages to install works for simple code snippets. When applied to files or directories I think there are much more things that could go wrong (otherwise Python packages wouldn't have to manually specify requirements) and it would be better not to go in that direction.

That being said, feel free to experiment in a standalone package with the ideas you propose.
