### ISSUE TITLE
Installing shared libraries in Pyodide venv

### ISSUE THREAD

**Issue by rth** [pyodide/pyodide#3186]
I finally got to try the venv functionality https://github.com/pyodide/pyodide/pull/2976 with some experiments in https://github.com/lesteve/scikit-learn-tests-pyodide  overall it's very impressive especially that pip works and installs from JsDelivr. Kudos for this work @hoodmane !

One thing that could be improved, is that currently, it doesn't seem to handle shared libraries. For instance, if I install scipy,
```
pip install pyodide-build==0.22.0a1
pyodide venv .venv-pyodide
source .venv-pyodide/bin/activate
python -c "import sklearn.linalg"
```
produces,
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/rth/src/scikit-learn/.venv-pyodide/lib/python3.10/site-packages/scipy/linalg/__init__.py", line 197, in <module>
  File "/home/rth/src/scikit-learn/.venv-pyodide/lib/python3.10/site-packages/scipy/linalg/_misc.py", line 3, in <module>
  File "/home/rth/src/scikit-learn/.venv-pyodide/lib/python3.10/site-packages/scipy/linalg/blas.py", line 213, in <module>
ImportError: Could not load dynamic lib: /home/rth/src/scikit-learn/.venv-pyodide/lib/python3.10/site-packages/scipy/linalg/_fblas.cpython-310-wasm32-emscripten.so
```
I suspect this is because CLAPACK was not installed (this version works fine in the [0.22.0a1 REPL](https://pyodide.org/en/0.22.0a1/console.html) for instance). It's also not just a matter of downloading `clapack_all.so`, it the env needs to be told to likely pre-load it.

Another unrelated issue I found is that the venv Python REPL doesn't seem to be working for me. If I type,
```
$ python
>>> 1+1 
```
and press Enter, it just hangs. Although `python -c "print(1+1)"` does work as expected.

**Comment by hoodmane** [comment]
Some of these issues will be resolved in #3098 though it doesn't fix the shared library problems. @ryanking13's work on auditwheel-emscripten in #3167 will also help. Loading all of scipy, numpy, etc takes almost 10 seconds, and if we are doing it eagerly then `python -c 'print("hi")'` by itself takes 10 seconds (at least `python -v` is still fast because it quits early).

node v18 now can be used with stack switching if you pass `--experimental-wasm-stack-switching` which is pretty exciting. When I have some time in December I will play around with making a variation on this stuff targeting node >= 18 that uses stack switching to only load libraries that we need. This should be a huge startup boost when scipy is around.

> Another unrelated issue I found is that the venv Python REPL doesn't seem to be working for me. 

In my experience it doesn't quite hang. It seems to need a `ctrl+D` to cause it to execute. I investigated how to fix this but we would need something like GNU readline. The ordinary version uses `select`. In old versions of node, we would have to move Pyodide into a worker and then set up the usual elaborate nonsense. Probably too hard to be worth it.

With stack switching it should be possible to get GNU readline to work in close to the intended manner. We might even be able to patch the select syscall and avoid patching readline.

**Comment by hoodmane** [comment]
For now, we should merge #3098, release another alpha, and then we can finally get https://github.com/numpy/numpy/pull/21895 merged.

**Comment by hoodmane** [comment]
But I'm pretty busy with math research and teaching right now so if I am responsible I might not get around to this for a while.

**Comment by rth** [comment]
Thanks for the explanations!

> For now, we should merge https://github.com/pyodide/pyodide/pull/3098, release another alpha, and then we can finally get https://github.com/numpy/numpy/pull/21895 merged.

Sounds like a plan. We can probably also make the final release shortly. Solving all of those larger issues is going to take time anyway.

> But I'm pretty busy with math research and teaching right now so if I am responsible I might not get around to this for a while.

No worries, I'll look at whether we could merge https://github.com/pyodide/pyodide/pull/3098 with a few extra tests added.

> It seems to need a ctrl+D to cause it to execute

Ahh, yes, indeed .
