### ISSUE TITLE
`ValueError: module functions cannot set METH_CLASS or METH_STATIC` when importing the wheel built via `pyodide build`

### ISSUE THREAD

**Issue by s3131212** [pyodide/pyodide#3195]
## 🐛 Bug
I tried to build a Python wheel for [python-axolotl-curve25519](https://github.com/s3131212/python-axolotl-curve25519) using `pyodide build`, following the instruction [here](https://pyodide.org/en/stable/development/new-packages.html#building-python-wheels-out-of-tree), but when I import the package, it throws `ValueError: module functions cannot set METH_CLASS or METH_STATIC`.

### To Reproduce

```
git clone https://github.com/s3131212/python-axolotl-curve25519.git
cd python-axolotl-curve25519
pyodide build
```

Then import the package:
```html
<!DOCTYPE html>
<html>
  <head>
      <script src="https://cdn.jsdelivr.net/pyodide/v0.21.3/full/pyodide.js"></script>
  </head>
  <body>
    <script type="text/javascript">
      async function main(){
        const pyodide = await loadPyodide();
        await pyodide.loadPackage("micropip");
        const micropip = pyodide.pyimport("micropip");
        await micropip.install('python_axolotl_curve25519-0.4.1.post2-cp310-cp310-emscripten_3_1_14_wasm32.whl');
        console.log(pyodide.runPython('import axolotl_curve25519'))
      }
      main();
    </script>
  </body>
</html>
```

It throws:
```
Uncaught (in promise) PythonError: Traceback (most recent call last):
  File "/lib/python3.10/site-packages/_pyodide/_base.py", line 435, in eval_code
    .run(globals, locals)
  File "/lib/python3.10/site-packages/_pyodide/_base.py", line 304, in run
    coroutine = eval(self.code, globals, locals)
  File "<exec>", line 1, in <module>
ValueError: module functions cannot set METH_CLASS or METH_STATIC
```

### Expected behavior

Should run without error.

### Environment

- Pyodide Version:  0.21.3
- Browser version: Firefox 105.0.3
- Any other relevant information: installed `pyodide-build` via pip, the version is `0.21.0`

### Additional context
Tried importing version `0.21.0` in the browser, but it didn't help.  

This package runs perfectly in normal Python 3.10.7.  
I am not sure whether this is a bug related to pyodide or the package I'm trying to build, though.

**Comment by hoodmane** [comment]
Interesting! Thanks for the report @s3131212!
