### ISSUE TITLE
Xonsh calls unavailable call getrusage resource.getrusage(resource.RUSAGE_SELF)[:2]

### ISSUE THREAD

**Issue by stuaxo** [pyodide/pyodide#3302]
I attempted to start Xonsh the python based shell.

It dies trying to call - `resource.getrusage(resource.RUSAGE_SELF)[:2]`

[1]

This field is to get time since the start of the process - of all the fields, this one seems like it may be straightforward to fake since start time is the time code for pyodides starts.

It would be good if `resource.getusage` was at least partially implemented - it seems like it used to be with fake values, but trying to import it doesn't show anything in `resource` now.

![image](https://user-images.githubusercontent.com/179677/204541857-dc9f6621-ae64-4b3f-8f55-01877d81b86d.png)

[1] 
![image](https://user-images.githubusercontent.com/179677/204542067-97d15400-8b68-4500-9e1d-8ab38c9827ac.png)

**Comment by rth** [comment]
Thanks for the report. In the latest version, we raise a more informative warning,
```
>>> import resource
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/lib/python3.10/_pyodide/_importhook.py", line 175, in find_spec
    raise ModuleNotFoundError(
ModuleNotFoundError: The module 'resource' is removed from the Python standard library in the Pyodide distribution due to browse
r limitations. See https://pyodide.org/en/stable/usage/wasm-constraints.html for more details.
```
and also in CPython 3.11 it does say 
![image](https://user-images.githubusercontent.com/630936/204566501-ceb87baf-75e8-448c-b9bd-66ae6018811c.png)

So I would say this is the expected behavior and it's up to xonsh to handle the fact that `resource` may not be available on some platforms.

As a temporary solution, you could monkeypach `resource` either via https://github.com/pyodide/micropip/pull/26 (it should be released very soon) or manually so it wouldn't error in xonsh.

**Comment by stuaxo** [comment]
Cheers - I had a really quick go, and then got stuck because of the lack of threads.. is some sort of thread implementation in pyodides future ?

**Comment by rth** [comment]
See https://github.com/pyodide/pyodide/issues/237 one day probably, but likely not in the near future. Also even when it works, it would be based on WebWorkers, so likely with more limitation in terms of interactions with the DOM (including this this case some terminal).

You could try opening an issue about it https://github.com/xonsh/xonsh maybe they would have some ideas on how feasible it would be to make it work without threads (or there could be people there also interested in hacking on it).

**Comment by stuaxo** [comment]
If I can get enough info together, I'll open an issue in xonsh.

I really went down this rabbit hole as it would be useful to have some sort shell (possibly minimal) to poke around the file-system as it is.

What I really wanted to get at are the executable scripts, that python programs install into the path, for things that are more frameworky, so I could see just how far django gets before failing for instance.

It would be pretty useful in JupyterLite for stuff like magic % commands like `% ls` to have some sort of shell...  I might open a ticket there for now; there could be other solutions like busybox in wasm for instance.

**Comment by rth** [comment]
Indeed a shell would very useful!
