### ISSUE TITLE
Add WNTR 0.5.0

### ISSUE THREAD

**Issue by DanielHabenicht** [pyodide/pyodide#3305]
## 🐍 Package Request

- Package Name and Version : wntr
- Package URL : https://github.com/USEPA/WNTR
- Package Dependencies that needs to be resolved first: <none? Hopefully!>

Glad if I could provide a PR myself, but I have run into a problem with this Code not being packaged into the wheel: 
https://github.com/USEPA/WNTR/blob/9eef07462caaa0a6f0fe033e7ac481153bc3a5de/setup.py#L38-L66

**Comment by DanielHabenicht** [comment]
Seems like this is blocked by: https://github.com/pyodide/pyodide/issues/2711

**Comment by hoodmane** [comment]
It looks like `WNTR` has idiosyncratic build settings. The following seems to work:
```
BUILD_WNTR_EXTENSIONS=true pyodide build
```

**Comment by DanielHabenicht** [comment]
Unfortunatly this crashes for me: 

```bash
BUILD_WNTR_EXTENSIONS=true pyodide build
...
running build_ext
building 'wntr.sim.aml._evaluator' extension
cc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -O2 -g0 -fPIC -I/tmp/build-env-qgmcm_u_/lib/python3.10/site-packages/numpy/core/include -I./wntr/sim/aml -I/tmp/build-env-qgmcm_u_/include -I/root/repo/cpython/installs/python-3.10.2/include/python3.10 -c ./wntr/sim/aml/evaluator.cpp -o build/temp.emscripten_3_1_14_wasm32-cpython-310/./wntr/sim/aml/evaluator.o
Traceback (most recent call last):
  File "/tmp/tmp1ib6z1ch/cc", line 5, in <module>
    from pyodide_build.pywasmcross import compiler_main
  File "/usr/local/python/3.10.4/lib/python3.10/site-packages/pyodide_build/pywasmcross.py", line 690, in <module>
    compiler_main()
  File "/usr/local/python/3.10.4/lib/python3.10/site-packages/pyodide_build/pywasmcross.py", line 686, in compiler_main
    sys.exit(handle_command(args, replay_args))
  File "/usr/local/python/3.10.4/lib/python3.10/site-packages/pyodide_build/pywasmcross.py", line 662, in handle_command
    returncode = subprocess.run(new_args).returncode
  File "/usr/local/python/3.10.4/lib/python3.10/subprocess.py", line 501, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/local/python/3.10.4/lib/python3.10/subprocess.py", line 966, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/python/3.10.4/lib/python3.10/subprocess.py", line 1842, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'em++'
error: command '/tmp/tmp1ib6z1ch/cc' failed with exit code 1

ERROR Backend subproccess exited when trying to invoke build_wheel
```

**Comment by hoodmane** [comment]
I think the problem is that Emscripten isn't installed correctly. I'm not sure how to fix it though.
