### ISSUE TITLE
If `pyodide build` fails, then next call to `pyodide build` should start fresh?

### ISSUE THREAD

**Issue by josephrocca** [pyodide/pyodide#3425]
## 🐛 Bug

It seems like `pyodide build` is kinda "stateful" in some way, or has some persistent side effects. I'd have thought it'd start completely fresh each time (i.e. delete `.pyodide-xbuildenv` and any other state), but maybe some stuff is cached for performance reasons, or something?

I haven't got a clean reproduction unfortunately, but sometimes I get an error like the one below that goes away if I run `pyodide build` again without changing anything or doing anything at all. Please note that this issue is not related to the specifics of the error messages presented here - i.e. I'm not trying to "get past" this error. This bug report is about the inconsistency of consecutive calls to `pyodide build`.

```
running bdist_wheel
running build
running build_py
running create_version
running cmake_build
Extra cmake args: ['-DONNX_USE_LITE_PROTO=ON', '-DProtobuf_INCLUDE_DIR=/workspaces/onnx/protobuf/src', '-DProtobuf_LIBRARIES=/workspaces/onnx/protobuf/build_source', '-DProtobuf_LITE_LIBRARY=/workspaces/onnx/protobuf/build_source/libprotobuf-lite.a', '-Dpybind11_DIR=/usr/local/python/3.10.4/lib/python3.10/site-packages/pybind11/share/cmake/pybind11']
Using cmake args: ['/tmp/tmpmcx3hk29/cmake', '-DPYTHON_INCLUDE_DIR=/root/repo/cpython/installs/python-3.10.2/include/python3.10', '-DPYTHON_EXECUTABLE=/tmp/build-env-6xusqkkh/bin/python', '-DBUILD_ONNX_PYTHON=ON', '-DCMAKE_EXPORT_COMPILE_COMMANDS=ON', '-DONNX_NAMESPACE=onnx', '-DPY_EXT_SUFFIX=.cpython-310-wasm32-emscripten.so', '-DCMAKE_BUILD_TYPE=Release', '-DONNX_ML=1', '-DONNX_USE_LITE_PROTO=ON', '-DProtobuf_INCLUDE_DIR=/workspaces/onnx/protobuf/src', '-DProtobuf_LIBRARIES=/workspaces/onnx/protobuf/build_source', '-DProtobuf_LITE_LIBRARY=/workspaces/onnx/protobuf/build_source/libprotobuf-lite.a', '-Dpybind11_DIR=/usr/local/python/3.10.4/lib/python3.10/site-packages/pybind11/share/cmake/pybind11', '/workspaces/onnx']
configure: cmake -DCMAKE_C_COMPILER=/tmp/tmpmcx3hk29/cc -DCMAKE_CXX_COMPILER=/tmp/tmpmcx3hk29/c++ -DCMAKE_AR=/tmp/tmpmcx3hk29/ar -DCMAKE_C_COMPILER_AR=/tmp/tmpmcx3hk29/ar -DCMAKE_CXX_COMPILER_AR=/tmp/tmpmcx3hk29/ar -DPYTHON_INCLUDE_DIR=/root/repo/cpython/installs/python-3.10.2/include/python3.10 -DPYTHON_EXECUTABLE=/tmp/build-env-6xusqkkh/bin/python -DBUILD_ONNX_PYTHON=ON -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DONNX_NAMESPACE=onnx -DPY_EXT_SUFFIX=.cpython-310-wasm32-emscripten.so -DCMAKE_BUILD_TYPE=Release -DONNX_ML=1 -DONNX_USE_LITE_PROTO=ON -DProtobuf_INCLUDE_DIR=/workspaces/onnx/protobuf/src -DProtobuf_LIBRARIES=/workspaces/onnx/protobuf/build_source -DProtobuf_LITE_LIBRARY=/workspaces/onnx/protobuf/build_source/libprotobuf-lite.a -Dpybind11_DIR=/usr/local/python/3.10.4/lib/python3.10/site-packages/pybind11/share/cmake/pybind11 /workspaces/onnx -DCMAKE_TOOLCHAIN_FILE=/workspaces/onnx/emsdk/upstream/emscripten/cmake/Modules/Platform/Emscripten.cmake -DCMAKE_CROSSCOMPILING_EMULATOR=/workspaces/onnx/emsdk/node/14.18.2_64bit/bin/node;--experimental-wasm-bulk-memory;--experimental-wasm-threads
CMake Error at CMakeLists.txt:17 (project):
  The CMAKE_C_COMPILER:

    /tmp/tmph8ytv7hj/cc

  is not a full path to an existing compiler tool.
```

<details>
<summary>Click here for full logs</summary>

```
pyodide build
Downloading xbuild environment
Installing xbuild environment
* Creating virtualenv isolated environment...
find interpreter for spec PythonSpec(path=/usr/local/python/3.10.4/bin/python)
proposed PythonInfo(spec=CPython3.10.4.final.0-64, exe=/usr/local/python/3.10.4/bin/python, platform=linux, version='3.10.4 (main, Dec 19 2022, 20:24:16) [GCC 9.4.0]', encoding_fs_io=utf-8-utf-8)
accepted PythonInfo(spec=CPython3.10.4.final.0-64, exe=/usr/local/python/3.10.4/bin/python, platform=linux, version='3.10.4 (main, Dec 19 2022, 20:24:16) [GCC 9.4.0]', encoding_fs_io=utf-8-utf-8)
filesystem is case-sensitive
create virtual environment via CPython3Posix(dest=/tmp/build-env-6xusqkkh, clear=False, no_vcs_ignore=False, global=False)
create folder /tmp/build-env-6xusqkkh/bin
create folder /tmp/build-env-6xusqkkh/lib/python3.10/site-packages
write /tmp/build-env-6xusqkkh/pyvenv.cfg
        home = /usr/local/python/3.10.4/bin
        implementation = CPython
        version_info = 3.10.4.final.0
        virtualenv = 20.17.1
        include-system-site-packages = false
        base-prefix = /usr/local/python/3.10.4
        base-exec-prefix = /usr/local/python/3.10.4
        base-executable = /usr/local/python/3.10.4/bin/python
symlink /usr/local/python/3.10.4/bin/python to /tmp/build-env-6xusqkkh/bin/python
create virtualenv import hook file /tmp/build-env-6xusqkkh/lib/python3.10/site-packages/_virtualenv.pth
create /tmp/build-env-6xusqkkh/lib/python3.10/site-packages/_virtualenv.py
============================== target debug ==============================
debug via /tmp/build-env-6xusqkkh/bin/python /usr/local/python/3.10.4/lib/python3.10/site-packages/virtualenv/create/debug.py
{
  "sys": {
    "executable": "/tmp/build-env-6xusqkkh/bin/python",
    "_base_executable": "/tmp/build-env-6xusqkkh/bin/python",
    "prefix": "/tmp/build-env-6xusqkkh",
    "base_prefix": "/usr/local/python/3.10.4",
    "real_prefix": null,
    "exec_prefix": "/tmp/build-env-6xusqkkh",
    "base_exec_prefix": "/usr/local/python/3.10.4",
    "path": [
      "/workspaces/onnx/.pyodide-xbuildenv/xbuildenv/pyodide-root/packages/.artifacts/lib/python3.10/site-packages",
      "/usr/local/python/3.10.4/lib/python310.zip",
      "/usr/local/python/3.10.4/lib/python3.10",
      "/usr/local/python/3.10.4/lib/python3.10/lib-dynload",
      "/tmp/build-env-6xusqkkh/lib/python3.10/site-packages"
    ],
    "meta_path": [
      "<class '_virtualenv._Finder'>",
      "<class '_frozen_importlib.BuiltinImporter'>",
      "<class '_frozen_importlib.FrozenImporter'>",
      "<class '_frozen_importlib_external.PathFinder'>"
    ],
    "fs_encoding": "utf-8",
    "io_encoding": "utf-8"
  },
  "version": "3.10.4 (main, Dec 19 2022, 20:24:16) [GCC 9.4.0]",
  "makefile_filename": "/usr/local/python/3.10.4/lib/python3.10/config-3.10-x86_64-linux-gnu/Makefile",
  "os": "<module 'os' from '/usr/local/python/3.10.4/lib/python3.10/os.py'>",
  "site": "<module 'site' from '/usr/local/python/3.10.4/lib/python3.10/site.py'>",
  "datetime": "<module 'datetime' from '/usr/local/python/3.10.4/lib/python3.10/datetime.py'>",
  "math": "<module 'math' from '/usr/local/python/3.10.4/lib/python3.10/lib-dynload/math.cpython-310-x86_64-linux-gnu.so'>",
  "json": "<module 'json' from '/usr/local/python/3.10.4/lib/python3.10/json/__init__.py'>"
}
add seed packages via FromAppData(download=False, pip=bundle, via=copy, app_data_dir=/home/codespace/.local/share/virtualenv)
got embed update of distribution pip from /home/codespace/.local/share/virtualenv/wheel/3.10/embed/3/pip.json
got embed update of distribution pip from /home/codespace/.local/share/virtualenv/wheel/3.10/embed/3/pip.json
install pip from wheel /usr/local/python/3.10.4/lib/python3.10/site-packages/virtualenv/seed/wheels/embed/pip-22.3.1-py3-none-any.whl via CopyPipInstall
Attempting to acquire lock 139932925956432 on /home/codespace/.local/share/virtualenv/wheel/3.10/image/1/CopyPipInstall/pip-22.3.1-py3-none-any.lock
Lock 139932925956432 acquired on /home/codespace/.local/share/virtualenv/wheel/3.10/image/1/CopyPipInstall/pip-22.3.1-py3-none-any.lock
Attempting to release lock 139932925956432 on /home/codespace/.local/share/virtualenv/wheel/3.10/image/1/CopyPipInstall/pip-22.3.1-py3-none-any.lock
Lock 139932925956432 released on /home/codespace/.local/share/virtualenv/wheel/3.10/image/1/CopyPipInstall/pip-22.3.1-py3-none-any.lock
copy directory /home/codespace/.local/share/virtualenv/wheel/3.10/image/1/CopyPipInstall/pip-22.3.1-py3-none-any/pip to /tmp/build-env-6xusqkkh/lib/python3.10/site-packages/pip
copy /home/codespace/.local/share/virtualenv/wheel/3.10/image/1/CopyPipInstall/pip-22.3.1-py3-none-any/pip-22.3.1.virtualenv to /tmp/build-env-6xusqkkh/lib/python3.10/site-packages/pip-22.3.1.virtualenv
copy directory /home/codespace/.local/share/virtualenv/wheel/3.10/image/1/CopyPipInstall/pip-22.3.1-py3-none-any/pip-22.3.1.dist-info to /tmp/build-env-6xusqkkh/lib/python3.10/site-packages/pip-22.3.1.dist-info
changing mode of /tmp/build-env-6xusqkkh/bin/pip-3.10 to 757
changing mode of /tmp/build-env-6xusqkkh/bin/pip3 to 757
changing mode of /tmp/build-env-6xusqkkh/bin/pip to 757
changing mode of /tmp/build-env-6xusqkkh/bin/pip3.10 to 757
generated console scripts pip-3.10 pip pip3.10 pip3
write /tmp/build-env-6xusqkkh/pyvenv.cfg
        home = /usr/local/python/3.10.4/bin
        implementation = CPython
        version_info = 3.10.4.final.0
        virtualenv = 20.17.1
        include-system-site-packages = false
        base-prefix = /usr/local/python/3.10.4
        base-exec-prefix = /usr/local/python/3.10.4
        base-executable = /usr/local/python/3.10.4/bin/python
* Installing packages in isolated environment... (setuptools >= 40.8.0, wheel)
* Installing packages in isolated environment... (cython, pythran, setuptools<65.6.0)
* Getting dependencies for wheel...
* Installing packages in isolated environment... (pytest-runner, wheel)
* Installing packages in isolated environment... (cython, pythran, setuptools<65.6.0)
* Building wheel...
running bdist_wheel
running build
running build_py
running create_version
running cmake_build
Extra cmake args: ['-DONNX_USE_LITE_PROTO=ON', '-DProtobuf_INCLUDE_DIR=/workspaces/onnx/protobuf/src', '-DProtobuf_LIBRARIES=/workspaces/onnx/protobuf/build_source', '-DProtobuf_LITE_LIBRARY=/workspaces/onnx/protobuf/build_source/libprotobuf-lite.a', '-Dpybind11_DIR=/usr/local/python/3.10.4/lib/python3.10/site-packages/pybind11/share/cmake/pybind11']
Using cmake args: ['/tmp/tmpmcx3hk29/cmake', '-DPYTHON_INCLUDE_DIR=/root/repo/cpython/installs/python-3.10.2/include/python3.10', '-DPYTHON_EXECUTABLE=/tmp/build-env-6xusqkkh/bin/python', '-DBUILD_ONNX_PYTHON=ON', '-DCMAKE_EXPORT_COMPILE_COMMANDS=ON', '-DONNX_NAMESPACE=onnx', '-DPY_EXT_SUFFIX=.cpython-310-wasm32-emscripten.so', '-DCMAKE_BUILD_TYPE=Release', '-DONNX_ML=1', '-DONNX_USE_LITE_PROTO=ON', '-DProtobuf_INCLUDE_DIR=/workspaces/onnx/protobuf/src', '-DProtobuf_LIBRARIES=/workspaces/onnx/protobuf/build_source', '-DProtobuf_LITE_LIBRARY=/workspaces/onnx/protobuf/build_source/libprotobuf-lite.a', '-Dpybind11_DIR=/usr/local/python/3.10.4/lib/python3.10/site-packages/pybind11/share/cmake/pybind11', '/workspaces/onnx']
configure: cmake -DCMAKE_C_COMPILER=/tmp/tmpmcx3hk29/cc -DCMAKE_CXX_COMPILER=/tmp/tmpmcx3hk29/c++ -DCMAKE_AR=/tmp/tmpmcx3hk29/ar -DCMAKE_C_COMPILER_AR=/tmp/tmpmcx3hk29/ar -DCMAKE_CXX_COMPILER_AR=/tmp/tmpmcx3hk29/ar -DPYTHON_INCLUDE_DIR=/root/repo/cpython/installs/python-3.10.2/include/python3.10 -DPYTHON_EXECUTABLE=/tmp/build-env-6xusqkkh/bin/python -DBUILD_ONNX_PYTHON=ON -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DONNX_NAMESPACE=onnx -DPY_EXT_SUFFIX=.cpython-310-wasm32-emscripten.so -DCMAKE_BUILD_TYPE=Release -DONNX_ML=1 -DONNX_USE_LITE_PROTO=ON -DProtobuf_INCLUDE_DIR=/workspaces/onnx/protobuf/src -DProtobuf_LIBRARIES=/workspaces/onnx/protobuf/build_source -DProtobuf_LITE_LIBRARY=/workspaces/onnx/protobuf/build_source/libprotobuf-lite.a -Dpybind11_DIR=/usr/local/python/3.10.4/lib/python3.10/site-packages/pybind11/share/cmake/pybind11 /workspaces/onnx -DCMAKE_TOOLCHAIN_FILE=/workspaces/onnx/emsdk/upstream/emscripten/cmake/Modules/Platform/Emscripten.cmake -DCMAKE_CROSSCOMPILING_EMULATOR=/workspaces/onnx/emsdk/node/14.18.2_64bit/bin/node;--experimental-wasm-bulk-memory;--experimental-wasm-threads
CMake Error at CMakeLists.txt:17 (project):
  The CMAKE_C_COMPILER:

    /tmp/tmph8ytv7hj/cc

  is not a full path to an existing compiler tool.

  Tell CMake where to find the compiler by setting either the environment
  variable "CC" or the CMake cache entry CMAKE_C_COMPILER to the full path to
  the compiler, or to the compiler name if it is in the PATH.


CMake Error at CMakeLists.txt:17 (project):
  The CMAKE_CXX_COMPILER:

    /tmp/tmph8ytv7hj/c++

  is not a full path to an existing compiler tool.

  Tell CMake where to find the compiler by setting either the environment
  variable "CXX" or the CMake cache entry CMAKE_CXX_COMPILER to the full path
  to the compiler, or to the compiler name if it is in the PATH.


-- Configuring incomplete, errors occurred!
See also "/workspaces/onnx/.setuptools-cmake-build/CMakeFiles/CMakeOutput.log".
emcmake: error: 'cmake -DCMAKE_C_COMPILER=/tmp/tmpmcx3hk29/cc -DCMAKE_CXX_COMPILER=/tmp/tmpmcx3hk29/c++ -DCMAKE_AR=/tmp/tmpmcx3hk29/ar -DCMAKE_C_COMPILER_AR=/tmp/tmpmcx3hk29/ar -DCMAKE_CXX_COMPILER_AR=/tmp/tmpmcx3hk29/ar -DPYTHON_INCLUDE_DIR=/root/repo/cpython/installs/python-3.10.2/include/python3.10 -DPYTHON_EXECUTABLE=/tmp/build-env-6xusqkkh/bin/python -DBUILD_ONNX_PYTHON=ON -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DONNX_NAMESPACE=onnx -DPY_EXT_SUFFIX=.cpython-310-wasm32-emscripten.so -DCMAKE_BUILD_TYPE=Release -DONNX_ML=1 -DONNX_USE_LITE_PROTO=ON -DProtobuf_INCLUDE_DIR=/workspaces/onnx/protobuf/src -DProtobuf_LIBRARIES=/workspaces/onnx/protobuf/build_source -DProtobuf_LITE_LIBRARY=/workspaces/onnx/protobuf/build_source/libprotobuf-lite.a -Dpybind11_DIR=/usr/local/python/3.10.4/lib/python3.10/site-packages/pybind11/share/cmake/pybind11 /workspaces/onnx -DCMAKE_TOOLCHAIN_FILE=/workspaces/onnx/emsdk/upstream/emscripten/cmake/Modules/Platform/Emscripten.cmake -DCMAKE_CROSSCOMPILING_EMULATOR=/workspaces/onnx/emsdk/node/14.18.2_64bit/bin/node;--experimental-wasm-bulk-memory;--experimental-wasm-threads' failed (returned 1)
Traceback (most recent call last):
  File "/usr/local/python/3.10.4/lib/python3.10/site-packages/pep517/in_process/_in_process.py", line 351, in <module>
    main()
  File "/usr/local/python/3.10.4/lib/python3.10/site-packages/pep517/in_process/_in_process.py", line 333, in main
    json_out['return_val'] = hook(**hook_input['kwargs'])
  File "/usr/local/python/3.10.4/lib/python3.10/site-packages/pep517/in_process/_in_process.py", line 249, in build_wheel
    return _build_backend().build_wheel(wheel_directory, config_settings,
  File "/tmp/build-env-6xusqkkh/lib/python3.10/site-packages/setuptools/build_meta.py", line 412, in build_wheel
    return self._build_with_temp_dir(['bdist_wheel'], '.whl',
  File "/tmp/build-env-6xusqkkh/lib/python3.10/site-packages/setuptools/build_meta.py", line 397, in _build_with_temp_dir
    self.run_setup()
  File "/tmp/build-env-6xusqkkh/lib/python3.10/site-packages/setuptools/build_meta.py", line 483, in run_setup
    super(_BuildMetaLegacyBackend,
  File "/tmp/build-env-6xusqkkh/lib/python3.10/site-packages/setuptools/build_meta.py", line 335, in run_setup
    exec(code, locals())
  File "<string>", line 358, in <module>
  File "/tmp/build-env-6xusqkkh/lib/python3.10/site-packages/setuptools/__init__.py", line 87, in setup
    return distutils.core.setup(**attrs)
  File "/tmp/build-env-6xusqkkh/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 185, in setup
    return run_commands(dist)
  File "/tmp/build-env-6xusqkkh/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
    dist.run_commands()
  File "/tmp/build-env-6xusqkkh/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 968, in run_commands
    self.run_command(cmd)
  File "/tmp/build-env-6xusqkkh/lib/python3.10/site-packages/setuptools/dist.py", line 1217, in run_command
    super().run_command(command)
  File "/tmp/build-env-6xusqkkh/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
    cmd_obj.run()
  File "/tmp/build-env-6xusqkkh/lib/python3.10/site-packages/wheel/bdist_wheel.py", line 325, in run
    self.run_command("build")
  File "/tmp/build-env-6xusqkkh/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 319, in run_command
    self.distribution.run_command(command)
  File "/tmp/build-env-6xusqkkh/lib/python3.10/site-packages/setuptools/dist.py", line 1217, in run_command
    super().run_command(command)
  File "/tmp/build-env-6xusqkkh/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
    cmd_obj.run()
  File "/tmp/build-env-6xusqkkh/lib/python3.10/site-packages/setuptools/_distutils/command/build.py", line 132, in run
    self.run_command(cmd_name)
  File "/tmp/build-env-6xusqkkh/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 319, in run_command
    self.distribution.run_command(command)
  File "/tmp/build-env-6xusqkkh/lib/python3.10/site-packages/setuptools/dist.py", line 1217, in run_command
    super().run_command(command)
  File "/tmp/build-env-6xusqkkh/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
    cmd_obj.run()
  File "<string>", line 233, in run
  File "/tmp/build-env-6xusqkkh/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 319, in run_command
    self.distribution.run_command(command)
  File "/tmp/build-env-6xusqkkh/lib/python3.10/site-packages/setuptools/dist.py", line 1217, in run_command
    super().run_command(command)
  File "/tmp/build-env-6xusqkkh/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
    cmd_obj.run()
  File "<string>", line 219, in run
  File "/usr/local/python/3.10.4/lib/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/tmp/tmpmcx3hk29/cmake', '-DPYTHON_INCLUDE_DIR=/root/repo/cpython/installs/python-3.10.2/include/python3.10', '-DPYTHON_EXECUTABLE=/tmp/build-env-6xusqkkh/bin/python', '-DBUILD_ONNX_PYTHON=ON', '-DCMAKE_EXPORT_COMPILE_COMMANDS=ON', '-DONNX_NAMESPACE=onnx', '-DPY_EXT_SUFFIX=.cpython-310-wasm32-emscripten.so', '-DCMAKE_BUILD_TYPE=Release', '-DONNX_ML=1', '-DONNX_USE_LITE_PROTO=ON', '-DProtobuf_INCLUDE_DIR=/workspaces/onnx/protobuf/src', '-DProtobuf_LIBRARIES=/workspaces/onnx/protobuf/build_source', '-DProtobuf_LITE_LIBRARY=/workspaces/onnx/protobuf/build_source/libprotobuf-lite.a', '-Dpybind11_DIR=/usr/local/python/3.10.4/lib/python3.10/site-packages/pybind11/share/cmake/pybind11', '/workspaces/onnx']' returned non-zero exit status 1.

ERROR Backend subproccess exited when trying to invoke build_wheel
```

</details>

### To Reproduce

As mentioned above, I don't yet have a clean reproduction. I'll add a follow-up comment in case I do get one.

### Expected behavior

Running `pyodide build` again after an error (without doing anything else in between) should result in the same error. The error message `/tmp/tmph8ytv7hj/c++  is not a full path to an existing compiler tool` seems to imply that some sort of "old" config is kept around and re-used?

### Environment

- Pyodide Version: Pyodide CLI Version: 0.2.2

**Comment by ryanking13** [comment]
Thanks for the report @josephrocca! I think the problem is that CMake reuses it's config, but the compiler symlinks we use are re-generated everytime. I guess we should add [`--clean-first`](https://cmake.org/cmake/help/latest/manual/cmake.1.html#cmdoption-cmake-build-clean-first) option?

**Comment by ryanking13** [comment]
I think #3445 would fix this. It seems like `--clean-first` does not remove `CMakeCache.txt`, but `--fresh` does.
