### ISSUE TITLE
Package Request - openai

### ISSUE THREAD

**Issue by RighiAmaral** [pyodide/pyodide#3588]
🐍 Package Request

- Package Name and Version: openai / latest:
- Package URL: https://pypi.org/project/openai/ 
- Package Dependencies that needs to be resolved first: 
  - aiohttp
    - aiosignal
      - frozenlist 
    - async-timeout 
    - attrs 
    - charset-normalizer
    - frozenlist 
    - multidict 
    - yarl 
      - idna 
      - multidict 
  - requests 
    - certifi 
    - charset-normalizer 
    - idna 
    - urllib3 
  - tqdm 
    - colorama

**Comment by rth** [comment]
yarl and idna will be added with https://github.com/pyodide/pyodide/pull/3703

Right now the installation would fail with,
```py
>>> await micropip.install('openai', keep_going=True)
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/lib/python3.11/site-packages/micropip/_micropip.py", line 580, in install
    raise ValueError(
ValueError: Can't find a pure Python 3 wheel for: 'multidict<5.0,>=4.5'
```
because we package multidict 6.0 and it's pulling this old version because it installs aiohttp 3.6.2 from 2019 as that's the last version that has a pure python wheel (and they switched to C extensions since).

So we would indeed also need to package `aiohttp` but then it's a bit unfortunate to also have to package all those pure Python packages it depends on. Maybe we need to rethink how we handle such cases.

**Comment by ht55ght55** [comment]
bump

**Comment by mgmorcos** [comment]
👍

**Comment by maksiksking** [comment]
bump
OpenAI's API tools are incredibly relevant right now with AI becoming more and more prominent, it's currently only possible to use GPT-3 (quite bad old models) without this module.

This would make developing ChatGPT apps way easier and is definitely in high demand.

**Comment by pritam-dey3** [comment]
bump. This will be helpful to build more applications that interact with chatGPT that runs entirely on client side. Since the applications mostly send requests back forth with OpenAI, it doesn't make sense to route the same requests through backend. True, it can be done with javascript, but we want to use Python.

**Comment by atbe** [comment]
bumop

**Comment by bbaranow** [comment]
bump

**Comment by subbu963** [comment]
bump

**Comment by avielfedida** [comment]
bump

**Comment by hoodmane** [comment]
Closed by #4539.
