### ISSUE TITLE
Build doesn't exit on build build error

### ISSUE THREAD

**Issue by rth** [pyodide/pyodide#3648]
Currently, when a package fails to build, it looks like in some cases the build doesn't exit outright and keeps being locked for minutes (even if only 1 package is being built).  Maybe some threading deadlock.

For instance, this happens when trying to build scipy in https://github.com/pyodide/pyodide/pull/3331 and it fails. 

![image](https://user-images.githubusercontent.com/630936/224306101-d0a62e58-01a0-4495-a771-1a0830796c60.png)

In this example, I have to enter Control+C for the build error log to be shown.

**Comment by hoodmane** [comment]
```
Exception ignored in atexit callback: <function shutdown at 0x7f996c438900>
Traceback (most recent call last):
  File "/usr/lib/python3.11/logging/__init__.py", line 2201, in shutdown
    h.release()
  File "/usr/lib/python3.11/logging/__init__.py", line 934, in release
    self.lock.release()
RuntimeError: cannot release un-acquired lock
^Cmake: *** [Makefile:8: all] Interrupt
```

**Comment by hoodmane** [comment]
Also causing trouble in CI:
https://app.circleci.com/pipelines/github/pyodide/pyodide/5471/workflows/84979f59-c82b-421c-8e81-07ea019f84a2/jobs/68531

**Comment by ryanking13** [comment]
Maybe it is because of my PR (#3607) that added a new lock. But I don't see how it can create a deadlock...

**Comment by hoodmane** [comment]
It prints "cannot release unacquired lock" on exit which definitely suggests a weird deadlock condition. And it seems to suggest that the `with` block was written like:
```py
try:
   acquireLock()
   yield
finally:
   releaseLock()
```
Whereas I think `acquireLock()` should be before the try block to prevent it from attempting to release the lock when a keyboard interrupt kills the thread while it's trying to acquire it.

I made a comment over there suggesting `sleep` with the lock released.

Also given that the gil exists maybe we don't need a second lock.

**Comment by hoodmane** [comment]
Yeah I'm pretty sure the explicit lock should be remote:

```py
if is_rust_pkg():
   if building_rust: # guarded by gil
      put_back_pkg()
      sleep() # release gil
      continue
   building_rust = True

build_pkg() # subprocess releases gil

if is_rust_pkg(): 
   building_rust = False # doesn't need guard
```

**Comment by hoodmane** [comment]
Though this also seems to be the purpose of [`threading.Condition`](https://docs.python.org/3/library/threading.html?highlight=lock#threading.Condition).

**Comment by ryanking13** [comment]
Yeah, that's worth trying. I'm very confused since the Roman's example builds only a single package with no rust packages.
