### ISSUE TITLE
RuntimeError: Incorrect Emscripten version 3.1.27. Need Emscripten version 3.1.32

### ISSUE THREAD

**Issue by dazzag24** [pyodide/pyodide#3733]
## 🐛 Bug

I'm building [pylibjpeg-openjpeg](https://github.com/pydicom/pylibjpeg-openjpeg) to allow [pydicom](https://github.com/pydicom/pydicom) (pure Python works in Pyodide already) to read Jpeg2000 encoded DICOM images.

### To Reproduce

```
mkdir pyodide_builds
cd pyodide_builds
pyenv local 3.11.2
python -m venv venv
source venv/bin/activate
python -m pip install pyodide-build
git clone https://github.com/emscripten-core/emsdk.git
cd emsdk
PYODIDE_EMSCRIPTEN_VERSION=$(pyodide config get emscripten_version)
./emsdk install ${PYODIDE_EMSCRIPTEN_VERSION}
./emsdk activate ${PYODIDE_EMSCRIPTEN_VERSION}
source emsdk_env.sh
cd ..
git clone --recurse-submodules https://github.com/pydicom/pylibjpeg-openjpeg
cd pylibjpeg-openjpeg
pyodide build
```

This works perfectly and builds a wheel (pylibjpeg_openjpeg-1.3.2-cp311-cp311-emscripten_3_1_32_wasm32.whl). However it won't load in JupyterLite or Pyscript because they all use Emscripten 3.2.27. They error with:

```
ValueError: Wheel was built with Emscripten v3.1.32 but Pyodide was built with Emscripten v3.1.27
```

So I attempted to change the build instructions to use  `PYODIDE_EMSCRIPTEN_VERSION=3.1.27` instead of `PYODIDE_EMSCRIPTEN_VERSION=$(pyodide config get emscripten_version)` but I attempt to run `pyodide build` this fails with:

`RuntimeError: Incorrect Emscripten version 3.1.27. Need Emscripten version 3.1.32`

So how can I build pyodide packages with older versions of Emscripten?

Thanks

**Comment by hoodmane** [comment]
I think your specific problem would be fixed with `rm -rf .pyodide-xbuildenv/`. But there is a problem that we don't detect when the xbuildenv comes from the wrong version of Pyodide and either automatically replace it or say something useful about it.

The new xbuildenv is also slightly broken, you need to wget one missing file. #3730

**Comment by ryanking13** [comment]
Each Pyodide / pyodide-build requires a specific version of Emscripten. Since jupyterlite is using Pyodide 0.22.1 now, you need to use pyodide-build==0.22.1.

**Comment by dazzag24** [comment]
Thanks @ryanking13.

Perhaps the docs could mention this?
Is there a table anywhere detailing which versions are used by common consumers of Pyodide e.g Pyscript and Jupyterlite?

**Comment by dazzag24** [comment]
I've run into a new error when attempting to build with pyodide-build==0.22.1:

`AssertionError: would build wheel with unsupported tag ('cp311', 'cp310', 'emscripten_3_1_27_wasm32')`

Steps to reproduce:

```bash
mkdir pyodide_build-0.22.
cd pyodide_build-0.22.1
pyenv local 3.11.2
python -m venv venv
source venv/bin/activate
python -m pip install pyodide-build==0.22.1
git clone https://github.com/emscripten-core/emsdk.git
cd emsdk
PYODIDE_EMSCRIPTEN_VERSION=$(pyodide config get emscripten_version)
./emsdk install ${PYODIDE_EMSCRIPTEN_VERSION}
./emsdk activate ${PYODIDE_EMSCRIPTEN_VERSION}
source emsdk_env.sh
cd ..
git clone --recurse-submodules https://github.com/pydicom/pylibjpeg-openjpeg
cd pylibjpeg-openjpeg
pyodide build
```

Details of error:

```
<snip>
cc build/temp.emscripten_3_1_27_wasm32-3.11/openjpeg/_openjpeg.o build/temp.emscripten_3_1_27_wasm32-3.11/openjpeg/src/interface/color.o build/temp.emscripten_3_1_27_wasm32-3.11/openjpeg/src/interface/decode.o build/temp.emscripten_3_1_27_wasm32-3.11/openjpeg/src/openjpeg/src/lib/openjp2/bio.o build/temp.emscripten_3_1_27_wasm32-3.11/openjpeg/src/openjpeg/src/lib/openjp2/cidx_manager.o build/temp.emscripten_3_1_27_wasm32-3.11/openjpeg/src/openjpeg/src/lib/openjp2/cio.o build/temp.emscripten_3_1_27_wasm32-3.11/openjpeg/src/openjpeg/src/lib/openjp2/dwt.o build/temp.emscripten_3_1_27_wasm32-3.11/openjpeg/src/openjpeg/src/lib/openjp2/event.o build/temp.emscripten_3_1_27_wasm32-3.11/openjpeg/src/openjpeg/src/lib/openjp2/function_list.o build/temp.emscripten_3_1_27_wasm32-3.11/openjpeg/src/openjpeg/src/lib/openjp2/ht_dec.o build/temp.emscripten_3_1_27_wasm32-3.11/openjpeg/src/openjpeg/src/lib/openjp2/image.o build/temp.emscripten_3_1_27_wasm32-3.11/openjpeg/src/openjpeg/src/lib/openjp2/invert.o build/temp.emscripten_3_1_27_wasm32-3.11/openjpeg/src/openjpeg/src/lib/openjp2/j2k.o build/temp.emscripten_3_1_27_wasm32-3.11/openjpeg/src/openjpeg/src/lib/openjp2/jp2.o build/temp.emscripten_3_1_27_wasm32-3.11/openjpeg/src/openjpeg/src/lib/openjp2/mct.o build/temp.emscripten_3_1_27_wasm32-3.11/openjpeg/src/openjpeg/src/lib/openjp2/mqc.o build/temp.emscripten_3_1_27_wasm32-3.11/openjpeg/src/openjpeg/src/lib/openjp2/openjpeg.o build/temp.emscripten_3_1_27_wasm32-3.11/openjpeg/src/openjpeg/src/lib/openjp2/opj_clock.o build/temp.emscripten_3_1_27_wasm32-3.11/openjpeg/src/openjpeg/src/lib/openjp2/opj_malloc.o build/temp.emscripten_3_1_27_wasm32-3.11/openjpeg/src/openjpeg/src/lib/openjp2/phix_manager.o build/temp.emscripten_3_1_27_wasm32-3.11/openjpeg/src/openjpeg/src/lib/openjp2/pi.o build/temp.emscripten_3_1_27_wasm32-3.11/openjpeg/src/openjpeg/src/lib/openjp2/ppix_manager.o build/temp.emscripten_3_1_27_wasm32-3.11/openjpeg/src/openjpeg/src/lib/openjp2/sparse_array.o build/temp.emscripten_3_1_27_wasm32-3.11/openjpeg/src/openjpeg/src/lib/openjp2/t1.o build/temp.emscripten_3_1_27_wasm32-3.11/openjpeg/src/openjpeg/src/lib/openjp2/t1_generate_luts.o build/temp.emscripten_3_1_27_wasm32-3.11/openjpeg/src/openjpeg/src/lib/openjp2/t1_ht_generate_luts.o build/temp.emscripten_3_1_27_wasm32-3.11/openjpeg/src/openjpeg/src/lib/openjp2/t2.o build/temp.emscripten_3_1_27_wasm32-3.11/openjpeg/src/openjpeg/src/lib/openjp2/tcd.o build/temp.emscripten_3_1_27_wasm32-3.11/openjpeg/src/openjpeg/src/lib/openjp2/tgt.o build/temp.emscripten_3_1_27_wasm32-3.11/openjpeg/src/openjpeg/src/lib/openjp2/thix_manager.o build/temp.emscripten_3_1_27_wasm32-3.11/openjpeg/src/openjpeg/src/lib/openjp2/thread.o build/temp.emscripten_3_1_27_wasm32-3.11/openjpeg/src/openjpeg/src/lib/openjp2/tpix_manager.o -o build/lib.emscripten_3_1_27_wasm32-3.11/_openjpeg.cpython-310-wasm32-emscripten.so
running install
running install_lib
creating build/bdist.emscripten_3_1_27_wasm32
creating build/bdist.emscripten_3_1_27_wasm32/wheel
creating build/bdist.emscripten_3_1_27_wasm32/wheel/openjpeg
creating build/bdist.emscripten_3_1_27_wasm32/wheel/openjpeg/tests
creating build/bdist.emscripten_3_1_27_wasm32/wheel/openjpeg/src
creating build/bdist.emscripten_3_1_27_wasm32/wheel/openjpeg/src/interface
creating build/bdist.emscripten_3_1_27_wasm32/wheel/openjpeg/src/openjpeg
creating build/bdist.emscripten_3_1_27_wasm32/wheel/openjpeg/src/openjpeg/cmake
creating build/bdist.emscripten_3_1_27_wasm32/wheel/openjpeg/src/openjpeg/src
creating build/bdist.emscripten_3_1_27_wasm32/wheel/openjpeg/src/openjpeg/src/lib
creating build/bdist.emscripten_3_1_27_wasm32/wheel/openjpeg/src/openjpeg/src/lib/openjp2
running install_egg_info
Copying pylibjpeg_openjpeg.egg-info to build/bdist.emscripten_3_1_27_wasm32/wheel/pylibjpeg_openjpeg-1.3.2-py3.11.egg-info
running install_scripts
Traceback (most recent call last):
  File "/Users/darreng/code/pyodide_builds/pyodide_build-0.22.1/venv/lib/python3.11/site-packages/pep517/in_process/_in_process.py", line 351, in <module>
    main()
  File "/Users/darreng/code/pyodide_builds/pyodide_build-0.22.1/venv/lib/python3.11/site-packages/pep517/in_process/_in_process.py", line 333, in main
    json_out['return_val'] = hook(**hook_input['kwargs'])
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/darreng/code/pyodide_builds/pyodide_build-0.22.1/venv/lib/python3.11/site-packages/pep517/in_process/_in_process.py", line 249, in build_wheel
    return _build_backend().build_wheel(wheel_directory, config_settings,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/private/var/folders/bl/fr9w87f904df129wpkqnpjrh0000gn/T/build-env-9e63o4ii/lib/python3.11/site-packages/setuptools/build_meta.py", line 230, in build_wheel
    return self._build_with_temp_dir(['bdist_wheel'], '.whl',
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/private/var/folders/bl/fr9w87f904df129wpkqnpjrh0000gn/T/build-env-9e63o4ii/lib/python3.11/site-packages/setuptools/build_meta.py", line 215, in _build_with_temp_dir
    self.run_setup()
  File "/private/var/folders/bl/fr9w87f904df129wpkqnpjrh0000gn/T/build-env-9e63o4ii/lib/python3.11/site-packages/setuptools/build_meta.py", line 268, in run_setup
    self).run_setup(setup_script=setup_script)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/private/var/folders/bl/fr9w87f904df129wpkqnpjrh0000gn/T/build-env-9e63o4ii/lib/python3.11/site-packages/setuptools/build_meta.py", line 158, in run_setup
    exec(compile(code, __file__, 'exec'), locals())
  File "setup.py", line 107, in <module>
    setup(
  File "/private/var/folders/bl/fr9w87f904df129wpkqnpjrh0000gn/T/build-env-9e63o4ii/lib/python3.11/site-packages/setuptools/__init__.py", line 155, in setup
    return distutils.core.setup(**attrs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/private/var/folders/bl/fr9w87f904df129wpkqnpjrh0000gn/T/build-env-9e63o4ii/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 148, in setup
    return run_commands(dist)
           ^^^^^^^^^^^^^^^^^^
  File "/private/var/folders/bl/fr9w87f904df129wpkqnpjrh0000gn/T/build-env-9e63o4ii/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 163, in run_commands
    dist.run_commands()
  File "/private/var/folders/bl/fr9w87f904df129wpkqnpjrh0000gn/T/build-env-9e63o4ii/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 967, in run_commands
    self.run_command(cmd)
  File "/private/var/folders/bl/fr9w87f904df129wpkqnpjrh0000gn/T/build-env-9e63o4ii/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
    cmd_obj.run()
  File "/private/var/folders/bl/fr9w87f904df129wpkqnpjrh0000gn/T/build-env-9e63o4ii/lib/python3.11/site-packages/wheel/bdist_wheel.py", line 337, in run
    impl_tag, abi_tag, plat_tag = self.get_tag()
                                  ^^^^^^^^^^^^^^
  File "/private/var/folders/bl/fr9w87f904df129wpkqnpjrh0000gn/T/build-env-9e63o4ii/lib/python3.11/site-packages/wheel/bdist_wheel.py", line 287, in get_tag
    assert tag in supported_tags, "would build wheel with unsupported tag {}".format(tag)
           ^^^^^^^^^^^^^^^^^^^^^
AssertionError: would build wheel with unsupported tag ('cp311', 'cp310', 'emscripten_3_1_27_wasm32')

ERROR Backend subproccess exited when trying to invoke build_wheel
```

**Comment by ryanking13** [comment]
> Perhaps the docs could mention this?

Right, we need to mention this clearly in the docs. Thanks.

> Is there a table anywhere detailing which versions are used by common consumers of Pyodide e.g Pyscript and Jupyterlite?

Maybe you can find it somewhere in Jupyterlite / Pyscript docs? @jtpio @antocuni

**Comment by ryanking13** [comment]
> I've run into a new error when attempting to build with pyodide-build==0.22.1:

Pyodide 0.22.1 use Python 3.10.2 so you need to match the host Python version. Sorry, this also needs to be mentioned in the docs.

**Comment by dazzag24** [comment]
Ah. OK. I've try with Python 3.10.2 then. Thanks

**Comment by dazzag24** [comment]
> > Perhaps the docs could mention this?
> 
> Right, we need to mention this clearly in the docs. Thanks.
> 
> > Is there a table anywhere detailing which versions are used by common consumers of Pyodide e.g Pyscript and Jupyterlite?
> 
> Maybe you can find it somewhere in Jupyterlite / Pyscript docs? @jtpio @antocuni

Closest I can find is in the Pyscript code:
https://github.com/pyscript/pyscript/blob/088a26491088de1e59b33d31fe76b177c989ffde/pyscriptjs/src/pyconfig.ts#L56

They are currently using pyodide-0.22.1.

**Comment by jtpio** [comment]
In the case of JupyterLite the Pyodide kernel is located in this repo: https://github.com/jupyterlite/pyodide-kernel

Users can check which version of Pyodide is being used by running the following snippet in a code cell:

```py
import pyodide
pyodide.__version__
```

![image](https://user-images.githubusercontent.com/591645/229752195-ef43e662-10df-4c21-a243-4b838e0321c6.png)

When a new version of Pyodide is available, we usually update `jupyterlite-pyodide-kernel` package soon after and make a new release so it can be used in JupyterLite deployments.

**Comment by dazzag24** [comment]
> > I've run into a new error when attempting to build with pyodide-build==0.22.1:
> 
> Pyodide 0.22.1 use Python 3.10.2 so you need to match the host Python version. Sorry, this also needs to be mentioned in the docs.

I tested a build using the recommended Python version and Pyodide 0.22.1 and I was able to produce a wheel.

**Comment by ryanking13** [comment]
> How can users like myself wanting to build packages have the best chance of compatibility? Is there forwards compatibility? e.g if I build using pyodide-0.22.1 + Python 3.10.2 will the wheels work in pyodide 0.23.0 as well?

Emscripten does not guarantee backward compatibility yet, so we can't be sure that a wheel built for Pyodide 0.22.1 (which uses Emscripten 3.1.27) will be compatible with Pyodide 0.23.0 (which uses Emscripten 3.1.32).

But from Python 0.23.0, we are trying to update the Emscripten version only when we update the CPython version (#2951), so there are some more possibilities that your wheel will be compatible with the next couple of Pyodide versions.

**Comment by hoodmane** [comment]
Though I'd like to enable wasm-exceptions in Pyodide 0.24.0 which would be an ABI break anyways...

**Comment by ryanking13** [comment]
> Though I'd like to enable wasm-exceptions in Pyodide 0.24.0 which would be an ABI break anyways...

I think we need to make a Emscripten version compatibility table before releasing the next version. I always had that in my mind but I was too lazy.

**Comment by hoodmane** [comment]
> too lazy

There's so many different things to do!
