### ISSUE TITLE
Limitation with Pyodide packages imports inside a function?

### ISSUE THREAD

**Issue by lesteve** [pyodide/pyodide#3771]
## 🐛 Bug

`import numpy` (or any other package that is packaged inside Pyodide) "just works" in Pyodide if you type it in the console but not if it is inside a function.

I am guessing the reason why may be in https://github.com/pyodide/pyodide/blob/main/src/py/_pyodide/_importhook.py but I thought I would open an issue to get a better idea whether this was a well known limitation and whether there was some hope it could be fixed.

### To Reproduce

```py
with open('test.py', 'w') as f:
    f.write('def test():\n    import numpy')

import test
test.test()
```

```
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/home/pyodide/test.py", line 2, in test
    import numpy
ModuleNotFoundError: The module 'numpy' is included in the Pyodide distribution, but it is not installed.
You can install it by calling:
  await micropip.install("numpy") in Python, or
  await pyodide.loadPackage("numpy") in JavaScript
See https://pyodide.org/en/stable/usage/loading-packages.html for more details.
```

A work-around is to do `import numpy` before calling the function but that is not very convenient.

### Expected behavior

No import error

### Environment

- Pyodide Version: latest console
- Browser version: Firefox and Chromium
- Any other relevant information:

### Additional context

An example why I care about it in a scikit-learn context, it would be very convenient if the following snippet "just worked":
```py
from sklearn.datasets import load_diabetes

load_diabetes(as_frame=True)
```

```
ModuleNotFoundError: The module 'pandas' is included in the Pyodide distribution, but it is not installed.
```

We are in a similar case as the simpler snippet above, since `sklearn.utils.check_pandas_support` tries to import pandas inside the function and fails with the same error message.

The work-around is to add `import pandas` before calling `load_diabetes` but that is not super convenient.

Another example I know of of the same issue is that in JupyterLite `%matplotlib inline` does raise the same kind of error.

**Comment by rth** [comment]
That logic is in [find_impots](https://github.com/pyodide/pyodide/blob/7cf5bd58095d6484d801cc535b11d60b13412a31/src/pyodide-py/pyodide/_base.py#L440) so we recursively parse ast nodes of the code that is sent to `pyodide.runPythonAsync`.   Actually, since we are already parsing AST, we should also be able to detect imports inside functions I think. So that's a feature we could add (unless it adds too much overhead). It would be something like,
```py
    for node in ast.walk(tree):
        if isinstance(node, ast.FunctionDef):
            for child_node in ast.iter_child_nodes(node):
                if isinstance(child_node, (ast.Import, ast.ImportFrom)):
                       # extract the import name
```
but then one would also need to do it for async functions, methods etc. But then it's a backward incompatible change, which might need to be behind some option flag.

In the example with scikit-learn and pandas  it's a much more challenging problem. There you need to detect imports not only in code that is sent to `runPythonAsync` but also recursively any modules that code imports. Technically it's doable (maybe [`modulefinder`](https://docs.python.org/3/library/modulefinder.html#modulefinder.ModuleFinder) does it, or applying `find_impots` recursively) but the problem is,
 - a) it's slow. You need to process a lot of AST, so it would add a few seconds overhead. So can't do it by default.
 - b) it's not very reliable. Python packages often have some optional or platform-independent imports in a  `try: import ... except ..`. And it's not obvious we actually want to load all the imports we find. For instance, there could be some Windows only imports that don't make sense for wasm. And loading optional stuff even it's not needed would be slow.
    To give a concrete example, look at [pandas](https://pandas.pydata.org/docs/getting_started/install.html#optional-dependencies) optional dependencies. A lot of it is either not built yet for WASM or in any case shouldn't be loaded by default. Yet all of those imports would be found as imports in methods if you do `import pandas as pd` and try to detect imports that way.

For completeness, since you asked, :) another workaround around the above problem was done in https://github.com/pyodide/pyodide-pack where we intercept `FS.open` calls in a sandbox, as a way to more reliably know what modules will be actually imported at runtime. But that has other constraints and I don't think it would help for this use case.

**Comment by pfebrer** [comment]
Couldn't you use a node visitor instead of adding each case separately?

```python
import ast

class ImportFinder(ast.NodeVisitor):
    def visit_Import(self, node):
        register_import(node)

tree = ast.parse(code)

ImportFinder().visit(tree)
```

That would find all imports recursively. And if you only one the first level ones I think you could a `generic_visit` that does nothing. Similarly, you could add a visit function for `try/except` blocks to stop visiting.

```python
import ast

class ImportFinder(ast.NodeVisitor):
    def visit_Import(self, node):
        register_import(node)

    def visit_Try(self, node):
        # Stop recursion
        pass

tree = ast.parse(code)

ImportFinder().visit(tree)
```

I don't know how efficient it is, but it looks clean :)

**Comment by pfebrer** [comment]
Or if you don't want to load the packages until the import line is reached, you could use an `ast.NodeTransformer` to convert import lines into calls of your `loadPackage` function. Then you `ast.unparse` to get the modified string of code. I guess that would mimic the "normal" behavior of how packages are loaded in python.

**Comment by hoodmane** [comment]
The issue is that in this case pandas is declared as an optional dependency of scikit learn. This is great because it reduces the amount of code we have to download and load. 

https://github.com/scikit-learn/scikit-learn/blob/main/sklearn/_min_dependencies.py#L35

If we wanted to load all optional dependencies we could... But we don't want to. 

> Or if you don't want to load the packages until the import line is reached, you could use an ast.NodeTransformer to convert import lines into calls of your loadPackage function

Well if `loadPackage` were a synchronous function you could do this with a metapath entry. With the upcoming js promise integration and stack switching you can also do something like this. But otherwise you run into the sync/async problem and there's no way to fix it with a tool as blunt as an ast transformation.

**Comment by rth** [comment]
@pfebrer You are right that a `NodeVisitor` would be better implementation-wise, if we went in that direction. But as mentioned above we cannot determine which optional dependencies should be loaded (loading all by default is not a very good idea, particularly in the browser).

In the end, I think the solution is just to specify the requirements needed explicitly. If one pip installs scikit-learn, and then try to run the above code snippet, one would also get an ImportError about pandas not being installed. Overall we are trying to get as close to the native user experience as possible, to avoid surprising users. So I feel there is no reason to do anything differently in this particular case. I mean this magic about auto-loading imports is nice in some limited situations, but then if you go further with it, you run in all sorts of problems which is why Python generally doesn't pip install things on import. 

So IMO it would make more sense to work on better requirements specification (e.g. make sure it's easy to do that when run with sphinx-gallery if you use it in the scikit-learn example gallery etc).

**Comment by pfebrer** [comment]
Ok, I think I misunderstood the problem, since I'm still new to pyodide. I thought a package could be installed (compiled files downloaded / available locally) but not loaded. From what you say, it seems like "installed" means the same as "loaded" in the context of pyodide and "loading" a package involves downloading and compiling.

**Comment by hoodmane** [comment]
Yeah that's correct. There are four steps: download, install, load, and import. In native python you do download and install at the same time and then later load and import at the same time. In Pyodide we download install and load at the same time and then later maybe import.
