### ISSUE TITLE
fatal crash running pydantic-core in the Chrime

### ISSUE THREAD

**Issue by samuelcolvin** [pyodide/pyodide#3792]
## 🐛 Bug

Error output:

```
Loading micropip, packaging, pyparsing, pytest, atomicwrites, attrs, six, more-itertools, pluggy, py, setuptools, distutils, iniconfig, exceptiongroup, pytz
pyodide.asm.js:9 Loaded six, pyparsing, packaging, micropip, pytz, attrs, pluggy, atomicwrites, py, exceptiongroup, more-itertools, iniconfig, distutils, setuptools, pytest
pyodide.asm.js:9 Loading typing-extensions, click, pygments
pyodide.asm.js:9 Loaded pygments, typing-extensions, click
pyodide.asm.js:9 Pyodide has suffered a fatal error. Please report this to the Pyodide maintainers.
API.fatal_error @ pyodide.asm.js:9
pyodide.asm.js:9 The cause of the fatal error was:
API.fatal_error @ pyodide.asm.js:9
pyodide.asm.js:9 RangeError: Maximum call stack size exceeded
    at invoke_viiiiiii (pyodide.asm.js:9:1263752)
    at 00ce5366:0xa2889
    at 00ce5366:0x8121a
    at 00ce5366:0x9e533
    at 00ce5366:0x1b0c7e
    at 00ce5366:0x9a535
    at invoke_viiiiiii (pyodide.asm.js:9:1263720)
    at 00ce5366:0xa2889
    at 00ce5366:0x8121a
    at 00ce5366:0x9e533
API.fatal_error @ pyodide.asm.js:9
pyodide.asm.js:9 Uncaught RangeError: Maximum call stack size exceeded
    at invoke_viiiiiii (pyodide.asm.js:9:1263752)
    at 00ce5366:0xa2889
    at 00ce5366:0x8121a
    at 00ce5366:0x9e533
    at 00ce5366:0x1b0c7e
    at 00ce5366:0x9a535
    at invoke_viiiiiii (pyodide.asm.js:9:1263720)
    at 00ce5366:0xa2889
    at 00ce5366:0x8121a
    at 00ce5366:0x9e533
```

### To Reproduce

Open [this](https://githubproxy.samuelcolvin.workers.dev/pydantic/pydantic-core/blob/main/wasm-preview/index.html) page **without** developer tools open.

Error does not happen with developer tools open, does not happen on firefox.

repo: https://github.com/pydantic/pydantic-core/tree/main/wasm-preview

### Expected behavior

tests should all pass

### Environment

* **Chrome**: Chrome is up to date Version 112.0.5615.137 (Official Build) (arm64)
* **Pyodide**: [v0.23.0](https://github.com/pydantic/pydantic-core/blob/da5577704f7dc5a2d285db3330a821c1d08af791/wasm-preview/worker.js#L88)

**Comment by samuelcolvin** [comment]
That that will stay unchanged:

https://githubproxy.samuelcolvin.workers.dev/pydantic/pydantic-core/blob/main/wasm-preview/index.html?pydantic_core_version=v0.25.0

**Comment by ryanking13** [comment]
Thanks for the report! I can reproduce it in my Chrome browser.

I'm not sure what change triggered this error... Emscripten update or CPython update might be relevant. Do you have any idea in which tests exactly the error occurs?

**Comment by samuelcolvin** [comment]
It's not on a specific test, it just happens around 10-15% of the way though tests, but if you run those files independently, they're fine.

**Comment by samuelcolvin** [comment]
@hoodmane mentioned that he thought this was probably a V8 bug, but I don't know if anyone reported it upstream, or if that's even possible without more specific information.

**Comment by JeffersGlass** [comment]
I believe this is now resolved. It appears to have been fixed sometime between pydantic-core 2.0.0 and 2.2.0, even for the old version of Chrome it was previously freezing on (112.0). Testing today on Chrome 114.0 and 115.0 with the most recent pydantic-core (2.4.0) works, as seen [here](https://githubproxy.samuelcolvin.workers.dev/pydantic/pydantic-core/blob/main/wasm-preview/index.html).
