### ISSUE TITLE
Scipy build is broken

### ISSUE THREAD

**Issue by hoodmane** [pyodide/pyodide#3816]
## 🐛 Bug

Scipy build seems to have been broken by some upstream change. Traceback is inside Pytran? Maybe a recent Pythran release caused a build regression?

```
Running from SciPy source directory.                                            
Traceback (most recent call last):                                              
  File                                                                          
"/usr/local/lib/python3.11/site-packages/pep517/in_process/_in_process.py", line
351, in <module>                                                                
    main()                                                                      
  File                                                                          
"/usr/local/lib/python3.11/site-packages/pep517/in_process/_in_process.py", line
333, in main                                                                    
    json_out['return_val'] = hook(**hook_input['kwargs'])                       
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^                       
  File                                                                          
"/usr/local/lib/python3.11/site-packages/pep517/in_process/_in_process.py", line
249, in build_wheel                                                             
    return _build_backend().build_wheel(wheel_directory, config_settings,       
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^       
  File                                                                          
"/tmp/build-env-nv3mavpb/lib/python3.11/site-packages/setuptools/build_meta.py",
line 230, in build_wheel                                                        
    return self._build_with_temp_dir(['bdist_wheel'], '.whl',                   
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                   
  File                                                                          
"/tmp/build-env-nv3mavpb/lib/python3.11/site-packages/setuptools/build_meta.py",
line 215, in _build_with_temp_dir                                               
    self.run_setup()                                                            
  File                                                                          
"/tmp/build-env-nv3mavpb/lib/python3.11/site-packages/setuptools/build_meta.py",
line 268, in run_setup                                                          
    self).run_setup(setup_script=setup_script)                                  
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                  
  File                                                                          
"/tmp/build-env-nv3mavpb/lib/python3.11/site-packages/setuptools/build_meta.py",
line 158, in run_setup                                                          
    exec(compile(code, __file__, 'exec'), locals())                             
  File "setup.py", line 532, in <module>                                        
    setup_package()                                                             
  File "setup.py", line 509, in setup_package                                   
    cmdclass['build_ext'] = get_build_ext_override()                            
                            ^^^^^^^^^^^^^^^^^^^^^^^^                            
  File "setup.py", line 139, in get_build_ext_override                          
    import pythran                                                              
  File                                                                          
"/tmp/build-env-nv3mavpb/lib/python3.11/site-packages/pythran/__init__.py", line
42, in <module>                                                                 
    from pythran.toolchain import (generate_cxx, compile_cxxfile,               
compile_cxxcode,                                                                
  File                                                                          
"/tmp/build-env-nv3mavpb/lib/python3.11/site-packages/pythran/toolchain.py",    
line 12, in <module>                                                            
    from pythran.middlend import refine, mark_unexported_functions              
  File                                                                          
"/tmp/build-env-nv3mavpb/lib/python3.11/site-packages/pythran/middlend.py", line
4, in <module>                                                                  
    from pythran.optimizations import (ComprehensionPatterns, ListCompToGenexp, 
  File                                                                          
"/tmp/build-env-nv3mavpb/lib/python3.11/site-packages/pythran/optimizations/__in
it__.py", line 21, in <module>                                                  
    from .pattern_transform import PatternTransform                             
  File                                                                          
"/tmp/build-env-nv3mavpb/lib/python3.11/site-packages/pythran/optimizations/patt
ern_transform.py", line 346, in <module>                                        
    getattr(PatternTransform, attr_name) + (known_pattern,))                    
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                        
AttributeError: type object 'PatternTransform' has no attribute 'typePatterns'. 
Did you mean: 'CallPatterns'?                         
```

**Comment by hoodmane** [comment]
Most recent pythran release was in January so it's not pythran.

**Comment by rth** [comment]
As a temporary workaround, we can probably set `SCIPY_USE_PYTHRAN=0` to disable pythran: https://github.com/scipy/scipy/issues/18390.

**Comment by ryanking13** [comment]
> As a temporary workaround, we can probably set SCIPY_USE_PYTHRAN=0 to disable pythran: https://github.com/scipy/scipy/issues/18390

What's would be the side effect of disabling pythran? Maybe we can pin `gast` instead?

**Comment by hoodmane** [comment]
Let's put a `!=` for the specific bad version of gast.

**Comment by ryanking13** [comment]
pythran released a new version, but sadly scipy 1.10.1 pins pythran version <0.13.0.

**Comment by hoodmane** [comment]
Can we force it to accept the new version anyways by dropping pythran caps?

**Comment by tupui** [comment]
The new version of Pythran does not solve the issue. This is still under investigation.

**Comment by hoodmane** [comment]
Looks like it's working again?
