### ISSUE TITLE
Aborted fetch requests freeze REPL

### ISSUE THREAD

**Issue by stephenmccalman** [pyodide/pyodide#3867]
## 🐛 Bug

Fetch requests aborted (using the [signal](https://developer.mozilla.org/en-US/docs/Web/API/AbortSignal/timeout_static#examples) options) freeze REPL, and do not raise exception.

### To Reproduce

```python
def fetch_response(url, timeout:
    options = js.Object.new()
    options.signal = js.AbortSignal.timeout(timeout)
    return js.fetch(url, options)

response = await fetch_response('slow api', 1)
```

Dev Console shows:
```
Uncaught (in promise) PythonError: TypeError: invalid exception object

    at new_error (pyodide.asm.js:9:14992)
    at pyodide.asm.wasm:0x152d67
    at pyodide.asm.wasm:0x152e6c
    at Module.callPyObjectKwargs (pyodide.asm.js:9:75811)
    at Module.callPyObject (pyodide.asm.js:9:76020)
    at onRejected (pyodide.asm.js:9:59090)
```

This appears to occur because the `PyodideFuture` object, which the fetch returns, expects to receive a python Exception object on rejection.   Instead, the returned `PyodideFuture` object gets a `JsProxy` of an `AbortError` (`DOMException`).  A  `JsProxy` of a `DOMException` can't be raised in pyodide. 

```python
>>> import js
>>> raise js.DOMException.new('')
```
```
Traceback (most recent call last):
  File "<console>", line 1, in <module>
TypeError: exceptions must derive from BaseException
```

### Expected behavior

Should raise a `JsException`. 

Possible solution: Allow js.DOMException objects to be raised much like js.Error objects:

```python
>>> from pyodide.webloop import PyodideFuture
>>> fut = PyodideFuture()
>>> fut.set_exception(js.Error('hi'))
>>> fut.exception()
Error: hi
```

### Environment

- Pyodide Version<0.23.2>:
```
>>> import pyodide
>>> pyodide.__version__
'0.23.2'
```
- Browser version<Chrome 113.0.5672.114->:

**Comment by hoodmane** [comment]
Interesting... This happens only in Chrome: in Firefox `raise js.DomException("")` works as expected. 
Thanks for the report @stephenmccalman!

**Comment by hoodmane** [comment]
This reproduces all the way back to Pyodide 0.17.0. It's a bit surprising nobody has noticed it before.

**Comment by hoodmane** [comment]
It seems that we feature detect exceptions with:
```
hasProperty(obj, "name") &&
hasProperty(obj, "message") &&
hasProperty(obj, "stack")
```
In Chrome, `DOMException` has no `stack` property (but in firefox it has it).

**Comment by hoodmane** [comment]
Interestingly this behavior of chrome is not compliant with a "should" in the whatwg spec:

> if an implementation gives native [Error](https://tc39.es/ecma262/multipage/fundamental-objects.html#sec-error-objects) objects special powers or nonstandard properties (such as a stack property), it should also expose those on [DOMException](https://webidl.spec.whatwg.org/#idl-DOMException) objects.

https://webidl.spec.whatwg.org/#es-DOMException-specialness

**Comment by hoodmane** [comment]
This bug also occurs in Safari.
