### ISSUE TITLE
AttributeError: module 'os' has no attribute 'link'

### ISSUE THREAD

**Issue by simonw** [pyodide/pyodide#3880]
I'm getting this traceback in my attempts to upgrade https://lite.datasette.io/ to the latest Pyodide:

```
Traceback (most recent call last):
  File "/lib/python311.zip/_pyodide/_base.py", line 540, in eval_code_async
    await CodeRunner(
  File "/lib/python311.zip/_pyodide/_base.py", line 365, in run_async
    await coroutine
  File "<exec>", line 133, in <module>
  File "/lib/python3.11/site-packages/datasette/__init__.py", line 2, in <module>
    from datasette.utils.asgi import Forbidden, NotFound, Request, Response  # noqa
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/datasette/utils/asgi.py", line 8, in <module>
    import aiofiles.os
  File "/lib/python3.11/site-packages/aiofiles/os.py", line 31, in <module>
    link = wrap(os.link)
                ^^^^^^^
AttributeError: module 'os' has no attribute 'link'
```
I can't find any mention of this in the Pyodide changelog.

I don't need to use `os.link` - but I have a dependency which has a dependency which references `os.link` in its source code.

Anything I can do about this? How can I understand the underlying change to Pyodide?

**Comment by rth** [comment]
`os.link`  has some [platform-dependent detection](https://github.com/python/cpython/blob/3.11/Modules/posixmodule.c#L3910) in CPython and becomes undefined if `HAVE_LINK` is not set on platforms with filesystems that do not support hard links (including Pyodide).

The related code in CPython didn't change much as far as I can tell between 3.10 and 3.11, so it might be due to a difference in the configuration after we switched to 3.11 using the setup that was reworked upstream to better work with WASM.  I haven't tracked the exact change.

In any case, it looks like it's the expected behavior in CPython, so I'm not sure we need to fix it. User code needs to handle the case if `os.link` is not defined in the long term. In the short term, maybe just monkeypatching to `os.symlink`, before importing that other module would be enough?
```py
import os
os.link = os.symlink
```

In Python 3.10 this function was not working anyway,
```py
>>> os.link('/tmp/a', '/tmp/b'')
Traceback (most recent call last):
  File "<console>", line 1, in <module>
OSError: [Errno 34] Too many links: '/tmp/a' -> '/tmp/b'
```

**Comment by rth** [comment]
Though for other methods in [`os` module](https://docs.python.org/3/library/os.html) the docstring explicitly states,
`Availability: ..., not Emscripten` while this one doesn't. So maybe we should open an issue upstream, at least to fix the docstring.

**Comment by hoodmane** [comment]
Yeah `HAVE_LINK` is defined to false since the `linkat` just returns an error saying it doesn't work:
```js
  __syscall_linkat: function(olddirfd, oldpath, newdirfd, newpath, flags) {
    return -{{{ cDefine('EMLINK') }}}; // no hardlinks for us
  },
```
interestingly Emscripten tip of tree they've removed it entirely. Either way, configure sees that it is missing.

**Comment by simonw** [comment]
>     import os
>.    os.link = os.symlink

Thank you! That hack totally fixed my problem.
