### ISSUE TITLE
Pyodide throwing `Cannot determine runtime environment` error in Next.js

### ISSUE THREAD

**Issue by spino17** [pyodide/pyodide#3893]
## 🐛 Bug
I am using pyodide in my next.js 13 project. I have placed following files inside `public` directory of next project:
package.json, pyodide.asm.js, pyodide.asm.wasm, pyodide.js, pyodide.mjs, python_stdlib.zip. I am doing following to load the module

### To Reproduce
```
import { loadPyodide } from "../public";
import { useEffect, useState } from "react";

// defining a custom hook to load the module
export function useInitProgrammingEnviroment(): InitializerResult {
  const [isInitialized, setIsInitialized] = useState<boolean>(false);
  const [pyodide, setPyodide] = useState<any | null>(null);
  useEffect(() => {
    const inner_func = async () => {
      let pyodideObject = await loadPyodide();
      setPyodide(pyodideObject);
      setIsInitialized(true);
    };
    inner_func();
  }, []);

  return { isInitialized, pyodide };
}
```

### Expected behavior
Now the problem is that I am seeing following error in my terminal while running the app `npm run dev`
```
error public/pyodide.js (1:8925) @ eval
- error Error: Cannot determine runtime environment
    at eval (./public/pyodide.js:231:29)
    at eval (./public/pyodide.js:2:13)
    at eval (./public/pyodide.js:3:2)
    at (sc_client)/./public/pyodide.js (/Users/bhavyabhatt/Desktop/bhavya/projects/www.jarvil-lang.org/.next/server/app/page.js:1930:1)
    at __webpack_require__ (/Users/bhavyabhatt/Desktop/bhavya/projects/www.jarvil-lang.org/.next/server/webpack-runtime.js:33:43)
    at eval (./hooks/playground.ts:10:65)
    at (sc_client)/./hooks/playground.ts (/Users/bhavyabhatt/Desktop/bhavya/projects/www.jarvil-lang.org/.next/server/app/page.js:622:1)
    at __webpack_require__ (/Users/bhavyabhatt/Desktop/bhavya/projects/www.jarvil-lang.org/.next/server/webpack-runtime.js:33:43)
    at eval (./app/page.tsx:11:75)
    at (sc_client)/./app/page.tsx (/Users/bhavyabhatt/Desktop/bhavya/projects/www.jarvil-lang.org/.next/server/app/page.js:589:1)
    at __webpack_require__ (/Users/bhavyabhatt/Desktop/bhavya/projects/www.jarvil-lang.org/.next/server/webpack-runtime.js:33:43)
```
But the code is working fine (the python code I am providing is executed and result is shown on the UI successfully) however I am not able to build the app using `npm run build`. Even though the app is working fine, I would have to fix this error to build the app.

**Comment by ryanking13** [comment]
Could you check if you can access `globalThis.document` just before calling `loadPyodide()`? The error message is about detecting whether you are running in the browser or in Node.js, and we do it by checking if globalThis.document exists.

**Comment by spino17** [comment]
Yeah, I am able to console.log `globalThis.document`. Currently I have bypassed the build issue but returning instead of throwing the error, but still it's feels hacky!

**Comment by ryanking13** [comment]
This is the full code that detects the runtime environment (browser / webworker / node):

https://github.com/pyodide/pyodide/blob/01e1fd6e38ecf036ce7394b4e5640bef393fa404/src/js/compat.ts#L179-L201

`IN_NODE` is defined as follows:

https://github.com/pyodide/pyodide/blob/69bbc529456b181fa5242f8eee007eb877a9a9a1/src/js/compat.ts#L4-L9

I don't know much about Next.js so I am not sure why it bypasses all three checks... Could you try setting a breakpoint in pyodide.js and see the conditions?

**Comment by spino17** [comment]
Yeah sure @ryanking13 I will try setting the breakpoints. Just one thing I need to understand is the error was throw in pyodide.js, above files are not those right ?

**Comment by ryanking13** [comment]
Yes, we generate pyodide.js from those files (using tsc), so pyodide.js should contain those code blocks.

It is worth noting that we also deploy source maps so browsers might be able to show original files which can be easy to debug.

**Comment by hoodmane** [comment]
Another thing that might help if the source maps aren't working is to run `npx prettier -w pyodide.js` before debugging. This doesn't improve readability as much as the source maps do but as a fallback I find that it is okay.

**Comment by ryanking13** [comment]
> @ryanking13 I have directly put the .wasm binaries and js glue code into public directory, can that be the reason of bypassing this check ?

No, I think it is a very normal way to use Pyodide. Maybe webpack do some optimization during the build which may break the check but I am not sure.

**Comment by JohannLai** [comment]
I also found this problem.

**Comment by david-andrew** [comment]
I'm also encountering this issue in next.js. I haven't quite solved it yet, but I think I'm close. With a bunch of logging, I've realized that `loadPyodide` is being called twice, once on the server side when next.js tries to compile the component, and once at runtime. The runtime one works fine since that's just running like normal in the browser, but the server side one fails because the next.js server environment is weird and doesn't have all the same things available that the client side does.

I think it basically comes down to preventing next.js from trying to compile `pyodide.js` in the server environment, and only treat it as a client side thing. Still working on how to do that, and will update when I figure it out!

For reference, this is the component I'm using to run a test pyodide script. I'm hosting the pyodide files in public, and am using the pyodide [npm library](https://www.npmjs.com/package/pyodide) for type information (notably though `loadPyodide` from the npm library works interchangeably here, but getting it from the publicly hosted version let me set debug messages and so forth):

```tsx
'use client'
import { useEffect, useState } from 'react'
import { PyodideInterface } from 'pyodide'
import { loadPyodide } from '@/public/pyodide@0.23.4'

export const usePyodide = () => {
    const [pyodide, setPyodide] = useState<PyodideInterface | null>(null)

    useEffect(() => {
        const initializePyodide = async () => {
            const loadedPyodide = await loadPyodide({
                // indexURL: 'https://cdn.jsdelivr.net/pyodide/v0.23.4/full/',
                indexURL: '/pyodide@0.23.4/',
            })
            console.log('Pyodide is ready to use:', loadedPyodide.version)
            setPyodide(loadedPyodide)
        }

        initializePyodide()
    }, [])

    return pyodide
}

export const Test = (): JSX.Element => {
    const [started, setStarted] = useState(false)
    const pyodide = usePyodide()
    useEffect(() => {
        if (!started) return
        pyodide
            ?.runPythonAsync(
                `
import sys

print("Hello from Python!")

sys.stdout.flush()
        `,
            )
            .then((result) => {
                console.log(result)
            })
    }, [started, pyodide])

    return (
        <>
            <button onClick={() => setStarted(true)}>Start</button>
        </>
    )
}
``` 

Also note with this component, in the next.js dev mode, the script can be run successfully. It's just when trying to build the app that the runtime environment exception is hit and the build fails

**Comment by david-andrew** [comment]
Ok, success at least with my test case. To get it working, you just have to **add a default export to your component** that is running the pyodide stuff (e.g. `export default Test` at the bottom of my code above). And then you have to **use a dynamic import with server-side-rendering turned off** wherever you want to use the component:

```tsx
import dynamic from 'next/dynamic'
const Test = dynamic(() => import('./test'), { ssr: false })

const Page = (): JSX.Element => {
    return (
        <Test/>
    )
}
```

I was not able to make it so you don't need the default export, but I think it's plenty workable for use in next.js projects

**Comment by robert** [comment]
@david-andrew thanks for posting the workaround - I haven't been able to get it to work though. Should this work as far as you can tell? 

```js
const pyodide = require("pyodide");

function PyodideTextArea() {
  
  async function runPythonCode() {
    const py = await pyodide.loadPyodide();
    await py.runPythonAsync(`
      import micropip
      await micropip.install('numpy')
      import numpy as np
      np.array([1, 2, 3])
    `);
  }

  return (
    <div>
      <button onClick={runPythonCode}>Run Python Code</button>
    </div>
  );
}

export default PyodideTextArea;
```

```js
import dynamic from 'next/dynamic'
const PyodideTextArea = dynamic(() => import("./pyodide/text_area"), { ssr: false })

export default function Home() {
  return <PyodideTextArea />;
}
```

**Comment by david-andrew** [comment]
@robert I'm not seeing anything majorly wrong (caveat that I'm still just a beginner with next.js). One thing I do recall is, I was having issues with the newer versions of pyodide. Not sure if it's relevant to your issues, but you might try setting it to use an earlier version, e.g.

```
const py = await pyodide.loadPyodide({
    indexURL: '/pyodide@0.23.4/',
})
```

**Comment by robert** [comment]
Thanks, that seems to have worked!

**Comment by type9** [comment]
For anyone looking for a solution with latest versions of pyodide with compatibility with npm package of pyodide here is my working solution

```ts
//next.config.js
/* eslint-disable @typescript-eslint/no-var-requires */
// Import the plugin
const { PyodidePlugin } = require("@pyodide/webpack-plugin")

/** @type {import('next').NextConfig} */
const nextConfig = {
	webpack: (config, { isServer }) => {
		// Add the PyodidePlugin to the plugins array
		if (!isServer) {
			config.plugins.push(new PyodidePlugin())
			// Replace node-fetch with an empty module on the client side, since it's not used there
			config.resolve.alias["node-fetch"] = false
		}
		if (isServer) {
			// Do not include Pyodide in the server-side bundle
			config.externals = ["pyodide", ...(config.externals || [])]
		}
		// Return the modified config
		return config
	},
}

module.exports = nextConfig
```

```ts
//usePyodide.ts
"use client"

import { useEffect, useState } from "react"
import { loadPyodide, PyodideInterface } from "pyodide"

export type UsePyodideProps = {
	packages?: string[]
}

export type UsePyodideState = {
	pyodide?: PyodideInterface
	isLoading: boolean
}

export const PYODIDE_INDEX_URL = `/pyodide/${process.env.NEXT_PUBLIC_PYODIDE_VERSION}/`

const loadPackages = async (pyodide: PyodideInterface, packages: string[]) => {
	await pyodide.loadPackage("micropip")
	const micropip = await pyodide.pyimport("micropip")
	await micropip.install(packages, true)
	console.log("Successfully insalled packages")
}

export const usePyodide = ({ packages }: UsePyodideProps) => {
	const [pyodideState, setPyodideState] = useState<UsePyodideState>({
		pyodide: undefined,
		isLoading: true,
	})

	useEffect(() => {
		if (typeof window === undefined) return
		if (pyodideState.pyodide !== undefined) {
			setPyodideState({ isLoading: true })
			loadPackages(pyodideState.pyodide, packages ?? []).then(() =>
				setPyodideState({
					isLoading: false,
				}),
			)
		}
		loadPyodide({ indexURL: PYODIDE_INDEX_URL })
			.then((pyodide) => {
				if (packages === undefined || packages.length === 0) {
					setPyodideState({ pyodide, isLoading: false })
					return
				}
				loadPackages(pyodide, packages)
					.then(() => setPyodideState({ pyodide, isLoading: false }))
					.catch((err) => console.log("Error loading packages:", err))
			})
			.catch((err) => console.log("Pyodide could not be loaded:", err))
	}, [packages])

	return pyodideState
}
```

in this example I'm serving v0.26.0a4 from my origin under my public folder and using pyodide package for typing and utility functions.
`npm i pyodide@0.26.0-alpha.4`

**Comment by terrablue** [comment]
@ryanking13 hi, I'm getting the same error when trying to use Bun. I saw that it has been generally resolved in https://github.com/pyodide/pyodide/issues/4915, thanks for that.

I would like to suggest a different approach for environment detection, one that is more robust than your current one and also generally doesn't pull in everything for every runtime: [conditional exports](https://nodejs.org/api/packages.html#conditional-exports). It's currently somewhat lesser known, although it has been supported since Node 13.

This is widely supported across the board, with Deno support `"deno"`, Bun supporting `"bun"` and most cloud providers supporting their own keys.

My library, rcompat, makes extensive use of this: https://github.com/rcompat/rcompat/blob/master/packages/webview/package.json#L29-L38

You could potentially completely get rid of your `compat.ts` file with this.

**Comment by ryanking13** [comment]
Thanks @terrablue. We do use [conditional exports](https://github.com/pyodide/pyodide/blob/139b40f48a6d0a6877fa3d564690dbf8722b1afe/src/js/package.json#L42-L47), but maybe we are not taking advantage of it correctly. I'll take a look when I have some bandwidth.

**Comment by hoodmane** [comment]
It looks to me like conditional exports won't really work for us: we have to support browsers as well as server-side JS runtimes and we bundle everything together ahead of time. It is possible we could use a bundler for the browser and conditional exports for bun/node/deno, but this would introduce a fair amount of extra complexity compared to our current approach.

**Comment by terrablue** [comment]
@hoodmane the `"browser"` target covers browsers; that's the [Svelte approach](https://github.com/sveltejs/svelte/blob/main/packages/svelte/package.json#L24-L25).

**Comment by hoodmane** [comment]
But what does that do? Does it change the behavior of esbuild? Browsers surely never look at `package.json`.

**Comment by terrablue** [comment]
Yes, it affects the behaviour of bundlers. I mean, anything in `package.json` isn't relevant for a browser unless you use a bundler anyway.

What's the rationale for prebundling here? It has become somewhat uncommon to prebundle today.

But even under that assumption, prebundling (by whatever tool) would only need to use the entrypoint that otherwise `"browser"` would point to, no? It would still allow for a clear separation of entrypoint files into Bun/Node/Browser.

**Comment by hoodmane** [comment]
Well there's a couple reasons. One is so that we can make `libpyodide.a` as a thing that you can link against. It's possible to use this with other projects that embed Python + Pyodide. After we bundle the JS code, we make a C source file with the JS code as a giant string and then compile that and stick the resulting object file into `libpyodide.a`
https://github.com/pyodide/pyodide/blob/main/Makefile?plain=1#L36-L85

But the other reason is that we prebundle as a hack to close over the state of the Emscripten code. Basically, the Emscripten/webassembly runtime has a bunch of state inside it, including a bunch of function definitions like `callIntoCompiledCode()`, and each time you call `loadPyodide` the resulting module that comes out should have its own distinct `callIntoCompiledCode()` bound to that particular webassembly runtime. I tried to remove all of the typescript "globals" that are actually bound to a single webassembly instance, but I ended up basically having to write my own inferior module resolution logic to get the state right. So I figured, if what needs to be done is module resolution, why not have the bundler do it for us.

**Comment by terrablue** [comment]
That's fair enough. FWIW, supporting a `"browser"` target might actually solve the problem described by this ticket -- by properly loading the correct entrypoint of Pyodide for backend and frontend.

In my case, I use Pyodide to write backend server routes in Python, but I figure that it would be equally interesting, within the same project, to write Python in the frontend components. So one invocation would be normal Bun/Node backend usage, and another would be bundleable by whatever bundler the framework uses (I use esbuild; I believe Next uses Webpack).

If you throw in additionally server-side rendering of components (as seems to be the case here), you might actually even have three distinct usages of Pyodide all in the same project. It would be nice if they were all supported in their own right.

Does that make sense to you?

**Comment by ryanking13** [comment]
cc: @Drranny

**Comment by Drranny** [comment]
> cc: [@Drranny](https://github.com/Drranny)

I’ve been looking into this issue and tried analyzing the runtime detection states.
Would it be possible to assign this to me?
I’d like to continue investigating it in this direction.
