### ISSUE TITLE
  File "<exec>", line 110, in <module> ValueError: Invalid file format. Only Excel, CSV, and JSON files are supported.

### ISSUE THREAD

**Issue by wanghaisheng** [pyodide/pyodide#3899]
## 🐛 Bug

```
[appConfig.js:1:962](moz-extension://3ba71175-cae3-463c-81c1-8b5b36d6b2e0/js/appConfig.js)
Loading pandas, numpy, python-dateutil, six, pytz, pillow [pyodide.asm.js:9:115741](https://cdn.jsdelivr.net/pyodide/v0.23.2/full/pyodide.asm.js)
Loaded six, python-dateutil, pytz, pillow, numpy, pandas [pyodide.asm.js:9:116103](https://cdn.jsdelivr.net/pyodide/v0.23.2/full/pyodide.asm.js)
Uncaught (in promise) PythonError: Traceback (most recent call last):
  File "/lib/python311.zip/_pyodide/_base.py", line 540, in eval_code_async
    await CodeRunner(
  File "/lib/python311.zip/_pyodide/_base.py", line 363, in run_async
    coroutine = eval(self.code, globals, locals)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<exec>", line 110, in <module>
ValueError: Invalid file format. Only Excel, CSV, and JSON files are supported.
    PythonError https://cdn.jsdelivr.net/pyodide/v0.23.2/full/pyodide.asm.js:9
    new_error https://cdn.jsdelivr.net/pyodide/v0.23.2/full/pyodide.asm.js:9
    _PyCFunctionWithKeywords_TrampolineCall https://cdn.jsdelivr.net/pyodide/v0.23.2/full/pyodide.asm.js:9
    callPyObjectKwargs https://cdn.jsdelivr.net/pyodide/v0.23.2/full/pyodide.asm.js:9
    callPyObject https://cdn.jsdelivr.net/pyodide/v0.23.2/full/pyodide.asm.js:9
    wrapper https://cdn.jsdelivr.net/pyodide/v0.23.2/full/pyodide.asm.js:9
    setTimeout handler*hiwire_call_bound https://cdn.jsdelivr.net/pyodide/v0.23.2/full/pyodide.asm.js:9
    _PyCFunctionWithKeywords_TrampolineCall https://cdn.jsdelivr.net/pyodide/v0.23.2/full/pyodide.asm.js:9
    callPyObjectKwargs https://cdn.jsdelivr.net/pyodide/v0.23.2/full/pyodide.asm.js:9
    callPyObject https://cdn.jsdelivr.net/pyodide/v0.23.2/full/pyodide.asm.js:9
    wrapper https://cdn.jsdelivr.net/pyodide/v0.23.2/full/pyodide.asm.js:9
    setTimeout handler*hiwire_call_bound https://cdn.jsdelivr.net/pyodide/v0.23.2/full/pyodide.asm.js:9
    _PyCFunctionWithKeywords_TrampolineCall https://cdn.jsdelivr.net/pyodide/v0.23.2/full/pyodide.asm.js:9
    __pyproxy_ensure_future https://cdn.jsdelivr.net/pyodide/v0.23.2/full/pyodide.asm.js:9
    _ensure_future https://cdn.jsdelivr.net/pyodide/v0.23.2/full/pyodide.asm.js:9
    callPyObjectKwargs https://cdn.jsdelivr.net/pyodide/v0.23.2/full/pyodide.asm.js:9
    callPyObject https://cdn.jsdelivr.net/pyodide/v0.23.2/full/pyodide.asm.js:9
    apply https://cdn.jsdelivr.net/pyodide/v0.23.2/full/pyodide.asm.js:9
    apply https://cdn.jsdelivr.net/pyodide/v0.23.2/full/pyodide.asm.js:9
    runPythonAsync https://cdn.jsdelivr.net/pyodide/v0.23.2/full/pyodide.asm.js:9
    onload https://wanghaisheng.github.io/video-publish-metadata-gpt/:72
    processFile https://wanghaisheng.github.io/video-publish-metadata-gpt/:62
    EventListener.handleEvent* https://wanghaisheng.github.io/video-publish-metadata-gpt/:221
```

### To Reproduce

url:
https://wanghaisheng.github.io/video-publish-metadata-gpt/

data.json

https://github.com/wanghaisheng/video-publish-metadata-gpt/blob/gh-pages/data.json

source code 

https://github.com/wanghaisheng/video-publish-metadata-gpt/blob/gh-pages/index.html

### Environment

- Pyodide Version:
- Browser version:
- Any other relevant information:

**Comment by ryanking13** [comment]
```
file_extension = '${fileExtension}'
if file_extension == '.xlsx':
    df = pd.read_excel(file_buffer)
elif file_extension == '.csv':
    df = pd.read_csv(file_buffer)
elif file_extension == '.json':
    data = pyodide.toPy(JSON.parse(pyodide.fromPy(file_buffer)))
    df = pd.DataFrame(data)
else:
    raise ValueError('Invalid file format. Only Excel, CSV, and JSON files are supported.')
```

I think you should check what value is stored in `file_extension `.

**Comment by wanghaisheng** [comment]
line 65
would that be 
          const fileExtension = fileName.split(".").pop().toLowerCase();

**Comment by wanghaisheng** [comment]
@ryanking13 thanks  I print the value and fix this one

I notice the source has 
```
        pyodide = await loadPyodide();

          await pyodide.runPythonAsync(`
................
pyodide.toPy(JSON.parse(pyodide.fromPy(file_buffer)))
...................
```
but it says 
NameError: name 'pyodide' is not defined

**Comment by ryanking13** [comment]
I guess you forgot `import pyodide`? Pyodide works on both Python and JavaScript, so you'll need to pay attention to which language you're working in.

**Comment by ryanking13** [comment]
Closing as no activity
