### ISSUE TITLE
fatal error: TypeError: Cannot read properties of null (reading 'atime')

### ISSUE THREAD

**Issue by EmileKroeger** [pyodide/pyodide#3962]
## 🐛 Bug

I sometimes get a crash, which includes this info:

```
Uncaught (in promise) TypeError: Cannot destructure property 'path' of 'a' as it is null.
    at I._onMessage (broadcast.ts:62:13)
Pyodide has suffered a fatal error. Please report this to the Pyodide maintainers.
API.fatal_error @ pyodide.asm.js:9
pyodide.asm.js:9 The cause of the fatal error was:
API.fatal_error @ pyodide.asm.js:9
pyodide.asm.js:9 TypeError: Cannot read properties of null (reading 'atime')
    at mi.getattr (worker.js:7:4645)
    at hi.getattr (worker.js:7:1854)
    at stat (pyodide.asm.js:9:214497)
    at Object.doStat (pyodide.asm.js:9:234649)
    at ___syscall_stat64 (pyodide.asm.js:9:276531)
    at pyodide.asm.wasm:0x430c5f
    at pyodide.asm.wasm:0x449d2f
    at pyodide.asm.wasm:0x381a6b
    at pyodide.asm.wasm:0x381303
    at pyodide.asm.wasm:0x2654b8
API.fatal_error @ pyodide.asm.js:9
pyodide.asm.js:9 Stack (most recent call first):
pyodide.asm.js:9   File "<frozen importlib._bootstrap_external>", line 147 in _path_stat
pyodide.asm.js:9   File "<frozen importlib._bootstrap_external>", line 153 in _path_is_mode_type
```
(omitting the rest of the call stap as it seems less relevant)

### To Reproduce

This bug is random, and I have observed it after opening two windows on the same jupyter lite website (ran locally on my computer); but I haven't narrowed down exact reproduction steps (sometimes it crashes, sometimes it doesn't). So far I've seen this crash happen twice.

### Environment

I'm using jupyter lite with the pyodide kernel
jupyterlite-pyodide-kernel 0.0.8

- Pyodide Version 0.23.2 (that looks like it's the one in jupyterlite-pyodide-kernel 0.0.8)
- Browser version Brave: [Version 1.52.126 Chromium: 114.0.5735.133 (Official Build) (64-bit)](https://brave.com/latest/)
- Any other relevant information:

### Additional context

Id id this in the context of testing a jupyter lite plugin, but actually had this crash on notebooks that didn't even try to use that plugin.

**Comment by EmileKroeger** [comment]
Missing context:
- this typically happens when executing a cell, in the last case this one (the first of the notebook):

> print(2+2)

(the cell then gets stuck in [*])
