### ISSUE TITLE
PydanticUserError when using pyodide build with pydantic>=2 

### ISSUE THREAD

**Issue by lesteve** [pyodide/pyodide#3978]
## 🐛 Bug

Pydantic 2 release (2.0 release is quite recent: June 30 2023) seems to break `pyodide build`. Maybe something to consider for 0.23.4 if it's an easy fix?

### To Reproduce

```
pip install pyodide-build
pyodide build
```

You get this error:
```
pydantic.errors.PydanticUserError: If you use `@root_validator` with pre=False (the default) you MUST specify `skip_on_failure=True`. Note that `@root_validator` is deprecated and should be replaced with `@model_validator`.
```

<details>
<summary>Full-traceback</summary>

```
Traceback (most recent call last):
  File "/home/lesteve/micromamba/envs/pyodide/bin/pyodide", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/lesteve/micromamba/envs/pyodide/lib/python3.11/site-packages/pyodide_cli/app.py", line 84, in main
    register_plugins()
  File "/home/lesteve/micromamba/envs/pyodide/lib/python3.11/site-packages/pyodide_cli/app.py", line 54, in register_plugins
    plugins = {ep.name: (ep.load(), ep) for ep in eps}
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lesteve/micromamba/envs/pyodide/lib/python3.11/site-packages/pyodide_cli/app.py", line 54, in <dictcomp>
    plugins = {ep.name: (ep.load(), ep) for ep in eps}
                         ^^^^^^^^^
  File "/home/lesteve/micromamba/envs/pyodide/lib/python3.11/importlib/metadata/__init__.py", line 202, in load
    module = import_module(match.group('module'))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lesteve/micromamba/envs/pyodide/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/lesteve/micromamba/envs/pyodide/lib/python3.11/site-packages/pyodide_build/cli/build.py", line 12, in <module>
    from .. import common
  File "/home/lesteve/micromamba/envs/pyodide/lib/python3.11/site-packages/pyodide_build/common.py", line 27, in <module>
    from .recipe import load_all_recipes
  File "/home/lesteve/micromamba/envs/pyodide/lib/python3.11/site-packages/pyodide_build/recipe.py", line 5, in <module>
    from .io import MetaConfig
  File "/home/lesteve/micromamba/envs/pyodide/lib/python3.11/site-packages/pyodide_build/io.py", line 19, in <module>
    class _SourceSpec(BaseModel):
  File "/home/lesteve/micromamba/envs/pyodide/lib/python3.11/site-packages/pyodide_build/io.py", line 30, in _SourceSpec
    @pydantic.root_validator
     ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lesteve/micromamba/envs/pyodide/lib/python3.11/site-packages/pydantic/deprecated/class_validators.py", line 222, in root_validator
    return root_validator()(*__args)  # type: ignore
           ^^^^^^^^^^^^^^^^
  File "/home/lesteve/micromamba/envs/pyodide/lib/python3.11/site-packages/pydantic/deprecated/class_validators.py", line 228, in root_validator
    raise PydanticUserError(
pydantic.errors.PydanticUserError: If you use `@root_validator` with pre=False (the default) you MUST specify `skip_on_failure=True`. Note that `@root_validator` is deprecated and should be replaced with `@model_validator`.

For further information visit https://errors.pydantic.dev/2.0.1/u/root-validator-pre-skip
```

</details>

### Expected behavior

No error

**Comment by rth** [comment]
Thanks I think this was fixed and scheduled for backporting in https://github.com/pyodide/pyodide/pull/3971

**Comment by lesteve** [comment]
Yeah I saw that just after opening this issue ... I swear I searched in the github issues before :sweat_smile:

**Comment by rth** [comment]
Looks like there were no issues, just a PR..
