### ISSUE TITLE
C++ exceptions are not getting caught in Pyodide. It's causing fatal error in pyodide

### ISSUE THREAD

**Issue by nayankr-jain** [pyodide/pyodide#4049]
## 🐛 Bug 
C++ exception are not getting caught in Pyodide. It's causing fatal error in pyodide. I am trying to catch the exception with try except block in python script but its not catching exception and causing fatal error. 

### To Reproduce
I am using shapely package of python on frontend to calculate area and perimeter of polygon with the help of pyodide. But when the area is invalid make_valid function is called. This is raising TopologyException. I am trying to catch this error with try except block, its not catching this exception. 

json_geom = {"type": "Polygon", "coordinates": [[[-82.499795, 27.350887], [-82.499783, 27.350895], [-82.49977, 27.350901], [-82.499739, 27.350912], [-82.499719, 27.35092], [-82.499706, 27.350926], [-82.49969, 27.35093], [-82.499678, 27.350929], [-82.499666, 27.350925], [-82.499661, 27.350917], [-82.499666, 27.35092], [-82.499676, 27.350915], [-82.499786, 27.350883], [-82.499801, 27.350878], [-82.499797, 27.35087], [-82.49982, 27.350864], [-82.499815, 27.350852], [-82.499849, 27.350842], [-82.499849, 27.350843], [-82.499855, 27.350852], [-82.500034, 27.350793], [-82.499978, 27.350685], [-82.499997, 27.350697], [-82.500007, 27.350707], [-82.500021, 27.350705], [-82.500021, 27.350708], [-82.500033, 27.350738], [-82.500041, 27.350757], [-82.500052, 27.350781], [-82.500052, 27.350793], [-82.50005, 27.350802], [-82.500049, 27.350804], [-82.500042, 27.350813], [-82.49997588888888, 27.35083244444445], [-82.499972, 27.350834], [-82.499795, 27.350887]], [[-82.499997, 27.350824], [-82.499974, 27.350833], [-82.49997588888888, 27.35083244444445], [-82.499997, 27.350824]]]}

from shapely.validation import make_valid
from shapely.geometry import shape

shape_geom  = shape(json_geom)
if not shape_geom.is_valid:
    try:
        shape_geom = make_valid(shape_geom)
    except Exception as e:
        return []

### Expected behavior
Should return empty list but it's giving fatal error

### Environment

- Pyodide Version: 0.23.4
- Browser version:Version 115.0.5790.102 (Official Build) (64-bit)
- Any other relevant information:
- shapely version: 1.8.2

**Comment by hoodmane** [comment]
I can't reproduce this. In particular, no exception is thrown when I try it:
```js
await pyodide.loadPackage("shapely");
pyodide.runPython(`
json_geom = { ... your geometry here }

from shapely.validation import make_valid
from shapely.geometry import shape

print("A")
shape_geom = shape(json_geom)
print("shape_geom.is_valid", shape_geom.is_valid) # for me says True
try:
    shape_geom = make_valid(shape_geom)
    print("no exception") # prints "no exception"
except Exception as e:
    print("caught exception", e)
`);
```

**Comment by nayankr-jain** [comment]
can you please try this geometry 
json_geom = {'type': 'Polygon', 'coordinates': [[[-82.499795, 27.350887], [-82.499783, 27.350895], [-82.49977, 27.350901], [-82.499739, 27.350912], [-82.499719, 27.35092], [-82.499706, 27.350926], [-82.49969, 27.35093], [-82.499678, 27.350929], [-82.499666, 27.350925], [-82.499661, 27.350917], [-82.499666, 27.35092], [-82.499676, 27.350915], [-82.499786, 27.350883], [-82.499801, 27.350878], [-82.499797, 27.35087], [-82.49982, 27.350864], [-82.499815, 27.350852], [-82.499849, 27.350842], [-82.499849, 27.350843], [-82.499855, 27.350852], [-82.500034, 27.350793], [-82.499978, 27.350685], [-82.499997, 27.350697], [-82.500007, 27.350707], [-82.500021, 27.350705], [-82.500021, 27.350708], [-82.500033, 27.350738], [-82.500041, 27.350757], [-82.500052, 27.350781], [-82.500052, 27.350793], [-82.50005, 27.350802], [-82.500049, 27.350804], [-82.500042, 27.350813], [-82.499976, 27.350832], [-82.499972, 27.350834], [-82.499795, 27.350887]], [[-82.499997, 27.350824], [-82.499974, 27.350833], [-82.499976, 27.350832], [-82.499997, 27.350824]]]}

**Comment by whatdym** [comment]
I ran into the same issue when using intersection method between 2 polygons

`Pyodide has suffered a fatal error. Please report this to the Pyodide maintainers.
The cause of the fatal error was:
CppException geos::util::TopologyException: TopologyException: found non-noded intersection between LINESTRING and LINESTRING at
    at convertCppException (https://cdn.jsdelivr.net/pyodide/v0.24.1/full/pyodide.asm.js:9:101541)
    at API.fatal_error (https://cdn.jsdelivr.net/pyodide/v0.24.1/full/pyodide.asm.js:9:101828)
    at API.maybe_fatal_error (https://cdn.jsdelivr.net/pyodide/v0.24.1/full/pyodide.asm.js:9:102669)
    at Module.callPyObjectKwargs (https://cdn.jsdelivr.net/pyodide/v0.24.1/full/pyodide.asm.js:9:81772)
    at Proxy.callKwargs (https://cdn.jsdelivr.net/pyodide/v0.24.1/full/pyodide.asm.js:9:97507)
    at Object.runPython (https://cdn.jsdelivr.net/pyodide/v0.24.1/full/pyodide.asm.js:9:118859)`
