### ISSUE TITLE
Cannot .toJs() a numpy.ndarray containing BigInt values - Error: Unrecognized format character 'O'

### ISSUE THREAD

**Issue by paulcalcraft** [pyodide/pyodide#4051]
## 🐛 Bug

Running `.toJs()` on a PyProxy of a numpy.ndarray containing BigInt throws an exception: "Error: Unrecognized format character 'O'"

### To Reproduce

```html
<!doctype html>
<html>
  <head>
      <script src="https://cdn.jsdelivr.net/pyodide/v0.23.4/full/pyodide.js"></script>
  </head>
  <body>
    NumPy BigInt toJs() error<br>
    Open your browser console to see Pyodide output
    <script type="text/javascript">
      async function main(){
        let pyodide = await loadPyodide();
        console.log(pyodide.runPython(`
            import sys
            sys.version
        `));
        await pyodide.loadPackage("numpy");
        let ndarray = await pyodide.runPython(`import numpy as np

# Creating a numpy array with Python's native integers
bigints = [10**100, 10**200, 10**300]
arr = np.array(bigints, dtype=object)

# Output the array
arr`);
        console.log(ndarray.type); // numpy.ndarray
        ndarray.toJs(); // PythonError: pyodide.ffi.JsException: Error: Unrecognized format character 'O'.
      }
      main();
    </script>
  </body>
</html>
```

```
Uncaught (in promise) PythonError: pyodide.ffi.JsException: Error: Unrecognized format character 'O'.

The above exception was the direct cause of the following exception:

pyodide.ffi.ConversionError: Conversion from python to javascript failed

    at new_error (pyodide.asm.js:9:14992)
    at pyodide.asm.wasm:0x152d67
    at pyodide.asm.wasm:0x152e6c
    at Module._pythonexc2js (pyodide.asm.js:9:656029)
    at Proxy.toJs (pyodide.asm.js:9:77512)
    at main (bigint_pyodide_error_repro.html:24:7)
new_error @ pyodide.asm.js:9
$wrap_exception @ pyodide.asm.wasm:0x152d67
$pythonexc2js @ pyodide.asm.wasm:0x152e6c
Module._pythonexc2js @ pyodide.asm.js:9
toJs @ pyodide.asm.js:9
main @ bigint_pyodide_error_repro.html:24
await in main (async)
(anonymous) @ bigint_pyodide_error_repro.html:26
```

### Expected behavior

According to type conversions, BigInt should convert to Number or int, which is possibly lossy, but should not throw an error. https://pyodide.org/en/stable/usage/type-conversions.html

### Environment

- Pyodide Version: v0.23.4
- Browser version: Chrome 115.0.5790.111 (Official Build) (64-bit)
- Any other relevant information:

### Additional context

N/A

**Comment by hoodmane** [comment]
Hmm, it seems that the numpy buffer has a format string of "O". [The Buffer protocol specification says](https://docs.python.org/3/c-api/buffer.html#c.Py_buffer.format) the format string is

> A NUL terminated string in [struct](https://docs.python.org/3/library/struct.html#format-characters) module style syntax describing the contents of a single item. If this is NULL, "B" (unsigned bytes) is assumed.

The format characters listed there include `"P"` for `void*` but not `"O"` for `PyObject*`. So it seems that numpy uses some nonstandard extensions to the python buffer protocol. @mattip @charris is there a place where this is documented? It would be helpful for consumers of the buffer protocol to have a single reference for the set of possible format strings that "accepted, well-behaving" implementations of `bf_getbuffer` can produce...

I see that in addition to `"O"` there are `"Zf"`, `"Zd"`, and `"Zg"` for complex floating point types. It's not obvious how we would handle those anyways other than making a clearer error message.

**Comment by mattip** [comment]
There is some documentation in the [array interface](https://numpy.org/devdocs/reference/arrays.interface.html#python-side) page, but I think this is not the whole story. As you point out, `Zf`, `Zd` and `Zg` do not appear there (in fact, `c` is character and not complex as appears there), and the [np.structured arrays](https://numpy.org/devdocs/user/basics.rec.html)  minilanguage is, as far as I could tell, not documented. A few examples:
```
>>> memoryview(np.ones([10], dtype=[('a', float), ('b', int)])).format
'T{d:a:l:b:}'
>>> memoryview(np.ones([10], dtype=[('a', float), ('b', int, [10,10])])).format
'T{d:a:(10,10)l:b:}'
```

**Comment by hoodmane** [comment]
Ah PEP 3118 has more:
https://peps.python.org/pep-3118/

**Comment by hoodmane** [comment]
Oh gross pep3118 was never fully implemented and in fact it is not entirely well specified:
https://github.com/python/cpython/issues/47382

> The new features of the struct-string syntax are so different that I think
> we need to specify a grammar. I think it will clarify some of the open
> questions.

**Comment by hoodmane** [comment]
Opened a question on the status of PEP 3118:
https://discuss.python.org/t/question-pep-3118-format-strings-and-the-buffer-protocol/31264
