### ISSUE TITLE
Tinygrad on Pyodide

### ISSUE THREAD

**Issue by jonah3218** [pyodide/pyodide#4067]
## 🐛 Bug

I was trying to use Tinygrad with Pyodide. Tinygrad is a bare bones deep learning framework, basically Pytorch with most of the extra functionality stripped away. Tinygrad is a pue python package so its pretty easy to import but it doesn't work for any larger examples. For instance, I was doing basic convolution like this:

```
BS, C1, H, W = 4, 16, 224, 224
C2, K, S, P = 64, 7, 2, 1
x = Tensor.uniform(BS, C1, H, W)
conv = Conv2d(C1, C2, kernel_size=K, stride=S, padding=P)
bn = BatchNorm2d(C2, track_running_stats=False)
for t in get_parameters([x, conv, bn]): t.realize()

print("running network")
y=x.sequential([conv, bn]).numpy()
```
And it fails with one of two errors depend how large i set the H and W parameters to. Typically, it will succeed if  H and W are below 200 and the other parameters remain constant.:
```
PythonError: Traceback (most recent call last):
  File "/lib/python3.10/asyncio/futures.py", line 201, in result
    raise self._exception
  File "/lib/python3.10/asyncio/tasks.py", line 232, in __step
    result = coro.send(None)
  File "/lib/python3.10/_pyodide/_base.py", line 532, in eval_code_async
    await CodeRunner(
  File "/lib/python3.10/_pyodide/_base.py", line 355, in run_async
    coroutine = eval(self.code, globals, locals)
  File "<exec>", line 31, in <module>
  File "/lib/python3.10/site-packages/tinygrad/tensor.py", line 102, in numpy
    def numpy(self) -> np.ndarray: return self.lazydata.toCPU()
  File "/lib/python3.10/site-packages/tinygrad/lazy.py", line 170, in toCPU
    realized = self.cast(dtypes.from_np(self.dtype.np)).contiguous().realize().realized
  File "/lib/python3.10/site-packages/tinygrad/lazy.py", line 116, in realize
    realized = self.op.src[0].realize().realized
  File "/lib/python3.10/site-packages/tinygrad/lazy.py", line 132, in realize
    for x in get_buffers(self.op): x.realize()
  File "/lib/python3.10/site-packages/tinygrad/lazy.py", line 132, in realize
    for x in get_buffers(self.op): x.realize()
  File "/lib/python3.10/site-packages/tinygrad/lazy.py", line 143, in realize
    self.realized = Device[self.device].exec_ast(self.op, output=self, **self._device_extra_args())
  File "/lib/python3.10/site-packages/tinygrad/ops.py", line 53, in exec_ast
    ret = self.buffer(self.fxn_for_op[ast.op](*([self.to_underlying(x) for x in srcs] + ([ast.arg] if ast.arg is not None else []))))
  File "<__array_function__ internals>", line 180, in broadcast_to
  File "/lib/python3.10/site-packages/numpy/lib/stride_tricks.py", line 413, in broadcast_to
    return _broadcast_to(array, shape, subok=subok, readonly=True)
  File "/lib/python3.10/site-packages/numpy/lib/stride_tricks.py", line 349, in _broadcast_to
    it = np.nditer(
ValueError: iterator is too large
```

or

```
PythonError: Traceback (most recent call last):
  File "/lib/python3.10/asyncio/futures.py", line 201, in result
    raise self._exception
  File "/lib/python3.10/asyncio/tasks.py", line 232, in __step
    result = coro.send(None)
  File "/lib/python3.10/_pyodide/_base.py", line 532, in eval_code_async
    await CodeRunner(
  File "/lib/python3.10/_pyodide/_base.py", line 355, in run_async
    coroutine = eval(self.code, globals, locals)
  File "<exec>", line 31, in <module>
  File "/lib/python3.10/site-packages/tinygrad/tensor.py", line 102, in numpy
    def numpy(self) -> np.ndarray: return self.lazydata.toCPU()
  File "/lib/python3.10/site-packages/tinygrad/lazy.py", line 170, in toCPU
    realized = self.cast(dtypes.from_np(self.dtype.np)).contiguous().realize().realized
  File "/lib/python3.10/site-packages/tinygrad/lazy.py", line 116, in realize
    realized = self.op.src[0].realize().realized
  File "/lib/python3.10/site-packages/tinygrad/lazy.py", line 132, in realize
    for x in get_buffers(self.op): x.realize()
  File "/lib/python3.10/site-packages/tinygrad/lazy.py", line 132, in realize
    for x in get_buffers(self.op): x.realize()
  File "/lib/python3.10/site-packages/tinygrad/lazy.py", line 132, in realize
    for x in get_buffers(self.op): x.realize()
  [Previous line repeated 10 more times]
  File "/lib/python3.10/site-packages/tinygrad/lazy.py", line 143, in realize
    self.realized = Device[self.device].exec_ast(self.op, output=self, **self._device_extra_args())
  File "/lib/python3.10/site-packages/tinygrad/ops.py", line 53, in exec_ast
    ret = self.buffer(self.fxn_for_op[ast.op](*([self.to_underlying(x) for x in srcs] + ([ast.arg] if ast.arg is not None else []))))
  File "<__array_function__ internals>", line 180, in broadcast_to
  File "/lib/python3.10/site-packages/numpy/lib/stride_tricks.py", line 413, in broadcast_to
    return _broadcast_to(array, shape, subok=subok, readonly=True)
  File "/lib/python3.10/site-packages/numpy/lib/stride_tricks.py", line 354, in _broadcast_to
    broadcast = it.itviews[0]
ValueError: array is too big; `arr.size * arr.dtype.itemsize` is larger than the maximum possible size
```

I'm pretty sure this a product of tinygrad using lazy computation and it overwhelming the memory. If anyone has any advice on how to fix this, that it would be greatly appreciated. It also may be a product of numpy using an alternate method to do convolutions which includes making a large array ith many dimensions.

### To Reproduce

Run this Python code in Pyodide to reproduce the error. It's the .Numpy() function that forces Tinygrad to do all the computation at once by the way.

Dependency list: numpy and tinygrad

```

from tinygrad.tensor import Tensor
from tinygrad.nn import Conv2d, BatchNorm2d
from typing import Dict, Union, List
from collections import OrderedDict

def get_state_dict(obj, prefix:str='', tensor_type=Tensor) -> Dict[str, Tensor]:
  if isinstance(obj, tensor_type): return {prefix.strip('.'):obj}
  if hasattr(obj, '_asdict'): return get_state_dict(obj._asdict(), prefix, tensor_type)  # namedtuple
  if isinstance(obj, OrderedDict): return get_state_dict(dict(obj), prefix, tensor_type)
  if hasattr(obj, '__dict__'): return get_state_dict(obj.__dict__, prefix, tensor_type)
  state_dict = {}
  if isinstance(obj, (list, tuple)):
    for i,x in enumerate(obj): state_dict.update(get_state_dict(x, f"{prefix}{str(i)}.", tensor_type))
  elif isinstance(obj, dict):
    for k,v in obj.items(): state_dict.update(get_state_dict(v, f"{prefix}{str(k)}.", tensor_type))
  return state_dict
  
def get_parameters(obj) -> List[Tensor]: return list(get_state_dict(obj).values())

if __name__ == "__main__":
  Tensor.training = True

  BS, C1, H, W = 4, 16, 224, 224
  C2, K, S, P = 64, 7, 2, 1
  x = Tensor.uniform(BS, C1, H, W)
  conv = Conv2d(C1, C2, kernel_size=K, stride=S, padding=P)
  bn = BatchNorm2d(C2, track_running_stats=False)
  for t in get_parameters([x, conv, bn]): t.realize()

  print("running network")
  y=x.sequential([conv, bn]).numpy()
```
Thanks in advance, it would be really cool to get all of this package's functionality working with Pyodide because it would allow for DL training and inferencing to be done in the browser with relatively large models.

**Comment by ryanking13** [comment]
> I'm pretty sure this a product of tinygrad using lazy computation and it overwhelming the memory. If anyone has any advice on how to fix this, that it would be greatly appreciated. It also may be a product of numpy using an alternate method to do convolutions which includes making a large array ith many dimensions.

Thanks for the report @jonah3218. If this is indeed a memory issue, I hate to say it, but I don't think there's much Pyodide can do about it. There are browser limitations on allocating more than 2GB (or 4GB) of memory, so if the problem is caused by allocating more than that, it's hard to fix.

If so, you'll need to find a way to avoid allocating memory all at once, which is something you'll need to ask the tinygrad or numpy teams about.

**Comment by jonah3218** [comment]
What do you think about running Pyodide in an environment with memory64, I think that firefox nightly build has that enabled? Would that help the memory limit?

**Comment by ryanking13** [comment]
> What do you think about running Pyodide in an environment with memory64

Yes, I think it would help the memory limit. But someone with strong interests would need to do a lot of trial and error. I mean, all Pyodide developers are interested in new features in WASM, including memory64, but we have more work to do than we can afford to do, especially considering that we are all volunteers working part-time.

So while memory64 could be helpful, we can't promise that it will be supported anytime soon.
