### ISSUE TITLE
Opencv Image Loading Error

### ISSUE THREAD

**Issue by zubairhassan652** [pyodide/pyodide#4124]
### To Reproduce
```
img_stream = io.StringIO(base64imgstr)
numpy_img = np.asarray(bytearray(img_stream.read(), "utf-8"), dtype=np.uint8)
img = cv2.imdecode(numpy_img, cv2.IMREAD_COLOR)
```

### Expected behavior

It should return img object of opencv image

### Environment

- cv2: 4.7.0
- numpy: 1.24.2
- pyscript: 2022.12.1.dev
- pyodide: 0.23.4
- Chrome 115.0.5790.170 

### Additional context
Basically i pick image from html <input type="file" id="fileInput" accept="image/*">  and try to read it in opencv for processing 
input tag returns me base64 image string which converted to stream using io.StringIO() and pass it to numpy to numpy array
for opencv image loading but got below exception.

```
pyodide.asm.js:9 Pyodide has suffered a fatal error. Please report this to the Pyodide maintainers.
API.fatal_error @ pyodide.asm.js:9
Module.callPyObjectKwargs @ pyodide.asm.js:9
Module.callPyObject @ pyodide.asm.js:9
apply @ pyodide.asm.js:9
apply @ pyodide.asm.js:9
reader.onload @ index.js:35
load (async)
fileHandler @ index.js:31
pyodide.asm.js:9 The cause of the fatal error was:
API.fatal_error @ pyodide.asm.js:9
Module.callPyObjectKwargs @ pyodide.asm.js:9
Module.callPyObject @ pyodide.asm.js:9
apply @ pyodide.asm.js:9
apply @ pyodide.asm.js:9
reader.onload @ index.js:35
load (async)
fileHandler @ index.js:31
pyodide.asm.js:9 CppException cv::Exception: OpenCV(4.7.0) /root/repo/packages/opencv-python/build/opencv-python-4.7.0.72/opencv/modules/imgproc/src/color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cvtColor'

    at convertCppException (https://cdn.jsdelivr.net/pyodide/v0.23.4/full/pyodide.asm.js:9:102351)
    at API.fatal_error (https://cdn.jsdelivr.net/pyodide/v0.23.4/full/pyodide.asm.js:9:102761)
    at Module.callPyObjectKwargs (https://cdn.jsdelivr.net/pyodide/v0.23.4/full/pyodide.asm.js:9:75641)
    at Module.callPyObject (https://cdn.jsdelivr.net/pyodide/v0.23.4/full/pyodide.asm.js:9:75942)
    at Function.apply (https://cdn.jsdelivr.net/pyodide/v0.23.4/full/pyodide.asm.js:9:89846)
    at Object.apply (https://cdn.jsdelivr.net/pyodide/v0.23.4/full/pyodide.asm.js:9:88624)
    at reader.onload (http://localhost:8080/index.js:35:29)
```

**Comment by hoodmane** [comment]
Could you give a complete reproduction? The code you gave raises:
```py
NameError: name 'base64imgstr' is not defined
```
