### ISSUE TITLE
pyodide-build: unable to locate numpy package while rebuilding the pandas 2.0.0 as pyodide

### ISSUE THREAD

**Issue by kishorekaruppusamy** [pyodide/pyodide#4160]
## 🐛 Bug

I am trying to build a `pyodide package` using the `pandas 2.0.0 tar.gz` version. pyodide build creates a isolated python environment and searching `numpy` .

### To Reproduce

- Build and Create a docker container using this [Image](https://github.com/docker-library/python/blob/81b6e5f0643965618d633cd6b811bf0879dee360/3.10/slim-bookworm/Dockerfile).
- Once created login to the container and follow [out of tree](https://pyodide.org/en/stable/development/building-and-testing-packages.html#building-and-testing-python-packages-out-of-tree) package building steps.
- Once the [Emscripten setup](https://pyodide.org/en/stable/development/building-and-testing-packages.html#set-up-emscripten) is completed. download the `pandas-2.0.0 tar.gz distribution` from [pypi](https://files.pythonhosted.org/packages/9f/12/0b6bdd627b99cb10816956c1047b0733ef33b61a84e3420faf4d3202df06/pandas-2.0.0.tar.gz) and extract that in some folder.
- Change directory into the package folder where the `setup.py or pyproject.toml file` is located and run pyodide build
### Expected behavior.

- Rebuild the `pandas 2.0.0` version as `pyodide package`.

### Error Log
```Downloading xbuild environment                                                                                                                                                                 
Installing xbuild environment                                                                                                                                                                  
* Creating virtualenv isolated environment...
* Installing packages in isolated environment... (Cython>=0.29.33,<3, setuptools>=61.0.0, versioneer[toml], wheel)
* Getting dependencies for wheel...
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/pep517/in_process/_in_process.py", line 351, in <module>
    main()
  File "/usr/local/lib/python3.10/site-packages/pep517/in_process/_in_process.py", line 333, in main
    json_out['return_val'] = hook(**hook_input['kwargs'])
  File "/usr/local/lib/python3.10/site-packages/pep517/in_process/_in_process.py", line 118, in get_requires_for_build_wheel
    return hook(config_settings)
  File "/tmp/build-env-f86aqev9/lib/python3.10/site-packages/setuptools/build_meta.py", line 355, in get_requires_for_build_wheel
    return self._get_build_requires(config_settings, requirements=['wheel'])
  File "/tmp/build-env-f86aqev9/lib/python3.10/site-packages/setuptools/build_meta.py", line 325, in _get_build_requires
    self.run_setup()
  File "/tmp/build-env-f86aqev9/lib/python3.10/site-packages/setuptools/build_meta.py", line 507, in run_setup
    super(_BuildMetaLegacyBackend, self).run_setup(setup_script=setup_script)
  File "/tmp/build-env-f86aqev9/lib/python3.10/site-packages/setuptools/build_meta.py", line 341, in run_setup
    exec(code, locals())
  File "<string>", line 18, in <module>
ModuleNotFoundError: No module named 'numpy'
* Getting dependencies for wheel...
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/pep517/in_process/_in_process.py", line 351, in <module>
    main()
  File "/usr/local/lib/python3.10/site-packages/pep517/in_process/_in_process.py", line 333, in main
    json_out['return_val'] = hook(**hook_input['kwargs'])
  File "/usr/local/lib/python3.10/site-packages/pep517/in_process/_in_process.py", line 118, in get_requires_for_build_wheel
    return hook(config_settings)
  File "/tmp/build-env-f86aqev9/lib/python3.10/site-packages/setuptools/build_meta.py", line 355, in get_requires_for_build_wheel
    return self._get_build_requires(config_settings, requirements=['wheel'])
  File "/tmp/build-env-f86aqev9/lib/python3.10/site-packages/setuptools/build_meta.py", line 325, in _get_build_requires
    self.run_setup()
  File "/tmp/build-env-f86aqev9/lib/python3.10/site-packages/setuptools/build_meta.py", line 507, in run_setup
    super(_BuildMetaLegacyBackend, self).run_setup(setup_script=setup_script)
  File "/tmp/build-env-f86aqev9/lib/python3.10/site-packages/setuptools/build_meta.py", line 341, in run_setup
    exec(code, locals())
  File "<string>", line 18, in <module>
ModuleNotFoundError: No module named 'numpy'

ERROR Backend subproccess exited when trying to invoke get_requires_for_build_wheel```

**Comment by ryanking13** [comment]
It looks like `numpy` is a build dependency of `pandas` but it is not declared in the `pyproject.toml` of Pandas 2.0.0. I guess this is fixed in Pandas 2.1.0 so could you try Pandas 2.1.0 instead?

`pyproject.toml` of Pandas 2.0.0

```
[build-system]
# Minimum requirements for the build system to execute.
# See https://github.com/scipy/scipy/pull/12940 for the AIX issue.
requires = [
    "setuptools>=61.0.0",
    "wheel",
    "Cython>=0.29.33,<3",  # Note: sync with setup.py, environment.yml and asv.conf.json
    "oldest-supported-numpy>=2022.8.16",
    "versioneer[toml]"
]
```

`pyproject.toml` of Pandas 2.1.0

```
[build-system]
# Minimum requirements for the build system to execute.
# See https://github.com/scipy/scipy/pull/12940 for the AIX issue.
requires = [
    "meson-python==0.13.1",
    "meson==1.0.1",
    "wheel",
    "Cython>=0.29.33,<3",  # Note: sync with setup.py, environment.yml and asv.conf.json
    # Note: numpy 1.25 has a backwards compatible C API by default
    # we don't want to force users to compile with 1.25 though
    # (Ideally, in the future, though, oldest-supported-numpy can be dropped when our min numpy is 1.25.x)
    "oldest-supported-numpy>=2022.8.16; python_version<'3.12'",
    "numpy>=1.22.4; python_version>='3.12'",
    "versioneer[toml]"
]

```

**Comment by kishorekaruppusamy** [comment]
@ryanking13 
it is acually not working not only for numpy it is also not working for onnxruntime

```
root@abddcd13be5c:/Pyodide_Builder/onnxruntime# pyodide build
xbuild environment already exists, skipping download                                                                                                  
Installing xbuild environment                                                                                                                         
* Creating virtualenv isolated environment...
* Installing packages in isolated environment... (setuptools >= 40.8.0, wheel)
* Getting dependencies for wheel...
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/pep517/in_process/_in_process.py", line 351, in <module>
    main()
  File "/usr/local/lib/python3.10/site-packages/pep517/in_process/_in_process.py", line 333, in main
    json_out['return_val'] = hook(**hook_input['kwargs'])
  File "/usr/local/lib/python3.10/site-packages/pep517/in_process/_in_process.py", line 118, in get_requires_for_build_wheel
    return hook(config_settings)
  File "/tmp/build-env-jrs4h3jo/lib/python3.10/site-packages/setuptools/build_meta.py", line 355, in get_requires_for_build_wheel
    return self._get_build_requires(config_settings, requirements=['wheel'])
  File "/tmp/build-env-jrs4h3jo/lib/python3.10/site-packages/setuptools/build_meta.py", line 325, in _get_build_requires
    self.run_setup()
  File "/tmp/build-env-jrs4h3jo/lib/python3.10/site-packages/setuptools/build_meta.py", line 507, in run_setup
    super(_BuildMetaLegacyBackend, self).run_setup(setup_script=setup_script)
  File "/tmp/build-env-jrs4h3jo/lib/python3.10/site-packages/setuptools/build_meta.py", line 341, in run_setup
    exec(code, locals())
  File "<string>", line 18, in <module>
ModuleNotFoundError: No module named 'packaging'
* Getting dependencies for wheel...
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/pep517/in_process/_in_process.py", line 351, in <module>
    main()
  File "/usr/local/lib/python3.10/site-packages/pep517/in_process/_in_process.py", line 333, in main
    json_out['return_val'] = hook(**hook_input['kwargs'])
  File "/usr/local/lib/python3.10/site-packages/pep517/in_process/_in_process.py", line 118, in get_requires_for_build_wheel
    return hook(config_settings)
  File "/tmp/build-env-jrs4h3jo/lib/python3.10/site-packages/setuptools/build_meta.py", line 355, in get_requires_for_build_wheel
    return self._get_build_requires(config_settings, requirements=['wheel'])
  File "/tmp/build-env-jrs4h3jo/lib/python3.10/site-packages/setuptools/build_meta.py", line 325, in _get_build_requires
    self.run_setup()
  File "/tmp/build-env-jrs4h3jo/lib/python3.10/site-packages/setuptools/build_meta.py", line 507, in run_setup
    super(_BuildMetaLegacyBackend, self).run_setup(setup_script=setup_script)
  File "/tmp/build-env-jrs4h3jo/lib/python3.10/site-packages/setuptools/build_meta.py", line 341, in run_setup
    exec(code, locals())
  File "<string>", line 18, in <module>
ModuleNotFoundError: No module named 'packaging'

ERROR Backend subproccess exited when trying to invoke get_requires_for_build_wheel
```

**Comment by ryanking13** [comment]
Yes, it seems like onnxruntime has [some build dependencies](https://github.com/microsoft/onnxruntime/blob/8d503138168d4ae54869c82b1032a38c6cb9f3a7/tools/ci_build/build.py#L817-L823) but they are installed inside complex build script, instead of [using standard way](https://peps.python.org/pep-0518/).

One possible way of handling it in Pyodide is to support [non-isolated build](https://pypa-build.readthedocs.io/en/stable/#python--m-build---no-isolation) but I am not sure it makes sense for cross-compiling.

So for now, I think what you can try is to add `pyproject.toml` file inside the onnxruntime directory before running `pyodide build` command and specify build dependencies in it.

**Comment by kishorekaruppusamy** [comment]
sure, i will look into that.
