### ISSUE TITLE
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'lstatSync')

### ISSUE THREAD

**Issue by jiangwengogo** [pyodide/pyodide#4183]
## 🐛 Bug

Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'lstatSync')
    at Object.getMode (pyodide.asm.js:10:285671)
    at Object.mount (pyodide.asm.js:10:285368)
    at Object.mount (pyodide.asm.js:10:314199)
    at eval (pm_AutoUpload.vue:101:1)
    at step (tslib.es6.js:102:1)
    at Object.eval [as next] (tslib.es6.js:83:1)
    at fulfilled (tslib.es6.js:73:1)
### To Reproduce

  pyodide = await loadPyodide();
  let mountDir = "/pkg";
  pyodide.FS.mkdir(mountDir);
  pyodide.FS.mount(pyodide.FS.filesystems.NODEFS, { root: "." }, mountDir);

### Environment

- Pyodide Version:https://cdn.jsdelivr.net/pyodide/v0.21.3/full/pyodide.js
- Browser version:114.0.5735.106
- Any other relevant information:

**Comment by rth** [comment]
Can you confirm that you are running in node and provide the node version? Mounting NODEFS doesn't work in the browser.
