### ISSUE TITLE
micropip not installing compatible version of typing-extensions

### ISSUE THREAD

**Issue by freddyaboulton** [pyodide/pyodide#4234]
## 🐛 Bug

I am installing the latest `fastapi` (0.104.0) with micropip, however I cannot import it because it relies on an [API](https://typing-extensions.readthedocs.io/en/latest/#Doc) introduced in `typing-extensions` 4.8.0. 

Why does micropip not install the right typing-extensions version?

### To Reproduce

```html
<!doctype html>
<html>
  <head>
      <script src="https://cdn.jsdelivr.net/pyodide/v0.24.1/full/pyodide.js"></script>
  </head>
  <body>
    <script type="text/javascript">
      async function main(){
        let pyodide = await loadPyodide();
        await pyodide.loadPackage("micropip");
        const micropip = pyodide.pyimport("micropip");
        await micropip.install("ssl");
        await micropip.install("fastapi==0.104.0");
        pyodide.runPython("import fastapi");
      }
      main();
    </script>
  </body>
</html>
```

```console
<module>
    from fastapi.exceptions import RequestErrorModel
  File "/lib/python3.11/site-packages/fastapi/exceptions.py", line 6, in <module>
    from typing_extensions import Annotated, Doc  # type: ignore [attr-defined]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ImportError: cannot import name 'Doc' from 'typing_extensions' (/lib/python3.11/site-packages/typing_extensions.py)

    at new_error (pyodide.asm.js:9:12519)
    at pyodide.asm.wasm:0x158827
    at pyodide.asm.wasm:0x15892c
    at Module._pythonexc2js (pyodide.asm.js:9:640895)
    at Module.callPyObjectKwargs (pyodide.asm.js:9:81856)
    at Proxy.callKwargs (pyodide.asm.js:9:97507)
    at Object.runPython (pyodide.asm.js:9:118859)
    at main (lite.html:14:17)
```

### Expected behavior
micropip installs correct typing_extensions version.

### Environment

- Pyodide Version 0.24.1
- Browser version: Chromium 117.0.5938.149
- Any other relevant information:

**Comment by hoodmane** [comment]
I think this is a known bug, but I can't find the appropriate issue. It  when there is a version of a package in our lockfile, micropip installs it even when it conflicts with the constraint. I think @ryanking13 was looking into a fix?
For now, the following will work:
```py
await micropip.install(["typing_extensions==4.8", "fastapi", "ssl"])
```

Also, I've been looking into using fastapi with Pyodide of late. I wrote this dumb asgi server for using fastapi in cloudflare workers:
https://github.com/hoodmane/workerd-python-experiments/blob/fastapi/src/asgi.py
If you wanted to use it in a serviceworker, the websocket code would have to be adjusted to use a `MessageChannel` somehow but other than that it should almost work.

**Comment by ryanking13** [comment]
What happens is:

1. `fastapi` requires `pydantic` and `typing_extension>4.8.0`.
2. `pydantic` requires `typing_extension`.
3. `pydantic` is in the Pyodide lockfile and it loads `typing_extension` from the lockfile (4.7.1).

I think it is not easy to fix... for now the workaround is installing typing_extensions first before installing other packages, as Hoodmane mentioned in the comment.
