### ISSUE TITLE
 cannot import name '_SimpleITK' from partially initialized module 'SimpleITK'

### ISSUE THREAD

**Issue by MountainAndMorning** [pyodide/pyodide#4259]
## 🐛 Bug

I download the SimpleITK whl from https://files.pythonhosted.org/packages/42/88/3552e6a03fe7b4284f9f4f7496d24b410b40407e0bb0e27ecff77dcdff20/SimpleITK-2.3.0-cp311-cp311-macosx_11_0_arm64.whl and put this file inside the pyodide node.js package. I try to import this package but failed.

### To Reproduce

```js
const { loadPyodide } = require("pyodide");

export async function hello_python() {
  let pyodide = await loadPyodide();
  await pyodide.loadPackage("micropip");
  const micropip = pyodide.pyimport("micropip");
  await micropip.install("numpy")
  await micropip.install("six")
  await micropip.install("pywavelets")
  await pyodide.loadPackage("./node_modules/pyodide/SimpleITK-2.3.0-cp311-cp311-macosx_11_0_arm64.whl")
  pyodide.runPython(`
  import SimpleITK
  print(SimpleITK)
`);
}

hello_python()
```

```bash
Loading micropip, packaging
Loaded packaging, micropip
Loading numpy
Loaded numpy
Loading six
Loaded six
numpy already loaded from default channel
six already loaded from default channel
packaging already loaded from default channel
Loading pywavelets, distutils, matplotlib, cycler, fonttools, kiwisolver, pillow, pyparsing, python-dateutil, pytz, matplotlib-pyodide, scipy, openblas
Loaded cycler, pyparsing, matplotlib-pyodide, python-dateutil, distutils, kiwisolver, pytz, fonttools, openblas, pillow, matplotlib, scipy, pywavelets
Loading simpleitk
Loaded simpleitk
Error occurred in handler for 'python': PythonError: Traceback (most recent call last):
  File "/lib/python311.zip/_pyodide/_base.py", line 499, in eval_code
    .run(globals, locals)
     ^^^^^^^^^^^^^^^^^^^^
  File "/lib/python311.zip/_pyodide/_base.py", line 340, in run
    coroutine = eval(self.code, globals, locals)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<exec>", line 2, in <module>
  File "/lib/python3.11/site-packages/SimpleITK/__init__.py", line 18, in <module>
    from SimpleITK.SimpleITK import *
  File "/lib/python3.11/site-packages/SimpleITK/SimpleITK.py", line 10, in <module>
    from . import _SimpleITK
ImportError: cannot import name '_SimpleITK' from partially initialized module 'SimpleITK' (most likely due to a circular import) (/lib/python3.11/site-packages/SimpleITK/__init__.py)
```
Node.js v16.16.0
MacBook Air (Apple M2)
macOS 14.0 (23A344)
### Environment

```json
"dependencies": {
    "@kitware/vtk.js": "^21.4.1",
    "address": "^1.2.2",
    "electron-log": "^5.0.0-beta.28",
    "electron-store": "^8.1.0",
    "itk-image-io": "^1.0.0-b.18",
    "itk-wasm": "^1.0.0-b.18",
    "js-yaml": "^4.1.0",
    "jszip": "^3.10.1",
    "pyodide": "^0.24.1",
    "vue": "^3.2.47",
    "vuetify": "^3.3.3",
  },
  "devDependencies": {
    "@mdi/js": "^7.2.96",
    "@vitejs/plugin-vue": "^4.1.0",
    "electron": "^24.4.0",
    "electron-builder": "^23.6.0",
    "typescript": "^5.0.2",
    "vite": "^4.3.2",
    "vite-plugin-electron": "^0.11.2",
    "vite-plugin-electron-renderer": "^0.14.5",
    "vite-plugin-static-copy": "^0.16.0",
    "vue-tsc": "^1.4.2"
  },

```

**Comment by lesteve** [comment]
You are trying to use a macosx arm wheel into a wasm environment, there is no chance it will work. I would have expected some kind of error in the `loadPackage(osx_wheel)` to be honest.

Have a look at [itkwasm](https://wasm.itk.org/en/latest/index.html), I have never used it but it seems like it is ITK on wasm and can use Python code via Pyodide.

**Comment by hoodmane** [comment]
> I would have expected some kind of error in the `loadPackage(osx_wheel)` to be honest.

Yes, ideally that should fail. @ryanking13 I wonder if we can copy-paste slightly better file name checking logic from packaging, or vendor the file that implements that, or something. I'm not sure how compatible it is with the goal of avoiding bulking up the main build. Currently we just check for the `.whl` ending, maybe as a simple heuristic we can also reject wheels that seem to be platformed for osx, windows, or linux.

**Comment by MountainAndMorning** [comment]
The reason for installing SimpleITK is that it is a dependency of the [pyradiomics](https://pypi.org/project/pyradiomics/) library, which is what I need. Therefore, I can not replace it with itkwasm. I also try the x86 version of SimpleITK downloaded from [there](https://files.pythonhosted.org/packages/09/10/8d846bf2ec9b67d5b5518c726f0f7dd376f01cfa49b5013f91122ff1f31e/SimpleITK-2.3.0-cp311-cp311-macosx_10_9_x86_64.whl) and get the same error.

```js
const { loadPyodide } = require("pyodide");

export async function hello_python() {
  let pyodide = await loadPyodide();
  await pyodide.loadPackage("micropip");
  const micropip = pyodide.pyimport("micropip");
  await micropip.install("numpy")
  await micropip.install("six")
  await micropip.install("pywavelets")
 
  await pyodide.loadPackage("./node_modules/pyodide/SimpleITK-2.3.0-cp311-cp311-macosx_10_9_x86_64.whl")

  pyodide.runPython(`
  import SimpleITK
  print(SimpleITK)
`);
}
```

```bash
Loading micropip, packaging
Loaded packaging, micropip
Loading numpy
Loaded numpy
Loading six
Loaded six
numpy already loaded from default channel
six already loaded from default channel
packaging already loaded from default channel
Loading pywavelets, distutils, matplotlib, cycler, fonttools, kiwisolver, pillow, pyparsing, python-dateutil, pytz, matplotlib-pyodide, scipy, openblas
Loaded cycler, pyparsing, matplotlib-pyodide, python-dateutil, distutils, pytz, kiwisolver, fonttools, openblas, pillow, matplotlib, scipy, pywavelets
Loading simpleitk
Loaded simpleitk
Error occurred in handler for 'python': PythonError: Traceback (most recent call last):
  File "/lib/python311.zip/_pyodide/_base.py", line 499, in eval_code
    .run(globals, locals)
     ^^^^^^^^^^^^^^^^^^^^
  File "/lib/python311.zip/_pyodide/_base.py", line 340, in run
    coroutine = eval(self.code, globals, locals)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<exec>", line 2, in <module>
  File "/lib/python3.11/site-packages/SimpleITK/__init__.py", line 18, in <module>
    from SimpleITK.SimpleITK import *
  File "/lib/python3.11/site-packages/SimpleITK/SimpleITK.py", line 10, in <module>
    from . import _SimpleITK
ImportError: cannot import name '_SimpleITK' from partially initialized module 'SimpleITK' (most likely due to a circular import) (/lib/python3.11/site-packages/SimpleITK/__init__.py)
```

If I directly install pyradiomics, I will get this error.

```js
const { loadPyodide } = require("pyodide");

export async function hello_python() {
  let pyodide = await loadPyodide();
  await pyodide.loadPackage("micropip");
  const micropip = pyodide.pyimport("micropip");
  await micropip.install("numpy")
  await micropip.install("six")
  await micropip.install("pywavelets")
  await micropip.install("pyradiomics")

  pyodide.runPython(`
  import radiomics
  print(radiomics)
`);
}
```
```bash
Loading micropip, packaging
Loaded packaging, micropip
Loading numpy
Loaded numpy
Loading six
Loaded six
numpy already loaded from default channel
six already loaded from default channel
packaging already loaded from default channel
Loading pywavelets, distutils, matplotlib, cycler, fonttools, kiwisolver, pillow, pyparsing, python-dateutil, pytz, matplotlib-pyodide, scipy, openblas
Loaded cycler, matplotlib-pyodide, pyparsing, python-dateutil, distutils, pytz, kiwisolver, fonttools, openblas, pillow, matplotlib, scipy, pywavelets
Error occurred in handler for 'python': PythonError: Traceback (most recent call last):
  File "/lib/python3.11/site-packages/micropip/_commands/install.py", line 142, in install
    await transaction.gather_requirements(requirements)
  File "/lib/python3.11/site-packages/micropip/transaction.py", line 204, in gather_requirements
    await asyncio.gather(*requirement_promises)
  File "/lib/python3.11/site-packages/micropip/transaction.py", line 211, in add_requirement
    return await self.add_requirement_inner(Requirement(req))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/micropip/transaction.py", line 300, in add_requirement_inner
    await self._add_requirement_from_package_index(req)
  File "/lib/python3.11/site-packages/micropip/transaction.py", line 339, in _add_requirement_from_package_index
    wheel = find_wheel(metadata, req)
            ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/micropip/transaction.py", line 431, in find_wheel
    raise ValueError(
ValueError: Can't find a pure Python 3 wheel for 'pyradiomics'.
See: https://pyodide.org/en/stable/usage/faq.html#why-can-t-micropip-find-a-pure-python-wheel-for-a-package
You can use `await micropip.install(..., keep_going=True)` to get a list of all packages with missing wheels.
}

```

The error say that I can try the `await micropip.install(..., keep_going=True)` statement. However, I find it is the python command and cannot used in the js context like above:
```js
let pyodide = await loadPyodide();
  await pyodide.loadPackage("micropip");
  const micropip = pyodide.pyimport("micropip");
  await micropip.install("numpy")
```
So, I try to install pyradiomics from url:
```js
await micropip.install("https://files.pythonhosted.org/packages/d0/09/80f28d9dd26e6952d779f2fff6fc37a61a6f5bbfcfc7bd96864a7b84fa9f/pyradiomics-3.1.0-cp39-cp39-macosx_11_0_x86_64.whl")
```
and get the error blow:
```bash
Loading micropip, packaging
Loaded packaging, micropip
Loading numpy
Loaded numpy
Loading six
Loaded six
numpy already loaded from default channel
six already loaded from default channel
packaging already loaded from default channel
Loading pywavelets, distutils, matplotlib, cycler, fonttools, kiwisolver, pillow, pyparsing, python-dateutil, pytz, matplotlib-pyodide, scipy, openblas
Loaded pyparsing, python-dateutil, matplotlib-pyodide, cycler, distutils, pytz, kiwisolver, fonttools, openblas, pillow, matplotlib, scipy, pywavelets
Error occurred in handler for 'python': PythonError: Traceback (most recent call last):
  File "/lib/python3.11/site-packages/micropip/_commands/install.py", line 142, in install
    await transaction.gather_requirements(requirements)
  File "/lib/python3.11/site-packages/micropip/transaction.py", line 204, in gather_requirements
    await asyncio.gather(*requirement_promises)
  File "/lib/python3.11/site-packages/micropip/transaction.py", line 215, in add_requirement
    check_compatible(wheel.filename)
  File "/lib/python3.11/site-packages/micropip/_utils.py", line 151, in check_compatible
    raise ValueError(
ValueError: Wheel platform 'macosx_11_0_x86_64' is not compatible with Pyodide's platform 'emscripten-3.1.45-wasm32'

```
Finally, I download this whl file and put it inside the pyodide npm package and the simpleitk depandency error occor.
```js
const { loadPyodide } = require("pyodide");

export async function hello_python() {
  let pyodide = await loadPyodide();
  await pyodide.loadPackage("micropip");
  const micropip = pyodide.pyimport("micropip");
  await micropip.install("numpy")
  await micropip.install("six")
  await micropip.install("pywavelets")

  await pyodide.loadPackage("./node_modules/pyodide/pyradiomics-3.1.0-cp39-cp39-macosx_11_0_x86_64.whl")

  pyodide.runPython(`
  import radiomics
  print(radiomics)
`);
}
```

```bash
Loading micropip, packaging
Loaded packaging, micropip
Loading numpy
Loaded numpy
Loading six
Loaded six
numpy already loaded from default channel
six already loaded from default channel
packaging already loaded from default channel
Loading pywavelets, distutils, matplotlib, cycler, fonttools, kiwisolver, pillow, pyparsing, python-dateutil, pytz, matplotlib-pyodide, scipy, openblas
Loaded pyparsing, matplotlib-pyodide, python-dateutil, cycler, distutils, pytz, kiwisolver, fonttools, openblas, pillow, matplotlib, scipy, pywavelets
Loading pyradiomics
Loaded pyradiomics
Error occurred in handler for 'python': PythonError: Traceback (most recent call last):
  File "/lib/python311.zip/_pyodide/_base.py", line 499, in eval_code
    .run(globals, locals)
     ^^^^^^^^^^^^^^^^^^^^
  File "/lib/python311.zip/_pyodide/_base.py", line 340, in run
    coroutine = eval(self.code, globals, locals)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<exec>", line 2, in <module>
  File "/lib/python3.11/site-packages/radiomics/__init__.py", line 15, in <module>
    from . import imageoperations
  File "/lib/python3.11/site-packages/radiomics/imageoperations.py", line 7, in <module>
    import SimpleITK as sitk
ModuleNotFoundError: No module named 'SimpleITK'

```

**Comment by lesteve** [comment]
You need a wasm wheel. Wasm wheels are not available on PyPI.

Your best bet is to ask on the itkwasm issue tracker for directions, explaining what you want to do and asking if it is possible.

An alternative would be that someone spendss the time to build SimpleITK and all its dependencies with emscripten, so that the package can be added to Pyodide. This is a significant amount of work and I would say is rather unlikely to happen soon. Also I am guessing that if the ITK people decided to do itkwasm, there are some reasons behind it.

**Comment by ryanking13** [comment]
> Yes, ideally that should fail. @ryanking13 I wonder if we can copy-paste slightly better file name checking logic from packaging, or vendor the file that implements that, or something. I'm not sure how compatible it is with the goal of avoiding bulking up the main build.

Yes, I think it is a good idea. If we add it to Pyodide main build, micropip can probably use it directly, instead of using packaging module... which remove the final dependency of micropip :)

**Comment by MountainAndMorning** [comment]
OK. I will try to build the wasm wheel.

**Comment by MountainAndMorning** [comment]
I want to build the SimpleITK. However I found there is no setup.py file in the source code. Can you include the SimpleITK library into the pyodide default package folder? The SimpleITK is very important for medical image. Thanks.

**Comment by xionghailong1205** [comment]
I also want to use simpleITK in the browser. How is this problem being handled?

**Comment by ryanking13** [comment]
@xionghailong1205 The problem in this issue was that the author tried to load the wheel built for MacOS in Pyodide, which is not available. You should build the wheel for Pyodide platform.

Please check our [documentation](https://pyodide.org/en/stable/development/building-packages.html) for building packages for Pyodide.
