### ISSUE TITLE
Invalid host defined options

### ISSUE THREAD

**Issue by qarlosalberto** [pyodide/pyodide#4267]
I'm developing a VSCode extension with Pyodide. I have this error using Yarn:

```
TypeError: Invalid host defined options
	at initNodeModules (vscode-file://vscode-app/home/carlos/.vscode/extensions/teros-technology.teroshdl-5.0.12/node_modules/teroshdl2/node_modules/pyodide/pyodide.js:9:802)
	at loadPyodide (vscode-file://vscode-app/home/carlos/.vscode/extensions/teros-technology.teroshdl-5.0.12/node_modules/teroshdl2/node_modules/pyodide/pyodide.js:9:9398)
	at Pyodide.load (vscode-file://vscode-app/home/carlos/.vscode/extensions/teros-technology.teroshdl-5.0.12/node_modules/teroshdl2/out/process/pyodide.js:54:34)
```

It works fine when I use npm.

**Comment by qarlosalberto** [comment]
Using npm I have the error:

```
TypeError: A dynamic import callback was not specified.
    at new NodeError (node:internal/errors:399:5)
    at importModuleDynamicallyCallback (node:internal/process/esm_loader:39:9)
    at initNodeModules (/home/carlos/.vscode/extensions/teros-technology.teroshdl-5.0.12/node_modules/pyodide/pyodide.js:9:802)
    at loadPyodide (/home/carlos/.vscode/extensions/teros-technology.teroshdl-5.0.12/node_modules/pyodide/pyodide.js:9:9398)
    at Pyodide.load (/home/carlos/.vscode/extensions/teros-technology.teroshdl-5.0.12/node_modules/teroshdl2/out/process/pyodide.js:54:34)
    at Pyodide.write_file_list (/home/carlos/.vscode/extensions/teros-technology.teroshdl-5.0.12/node_modules/teroshdl2/out/process/pyodide.js:38:38)
```

**Comment by qarlosalberto** [comment]
Thanks, I have opened an issue in VSCode repository.

**Comment by qarlosalberto** [comment]
How could I create the npm package from source? I would like to try some changes.

**Comment by hoodmane** [comment]
If your changes are going into `pyodide.js` you can run `node src/js/esbuild.js` which will generate new `dist/pyodide.js` and `dist/pyodide.mjs` files. If you then copy these on top of the corresponding files in the npm installed package that should work.

**Comment by qarlosalberto** [comment]
I don't see `src/js/esbuild.js`: https://github.com/pyodide/pyodide/tree/main/src/js

**Comment by hoodmane** [comment]
I mean [esbuild.config.mjs](https://github.com/pyodide/pyodide/blob/main/src/js/esbuild.config.mjs)

**Comment by qarlosalberto** [comment]
Thanks! I see that all the fails are in the dynamic imports:

- https://github.com/pyodide/pyodide/blob/main/src/js/compat.ts#L215
- https://github.com/pyodide/pyodide/blob/main/src/js/compat.ts#L41
- https://github.com/pyodide/pyodide/blob/main/src/js/compat.ts#L42
- https://github.com/pyodide/pyodide/blob/main/src/js/compat.ts#L49
- https://github.com/pyodide/pyodide/blob/main/src/js/compat.ts#L67

Any idea about how to replace them? Specially this one: https://github.com/pyodide/pyodide/blob/main/src/js/compat.ts#L215
