### ISSUE TITLE
Make build not working

### ISSUE THREAD

**Issue by kishorekaruppusamy** [pyodide/pyodide#4287]
## 🐛 Bug

unable to build the onnx repo `https://github.com/microsoft/onnxruntime` using pyodide out_of_tree,
i am able to build this repo using `python -m build`
but while running `pyodide build` i got the exception..

```
running cmake_build
Using cmake args: ['/var/folders/q9/ms4_8l4970q525dlsjp_b9n0x6l4j9/T/tmp_qhkbeeh/cmake', '-DPYTHON_INCLUDE_DIR=/Users/kishore-17103/anaconda3/include/python3.11', '-DPYTHON_EXECUTABLE=/private/var/folders/q9/ms4_8l4970q525dlsjp_b9n0x6l4j9/T/build-env-30el05wo/bin/python', '-DBUILD_ONNX_PYTHON=ON', '-DCMAKE_EXPORT_COMPILE_COMMANDS=ON', '-DONNX_NAMESPACE=onnx', '-DPY_EXT_SUFFIX=.cpython-311-wasm32-emscripten.so', '-DCMAKE_BUILD_TYPE=Release', '-DONNX_ML=1', '/Users/kishore-17103/ONNX/onnx']
configure: cmake -DCMAKE_C_COMPILER=/var/folders/q9/ms4_8l4970q525dlsjp_b9n0x6l4j9/T/tmp_qhkbeeh/cc -DCMAKE_CXX_COMPILER=/var/folders/q9/ms4_8l4970q525dlsjp_b9n0x6l4j9/T/tmp_qhkbeeh/c++ -DCMAKE_AR=/var/folders/q9/ms4_8l4970q525dlsjp_b9n0x6l4j9/T/tmp_qhkbeeh/ar -DCMAKE_C_COMPILER_AR=/var/folders/q9/ms4_8l4970q525dlsjp_b9n0x6l4j9/T/tmp_qhkbeeh/ar -DCMAKE_CXX_COMPILER_AR=/var/folders/q9/ms4_8l4970q525dlsjp_b9n0x6l4j9/T/tmp_qhkbeeh/ar --fresh -DPYTHON_INCLUDE_DIR=/Users/kishore-17103/anaconda3/include/python3.11 -DPYTHON_EXECUTABLE=/private/var/folders/q9/ms4_8l4970q525dlsjp_b9n0x6l4j9/T/build-env-30el05wo/bin/python -DBUILD_ONNX_PYTHON=ON -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DONNX_NAMESPACE=onnx -DPY_EXT_SUFFIX=.cpython-311-wasm32-emscripten.so -DCMAKE_BUILD_TYPE=Release -DONNX_ML=1 /Users/kishore-17103/ONNX/onnx -DCMAKE_CROSSCOMPILING_EMULATOR=/Users/kishore-17103/ONNX/emsdk/node/16.20.0_64bit/bin/node
CMake Deprecation Warning at CMakeLists.txt:2 (cmake_minimum_required):
  Compatibility with CMake < 3.5 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


CMake Error at /Users/kishore-17103/.temp_env/client_env/lib/python3.11/site-packages/cmake/data/share/cmake-3.27/Modules/CMakeDetermineSystem.cmake:154 (message):
  Could not find toolchain file:
  /Users/kishore-17103/.temp_env/client_env/lib/python3.11/site-packages/pyodide_build/tools/cmake/Modules/Platform/Emscripten.cmake
Call Stack (most recent call first):
  CMakeLists.txt:17 (project)


CMake Error: CMake was unable to find a build program corresponding to "Unix Makefiles".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
-- Configuring incomplete, errors occurred!
emcmake: error: 'cmake -DCMAKE_C_COMPILER=/var/folders/q9/ms4_8l4970q525dlsjp_b9n0x6l4j9/T/tmp_qhkbeeh/cc -DCMAKE_CXX_COMPILER=/var/folders/q9/ms4_8l4970q525dlsjp_b9n0x6l4j9/T/tmp_qhkbeeh/c++ -DCMAKE_AR=/var/folders/q9/ms4_8l4970q525dlsjp_b9n0x6l4j9/T/tmp_qhkbeeh/ar -DCMAKE_C_COMPILER_AR=/var/folders/q9/ms4_8l4970q525dlsjp_b9n0x6l4j9/T/tmp_qhkbeeh/ar -DCMAKE_CXX_COMPILER_AR=/var/folders/q9/ms4_8l4970q525dlsjp_b9n0x6l4j9/T/tmp_qhkbeeh/ar --fresh -DPYTHON_INCLUDE_DIR=/Users/kishore-17103/anaconda3/include/python3.11 -DPYTHON_EXECUTABLE=/private/var/folders/q9/ms4_8l4970q525dlsjp_b9n0x6l4j9/T/build-env-30el05wo/bin/python -DBUILD_ONNX_PYTHON=ON -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DONNX_NAMESPACE=onnx -DPY_EXT_SUFFIX=.cpython-311-wasm32-emscripten.so -DCMAKE_BUILD_TYPE=Release -DONNX_ML=1 /Users/kishore-17103/ONNX/onnx -DCMAKE_CROSSCOMPILING_EMULATOR=/Users/kishore-17103/ONNX/emsdk/node/16.20.0_64bit/bin/node' failed (returned 1)
Traceback (most recent call last):
  File "/Users/kishore-17103/.temp_env/client_env/lib/python3.11/site-packages/pep517/in_process/_in_process.py", line 351, in <module>
    main()
  File "/Users/kishore-17103/.temp_env/client_env/lib/python3.11/site-packages/pep517/in_process/_in_process.py", line 333, in main
    json_out['return_val'] = hook(**hook_input['kwargs'])
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kishore-17103/.temp_env/client_env/lib/python3.11/site-packages/pep517/in_process/_in_process.py", line 249, in build_wheel
    return _build_backend().build_wheel(wheel_directory, config_settings,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/private/var/folders/q9/ms4_8l4970q525dlsjp_b9n0x6l4j9/T/build-env-30el05wo/lib/python3.11/site-packages/setuptools/build_meta.py", line 434, in build_wheel
    return self._build_with_temp_dir(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/private/var/folders/q9/ms4_8l4970q525dlsjp_b9n0x6l4j9/T/build-env-30el05wo/lib/python3.11/site-packages/setuptools/build_meta.py", line 419, in _build_with_temp_dir
    self.run_setup()
  File "/private/var/folders/q9/ms4_8l4970q525dlsjp_b9n0x6l4j9/T/build-env-30el05wo/lib/python3.11/site-packages/setuptools/build_meta.py", line 341, in run_setup
    exec(code, locals())
  File "<string>", line 327, in <module>
  File "/private/var/folders/q9/ms4_8l4970q525dlsjp_b9n0x6l4j9/T/build-env-30el05wo/lib/python3.11/site-packages/setuptools/__init__.py", line 103, in setup
    return distutils.core.setup(**attrs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/private/var/folders/q9/ms4_8l4970q525dlsjp_b9n0x6l4j9/T/build-env-30el05wo/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 185, in setup
    return run_commands(dist)
           ^^^^^^^^^^^^^^^^^^
  File "/private/var/folders/q9/ms4_8l4970q525dlsjp_b9n0x6l4j9/T/build-env-30el05wo/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
    dist.run_commands()
  File "/private/var/folders/q9/ms4_8l4970q525dlsjp_b9n0x6l4j9/T/build-env-30el05wo/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
    self.run_command(cmd)
  File "/private/var/folders/q9/ms4_8l4970q525dlsjp_b9n0x6l4j9/T/build-env-30el05wo/lib/python3.11/site-packages/setuptools/dist.py", line 989, in run_command
    super().run_command(command)
  File "/private/var/folders/q9/ms4_8l4970q525dlsjp_b9n0x6l4j9/T/build-env-30el05wo/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/private/var/folders/q9/ms4_8l4970q525dlsjp_b9n0x6l4j9/T/build-env-30el05wo/lib/python3.11/site-packages/wheel/bdist_wheel.py", line 369, in run
    self.run_command("build")
  File "/private/var/folders/q9/ms4_8l4970q525dlsjp_b9n0x6l4j9/T/build-env-30el05wo/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "/private/var/folders/q9/ms4_8l4970q525dlsjp_b9n0x6l4j9/T/build-env-30el05wo/lib/python3.11/site-packages/setuptools/dist.py", line 989, in run_command
    super().run_command(command)
  File "/private/var/folders/q9/ms4_8l4970q525dlsjp_b9n0x6l4j9/T/build-env-30el05wo/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/private/var/folders/q9/ms4_8l4970q525dlsjp_b9n0x6l4j9/T/build-env-30el05wo/lib/python3.11/site-packages/setuptools/_distutils/command/build.py", line 131, in run
    self.run_command(cmd_name)
  File "/private/var/folders/q9/ms4_8l4970q525dlsjp_b9n0x6l4j9/T/build-env-30el05wo/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "/private/var/folders/q9/ms4_8l4970q525dlsjp_b9n0x6l4j9/T/build-env-30el05wo/lib/python3.11/site-packages/setuptools/dist.py", line 989, in run_command
    super().run_command(command)
  File "/private/var/folders/q9/ms4_8l4970q525dlsjp_b9n0x6l4j9/T/build-env-30el05wo/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "<string>", line 264, in run
  File "/private/var/folders/q9/ms4_8l4970q525dlsjp_b9n0x6l4j9/T/build-env-30el05wo/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "/private/var/folders/q9/ms4_8l4970q525dlsjp_b9n0x6l4j9/T/build-env-30el05wo/lib/python3.11/site-packages/setuptools/dist.py", line 989, in run_command
    super().run_command(command)
  File "/private/var/folders/q9/ms4_8l4970q525dlsjp_b9n0x6l4j9/T/build-env-30el05wo/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "<string>", line 235, in run
  File "/Users/kishore-17103/anaconda3/lib/python3.11/subprocess.py", line 413, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/var/folders/q9/ms4_8l4970q525dlsjp_b9n0x6l4j9/T/tmp_qhkbeeh/cmake', '-DPYTHON_INCLUDE_DIR=/Users/kishore-17103/anaconda3/include/python3.11', '-DPYTHON_EXECUTABLE=/private/var/folders/q9/ms4_8l4970q525dlsjp_b9n0x6l4j9/T/build-env-30el05wo/bin/python', '-DBUILD_ONNX_PYTHON=ON', '-DCMAKE_EXPORT_COMPILE_COMMANDS=ON', '-DONNX_NAMESPACE=onnx', '-DPY_EXT_SUFFIX=.cpython-311-wasm32-emscripten.so', '-DCMAKE_BUILD_TYPE=Release', '-DONNX_ML=1', '/Users/kishore-17103/ONNX/onnx']' returned non-zero exit status 1.
```

### To Reproduce

clone onnx repo and build the pyodide build using out_of_tree approach

**Comment by ryanking13** [comment]
> CMake Error: CMake was unable to find a build program corresponding to "Unix Makefiles".

Is `make` or `ninja` installed in the system?

**Comment by kishorekaruppusamy** [comment]
yes ..
but inside `.temp_env/client_env/lib/python3.11/site-packages/pyodide_build/tools`
there is no cmake available only one file is available `pyo3_config.ini`

**Comment by ryanking13** [comment]
> but inside .temp_env/client_env/lib/python3.11/site-packages/pyodide_build/tools
there is no cmake available only one file is available pyo3_config.ini

Oh, yeah, that issue has been resolved, but I didn't make a release yet (https://github.com/pyodide/pyodide/pull/4223). Could you try pyodide-build 0.23.4 instead which will work?

**Comment by kishorekaruppusamy** [comment]
ohh okey i am using `pyodide-build => 0.24.1` i try this version ..

**Comment by kishorekaruppusamy** [comment]
by using this version i got another issue build itself not starting
```
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /Users/kishore-17103/.temp_env/client_env/lib/python3.11/site-packages/pyodide_build/cli/build.p │
│ y:243 in main                                                                                    │
│                                                                                                  │
│   240 │   │   │   source_location = source_location[0 : source_location.find("[")]               │
│   241 │   if not source_location:                                                                │
│   242 │   │   # build the current folder                                                         │
│ ❱ 243 │   │   wheel = source(Path.cwd(), outpath, exports, ctx)                                  │
│   244 │   elif source_location.find("://") != -1:                                                │
│   245 │   │   wheel = url(source_location, outpath, exports, ctx)                                │
│   246 │   elif Path(source_location).is_dir():                                                   │
│                                                                                                  │
│ /Users/kishore-17103/.temp_env/client_env/lib/python3.11/site-packages/pyodide_build/cli/build.p │
│ y:130 in source                                                                                  │
│                                                                                                  │
│   127 │   initialize_pyodide_root()                                                              │
│   128 │   common.check_emscripten_version()                                                      │
│   129 │   backend_flags = ctx.args                                                               │
│ ❱ 130 │   built_wheel = build.run(                                                               │
│   131 │   │   source_location, output_directory, convert_exports(exports), backend_flags         │
│   132 │   )                                                                                      │
│   133 │   return built_wheel                                                                     │
│                                                                                                  │
│ /Users/kishore-17103/.temp_env/client_env/lib/python3.11/site-packages/pyodide_build/out_of_tree │
│ /build.py:19 in run                                                                              │
│                                                                                                  │
│   16 │   ldflags = common.get_make_flag("SIDE_MODULE_LDFLAGS")                                   │
│   17 │   ldflags += f" {os.environ.get('LDFLAGS', '')}"                                          │
│   18 │   env = os.environ.copy()                                                                 │
│ ❱ 19 │   common.set_build_environment(env)                                                       │
│   20 │                                                                                           │
│   21 │   build_env_ctx = pypabuild.get_build_env(                                                │
│   22 │   │   env=env,                                                                            │
│                                                                                                  │
│ /Users/kishore-17103/.temp_env/client_env/lib/python3.11/site-packages/pyodide_build/common.py:4 │
│ 03 in set_build_environment                                                                      │
│                                                                                                  │
│   400 │                                                                                          │
│   401 │   Sets common environment between in tree and out of tree package builds.                │
│   402 │   """                                                                                    │
│ ❱ 403 │   env.update({key: os.environ[key] for key in BUILD_VARS})                               │
│   404 │   env["PYODIDE"] = "1"                                                                   │
│   405 │   if "PYODIDE_JOBS" in os.environ:                                                       │
│   406 │   │   env["PYODIDE_JOBS"] = os.environ["PYODIDE_JOBS"]                                   │
│                                                                                                  │
│ /Users/kishore-17103/.temp_env/client_env/lib/python3.11/site-packages/pyodide_build/common.py:4 │
│ 03 in <dictcomp>                                                                                 │
│                                                                                                  │
│   400 │                                                                                          │
│   401 │   Sets common environment between in tree and out of tree package builds.                │
│   402 │   """                                                                                    │
│ ❱ 403 │   env.update({key: os.environ[key] for key in BUILD_VARS})                               │
│   404 │   env["PYODIDE"] = "1"                                                                   │
│   405 │   if "PYODIDE_JOBS" in os.environ:                                                       │
│   406 │   │   env["PYODIDE_JOBS"] = os.environ["PYODIDE_JOBS"]                                   │
│ in __getitem__:679                                                                               │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
KeyError: 'WASM_PKG_CONFIG_PATH'
```

**Comment by ryanking13** [comment]
You need to remove the xbuildenv installd from pyodide-build 0.24.1, which is incompatible with other versions. Check if there is `.pyodide-xbuildenv` in the repository and remove it.

```
rm -r .pyodide-xbuildenv
```

**Comment by kishorekaruppusamy** [comment]
@ryanking13 tried with pyodide 0.23.4 version with fresh python env
this time it almost builded but at last i stucked with some issue

```
[ 86%] Built target libprotoc
[ 86%] Building CXX object _deps/protobuf-build/CMakeFiles/protoc.dir/src/google/protobuf/compiler/main.cc.o
[ 86%] Linking CXX executable protoc.js
cache:INFO: generating system asset: symbol_lists/4d2d458438ac40147889ca7e78fc23a6e1f82fa7.txt... (this will be cached in "/Users/kishore-17103/ONNX/emsdk/upstream/emscripten/cache/symbol_lists/4d2d458438ac40147889ca7e78fc23a6e1f82fa7.txt" for subsequent builds)
cache:INFO:  - ok
[ 86%] Built target protoc
[ 86%] Running gen_proto.py on onnx/onnx.in.proto
Processing /Users/kishore-17103/ONNX/onnx/onnx/onnx.in.proto
Writing /Users/kishore-17103/ONNX/onnx/.setuptools-cmake-build/onnx/onnx-ml.proto
Writing /Users/kishore-17103/ONNX/onnx/.setuptools-cmake-build/onnx/onnx-ml.proto3
generating /Users/kishore-17103/ONNX/onnx/.setuptools-cmake-build/onnx/onnx_pb.py
[ 86%] Running C++ protocol buffer compiler on /Users/kishore-17103/ONNX/onnx/.setuptools-cmake-build/onnx/onnx-ml.proto
gmake[2]: _deps/protobuf-build/protoc.js-22.3.0: Permission denied
gmake[2]: *** [CMakeFiles/gen_onnx_proto.dir/build.make:74: onnx/onnx-ml.pb.cc] Error 127
gmake[1]: *** [CMakeFiles/Makefile2:722: CMakeFiles/gen_onnx_proto.dir/all] Error 2
gmake: *** [Makefile:136: all] Error 2
Traceback (most recent call last):
  File "/Users/kishore-17103/.temp_env/client_env/lib/python3.11/site-packages/pep517/in_process/_in_process.py", line 351, in <module>
    main()
  File "/Users/kishore-17103/.temp_env/client_env/lib/python3.11/site-packages/pep517/in_process/_in_process.py", line 333, in main
    json_out['return_val'] = hook(**hook_input['kwargs'])
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kishore-17103/.temp_env/client_env/lib/python3.11/site-packages/pep517/in_process/_in_process.py", line 249, in build_wheel
    return _build_backend().build_wheel(wheel_directory, config_settings,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/private/var/folders/q9/ms4_8l4970q525dlsjp_b9n0x6l4j9/T/build-env-ii3sfv22/lib/python3.11/site-packages/setuptools/build_meta.py", line 434, in build_wheel
    return self._build_with_temp_dir(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/private/var/folders/q9/ms4_8l4970q525dlsjp_b9n0x6l4j9/T/build-env-ii3sfv22/lib/python3.11/site-packages/setuptools/build_meta.py", line 419, in _build_with_temp_dir
    self.run_setup()
  File "/private/var/folders/q9/ms4_8l4970q525dlsjp_b9n0x6l4j9/T/build-env-ii3sfv22/lib/python3.11/site-packages/setuptools/build_meta.py", line 341, in run_setup
    exec(code, locals())
  File "<string>", line 327, in <module>
  File "/private/var/folders/q9/ms4_8l4970q525dlsjp_b9n0x6l4j9/T/build-env-ii3sfv22/lib/python3.11/site-packages/setuptools/__init__.py", line 103, in setup
    return distutils.core.setup(**attrs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/private/var/folders/q9/ms4_8l4970q525dlsjp_b9n0x6l4j9/T/build-env-ii3sfv22/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 185, in setup
    return run_commands(dist)
           ^^^^^^^^^^^^^^^^^^
  File "/private/var/folders/q9/ms4_8l4970q525dlsjp_b9n0x6l4j9/T/build-env-ii3sfv22/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
    dist.run_commands()
  File "/private/var/folders/q9/ms4_8l4970q525dlsjp_b9n0x6l4j9/T/build-env-ii3sfv22/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
    self.run_command(cmd)
  File "/private/var/folders/q9/ms4_8l4970q525dlsjp_b9n0x6l4j9/T/build-env-ii3sfv22/lib/python3.11/site-packages/setuptools/dist.py", line 989, in run_command
    super().run_command(command)
  File "/private/var/folders/q9/ms4_8l4970q525dlsjp_b9n0x6l4j9/T/build-env-ii3sfv22/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/private/var/folders/q9/ms4_8l4970q525dlsjp_b9n0x6l4j9/T/build-env-ii3sfv22/lib/python3.11/site-packages/wheel/bdist_wheel.py", line 369, in run
    self.run_command("build")
  File "/private/var/folders/q9/ms4_8l4970q525dlsjp_b9n0x6l4j9/T/build-env-ii3sfv22/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "/private/var/folders/q9/ms4_8l4970q525dlsjp_b9n0x6l4j9/T/build-env-ii3sfv22/lib/python3.11/site-packages/setuptools/dist.py", line 989, in run_command
    super().run_command(command)
  File "/private/var/folders/q9/ms4_8l4970q525dlsjp_b9n0x6l4j9/T/build-env-ii3sfv22/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/private/var/folders/q9/ms4_8l4970q525dlsjp_b9n0x6l4j9/T/build-env-ii3sfv22/lib/python3.11/site-packages/setuptools/_distutils/command/build.py", line 131, in run
    self.run_command(cmd_name)
  File "/private/var/folders/q9/ms4_8l4970q525dlsjp_b9n0x6l4j9/T/build-env-ii3sfv22/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "/private/var/folders/q9/ms4_8l4970q525dlsjp_b9n0x6l4j9/T/build-env-ii3sfv22/lib/python3.11/site-packages/setuptools/dist.py", line 989, in run_command
    super().run_command(command)
  File "/private/var/folders/q9/ms4_8l4970q525dlsjp_b9n0x6l4j9/T/build-env-ii3sfv22/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "<string>", line 264, in run
  File "/private/var/folders/q9/ms4_8l4970q525dlsjp_b9n0x6l4j9/T/build-env-ii3sfv22/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "/private/var/folders/q9/ms4_8l4970q525dlsjp_b9n0x6l4j9/T/build-env-ii3sfv22/lib/python3.11/site-packages/setuptools/dist.py", line 989, in run_command
    super().run_command(command)
  File "/private/var/folders/q9/ms4_8l4970q525dlsjp_b9n0x6l4j9/T/build-env-ii3sfv22/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "<string>", line 243, in run
  File "/Users/kishore-17103/anaconda3/lib/python3.11/subprocess.py", line 413, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/var/folders/q9/ms4_8l4970q525dlsjp_b9n0x6l4j9/T/tmp3sisqqib/cmake', '--build', '.', '--', '-j', '8']' returned non-zero exit status 2.

ERROR Backend subproccess exited when trying to invoke build_wheel
```

**Comment by kishorekaruppusamy** [comment]
After running pyodide build command with sudo

```
gmake[2]: _deps/protobuf-build/protoc.js-22.3.0: Operation not permitted
gmake[2]: *** [CMakeFiles/gen_onnx_proto.dir/build.make:74: onnx/onnx-ml.pb.cc] Error 127
gmake[1]: *** [CMakeFiles/Makefile2:722: CMakeFiles/gen_onnx_proto.dir/all] Error 2
gmake: *** [Makefile:136: all] Error 2
```

**Comment by ryanking13** [comment]
The problem is that onnxruntime builds `protoc` executable during the build process and use it to compile proto files. But since we are cross compiling, the protoc executable is not runnable in the host environment (as you can see, the suffix of protoc it is `.js`).

I found this issue in the onnx runtime issue tracker https://github.com/microsoft/onnxruntime/issues/113. This might be a bit outdated, but I guess it should support a similar flag that you can specify `protoc` executable path.

**Comment by kishorekaruppusamy** [comment]
``` set(ONNX_CUSTOM_PROTOC_EXECUTABLE /opt/homebrew/bin/protoc) ```
@ryanking13  i tried using this but again i am facing the same issue build compilation is intreputed after ``` 86 % ```.

**Comment by ryanking13** [comment]
Could you check the build log if it is still using protoc.js? If so, I think you need to ask to onnx-runtime devs how you can use custom protoc when cross compilling.

**Comment by kishorekaruppusamy** [comment]
yes @ryanking13 it still using protoc.js, let's check with onnx devs, Thanks for the instant reply ..
