### ISSUE TITLE
pyodide-build: unable to locate numpy package while building the pymatgen package

### ISSUE THREAD

**Issue by jonvanbuskirk0** [pyodide/pyodide#4347]
## 🐛 Bug

During the build of a pymatgen wasm/emscripten whl file following the tutorial: https://pyodide.org/en/stable/development/building-and-testing-packages.html, the 'pyodide build' command returns an error: "ModuleNotFoundError: No module named 'numpy'

### To Reproduce

git clone https://github.com/materialsproject/pymatgen

then follow [this](https://pyodide.org/en/stable/development/building-and-testing-packages.html) tutorial

### Expected behavior

build pymatgen-cp310-cp310-emscripten_3_1_27_wasm32.whl file

### Environment

- Pyodide Version: 0.2.3
- Browser version: 120.0.6099.71
- Any other relevant information: Pymatgen version: 2023.11.18

### Error Log

`xbuild environment already exists, skipping download                                                                                                                         
Installing xbuild environment                                                                                                                                                
* Creating virtualenv isolated environment...
* Installing packages in isolated environment... (Cython>=0.29.23, setuptools>=65.0.0, versioneer[toml], wheel)
* Getting dependencies for wheel...
Traceback (most recent call last):
  File "/home/jvanbuskirk/.local/lib/python3.10/site-packages/pep517/in_process/_in_process.py", line 351, in <module>
    main()
  File "/home/jvanbuskirk/.local/lib/python3.10/site-packages/pep517/in_process/_in_process.py", line 333, in main
    json_out['return_val'] = hook(**hook_input['kwargs'])
  File "/home/jvanbuskirk/.local/lib/python3.10/site-packages/pep517/in_process/_in_process.py", line 118, in get_requires_for_build_wheel
    return hook(config_settings)
  File "/tmp/build-env-bmttes29/lib/python3.10/site-packages/setuptools/build_meta.py", line 325, in get_requires_for_build_wheel
    return self._get_build_requires(config_settings, requirements=['wheel'])
  File "/tmp/build-env-bmttes29/lib/python3.10/site-packages/setuptools/build_meta.py", line 295, in _get_build_requires
    self.run_setup()
  File "/tmp/build-env-bmttes29/lib/python3.10/site-packages/setuptools/build_meta.py", line 311, in run_setup
    exec(code, locals())
  File "<string>", line 8, in <module>
ModuleNotFoundError: No module named 'numpy'
* Getting dependencies for wheel...
Traceback (most recent call last):
  File "/home/jvanbuskirk/.local/lib/python3.10/site-packages/pep517/in_process/_in_process.py", line 351, in <module>
    main()
  File "/home/jvanbuskirk/.local/lib/python3.10/site-packages/pep517/in_process/_in_process.py", line 333, in main
    json_out['return_val'] = hook(**hook_input['kwargs'])
  File "/home/jvanbuskirk/.local/lib/python3.10/site-packages/pep517/in_process/_in_process.py", line 118, in get_requires_for_build_wheel
    return hook(config_settings)
  File "/tmp/build-env-bmttes29/lib/python3.10/site-packages/setuptools/build_meta.py", line 325, in get_requires_for_build_wheel
    return self._get_build_requires(config_settings, requirements=['wheel'])
  File "/tmp/build-env-bmttes29/lib/python3.10/site-packages/setuptools/build_meta.py", line 295, in _get_build_requires
    self.run_setup()
  File "/tmp/build-env-bmttes29/lib/python3.10/site-packages/setuptools/build_meta.py", line 311, in run_setup
    exec(code, locals())
  File "<string>", line 8, in <module>
ModuleNotFoundError: No module named 'numpy'

ERROR Backend subproccess exited when trying to invoke get_requires_for_build_wheel
`

### Additional context

As stated in the tutorial, I verified that I can build the whl file with the regular

pip install build
python -m build

workflow, and indeed, that resulted in a whl file appropriate for my local operating system (Ubuntu, x86_64)

This issue seems to be related to an existing issue: https://github.com/pyodide/pyodide/issues/4160 but pymatgen comes with a pyproject.toml, which requires setuptools, not meson for building.

**Comment by stefdoerr** [comment]
I am getting the same error when building [moleculekit](https://github.com/Acellera/moleculekit)
If you look at the `pyproject.toml` it includes numpy in the build dependencies but when running `pyodide-build` it removes it from the packages

```
Downloading xbuild environment                                                                                                          
Installing xbuild environment                                                                                                           
* Creating virtualenv isolated environment...
* Installing packages in isolated environment... (Cython>=0.29.21, setuptools, toml, versioneer[toml]==0.28)
```
I played around to see if it was maybe reading these packages from elsewhere and removed versioneer from the list and indeed `pyodide-build` updated that message, so it's reading them from `pyproject.toml` but for some reason it ignores `numpy` when it's in that list.

`python -m build` works perfectly fine

**Comment by stefdoerr** [comment]
I dug into the source code.
In the file `pypabuild.py` which is the modified pypa/build used by pyodide-build, there is a function `remove_avoided_requirements` which takes as input `get_unisolated_packages() + AVOIDED_REQUIREMENTS`.
Looking at `build_env.py` in the `get_unisolated_packages()` it reads a file `/home/user/moleculekit/.pyodide-xbuildenv/xbuildenv/pyodide-root/unisolated.txt` which contains `numpy` in it. So indeed pyodide-build is removing on purpose numpy from our build requirements. I don't understand why though.

**Comment by stefdoerr** [comment]
Removing `numpy` from the `unisolated.txt` file continues along with the build but eventually crashes with:
```
AssertionError: would build wheel with unsupported tag ('cp310', 'cp311', 'emscripten_3_1_45_wasm32')

ERROR Backend subproccess exited when trying to invoke build_wheel
```
Which according to this stackoverflow question is a bug in python 3.10 and numpy? https://stackoverflow.com/a/66908804
I'm out of ideas

**Comment by jonvanbuskirk0** [comment]
Hi, Stefan, thanks for sharing your similar error. Hopefully this is addressed soon. As an update, I did manage to make a little more progress. 

Since you were able to determine the error is confined to python3.10 and numpy, I went ahead and installed a local copy of python3.11, and all of the requisite packages, hoping to simply repeat the process with the newer python version. 

Unfortunately, pymatgen does not have a `/home/user/pymatgen/.pyodide-xbuildenv/` directory, but I was eventually able to get it running on pyodide anyways by hosting a local copy of the .tar.gz file from https://pypi.org/project/pymatgen/#files following this procedure: https://pyodide.org/en/stable/usage/loading-custom-python-code.html#from-python. Note, if you do this, you'll need to extract the [package] directory from the untared [package]-X.X.X directory, then retar that into the .tar.gz you use to upload.

This worked for pymatgen, but then I had to go through and find/install all of it's dependencies manually. This led me to needing to repeat the process for another unsupported package, spglib. This package has a `.pyodide-buildenv/` directory though. Following your procedure of removing numpy from the `/home/user/package/.pyodide-xbuildenv/xbuildenv/pyodide-root/unisolated.txt` file, I was able to call `pyodide build` in the `/home/user/package` directory, and build a -none-any.whl file. 

Unfortunately, now this wheel file is being installed correctly, but is not being seen by pymatgen. I can call `micropip.install("./spglib-2.2.0-py3-none-any.whl");`, and importing micropip and calling `micropip.list()` shows spglib is imported, but I still get `ModuleNotFoundError: No module named 'spglib'` when one of the pymatgen modules calls `import spglib`. 

Does anyone have any thoughts about this?

**Comment by stefdoerr** [comment]
Any update on this issue? It's still around in the latest pyodide-build version 0.25.1

**Comment by hoodmane** [comment]
I guess we should look into this @ryanking13...

**Comment by ryanking13** [comment]
Oh, thanks for the ping @hoodmane. I must have missed this issue.

> In the file pypabuild.py which is the modified pypa/build used by pyodide-build, there is a function remove_avoided_requirements which takes as input get_unisolated_packages() + AVOIDED_REQUIREMENTS.
Looking at build_env.py in the get_unisolated_packages() it reads a file /home/user/moleculekit/.pyodide-xbuildenv/xbuildenv/pyodide-root/unisolated.txt which contains numpy in it. So indeed pyodide-build is removing on purpose numpy from our build requirements. I don't understand why though.

This is intended. WebAssembly is a 32-bit environment, so if you install numpy from PyPI when you build, some headers will be incorrect because their values are set based on a 64-bit system. So instead of pulling numpy from PyPI, we redirect it to the numpy we built for WebAssembly to handle it, but I think something was going wrong and this wasn't working properly.

**Comment by stefdoerr** [comment]
@ryanking13 I see, but the issue is that my package contains some cython modules and that cython code uses numpy types so we need to have numpy installed to be able to compile the cython code. This used to work in the past as I was able to correctly build and use my packages through pyodide including the cython code.

**Comment by hoodmane** [comment]
@stefdoerr Are you building with Python 3.11?

**Comment by hoodmane** [comment]
I just successfully built moleculekit with the following:
```sh
git clone https://github.com/emscripten-core/emsdk --depth 1
./emsdk/emsdk install 3.1.46
source ./emsdk/emsdk_enc.sh
python3.11 -m venv .venv
source .venv/bin/activate
pip install pyodide-build
pyodide build
```
so it is at least possible to build pymatgen. It would help if you could give more precise information about what you did for us to reproduce it.

**Comment by hoodmane** [comment]
Ah from your message above:
```
would build wheel with unsupported tag ('cp310', 'cp311', 'emscripten_3_1_45_wasm32')
```
it sounds like you are trying to build with Python3.10 but you need to use Python 3.11. I think that'll fix your trouble. We should have better error reporting for this...

**Comment by stefdoerr** [comment]
Oh well.. that fixed it :smile: Thanks for the help! But yes that error is really not very helpful, I thought it meant that it had trouble with both python 3.10 and 3.11 not that I should switch from 3.10 to 3.11.
