### ISSUE TITLE
pyodide-build error: OSError: [Errno 7] Argument list too long: 'em++'

### ISSUE THREAD

**Issue by NelisDrost** [pyodide/pyodide#4416]
## 🐛 Bug

I'm trying to build the Parselmouth package out-of-tree, following instructions in the documentation. Most of the build completed succesfully, but fails while linking, I think due to the error: `OSError: [Errno 7] Argument list too long: 'em++'`

I have confirmed that building with `python -m build` completes successfully, producing `praat_parselmouth-0.5.0.dev0-cp311-cp311-linux_x86_64.whl`.

I've tried increasing the stack limit with `ulimit -s 65536`.

### To Reproduce

Set up pyodide-build and emsdk as in the documentation
```
git clone https://github.com/YannickJadoul/Parselmouth.git
cd Parselmouth
git submodule init
git submodule update
pyodide build
```

### Expected behavior

A successful build.

### Environment

- pyodide-build 0.25.0
- python 3.11
- Ubuntu 22.04.2 LTS running under WSL2

### Additional context

The console output, starting with the penultimate linking step:
```
[1462/1463] Linking CXX shared module src/parselmouth.cpython-311-x86_64-linux-gnu.so
FAILED: src/parselmouth.cpython-311-x86_64-linux-gnu.so
: && /tmp/tmprkhena0x/c++ -fPIC -O3 -DNDEBUG  -flto -shared  -o src/parselmouth.cpython-311-x86_64-linux-gnu.so src/CMakeFiles/parselmouth.dir/parselmouth.cpp.o src/CMakeFiles/parselmouth.dir/parselmouth/CC.cpp.o src/CMakeFiles/parselmouth.dir/parselmouth/Data.cpp.o src/CMakeFiles/parselmouth.dir/parselmouth/Formant.cpp.o src/CMakeFiles/parselmouth.dir/parselmouth/Function.cpp.o src/CMakeFiles/parselmouth.dir/parselmouth/Harmonicity.cpp.o src/CMakeFiles/parselmouth.dir/parselmouth/Intensity.cpp.o src/CMakeFiles/parselmouth.dir/parselmouth/Matrix.cpp.o src/CMakeFiles/parselmouth.dir/parselmouth/MFCC.cpp.o src/CMakeFiles/parselmouth.dir/parselmouth/Pitch.cpp.o src/CMakeFiles/parselmouth.dir/parselmouth/Sampled.cpp.o src/CMakeFiles/parselmouth.dir/parselmouth/SampledXY.cpp.o src/CMakeFiles/parselmouth.dir/parselmouth/Sound.cpp.o src/CMakeFiles/parselmouth.dir/parselmouth/Spectrogram.cpp.o src/CMakeFiles/parselmouth.dir/parselmouth/Spectrum.cpp.o src/CMakeFiles/parselmouth.dir/parselmouth/TextGrid.cpp.o src/CMakeFiles/parselmouth.dir/parselmouth/TextGridTools.cpp.o src/CMakeFiles/parselmouth.dir/parselmouth/Thing.cpp.o src/CMakeFiles/parselmouth.dir/parselmouth/Vector.cpp.o src/CMakeFiles/parselmouth.dir/parselmouth/praat.cpp.o  praat/libpraat.a  extern/fmt/libfmt.a && cd /home/ubuntu/github/pyd2/Parselmouth/_skbuild/emscripten_3_1_46_wasm32-3.11/cmake-build/src && /tmp/tmprkhena0x/strip /home/ubuntu/github/pyd2/Parselmouth/_skbuild/emscripten_3_1_46_wasm32-3.11/cmake-build/src/parselmouth.cpython-311-x86_64-linux-gnu.so
Traceback (most recent call last):
  File "/tmp/tmprkhena0x/c++", line 709, in <module>
    compiler_main()
  File "/tmp/tmprkhena0x/c++", line 705, in compiler_main
    sys.exit(handle_command(args, build_args))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/tmprkhena0x/c++", line 696, in handle_command
    result = subprocess.run(new_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 546, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 1022, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.11/subprocess.py", line 1899, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 7] Argument list too long: 'em++'
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "/tmp/build-env-gb9jjrau/lib/python3.11/site-packages/skbuild/setuptools_wrap.py", line 674, in setup
    cmkr.make(make_args, install_target=cmake_install_target, env=env)
  File "/tmp/build-env-gb9jjrau/lib/python3.11/site-packages/skbuild/cmaker.py", line 697, in make
    self.make_impl(clargs=clargs, config=config, source_dir=source_dir, install_target=install_target, env=env)
  File "/tmp/build-env-gb9jjrau/lib/python3.11/site-packages/skbuild/cmaker.py", line 742, in make_impl
    raise SKBuildError(msg)

An error occurred while building with CMake.
  Command:
    /tmp/tmprkhena0x/cmake --build . --target install --config Release --
  Install target:
    install
  Source directory:
    /home/ubuntu/github/pyd2/Parselmouth
  Working directory:
    /home/ubuntu/github/pyd2/Parselmouth/_skbuild/emscripten_3_1_46_wasm32-3.11/cmake-build
Please check the install target is valid and see CMake's output for more information.


ERROR Backend subprocess exited when trying to invoke build_wheel
```

**Comment by NelisDrost** [comment]
Full build output: https://gist.github.com/NelisDrost/47336209111255a4ae131613b3a279ea

**Comment by ryanking13** [comment]
Could you try:

```
pyodide build --exports whole_archive
```
?

`Argument list too long` often happens when a package has too many public symbols. adding `--exports whole_archive` will simply export every symbols. The drawback is that it will slightly increase the output size, but I think it won't be a big problem.

**Comment by NelisDrost** [comment]
That got me a little further, thanks - I'm now getting a different error.

Output (from the same line as above) below, but the actual error seems to be:
```
wasm-ld: error: function signature mismatch: GRAPHICS_PostScript_settings
>>> defined as (i32, i32, i32, i32, i32, i32, i32, i32) -> void in praat/libpraat.a(HyperPage.cpp.o)
>>> defined as (i32, i32, i32, i32, i32, i32, i32, i32, i32) -> void in praat/libpraat.a(praat_picture.cpp.o)
```

This looks like it's probably an issue with the source, but I'm hoping you have some insight?

```
FAILED: src/parselmouth.cpython-311-x86_64-linux-gnu.so
: && /tmp/tmpc_2coytp/c++ -fPIC -O3 -DNDEBUG  -flto -shared  -o src/parselmouth.cpython-311-x86_64-linux-gnu.so src/CMakeFiles/parselmouth.dir/parselmouth.cpp.o src/CMakeFiles/parselmouth.dir/parselmouth/CC.cpp.o src/CMakeFiles/parselmouth.dir/parselmouth/Data.cpp.o src/CMakeFiles/parselmouth.dir/parselmouth/Formant.cpp.o src/CMakeFiles/parselmouth.dir/parselmouth/Function.cpp.o src/CMakeFiles/parselmouth.dir/parselmouth/Harmonicity.cpp.o src/CMakeFiles/parselmouth.dir/parselmouth/Intensity.cpp.o src/CMakeFiles/parselmouth.dir/parselmouth/Matrix.cpp.o src/CMakeFiles/parselmouth.dir/parselmouth/MFCC.cpp.o src/CMakeFiles/parselmouth.dir/parselmouth/Pitch.cpp.o src/CMakeFiles/parselmouth.dir/parselmouth/Sampled.cpp.o src/CMakeFiles/parselmouth.dir/parselmouth/SampledXY.cpp.o src/CMakeFiles/parselmouth.dir/parselmouth/Sound.cpp.o src/CMakeFiles/parselmouth.dir/parselmouth/Spectrogram.cpp.o src/CMakeFiles/parselmouth.dir/parselmouth/Spectrum.cpp.o src/CMakeFiles/parselmouth.dir/parselmouth/TextGrid.cpp.o src/CMakeFiles/parselmouth.dir/parselmouth/TextGridTools.cpp.o src/CMakeFiles/parselmouth.dir/parselmouth/Thing.cpp.o src/CMakeFiles/parselmouth.dir/parselmouth/Vector.cpp.o src/CMakeFiles/parselmouth.dir/parselmouth/praat.cpp.o  praat/libpraat.a  extern/fmt/libfmt.a && cd /home/ubuntu/github/pyd2/Parselmouth/_skbuild/emscripten_3_1_46_wasm32-3.11/cmake-build/src && /tmp/tmpc_2coytp/strip /home/ubuntu/github/pyd2/Parselmouth/_skbuild/emscripten_3_1_46_wasm32-3.11/cmake-build/src/parselmouth.cpython-311-x86_64-linux-gnu.so
wasm-ld: error: function signature mismatch: GRAPHICS_PostScript_settings
>>> defined as (i32, i32, i32, i32, i32, i32, i32, i32) -> void in praat/libpraat.a(HyperPage.cpp.o)
>>> defined as (i32, i32, i32, i32, i32, i32, i32, i32, i32) -> void in praat/libpraat.a(praat_picture.cpp.o)
em++: error: '/home/ubuntu/github/pyd2/emsdk/upstream/bin/wasm-ld -o src/parselmouth.cpython-311-x86_64-linux-gnu.so --whole-archive src/CMakeFiles/parselmouth.dir/parselmouth.cpp.o src/CMakeFiles/parselmouth.dir/parselmouth/CC.cpp.o src/CMakeFiles/parselmouth.dir/parselmouth/Data.cpp.o src/CMakeFiles/parselmouth.dir/parselmouth/Formant.cpp.o src/CMakeFiles/parselmouth.dir/parselmouth/Function.cpp.o src/CMakeFiles/parselmouth.dir/parselmouth/Harmonicity.cpp.o src/CMakeFiles/parselmouth.dir/parselmouth/Intensity.cpp.o src/CMakeFiles/parselmouth.dir/parselmouth/Matrix.cpp.o src/CMakeFiles/parselmouth.dir/parselmouth/MFCC.cpp.o src/CMakeFiles/parselmouth.dir/parselmouth/Pitch.cpp.o src/CMakeFiles/parselmouth.dir/parselmouth/Sampled.cpp.o src/CMakeFiles/parselmouth.dir/parselmouth/SampledXY.cpp.o src/CMakeFiles/parselmouth.dir/parselmouth/Sound.cpp.o src/CMakeFiles/parselmouth.dir/parselmouth/Spectrogram.cpp.o src/CMakeFiles/parselmouth.dir/parselmouth/Spectrum.cpp.o src/CMakeFiles/parselmouth.dir/parselmouth/TextGrid.cpp.o src/CMakeFiles/parselmouth.dir/parselmouth/TextGridTools.cpp.o src/CMakeFiles/parselmouth.dir/parselmouth/Thing.cpp.o src/CMakeFiles/parselmouth.dir/parselmouth/Vector.cpp.o src/CMakeFiles/parselmouth.dir/parselmouth/praat.cpp.o praat/libpraat.a extern/fmt/libfmt.a --fatal-warnings -L/home/ubuntu/github/pyd2/Parselmouth/.pyodide-xbuildenv/xbuildenv/pyodide-root/cpython/installs/python-3.11.3/lib/ -L/home/ubuntu/github/pyd2/emsdk/upstream/emscripten/cache/sysroot/lib/wasm32-emscripten/lto-pic --no-whole-archive -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr --import-memory --strip-debug --export-dynamic --export-if-defined=main --export-if-defined=__start_em_asm --export-if-defined=__stop_em_asm --export-if-defined=__start_em_lib_deps --export-if-defined=__stop_em_lib_deps --export-if-defined=__start_em_js --export-if-defined=__stop_em_js --export-if-defined=__main_argc_argv --export-if-defined=__wasm_apply_data_relocs --export=__wasm_call_ctors --experimental-pic -shared' failed (returned 1)
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "/tmp/build-env-wwuu66c1/lib/python3.11/site-packages/skbuild/setuptools_wrap.py", line 674, in setup
    cmkr.make(make_args, install_target=cmake_install_target, env=env)
  File "/tmp/build-env-wwuu66c1/lib/python3.11/site-packages/skbuild/cmaker.py", line 697, in make
    self.make_impl(clargs=clargs, config=config, source_dir=source_dir, install_target=install_target, env=env)
  File "/tmp/build-env-wwuu66c1/lib/python3.11/site-packages/skbuild/cmaker.py", line 742, in make_impl
    raise SKBuildError(msg)

An error occurred while building with CMake.
  Command:
    /tmp/tmpc_2coytp/cmake --build . --target install --config Release --
  Install target:
    install
  Source directory:
    /home/ubuntu/github/pyd2/Parselmouth
  Working directory:
    /home/ubuntu/github/pyd2/Parselmouth/_skbuild/emscripten_3_1_46_wasm32-3.11/cmake-build
Please check the install target is valid and see CMake's output for more information.
```

**Comment by hoodmane** [comment]
Looks to me like you need to apply this patch. It looks to me like an actual bug in praat since it looks like `GRAPHICS_PostScript_settings` actually uses the `optionalEditor` argument.
```patch
diff --git a/sys/HyperPage.cpp b/sys/HyperPage.cpp
index 9b3d6b4..71b4f56 100644
--- a/sys/HyperPage.cpp
+++ b/sys/HyperPage.cpp
@@ -654,12 +654,12 @@ static void gui_drawingarea_cb_mouse (HyperPage me, GuiDrawingArea_MouseEvent ev
        }
 }
 
-extern "C" void GRAPHICS_PostScript_settings (UiForm sendingForm, int narg, Stackel args, conststring32 sendingString, Interpreter interpreter, conststring32 invokingButtonTitle, bool modified, void *buttonClosure);
+extern "C" void GRAPHICS_PostScript_settings (UiForm sendingForm, int narg, Stackel args, conststring32 sendingString, Interpreter interpreter, conststring32 invokingButtonTitle, bool modified, void *buttonClosure, Editor optionalEditor);
 
 static void menu_cb_postScriptSettings (HyperPage me, EDITOR_ARGS) {
        (void) me;
        (void) cmd;
-       GRAPHICS_PostScript_settings (_sendingForm_, _narg_, _args_, _sendingString_, optionalInterpreter, nullptr, false, nullptr);
+       GRAPHICS_PostScript_settings (_sendingForm_, _narg_, _args_, _sendingString_, optionalInterpreter, nullptr, false, nullptr, nullptr);
 }
 
 #ifdef macintosh
```

**Comment by NelisDrost** [comment]
That fixed it, thanks - I now have a completed build.

I'm sure I'll run into more issues, but those are beyond the scope of this issue, so marking it as resolved.

Many thanks for the help!
