### ISSUE TITLE
Unable to load pyodide from different indexURL

### ISSUE THREAD

**Issue by savakarrohan** [pyodide/pyodide#4504]
## 🐛 Bug
While using a custom distribution of pyodide, I am using the indexURL of the loadPyodide settings in a react component which is being compiled using webpack. Part of the code looks like this in the `useEffect` of the component. 

```
  async function hello_python() {
    let pyodide = await loadPyodide({
      indexURL: "https://cdn.jsdelivr.net/pyodide/v0.24.0/full/",
    });
    return pyodide.runPythonAsync("1+1");
  }
    hello_python().then((result) => {
      console.log("Python says that 1+1 =", result);
    });
```

## Error
```
Cannot find module 'https://cdn.jsdelivr.net/pyodide/v0.24.0/full/pyodide.asm.js'
    at http://localhost:3000/static/js/bundle.js:81938:11
    at async loadScript (http://localhost:3000/static/js/bundle.js:84912:43)
    at async loadPyodide (http://localhost:3000/static/js/bundle.js:85242:5)
    at async hello_python (http://localhost:3000/static/js/bundle.js:1282:19)
```

### Environment

- Pyodide Version: v.0.25.0
- Browser version: edge
- Any other relevant information:

### Additional context

#4419 , #3550 

![image](https://github.com/pyodide/pyodide/assets/50200523/b6224734-eb8f-499d-978b-2f112abf49fd)

**Comment by ryanking13** [comment]
This is an issue with Webpack's behavior in the bundling of dynamic imports.  Could you try [pyodide-webpack-plugin](https://github.com/pyodide/pyodide-webpack-plugin), and see if it works?
