### ISSUE TITLE
pyodide cannot call div.removeChild() method successfully

### ISSUE THREAD

**Issue by yu0A** [pyodide/pyodide#4535]
## 🐛 Bug

When I call div.removeChild() method in pyodide Python env, it doesn't work. 
I'm fixing [that bug](https://github.com/pyodide/matplotlib-pyodide/issues/49). If pyodide cannot removeChild, that bug cannot be fixed.

### To Reproduce

[Clone this repo](https://github.com/yu0A/test_pyodide_whl_files.git)
*  deploy the code and visit index.html
*  click "Load Files" button
*  use Chrome browser to load the folder matplotlib_pyodide 
*  then click "Draw Matplotlib" button
*  after several seconds, new divs will appears

### Expected behavior

Since I called div.removeChild() method in:
![image](https://github.com/pyodide/pyodide/assets/111437058/3fa7b77f-5a91-4dd6-a937-7bc20c27c33e)
The new divs should be removed.

### Environment

- Pyodide Version: 0.25.0
- Browser version Chrome: 121.0.6167.185
- Any other relevant information:

**Comment by hoodmane** [comment]
Thanks for looking into fixing matplotlib @yu0A. I tried it out and I got this error:
```
Uncaught (in promise) PythonError: Traceback (most recent call last):
  File "/lib/python311.zip/_pyodide/_base.py", line 501, in eval_code
    .run(globals, locals)
     ^^^^^^^^^^^^^^^^^^^^
  File "/lib/python311.zip/_pyodide/_base.py", line 339, in run
    coroutine = eval(self.code, globals, locals)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<exec>", line 39, in <module>
  File "/lib/python3.11/site-packages/matplotlib/pyplot.py", line 935, in close
    _pylab_helpers.Gcf.destroy(manager)
  File "/lib/python3.11/site-packages/matplotlib/_pylab_helpers.py", line 67, in destroy
    manager.destroy()
  File "/mount_dir/matplotlib_pyodide/html5_canvas_backend.py", line 435, in destroy
    self.canvas.destroy()
  File "/mount_dir/matplotlib_pyodide/browser_backend.py", line 201, in destroy
    return self.destroy_by_id("target")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mount_dir/matplotlib_pyodide/browser_backend.py", line 210, in destroy_by_id
    childElements = div.childNodes
                    ^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'childNodes'
```
Seems that the problem is that `document.getElementById("target")` returns `null` and so it has no children. I can't say why you would expect there to be an element of id target at that point or why there isn't one though.

**Comment by yu0A** [comment]
> Seems that the problem is that `document.getElementById("target")` returns `null` and so it has no children. I can't say why you would expect there to be an element of id target at that point or why there isn't one though.
The id "target" is a hardcoded div, you can see it in the line 20 of my repo.
![image](https://github.com/pyodide/pyodide/assets/111437058/0645d328-cc89-4282-80c4-342f310c37d9)

**Comment by yu0A** [comment]
> Seems that the problem is that `document.getElementById("target")` returns `null` and so it has no children. I can't say why you would expect there to be an element of id target at that point or why there isn't one though.

After calling pyplot.show() method, you can see new divs generated as the child of div id="target". This is not an expect, because you can see this on the page.

**Comment by ryanking13** [comment]
I am not sure how matplotlib finds a backend, but when I tested, it seems like your patched backend is not used in your example

So, I think you need to overwrite existing `matplotib_pyodide` packages to make matplotlib use your patched code, before importing matplotlib and set backend.

```python
import shutil
shutil.rmtree('/lib/python3.11/site-packages/matplotlib_pyodide')
shutil.copytree('/mount_dir', '/lib/python3.11/site-packages/matplotlib_pyodide')
```

**Comment by hoodmane** [comment]
But @yu0A it would help us figure out what's going on if you:
1. Include the traceback you're getting (or the information that there isn't one)
2. Make a MWE.

It seems to work fine to call `div.removeChild` when I try it directly.

**Comment by yu0A** [comment]
> I am not sure how matplotlib finds a backend, but when I tested, it seems like your patched backend is not used in your example
> 
> So, I think you need to overwrite existing `matplotib_pyodide` packages to make matplotlib use your patched code, before importing matplotlib and set backend.
> 
> ```python
> import shutil
> shutil.rmtree('/lib/python3.11/site-packages/matplotlib_pyodide')
> shutil.copytree('/mount_dir', '/lib/python3.11/site-packages/matplotlib_pyodide')
> ```

After adding this code, the error log in browser changed as below:
`AttributeError: 'FigureCanvasHTMLCanvas' object has no attribute 'destroy'`
![image](https://github.com/pyodide/pyodide/assets/111437058/2e3cdab1-1525-4ae5-8c03-27055dab2bbb)
I will try to add a destroy() method and try again.

**Comment by yu0A** [comment]
After adding a destroy() method and try again, the error log in browser changed as below:
`AttributeError: type object 'FigureCanvasWasm' has no attribute 'destroy'`
![image](https://github.com/pyodide/pyodide/assets/111437058/b72dcdca-6664-4f80-b68f-e63334cce6d3)

**Comment by yu0A** [comment]
> 1. Include the traceback you're getting (or the information that there isn't one)
Traceback:
Uncaught (in promise) PythonError: Traceback (most recent call last):
  File "/lib/python311.zip/_pyodide/_base.py", line 501, in eval_code
    .run(globals, locals)
     ^^^^^^^^^^^^^^^^^^^^
  File "/lib/python311.zip/_pyodide/_base.py", line 339, in run
    coroutine = eval(self.code, globals, locals)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<exec>", line 36, in <module>
  File "/lib/python3.11/site-packages/matplotlib/pyplot.py", line 935, in close
    _pylab_helpers.Gcf.destroy(manager)
  File "/lib/python3.11/site-packages/matplotlib/_pylab_helpers.py", line 67, in destroy
    manager.destroy()
  File "/lib/python3.11/site-packages/matplotlib_pyodide/html5_canvas_backend.py", line 438, in destroy
    self.canvas.destroy()
  File "/lib/python3.11/site-packages/matplotlib_pyodide/html5_canvas_backend.py", line 48, in destroy
    FigureCanvasWasm.destroy(self)
    ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: type object 'FigureCanvasWasm' has no attribute 'destroy'

    at new_error (pyodide.asm.js:9:10014)
    at pyodide.asm.wasm:0x158e62
    at pyodide.asm.wasm:0x158f69
    at Module._pythonexc2js (pyodide.asm.js:9:608600)
    at Module.callPyObjectKwargs (pyodide.asm.js:9:64408)
    at Proxy.callKwargs (pyodide.asm.js:9:79802)
    at Proxy.runPython (pyodide.asm.js:9:102102)
    at Proxy.draw (index.html:64:30)
    at callWithErrorHandling (vue@3:1760:21)
    at callWithAsyncErrorHandling (vue@3:1767:19)
    at emit (vue@3:2278:7)
    at vue@3:9266:47
    at handleClick (element-plus:17170:7)
    at callWithErrorHandling (vue@3:1760:21)
    at callWithAsyncErrorHandling (vue@3:1767:19)
    at HTMLButtonElement.invoker (vue@3:10272:7)
> 2. Make a MWE.
What is MWE? Can you give me an instruction about it?

**Comment by yu0A** [comment]
My code in [Clone this repo](https://github.com/yu0A/test_pyodide_whl_files.git) is updated too

**Comment by ryanking13** [comment]
> After adding this code, the error log in browser changed as below:
AttributeError: 'FigureCanvasHTMLCanvas' object has no attribute 'destroy'

Could you try putting the code before any import on matplotlib_pyodide or matplotlib happens, so that import does not mess up?

**Comment by yu0A** [comment]
> Could you try putting the code before any import on matplotlib_pyodide or matplotlib happens, so that import does not mess up?

OK, the new error log is as below:
Uncaught (in promise) PythonError: Traceback (most recent call last):
  File "/lib/python311.zip/_pyodide/_base.py", line 501, in eval_code
    .run(globals, locals)
     ^^^^^^^^^^^^^^^^^^^^
  File "/lib/python311.zip/_pyodide/_base.py", line 339, in run
    coroutine = eval(self.code, globals, locals)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<exec>", line 36, in <module>
  File "/lib/python3.11/site-packages/matplotlib/pyplot.py", line 935, in close
    _pylab_helpers.Gcf.destroy(manager)
  File "/lib/python3.11/site-packages/matplotlib/_pylab_helpers.py", line 67, in destroy
    manager.destroy()
  File "/lib/python3.11/site-packages/matplotlib_pyodide/html5_canvas_backend.py", line 438, in destroy
    self.canvas.destroy()
  File "/lib/python3.11/site-packages/matplotlib_pyodide/html5_canvas_backend.py", line 48, in destroy
    FigureCanvasWasm.destroy(self)
  File "/lib/python3.11/site-packages/matplotlib_pyodide/browser_backend.py", line 201, in destroy
    return self.destroy_by_id("target")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/matplotlib_pyodide/browser_backend.py", line 206, in destroy_by_id
    childElements = div.childNodes
                    ^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'childNodes'

    at new_error (pyodide.asm.js:9:10014)
    at pyodide.asm.wasm:0x158e62
    at pyodide.asm.wasm:0x158f69
    at Module._pythonexc2js (pyodide.asm.js:9:608600)
    at Module.callPyObjectKwargs (pyodide.asm.js:9:64408)
    at Proxy.callKwargs (pyodide.asm.js:9:79802)
    at Proxy.runPython (pyodide.asm.js:9:102102)
    at Proxy.draw (index.html:64:30)
    at callWithErrorHandling (vue@3:1760:21)
    at callWithAsyncErrorHandling (vue@3:1767:19)
    at emit (vue@3:2278:7)
    at vue@3:9266:47
    at handleClick (element-plus:17170:7)
    at callWithErrorHandling (vue@3:1760:21)
    at callWithAsyncErrorHandling (vue@3:1767:19)
    at HTMLButtonElement.invoker (vue@3:10272:7)

**Comment by ryanking13** [comment]
> AttributeError: 'NoneType' object has no attribute 'childNodes'

This seems because the parent div is removed.

In your code,

```python
        div = document.getElementById("app")
        parentElement = div.parentNode
        if parentElement: 
            parentElement.removeChild(div)
```

will remove the div with id `app` and it holds the div `target`, so after removing it, there is no target div anymore.

**Comment by yu0A** [comment]
> will remove the div with id `app` and it holds the div `target`, so after removing it, there is no target div anymore.

Yes, the code seems like successfully deleted <div id="app">, but if you check the DOM structure, you can see the div remains not deleted.

**Comment by yu0A** [comment]
> Hmm, no, when I checked, it removed both `<div id="app">` and the `<div id="target">` inside it. How can a child div survive without the parent div?
I tried to delete only one div of `<div id="app">` and `<div id="target">`, but it still throw an error.

**Comment by yu0A** [comment]
And, if you think I have successfully deleted a whatever div for 2 times, why the div remains not deleted in the DOM finally?

**Comment by ryanking13** [comment]
> why the div remains not deleted in the DOM finally

This wasn't my case. Both divs are removed, and there is no remaining div, which results in `document.getElementById` returning None.

Here is a result I get, you can see the divs are removed.

https://github.com/pyodide/pyodide/assets/24893111/d73017c1-f266-4021-9482-185ad0088d8c

This is a script that I used

```html
<html>
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width,initial-scale=1.0" />
    <script src="https://cdn.jsdelivr.net/pyodide/v0.25.0/full/pyodide.js"></script>
  </head>
  <body>
    <button onclick="main()">Run</button>
    <div id="app">
      <div id="target"></div>
    </div>
    <script>

      async function main() {
        const dirHandle = await showDirectoryPicker();
        const pyodide = await loadPyodide();  
        const nativefs = await pyodide.mountNativeFS("/mount_dir", dirHandle);
        pyodide.pyimport("sys").path.insert(0, "/mount_dir")

        document.pyodideMplTarget = document.getElementById('target')
        await pyodide.loadPackage("matplotlib");

        result = pyodide.runPythonAsync(`
import asyncio
import js
import shutil
shutil.rmtree('/lib/python3.11/site-packages/matplotlib_pyodide')
shutil.copytree('/mount_dir', '/lib/python3.11/site-packages/matplotlib_pyodide')

import matplotlib.pyplot as plt
import numpy as np
import matplotlib as mpl
mpl.use("module://matplotlib_pyodide.html5_canvas_backend")

t = np.arange(0.0, 2.0, 0.01)
s = 1 + np.sin(2 * np.pi * t)
fig, ax = plt.subplots()
ax.plot(t, s)

print("showing figure")
print(f"js.document.app: {js.document.getElementById('app')}")
print(f"js.document.target: {js.document.getElementById('target')}")

plt.show()

print("waiting for 1sec")
print("closing figure")
plt.close(fig)

print(f"js.document.app: {js.document.getElementById('app')}")
print(f"js.document.target: {js.document.getElementById('target')}")
        `);
      };
    </script>
  </body>
</html>
```

**Comment by yu0A** [comment]
> > why the div remains not deleted in the DOM finally
> 
> This wasn't my case. Both divs are removed, and there is no remaining div, which results in `document.getElementById` returning None.

This is good news. I can use your html to fix python script bugs.

**Comment by yu0A** [comment]
I see the div id=app can be removed in vanilla html. But that div cannot be removed in my Vue html. Could you be a little bit of an idea from me?

**Comment by ryanking13** [comment]
> I see the div id=app can be removed in vanilla html. But that div cannot be removed in my Vue html. Could you be a little bit of an idea from me?

I don't know much about vue, but if you could share the code to reproduce the issue, I'll try to help.

**Comment by ArneBachmann** [comment]
Just ran into the same issue with a matplotlib call...
```python3
Uncaught PythonError: Traceback (most recent call last):
  File "/home/pyodide/fitrack/web.py", line 59, in wrapper
    def wrapper(*args:Any, **kwargs:Any) -> None: func(*args, **kwargs)
                                                  ^^^^^^^^^^^^^^^^^^^^^
  File "/home/pyodide/fitrack/ap2.py", line 527, in _per_exercise_stats_popup_action
    plot_b:bytes = make_plot(
                   ^^^^^^^^^^
  File "<@beartype(fitrack.ap2.make_plot) at 0x1cb4e18>", line 270, in make_plot
  File "/home/pyodide/fitrack/ap2.py", line 331, in make_plot
    plt.close()
  File "/lib/python3.12/site-packages/matplotlib/pyplot.py", line 935, in close
    _pylab_helpers.Gcf.destroy(manager)
  File "/lib/python3.12/site-packages/matplotlib/_pylab_helpers.py", line 67, in destroy
    manager.destroy()
  File "/lib/python3.12/site-packages/matplotlib_pyodide/wasm_backend.py", line 99, in destroy
    self.canvas.destroy(*args, **kwargs)
  File "/lib/python3.12/site-packages/matplotlib_pyodide/browser_backend.py", line 195, in destroy
    parentElement = div.parentNode
                    ^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'parentNode'
```

Not sure how to proceed.

**Comment by ryanking13** [comment]
@ArneBachmann Could you please open an issue in matplotlib-pyodide repository, with how we can reproduce the error? Unfortunately, matplotlib-pyodide is not actively maintained, so we can't say it will be fixed soon. So it would be helpful if you could investigate an error and open a PR.

**Comment by yu0A** [comment]
I reopened this discussion

**Comment by ryanking13** [comment]
We switched the matplotlib backend from matplotlib-pyodide to patched webagg-backend, so this issue is not relavant anymore.

**Comment by yu0A** [comment]
wow nice

Gyeongjae Choi ***@***.***> 于 2025年9月20日周六 下午3:25写道：
