### ISSUE TITLE
Package request: add the CasADi framework

### ISSUE THREAD

**Issue by agriyakhetarpal** [pyodide/pyodide#4551]
## 🐍 Package Request

- Package Name and Version : `casadi` (version 3.6.4 and later)
- Package URL : https://github.com/casadi/casadi, https://pypi.org/project/casadi/
- Package Dependencies that needs to be resolved first: CasADi is primarily written in C++ with bindings for Python and MATLAB, and AFAIK it does not mark dependencies on any Python packages, with the exception of NumPy. It does [provide interfaces](https://github.com/casadi/casadi/tree/main/casadi/interfaces) to a lot of C/C++ based solvers, however, such as BONMIN, IPOPT, NLOPT, SUNDIALS, Alpaqa, HiGHS, and more. The source build instructions for CasADi are available here: https://github.com/casadi/casadi/wiki/InstallationLinux

**Comment by hoodmane** [comment]
If you work on this, we will answer your questions.

**Comment by hoodmane** [comment]
What happens if you clone it and run `python -m build .` in the source directory? Presumably you're saying that doesn't work?

**Comment by hoodmane** [comment]
Looks like the sdist at least includes a `setup.py`, so being optimistic, maybe they already did the extra weird steps before making the sdist and it won't be a problem?

**Comment by agriyakhetarpal** [comment]
I just tried compiling it with the following command:

```bash
$ pip install casadi --no-binary casadi
```

<details><summary>Expand to view logs
</summary>
<p>

```bash
casadi-pyodide % 
Collecting casadi
  Downloading casadi-3.6.4.tar.gz (5.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.1/5.1 MB 2.5 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Collecting numpy (from casadi)
  Using cached numpy-1.26.4-cp311-cp311-macosx_11_0_arm64.whl.metadata (114 kB)
Using cached numpy-1.26.4-cp311-cp311-macosx_11_0_arm64.whl (14.0 MB)
Building wheels for collected packages: casadi
  Building wheel for casadi (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [130 lines of output]
      running bdist_wheel
      running build
      running build_ext
      /private/var/folders/jg/wkd_9vqx7qlbdkrf0yw7hmtr0000gn/T/pip-install-vk9uci24/casadi_0c4bbd6e85c94d0ca9839c94b5dacf95/setup.py:29: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
        cmake_version = LooseVersion(re.search(
      -- The C compiler identification is AppleClang 15.0.0.15000100
      -- The CXX compiler identification is AppleClang 15.0.0.15000100
      -- Detecting C compiler ABI info
      -- Detecting C compiler ABI info - done
      -- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc - skipped
      -- Detecting C compile features
      -- Detecting C compile features - done
      -- Detecting CXX compiler ABI info
      -- Detecting CXX compiler ABI info - done
      -- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++ - skipped
      -- Detecting CXX compile features
      -- Detecting CXX compile features - done
      -- The Fortran compiler identification is GNU 13.2.0
      -- Checking whether Fortran compiler has -isysroot
      -- Checking whether Fortran compiler has -isysroot - yes
      -- Checking whether Fortran compiler supports OSX deployment target flag
      -- Checking whether Fortran compiler supports OSX deployment target flag - yes
      -- Detecting Fortran compiler ABI info
      -- Detecting Fortran compiler ABI info - done
      -- Check for working Fortran compiler: /opt/homebrew/bin/gfortran - skipped
      -- Flag needed for enabling C++11 features: -std=c++11
      EXTERNAL_CMAKE_COMMAND: /Users/agriyakhetarpal/Library/Application Support/pipx/venvs/cmake/lib/python3.11/site-packages/cmake/data/bin/cmake
      CXX /Library/Developer/CommandLineTools/usr/bin/c++
      FC /opt/homebrew/bin/gfortran
      CC /Library/Developer/CommandLineTools/usr/bin/cc
      CMAKE_C_COMPILER_ID: AppleClang
      -- CMAKE_SYSTEM_NAME: Darwin
      WITH_SPRAL OFF WITH_BUILD_SPRAL OFF
      -- /Users/agriyakhetarpal/Desktop/casadi-pyodide/casadi-dev/include
      CMake Error at swig/python/CMakeLists.txt:32 (file):
        file STRINGS file
        "/Users/agriyakhetarpal/Desktop/casadi-pyodide/casadi-dev/include/patchlevel.h"
        cannot be read.
      Call Stack (most recent call first):
        swig/python/CMakeLists.txt:62 (CasadiGetPythonVersionMajor)
      
      
      PYTHONFLAGS: -DSWIG_TYPE_TABLE=casadi;-fvirtual;-DWITH_DEPRECATED_FEATURES;-DPy_USING_UNICODE;-noproxydel;-fastunpack;-modernargs
      COMPILE_FLAGS: -Wno-dynamic-class-memaccess -Wno-self-assign
      -- Performing Test COMPILER_HAS_HIDDEN_VISIBILITY
      -- Performing Test COMPILER_HAS_HIDDEN_VISIBILITY - Success
      -- Performing Test COMPILER_HAS_HIDDEN_INLINE_VISIBILITY
      -- Performing Test COMPILER_HAS_HIDDEN_INLINE_VISIBILITY - Success
      -- Performing Test COMPILER_HAS_DEPRECATED_ATTR
      -- Performing Test COMPILER_HAS_DEPRECATED_ATTR - Success
      -- The following features have been enabled:
      
       * dynamic-loading, Support for import of FMI 2.0 binaries
       * sundials-interface, Interface to the ODE/DAE integrator suite SUNDIALS.
       * csparse-interface, Interface to the sparse direct linear solver CSparse.
       * tinyxml-interface, Interface to the XML parser TinyXML.
      
      -- The following features have been disabled:
      
       * opencl-support, Enable just-in-time compiliation to CPUs and GPUs with OpenCL.
       * superscs-interface, Interface to QP solver SUPERSCS.
       * osqp-interface, Interface to QP solver OSQP.
       * dsdp-interface, Interface to the interior point SDP solver DSDP.
       * clang-interface, Interface to the Clang JIT compiler.
       * qpoases-interface, Interface to the active-set QP solver qpOASES.
       * blocksqp-interface, Interface to the NLP solver blockSQP.
       * cplex-interface, Interface to the QP solver CPLEX.
       * gurobi-interface, Interface to the (mixed-integer) QP solver GUROBI
       * knitro-interface, Interface to the NLP solver KNITRO.
       * snopt-interface, Interface to the NLP solver KNITRO.
       * worhp-interface, Interface to the NLP solver Worhp (requires gfortran, gomp).
       * lapack-interface, Interface to LAPACK.
       * mumps-interface, Interface to MUMPS.
       * spral-interface, Interface to SPRAL.
       * clp-interface, Interface to the LP solver CLP.
       * cbc-interface, Interface to the LP solver CBC.
       * ipopt-interface, Interface to the NLP solver Ipopt.
       * bonmin-interface, Interface to the MINLP framework Bonmin.
       * highs-interface, Interface to the MILP / QP solver HiGHS.
       * sleqp-interface, Interface to the NLP solver SLEQP.
       * alpaqa-interface, Interface to the NLP solver Alpaqa.
       * proxqp-interface, Interface to QP solver PROXQP.
       * ooqp-interface, Interface to the QP solver OOQP (requires BLAS and HSL libraries).
       * sqic-interface, Interface to the QP solver SQIC.
       * ampl-interface, Interface to the AMPL solver library.
       * slicot-interface, Interface to the controls library SLICOT.
      
      -- Configuring incomplete, errors occurred!
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/jg/wkd_9vqx7qlbdkrf0yw7hmtr0000gn/T/pip-install-vk9uci24/casadi_0c4bbd6e85c94d0ca9839c94b5dacf95/setup.py", line 104, in <module>
          setup(
        File "/Users/agriyakhetarpal/Desktop/casadi-pyodide/casadi-dev/lib/python3.11/site-packages/setuptools/__init__.py", line 103, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/agriyakhetarpal/Desktop/casadi-pyodide/casadi-dev/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
                 ^^^^^^^^^^^^^^^^^^
        File "/Users/agriyakhetarpal/Desktop/casadi-pyodide/casadi-dev/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/Users/agriyakhetarpal/Desktop/casadi-pyodide/casadi-dev/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/Users/agriyakhetarpal/Desktop/casadi-pyodide/casadi-dev/lib/python3.11/site-packages/setuptools/dist.py", line 963, in run_command
          super().run_command(command)
        File "/Users/agriyakhetarpal/Desktop/casadi-pyodide/casadi-dev/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/Users/agriyakhetarpal/Desktop/casadi-pyodide/casadi-dev/lib/python3.11/site-packages/wheel/bdist_wheel.py", line 368, in run
          self.run_command("build")
        File "/Users/agriyakhetarpal/Desktop/casadi-pyodide/casadi-dev/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/Users/agriyakhetarpal/Desktop/casadi-pyodide/casadi-dev/lib/python3.11/site-packages/setuptools/dist.py", line 963, in run_command
          super().run_command(command)
        File "/Users/agriyakhetarpal/Desktop/casadi-pyodide/casadi-dev/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/Users/agriyakhetarpal/Desktop/casadi-pyodide/casadi-dev/lib/python3.11/site-packages/setuptools/_distutils/command/build.py", line 131, in run
          self.run_command(cmd_name)
        File "/Users/agriyakhetarpal/Desktop/casadi-pyodide/casadi-dev/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/Users/agriyakhetarpal/Desktop/casadi-pyodide/casadi-dev/lib/python3.11/site-packages/setuptools/dist.py", line 963, in run_command
          super().run_command(command)
        File "/Users/agriyakhetarpal/Desktop/casadi-pyodide/casadi-dev/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/private/var/folders/jg/wkd_9vqx7qlbdkrf0yw7hmtr0000gn/T/pip-install-vk9uci24/casadi_0c4bbd6e85c94d0ca9839c94b5dacf95/setup.py", line 37, in run
          self.build_extension(ext)
        File "/private/var/folders/jg/wkd_9vqx7qlbdkrf0yw7hmtr0000gn/T/pip-install-vk9uci24/casadi_0c4bbd6e85c94d0ca9839c94b5dacf95/setup.py", line 76, in build_extension
          subprocess.check_call(
        File "/opt/homebrew/Cellar/python@3.11/3.11.7_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 413, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['cmake', '/private/var/folders/jg/wkd_9vqx7qlbdkrf0yw7hmtr0000gn/T/pip-install-vk9uci24/casadi_0c4bbd6e85c94d0ca9839c94b5dacf95', '-DSWIG_IMPORT=ON', '-DWITH_PYTHON=ON', '-DWITH_EXAMPLES=OFF', '-DPYTHON_INCLUDE_DIR=/Users/agriyakhetarpal/Desktop/casadi-pyodide/casadi-dev/include', '-DCMAKE_INSTALL_PREFIX=/private/var/folders/jg/wkd_9vqx7qlbdkrf0yw7hmtr0000gn/T/pip-install-vk9uci24/casadi_0c4bbd6e85c94d0ca9839c94b5dacf95/build/lib.macosx-14-arm64-cpython-311', '-DWITH_SELFCONTAINED=ON', '-DWITH_DEEPBIND=ON', '-DWITH_PYTHON3=ON']' returned non-zero exit status 1.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for casadi
  Running setup.py clean for casadi
Failed to build casadi
ERROR: Could not build wheels for casadi, which is required to install pyproject.toml-based projects
```

</p>
</details> 

and the relevant section looks to be:

```cmake
CMake Error at swig/python/CMakeLists.txt:32 (file):
        file STRINGS file
        "/Users/agriyakhetarpal/Desktop/casadi-pyodide/casadi-dev/include/patchlevel.h"
        cannot be read.
```

~~So I'm supposing that they upload the source distribution as a separate build procedure and do not compile the wheel in-place from it, but rather from the root directory~~

They do seem to be testing the installation from the source distribution in CI: https://github.com/casadi/casadi/blob/70f5cc19a288a1e753d06670060d2563aa63fafa/.github/workflows/binaries.yml#L131

**Comment by agriyakhetarpal** [comment]
> What happens if you clone it and run `python -m build .` in the source directory? Presumably you're saying that doesn't work?

I missed this comment – yes, this, as expected, doesn't work with the cloned GitHub repository and returns the error message: "does not appear to be a Python project: no `pyproject.toml` or `setup.py` is available"

**Comment by ryanking13** [comment]
> doesn't work with the cloned GitHub repository and returns the error message

What happens if you build from the sdist in the PyPI?

**Comment by agriyakhetarpal** [comment]
> What happens if you build from the sdist in the PyPI?

That scenario should be this one, as highlighted here in the comment above: https://github.com/pyodide/pyodide/issues/4551#issuecomment-1961777767

**Comment by ryanking13** [comment]
I see. Looking at the swig/python/CMakeLists.txt file, it seems that `PYTHON_INCLUDE_PATH` (or `PYTHON_INCLUDE_DIR)` is being entered with the wrong value: https://github.com/casadi/casadi/blob/70f5cc19a288a1e753d06670060d2563aa63fafa/swig/python/CMakeLists.txt#L37-L63

**Comment by agriyakhetarpal** [comment]
I just realised I missed this comment – I probably had way too many notifications last month :) Let me try revisiting it, thanks for the pointer!

**Comment by agriyakhetarpal** [comment]
> I think you need to overwrite it with the include dir under the xbuildenv, which will be under .pyodide-xbuildenv/xbuildenv/pyodide-root/cpython/installs/python-3.11.3/include/python3.11 (assuming that you are using pyodide-build 0.25.0)

> (I guess we need to make this add this path to pyodide config CLI)

@ryanking13, I was able to fix this inside the `setup.py` code. I'll open a separate issue to add `python_interp_include_dir` or something similar to the `pyodide config` CLI, which should point to where the xbuildenv stores the header files.
