### ISSUE TITLE
pyodide is not downloading

### ISSUE THREAD

**Issue by rdevrajsinh** [pyodide/pyodide#4582]
When i use pip install pyodide its showing like this
Collecting pyodide
  Using cached pyodide-0.0.2.tar.gz (19 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

**Comment by agriyakhetarpal** [comment]
Hi @rdevrajsinh, this looks like you are downloading `pyodide`, rather than `pyodide-build` – as noted in the instructions on https://pypi.org/project/pyodide/.

The correct command should be `pip install pyodide-build`.

**Comment by hoodmane** [comment]
We should try to improve the error message that happens if you do `pip install pyodide`, to mention `pyodide-py` and `pyodide-build` as possible alternatives. Also, I wonder if we could get our message into a more obvious spot:
```
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [7 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-3fm0rbiq/pyodide_140df28c134c42308530538f335e130b/setup.py", line 7, in <module>
          raise ValueError(
      ValueError: Pyodide is a Python distribution that runs in the browser or Node.js. It cannot be installed from PyPi.
                  See https://github.com/pyodide/pyodide for how to use Pyodide.

```

**Comment by hoodmane** [comment]
I like something like this a bit better since it doesn't have the traceback:

<details><summary>setup.py</summary>
<p>

```py
# The very first thing we do is give a useful error if someone is
# running this code under Python 3.
import sys
msg = "You're trying to run a very old release of Beautiful Soup under Python 3. This will not work."
print("\n", file=sys.stdout)
print("="*len(msg), file=sys.stdout)
print("", file=sys.stdout)
print(msg, file=sys.stdout)
print("", file=sys.stdout)
print("="*len(msg), file=sys.stdout)
print("\n", file=sys.stdout)

import sys
sys.exit(1)
```


</p>
</details> 


<details><summary>Output</summary>

```
Processing /home/hood/Documents/programming/tmp/pip-intentional-install-error
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [9 lines of output]
      
      
      =============================================================================================
      
      You're trying to run a very old release of Beautiful Soup under Python 3. This will not work.
      
      =============================================================================================
      
      
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

<p>



</p>
</details>

**Comment by hoodmane** [comment]
@henryiii do you have an opinion about the best way to make `pip install wrong_thing` print instructions to install something else instead?

**Comment by agriyakhetarpal** [comment]
> I like something like this a bit better since it doesn't have the traceback:

Interesting! It makes the message neater, but this will still break the creation of the SDist (though that shouldn't matter if the package is simply meant to be a "lodestar" project on PyPI).

The SDist could be created manually or by checking for environment variables or pretty much any way else.

**Comment by henryiii** [comment]
You should throw SystemExit(n) (n!=0) in setup.py to get a nice (no) traceback from pip. (Or whatever build script your backend uses, this is assuming setuptools)

**Comment by rdevrajsinh** [comment]
Thank you Agriya -build one worked
