### ISSUE TITLE
ERROR: Pyodide already fatally failed and can no longer be used.

### ISSUE THREAD

**Issue by rajubish** [pyodide/pyodide#4621]
## 🐛 Bug
We have configured n8n workflow with python. While execution time of workflow getting below error.

Error: Pyodide already fatally failed and can no longer be used.
    at Object.get [as runPythonAsync] (/usr/lib/node_modules/n8n/node_modules/pyodide/pyodide.asm.js:9:103459)
    at PythonSandbox.runCodeInPython (/usr/lib/node_modules/n8n/node_modules/n8n-nodes-base/nodes/Code/PythonSandbox.ts:62:18)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at PythonSandbox.runCodeAllItems (/usr/lib/node_modules/n8n/node_modules/n8n-nodes-base/nodes/Code/PythonSandbox.ts:47:27)
    at Object.execute (/usr/lib/node_modules/n8n/node_modules/n8n-nodes-base/nodes/Code/Code.node.ts:135:14)
    at Workflow.runNode (/usr/lib/node_modules/n8n/node_modules/n8n-workflow/src/Workflow.ts:1332:8)
    at /usr/lib/node_modules/n8n/node_modules/n8n-core/src/WorkflowExecute.ts:1046:29
    at /usr/lib/node_modules/n8n/node_modules/n8n-core/src/WorkflowExecute.ts:1722:11

**Comment by ryanking13** [comment]
Thanks for raising the issue, but it doesn't give us any information other than "an error occurred". If you could provide us with some minimal code to reproduce the issue, we might be able to test it.
