### ISSUE TITLE
Deno -- attempt to write to file in NODEFS results in `raw write() returned invalid length`

### ISSUE THREAD

**Issue by JanPokorny** [pyodide/pyodide#4647]
## 🐛 Bug

When running in Deno and using NODEFS to mount files, attepting to write a file results in error `raw write() returned invalid length`.

### To Reproduce

Save as `test.ts` and run using `deno run --allow-read --allow-write --allow-net test.ts`:
```js
import pyodideModule from "npm:pyodide/pyodide.js"

await Deno.writeTextFile("test_deno.txt", "Hello, World!")

const pyodide = await pyodideModule.loadPyodide()

pyodide.setStdout()
pyodide.setStderr()

pyodide.FS.mkdir("/test")
pyodide.FS.mount(pyodide.FS.filesystems.NODEFS, { root: "." }, "/home/pyodide")

await pyodide.runPythonAsync("from pathlib import Path; Path('test_pyodide.txt').write_text('Hello, World!')");
```

This will result in creation of files `test_deno.txt` and `test_pyodide.txt`. While `test_deno.txt` will have the expected content, `test_pyodide.txt` will be empty, and the program will produce the following error:

```
error: Uncaught (in promise) PythonError: OSError: raw write() returned invalid length 2831100 (should have been between 0 and 13)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/lib/python311.zip/_pyodide/_base.py", line 573, in eval_code_async
    await CodeRunner(
  File "/lib/python311.zip/_pyodide/_base.py", line 393, in run_async
    coroutine = eval(self.code, globals, locals)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<exec>", line 1, in <module>
  File "/lib/python311.zip/pathlib.py", line 1078, in write_text
    with self.open(mode='w', encoding=encoding, errors=errors, newline=newline) as f:
OSError: raw write() returned invalid length 9188352 (should have been between 0 and 13)

    at new_error (file:///Users/jp/Library/Caches/deno/npm/registry.npmjs.org/pyodide/0.25.0/pyodide.asm.js:9:10014)
    at <anonymous> (wasm://wasm/02257296:1:1412707)
    at <anonymous> (wasm://wasm/02257296:1:1441695)
    at _PyEM_TrampolineCall_JS (file:///Users/jp/Library/Caches/deno/npm/registry.npmjs.org/pyodide/0.25.0/pyodide.asm.js:9:120166)
    at <anonymous> (wasm://wasm/02257296:1:1717397)
    at <anonymous> (wasm://wasm/02257296:1:2663102)
    at <anonymous> (wasm://wasm/02257296:1:1983263)
    at <anonymous> (wasm://wasm/02257296:1:1718654)
    at <anonymous> (wasm://wasm/02257296:1:1719359)
    at <anonymous> (wasm://wasm/02257296:1:1719521)
    at <anonymous> (wasm://wasm/02257296:1:2525605)
    at <anonymous> (wasm://wasm/02257296:1:2549761)
    at <anonymous> (wasm://wasm/02257296:1:1719817)
    at <anonymous> (wasm://wasm/02257296:1:1718937)
    at <anonymous> (wasm://wasm/02257296:1:1439596)
    at Object.Module.callPyObjectKwargs (file:///Users/jp/Library/Caches/deno/npm/registry.npmjs.org/pyodide/0.25.0/pyodide.asm.js:9:64297)
    at Object.Module.callPyObject (file:///Users/jp/Library/Caches/deno/npm/registry.npmjs.org/pyodide/0.25.0/pyodide.asm.js:9:65365)
    at Timeout.wrapper [as _onTimeout] (file:///Users/jp/Library/Caches/deno/npm/registry.npmjs.org/pyodide/0.25.0/pyodide.asm.js:9:32855)
    at cb (ext:deno_node/internal/timers.mjs:64:31)
    at eventLoopTick (ext:core/01_core.js:204:13)
```

### Expected behavior

Both files should contain `Hello, world!` with no error.

### Environment

- Pyodide Version: 0.25.0
- Browser version: deno 1.41.3
- Any other relevant information: Running on M2 Mac, but also managed to reproduce on Repl.it, so it might not be OS-related.

**Comment by ryanking13** [comment]
Thanks for the report! What happens if you run the same code with Node.js?

If it runs fine in Node.js environment, the problem would be caused by some incompatibility between Deno and Node.js. But since the implementation of NODEFS is [from emscripten](https://github.com/emscripten-core/emscripten/blob/main/src/library_nodefs.js), probably you can open an issue in Emscripten to get a better answer.

**Comment by hoodmane** [comment]
I think I ran into an issue like this when I was using Pyodide in Deno a year ago. I think the problem was that the Deno Node shims were not quite right -- the read() command is right but the `write()` command has some unexpected differences.

**Comment by JanPokorny** [comment]
@ryanking13 The same code (with just the import and filename adjusted) works correctly in Node.js.

**Comment by JanPokorny** [comment]
Upstream reported fixed.
