### ISSUE TITLE
request to add Boto3

### ISSUE THREAD

**Issue by cosmosanalytics** [pyodide/pyodide#4731]
## 🐍 Package Request

- Package Name and Version : boto3 1.34.95
- Package URL : https://pypi.org/project/boto3/
- Package Dependencies that needs to be resolved first:
- 
![image](https://github.com/pyodide/pyodide/assets/100080151/799a2105-29df-468a-9798-9edec0748c99)

But when I import boto3 in pyscript, it no longer can run.

**Comment by cosmosanalytics** [comment]
when I add "boto3" in the package list in pyscript, it does not install
![image](https://github.com/pyodide/pyodide/assets/100080151/5e91939d-fc04-4086-9214-3ff13049f4eb)

**Comment by JamesParrott** [comment]
Boto and its sub projects use threading, sockets and urllib3, so it's unlikely to be smooth and I imagine it would be a big job even if it didn't require managing other known issues.

https://pyodide.org/en/stable/usage/wasm-constraints.html#synchronous-http-requests-support

**Comment by cosmosanalytics** [comment]
I am thinking invoking aws sagemaker endpoint in pyscript by using boto3.

If boto3 is difficult to install in web browser, I can just use request to
call aws api, at the same time, translate aws sagemaker endpoint to api.

Do you have an example for this?

**Comment by JamesParrott** [comment]
I do not.  I'm just estimating what the original idea requires from a Pyodide contributor, and managing your expectations.

**Comment by rickdelpo1** [comment]
when I import boto3 into pyscript i get the following error

 File "/lib/python3.12/site-packages/botocore/httpsession.py", line 22, in <module>
    from urllib3.util.ssl_ import (
ImportError: cannot import name 'ssl' from 'urllib3.util.ssl_' (/lib/python3.12/site-packages/urllib3/util/ssl_.py)

**Comment by ryanking13** [comment]
@rickdelpo1 Please do `await pyodide.loadPackage("ssl")` before loading boto3. We unvendor SSL package to reduce the size of the distribution ([ref](https://pyodide.org/en/stable/usage/wasm-constraints.html#optional-modules))

**Comment by rickdelpo1** [comment]
thanks @ryanking13 but I am not sure where to put this line of code u are recommending
here is my code
```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://pyscript.net/releases/2024.6.1/core.css">
    <script type="module" src="https://pyscript.net/releases/2024.6.1/core.js"></script>
    <py-config>packages = ["boto3"]</py-config>
</head>
<body>
        <script type="py" async>
        from datetime import datetime
        from time import sleep
        import json
        import boto3
        from pyscript import fetch
        async def get_data():
            await pyodide.loadPackage("ssl")  #this is the boto3 fix ??? not sure where to put this line ?????
            i = 1
            time=1
            while i < 3:
                response = await fetch('https://xxxxxxxxapikey=xxxx')
                jsonData = await response.json()
                res = [ i["price"] for i in jsonData ]
                s = ''.join(str(x) for x in res) #convert list to string
                print(s,time)
                sleep(31)
                i = i+1
                time=time+1
                print ("while loop finished")
            await get_data()
        </script>
</body>
</html>
```

**Comment by ryanking13** [comment]
`await pyodide.loadPackage("ssl")` is a javascript code. In python, the equivalent thing can be done using

```python
import micropip
await micropip.install("ssl")
```

or as you are using pyscript, I believe putting it under <py-config> would work too.

```
<py-config>packages = ["boto3", "ssl"]</py-config>
```

**Comment by rickdelpo1** [comment]
@ryanking13 , I took your advice and now boto3 loads but I get a connection error, see comments below. Here is my full code
```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>run pyscript</title>
    <link rel="stylesheet" href="https://pyscript.net/releases/2024.6.1/core.css">
    <script type="module" src="https://pyscript.net/releases/2024.6.1/core.js"></script>
    <py-config>packages = ["boto3", "ssl"]</py-config>
</head>
<body>
        <script type="py" async>
        from datetime import datetime
        from time import sleep
        import json
        import micropip  #added this
        await micropip.install("ssl") #added this, looks like perhaps this is a special pyodide ssl module
                                          # We unvendor SSL package to reduce the size of the distribution per Gyeongjae Choi / ryanking13
        import boto3  #boto3 does not import without above
        from pyscript import fetch
        async def get_data():
            i = 1
            time=1
            while i < 3:
                resp = await fetch('https://fxxxxxxxxxxxxxxxxxxxxxxx')
                jsonData = await resp.json()
                res = [ i["price"] for i in jsonData ]
                s = ''.join(str(x) for x in res)  #convert list to string
                print(s,time)
                #above fetch is returning data correctly, below connection attempt throws error
                s3 = boto3.client(
                    service_name='s3',
                    region_name='us-east-2',
                    aws_access_key_id='xxxxxxxxxxxxxxxxx',
                    aws_secret_access_key='xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
                )
                response= s3.get_object(Bucket='rickd', Key='tracker.json')
                content = response['Body']
                list = json.loads(content.read())
                list.append({"price":s,"time":time,"symbol":"AMD"})
                s3.put_object(Bucket='rickd', Key='tracker.json', ContentType ='text/html', Body=json.dumps(list).encode())    
                sleep(31) #run every 31 seconds
                i = i+1
                time=time+1
            print ("while loop finished")
        await get_data()
        </script>

<!--
first I am getting below  6 lines without an error

Loading micropip, packaging                                     pyodide.asm.js:10
Loaded micropip, packaging                                      pyodide.asm.js:10
Loading openssl, python-dateutil, six, ssl, urllib3       pyodide.asm.js:10
Loaded openssl, python-dateutil, six, ssl, urllib3        pyodide.asm.js:10
ssl already loaded from default channel                     pyodide.asm.js:10
No new packages to load                                           pyodide.asm.js:10

   this part of above raises a flag on my end
ssl already loaded from default channel
No new packages to load

it concerns me because I thought the micropip ssl is suppossed to override (unvendor the SSL package) the default ssl ???

below, looks like urllib3 is unhappy
    with some research I found this
Networking in Python does not work, since it relies on low-level networking primitives (socket) that aren't allowed in the browser sandbox.
So, although urllib3 is present in Pyodide, it can't actually connect to anything.

can we connect using this as a workaround??? pyodide.open_url() with pyodide.http.pyfetch ??
see this link https://www.bentasker.co.uk/posts/blog/software-development/monkeying-about-with-pyodide-and-pyscript.html

Traceback (most recent call last):
  File "/lib/python3.12/site-packages/urllib3/connection.py", line 198, in _new_conn
    sock = connection.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.12/site-packages/urllib3/util/connection.py", line 85, in create_connection
    raise err
  File "/lib/python3.12/site-packages/urllib3/util/connection.py", line 67, in create_connection
    _set_socket_options(sock, socket_options)
  File "/lib/python3.12/site-packages/urllib3/util/connection.py", line 100, in _set_socket_options
    sock.setsockopt(*opt)
OSError: [Errno 50] Protocol not available

The above exception was the direct cause of the following exception:

several more lines
then this one happens

 File "/lib/python3.12/site-packages/botocore/retryhandler.py", line 416, in _check_caught_exception
    raise caught_exception
  File "/lib/python3.12/site-packages/botocore/endpoint.py", line 281, in _do_get_response
    http_response = self._send(request)
                    ^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.12/site-packages/botocore/endpoint.py", line 377, in _send
    return self.http_session.send(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.12/site-packages/botocore/httpsession.py", line 493, in send
    raise EndpointConnectionError(endpoint_url=request.url, error=e)
botocore.exceptions.EndpointConnectionError: Could not connect to the endpoint URL: "https://rickd.s3.us-east-2.amazonaws.com/tracker.json"

my opinion
I think the pyscript browser virtual machine does not provide APIs to open sockets. All network I/O must go thru APIs provided by the browser. So is there a workaround for this?

-->

</body>
</html>
```

**Comment by ryanking13** [comment]
> I think the pyscript browser virtual machine does not provide APIs to open sockets. All network I/O must go thru APIs provided by the browser.

Yes, this is the exact reason for the failure.

> So is there a workaround for this?

@joemarshall contributed to the urllib3 side to make some simple requests work in the Pyodide environment ([doc](https://github.com/urllib3/urllib3/blob/79a2a30f06b61127dc138158b82ffa791ab16733/docs/reference/contrib/emscripten.rst#pyodide-emscripten-and-pyscript)). But I think it will only work for straightforward cases that do low-level socket operations. So I can't say Yes or No because I don't know about boto3 in detail. But it would be worth to experiment.

**Comment by rickdelpo1** [comment]
@ryanking13 and @joemarshall , thanks very much for continuing this thread. My use case is very simple. All that is needed is to connect to an s3 bucket in AWS to store and update a json file. I have this working in plain js, python and in aws Lambda. My ultimate goal is to offload several of my Lambdas to pyscript because I don't need all the overhead over on the Lambda side. The specific app I am working on is a stock market app. Plain JS has allowed network connections for years so why not Pyscript for this? I am only using the most simplest part of boto3 here.

**Comment by hoodmane** [comment]
The problem in your traceback seems to be that urllib3 connection pools don't work in Pyodide. We'll need a custom implementation that just ignores the pool.

**Comment by SNagarajan2243** [comment]
> The problem in your traceback seems to be that urllib3 connection pools don't work in Pyodide. We'll need a custom implementation that just ignores the pool.

@hoodmane Ah, I see — thanks for the clarification! I initially thought the issue might be related to botocore, but it makes more sense now that it’s tied to urllib3 and how its connection pooling behaves in Pyodide. Appreciate the insight!

If you have any suggestions on how to approach the custom implementation (or can point me to any prior work), I’d really appreciate your guidance.
