### ISSUE TITLE
Error when loading bundled python packages using Pyodide from NPM

### ISSUE THREAD

**Issue by elibdev** [pyodide/pyodide#4815]
## 🐛 Bug

Loading a bundled python package (e.g. `requests`) from Pyodide distributed through NPM in a Vite app fails and throws an error. Loading via `loadPyodide({ packages: ["requests"] })` or `pyodide.loadPackage(["requests"])` both result in the same error.

### To Reproduce

I created a minimal self-contained project to reproduce this error: https://github.com/elibdev/vite-pyodide-requests

If you run `npm run dev` in that repo and visit http://localhost:5173/ you should see the following errors in the console:

![Screenshot 2024-05-28 at 19 38 32](https://github.com/pyodide/pyodide/assets/4471727/ce227ec6-ab3a-4529-a5dd-491396c20fef)

I also tried disabling integrity checks but that resulted in a different error, and I think ideally the integrity checks wouldn't need to be disabled.

There is a line in `vite.config.js` that prevents Vite from touching the pyodide distribution so I don't think the error is caused by Vite itself.

```ts
export default defineConfig({
  plugins: [vue()],
  optimizeDeps: { exclude: ["pyodide"] },  // <-- This should prevent vite from messing with the pyodide distribution.
});
```

### Expected behavior

The built-in packages should load without error and with successful integrity checks.

### Environment

- Pyodide Version: 0.26.0
- Browser version: Chrome 125.0.6422.77 (Official Build) (arm64) 
- Any other relevant information:

I am using the Pyodide NPM distribution in a Vite project here: https://github.com/elibdev/vite-pyodide-requests

### Additional context

I would be happy to test different scenarios and help with debugging as much as possible.

**Comment by hoodmane** [comment]
@pauleveritt we have a bunch of issues asking about vite support and we're not really sure what to do with them. You know anyone who can help?

**Comment by pauleveritt** [comment]
Sure, give me a nudge on any issues that mention Vite.

On this, I was also able to reproduce in Firefox also. As a note, I had [a long series about Pyodide+Vite](https://pyodide-components.readthedocs.io/en/latest/). We can try working through it until something breaks. Looks like bundling has changed in some way.

**Comment by pauleveritt** [comment]
@elibdev I think you covered the same ground I did in this [step of my tutorial](https://pyodide-components.readthedocs.io/en/latest/downloader.html).

**Comment by CNSeniorious000** [comment]
@elibdev I came into the same problem when I tried using pyodide with vite. In fact the npm library is only the bootstrap part of pyodide, and it's recommended to set the `indexURL` to the [official CDN](https://pyodide.org/en/stable/usage/downloading-and-deploying.html#cdn) of full pyodide assets.

If you want to self-host these assets, I came into the same situation as yours again. Here are 3 approachs that I had tried:
1. If you deploys your vite app on Vercel/Netlify/Cloudflare, you can use a single line in the `_redirects` file to rewrites all GET requests for pyodide assets to the official CDN. For me I usually use `/pyodide/*`
2. You can also download the tar bundle from GitHub in your `postInstall` script, and extract it into the static assets folder. I think this is @pauleveritt's approach
3. I don't want to code these download scripts inside my frontend project, or think the time cost is too much (and downloading the same file for each build is not best practice. So I finally built [a CDN for pyodide assets](https://promplate-cdn.onrender.com/pyodide/v0.26.0/console.html) myself. It is [simply list out all the pyodide's releases and download them all](https://github.com/promplate/cdn/blob/ccbcf050808888af3513623b5848b005c08775e9/main.py). You can deploy that in whatever static site hosts you like. For me, I deployed one on Netlify and another on Render. It only need to be rerun everytime pyodide creates a new release. And I recommend setting indexURL from an env to provide max flexibility

**Comment by CNSeniorious000** [comment]
I just came up with an idea that publishing the full pyodide build assets bundle to npm as a separate package (maybe naming `pyodide-full` or `@pyodide/full`) may perfectly solve this problem.

**Comment by ilopezdeaudikana** [comment]
@elibdev I am afraid that your example doesn't work, or at least not fully. If you run the `dev` script you get to see the result on the console. But running `preview` leads to a type error

> Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'invalidate_caches')
    at loadPackage (pyodide.asm.js:10:95784)
    at async initializePackageIndex (pyodide.asm.js:10:91565)
