### ISSUE TITLE
NumPy: `numpy.linalg.LinAlgError` not thrown

### ISSUE THREAD

**Issue by henryiii** [pyodide/pyodide#4859]
## 🐛 Bug

The following code:

```python
import numpy as np

A = np.array([[1,-2j],[2j,5]])
print(np.linalg.cholesky(A))

B = np.array([[1,3],[2,4]])
np.linalg.cholesky(B)
```

Produces an error on normal CPython, just like the [docs state it should](https://numpy.org/doc/stable/reference/generated/numpy.linalg.cholesky.html).

```pytb
[[1.+0.j 0.+0.j]
 [0.+2.j 1.+0.j]]
Traceback (most recent call last):
  File "/Users/henryschreiner/git/webpages/iscinumpy.gitlab.io/np.py", line 7, in <module>
    np.linalg.cholesky(B)
  File "/usr/local/lib/python3.12/site-packages/numpy/linalg/linalg.py", line 779, in cholesky
    r = gufunc(a, signature=signature, extobj=extobj)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/numpy/linalg/linalg.py", line 115, in _raise_linalgerror_nonposdef
    raise LinAlgError("Matrix is not positive definite")
numpy.linalg.LinAlgError: Matrix is not positive definite
```

Pyodide does not get the exception, though, and instead just sets NaN's.

### To Reproduce

On https://pyodide.org/en/stable/console.html

```pycon
>>> import numpy as np
>>> A = np.array([[1,-2j],[2j,5]])
>>> print(np.linalg.cholesky(A))
[[1.+0.j 0.+0.j]
 [0.+2.j 1.+0.j]]
>>> B = np.array([[1,3],[2,4]])
>>> np.linalg.cholesky(B)
array([[nan, nan],
       [nan, nan]])
```

The same code produces an error outside a pyodide.

### Expected behavior

It should throw `numpy.linalg.LinAlgError`.

### Additional context

See https://github.com/scikit-hep/iminuit/pull/995, this is breaking iminuit's test suite.

**Comment by hoodmane** [comment]
Unfortunately, I think this is very hard for us to fix without webassembly getting support for floating point exception modes. This would require a whole process with the wasm committees. Probably someone should inquire whether it's a change they'd consider...

**Comment by henryiii** [comment]
Maybe NumPy should check for NaN in situations like this if running on WASM?

**Comment by lesteve** [comment]
Just for explicitness:
- `np.linalg.cholesky` uses `np.errstate`. Inside Pyodide `np.errstate` (or `np.seterr`) will never raise an exception because of lack of floating point exception support in webassembly. This was noted in https://github.com/pyodide/pyodide/issues/156 for example. I have seen cases  where `np.errstate` + try/catch is used for control flow and you sometimes end-up in a very confusing code branch.
- here is the canonical link to the numpy comment about floating point exception in webassembly https://github.com/numpy/numpy/pull/21895#issuecomment-1311525881

**Comment by lesteve** [comment]
As a potential work-around (probably not applicable in iminuit but maybe useful in other cases) `scipy.linalg.cholesky` does raise an exception on the same data inside Pyodide:


```
>>> import numpy as np
A = np.array([[1,-2j],[2j,5]])
print(np.linalg.cholesky(A))
B = np.array([[1,3],[2,4]])
np.linalg.cholesky(B)
[[1.+0.j 0.+0.j]
 [0.+2.j 1.+0.j]]
array([[nan, nan],
       [nan, nan]])
>>> import scipy.linalg
>>> scipy.linalg.cholesky
<function cholesky at 0x25dbaa0>
>>> scipy.linalg.cholesky(B)
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/lib/python3.12/site-packages/scipy/linalg/_decomp_cholesky.py", line 88, in cholesky
    c, lower = _cholesky(a, lower=lower, overwrite_a=overwrite_a, clean=True,
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.12/site-packages/scipy/linalg/_decomp_cholesky.py", line 36, in _cholesky
    raise LinAlgError("%d-th leading minor of the array is not positive "
numpy.linalg.LinAlgError: 2-th leading minor of the array is not positive definite
```

**Comment by agriyakhetarpal** [comment]
I have noticed the same problem when running the test suite for `statsmodels` and xfailed for now: https://github.com/statsmodels/statsmodels/pull/9270

**Comment by agriyakhetarpal** [comment]
This will be fixed in NumPy 2.6, via https://github.com/numpy/numpy/pull/32036.
