### ISSUE TITLE
Typer: got an unexpected keyword argument 'rich_markup_mode'

### ISSUE THREAD

**Issue by elmurci** [pyodide/pyodide#4879]
## 🐛 Bug

When I install `pyodide-build` I can see the following warning:

```
WARNING: typer 0.12.3 does not provide the extra 'all'
```

If I run `pyodide` on the console right after installing, I get:

```
% pyodide
Traceback (most recent call last):
  File "/opt/homebrew/bin/pyodide", line 5, in <module>
    from pyodide_cli.__main__ import main
  File "/opt/homebrew/lib/python3.12/site-packages/pyodide_cli/__main__.py", line 1, in <module>
    from .app import main
  File "/opt/homebrew/lib/python3.12/site-packages/pyodide_cli/app.py", line 11, in <module>
    app = typer.Typer(
          ^^^^^^^^^^^^
TypeError: Typer.__init__() got an unexpected keyword argument 'rich_markup_mode'
```

**Comment by ryanking13** [comment]
Thanks for the report. It seems like typer removed extra `all` instead they now have `standard`.

I am not sure about the `rich_markup_mode` though. Could you show the result of `pip freeze` in your local environment?

**Comment by elmurci** [comment]
```
annotated-types==0.7.0
anyio==4.4.0
auditwheel_emscripten==0.0.15
bottle==0.12.25
build==1.2.1
certifi @ file:///private/tmp/certifi-20240307-4874-p3lgkm/certifi-2024.2.2
charset-normalizer==3.3.2
click==8.1.7
cloudpickle==3.0.0
cmake==3.29.5.1
colorama==0.4.6
commonmark==0.9.1
conan==1.62.0
distlib==0.3.8
fasteners==0.19
filelock==3.15.1
h11==0.14.0
httpcore==1.0.5
httpx==0.27.0
idna==3.7
Jinja2==3.1.4
leb128==1.0.7
loky==3.4.1
markdown-it-py==3.0.0
MarkupSafe==2.1.5
mdurl==0.1.2
node-semver==0.6.1
packaging==24.1
patch-ng==1.17.4
platformdirs==4.2.2
pluginbase==1.0.1
protobuf==4.25.1
pydantic==2.7.4
pydantic_core==2.18.4
Pygments==2.18.0
PyJWT==2.8.0
pyodide-cli==0.2.3
pyodide-lock==0.1.0a6
pyodide-pack==0.2.0
pyproject_hooks==1.1.0
python-dateutil==2.9.0.post0
PyYAML @ file:///private/tmp/pyyaml-20231018-5457-utbrds/PyYAML-6.0.1
requests==2.31.0
resolvelib==1.0.1
rich==12.3.0
ruamel.yaml==0.18.6
ruamel.yaml.clib==0.2.8
shellingham==1.5.4
six==1.16.0
sniffio==1.3.1
tqdm==4.66.4
typer==0.4.2
types-requests==2.32.0.20240602
typing_extensions==4.12.2
unearth==0.15.4
urllib3==1.26.19
virtualenv==20.26.2
```

**Comment by ryanking13** [comment]
> typer==0.4.2

So it seems like the recent version of typer is not installed because of extra requirements. I think you can do `pip install typer --upgrade` as a workaround. I'll fix the warning soon.
