### ISSUE TITLE
Issue with Pickle in 0.26.1

### ISSUE THREAD

**Issue by dmmiller** [pyodide/pyodide#4887]
## 🐛 Bug

I am using python 3.12.1 (installed from python.org) to pickle a Trie and then via pyscript (2024.6.2) which uses pyodide (0.26.1) in a background worker trying to pickle.load the Trie from the binary file and it fails with this error :

`ModuleNotFoundError: No module named 'public'`

### To Reproduce

In a python script on my laptop 
```
    with open(outFile, 'wb') as out:
        pickle.dump(trie, out)
```

In a python script running pyodide in my browser

```
def loadTrie(file: str) -> Trie:
    with open(file, 'rb') as f:
        trie = cast(Trie, pickle.load(f))
        return trie
```

The Trie class is
```
class Trie:
    def __init__(self):
        self.root = TrieNode()

class TrieNode:
    def __init__(self):
        self.terminal = False
        self.children = {}

```

### Expected behavior

I would expect the object to load given the same version of python is used to pickle the object.
Instead I see the following error:
```
PythonError: Traceback (most recent call last):
  File "/lib/python312.zip/_pyodide/_base.py", line 502, in eval_code
    .run(globals, locals)
     ^^^^^^^^^^^^^^^^^^^^
  File "/lib/python312.zip/_pyodide/_base.py", line 340, in run
    coroutine = eval(self.code, globals, locals)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<exec>", line 7, in <module>
  File "/home/pyodide/filters/word.py", line 25, in <module>
    trie = loadTrie("./bin/words.bin")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pyodide/filters/word.py", line 22, in loadTrie
    trie = cast(Trie, pickle.load(f))
                      ^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'public'

    at new_error (pyodide.asm.js:10:9965)
    at pyodide.asm.wasm:0x16dbfd
    at pyodide.asm.wasm:0x16dcc3
    at Module._pythonexc2js (pyodide.asm.js:10:700547)
    at callPyObjectKwargs (pyodide.asm.js:10:64179)
    at Proxy.callKwargs (pyodide.asm.js:10:81684)
    at Object.runPython (pyodide.asm.js:10:107372)
    at Mt (b04dfc32-b8c2-43d4-9d33-7b68b9378983:2:13637)
    at Object.run (b04dfc32-b8c2-43d4-9d33-7b68b9378983:2:25003)
    at Object.run (b04dfc32-b8c2-43d4-9d33-7b68b9378983:2:32238)
    at b04dfc32-b8c2-43d4-9d33-7b68b9378983:2:33252
```

### Environment

- Pyodide Version : 0.26.1 (via pyscript)
- Browser version : Chrome 124.0.6367.118
- Any other relevant information:
-- I use python 3.12.1 on my laptop to call the pickle code `3.12.1 (v3.12.1:2305ca5144, Dec  7 2023, 17:23:38) [Clang 13.0.0 (clang-1300.0.29.30)]`
-- On the browser, pyodide reports the version of python as `3.12.1 (main, Jun  7 2024, 22:40:30) [Clang 19.0.0git (https:/github.com/llvm/llvm-project 0a8cd1ed1f4f35905df318015b`

### Additional context

I am able to pickle and load a pickle in both the desktop version of python and also in pyodide as I long as I pickle and load in the same environment.  I am unable to do it if I pickle in one and load in the other.

I don't think the Trie code is relevant, but happy to share more if necesary.

**Comment by dmmiller** [comment]
I have realized the issue, thanks to help on the pyscript discord.

The problem was that I had imported the trie code slightly different ways and so in my script, it imported it as public.trie but in my worker code, it imported as trie.

This was user error.
