### ISSUE TITLE
Request to add the popular reportlab PDF generation package to pyodide

### ISSUE THREAD

**Issue by Code4SAFrankie** [pyodide/pyodide#4931]
## 🐍 Package Request

- Package Name and Version: reportlab / latest
- Package URL: https://files.pythonhosted.org/packages/08/69/1fadb986011de190d0a7c7df404e471b5ccd0d3d3df4b9bf095c29c22d21/reportlab-4.2.2-py3-none-any.whl
- Package Dependencies that needs to be resolved first:

## Checklists

- [Y] I have tried to install the package using `micropip.install(...)` and encountered the issue.
- [Y] I have read the [documentation](https://pyodide.org/en/stable/development/building-and-testing-packages.html) and tried building the package myself.

I would like to use the popular reportlab Python package to create PDF reports from my browser. This git seems to suggest that it is possible (although it does not make much sense to me): [https://gist.github.com/mbotsu/5d87dff8cf240062eda24e1af15ce92d](https://gist.github.com/mbotsu/5d87dff8cf240062eda24e1af15ce92d)

I tried to import reportlab (just like that and with pure Python wheel), but it gives me this error when running with the example code below and Edge browser:

```
pyodide.asm.js:10  Uncaught (in promise) PythonError: Traceback (most recent call last):
  File "/lib/python3.12/site-packages/packaging/requirements.py", line 35, in __init__
    parsed = _parse_requirement(requirement_string)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.12/site-packages/packaging/_parser.py", line 64, in parse_requirement
    return _parse_requirement(Tokenizer(source, rules=DEFAULT_RULES))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.12/site-packages/packaging/_parser.py", line 82, in _parse_requirement
    url, specifier, marker = _parse_requirement_details(tokenizer)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.12/site-packages/packaging/_parser.py", line 126, in _parse_requirement_details
    marker = _parse_requirement_marker(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.12/site-packages/packaging/_parser.py", line 147, in _parse_requirement_marker
    tokenizer.raise_syntax_error(
  File "/lib/python3.12/site-packages/packaging/_tokenizer.py", line 165, in raise_syntax_error
    raise ParserSyntaxError(
packaging._tokenizer.ParserSyntaxError: Expected end or semicolon (after name and no valid version specifier)
    file://D:EBackupWorkPythonpyodide
eportlab-4.2.2dist
eportlab-4.2.2-py3-none-any.whl
        ^

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/lib/python3.12/site-packages/micropip/_commands/install.py", line 142, in install
    await transaction.gather_requirements(requirements)
  File "/lib/python3.12/site-packages/micropip/transaction.py", line 55, in gather_requirements
    await asyncio.gather(*requirement_promises)
  File "/lib/python3.12/site-packages/micropip/transaction.py", line 62, in add_requirement
    return await self.add_requirement_inner(Requirement(req))
                                            ^^^^^^^^^^^^^^^^
  File "/lib/python3.12/site-packages/packaging/requirements.py", line 37, in __init__
    raise InvalidRequirement(str(e)) from e
packaging.requirements.InvalidRequirement: Expected end or semicolon (after name and no valid version specifier)
    file://D:EBackupWorkPythonpyodide
eportlab-4.2.2dist
eportlab-4.2.2-py3-none-any.whl
        ^

    at new_error (pyodide.asm.js:10:9965)
    at pyodide.asm.wasm:0x16dbfd
    at pyodide.asm.wasm:0x177431
    at _PyEM_TrampolineCall_JS (pyodide.asm.js:10:125894)
    at pyodide.asm.wasm:0x1c2eaf
    at pyodide.asm.wasm:0x2c7c0f
    at pyodide.asm.wasm:0x20a884
    at pyodide.asm.wasm:0x1c359c
    at pyodide.asm.wasm:0x1c38ab
    at pyodide.asm.wasm:0x1c3929
    at pyodide.asm.wasm:0x29e95d
    at pyodide.asm.wasm:0x2a4f54
    at pyodide.asm.wasm:0x1c3a69
    at pyodide.asm.wasm:0x1c36d2
    at pyodide.asm.wasm:0x176a95
    at callPyObjectKwargs (pyodide.asm.js:10:64068)
    at Module.callPyObjectMaybePromising (pyodide.asm.js:10:65316)
    at wrapper (pyodide.asm.js:10:27006)
    at onGlobalMessage (pyodide.asm.js:10:101788)
```

Example code: 

```
<html>
<head>
<meta charset="utf-8" />
</head>
<body>
<script src="https://cdn.jsdelivr.net/pyodide/v0.26.1/full/pyodide.js"></script>
<script type="text/javascript">
async function main() {
    let pyodide = await loadPyodide();

    await pyodide.loadPackage([
        "micropip", "Pillow"
    ]);
    const micropip = pyodide.pyimport("micropip");
    await micropip.install('file://D:\EBackup\Work\Python\pyodide\reportlab-4.2.2\dist\reportlab-4.2.2-py3-none-any.whl');

    await pyodide.runPythonAsync(`

        from reportlab.pdfgen import canvas
        from reportlab.lib.pagesizes import A4, portrait
        from reportlab.pdfbase import pdfmetrics
        from reportlab.pdfbase.ttfonts import TTFont
        from reportlab.pdfbase.cidfonts import UnicodeCIDFont
        import base64
        import pyodide_js
        await pyodide_js.loadPackage('reportlab')

        FILENAME = 'HelloWorld.pdf'
        c = canvas.Canvas(FILENAME, pagesize=portrait(A4))

        font_size = 20
        #pdfmetrics.registerFont(UnicodeCIDFont('HeiseiMin-W3'))
        #c.setFont('HeiseiMin-W3', font_size)

        width, height = A4
        c.drawCentredString(width / 2, height / 2 - font_size * 0.4, 'Hello World')
        c.showPage()
        c.save()
    `)

    const fileName = pyodide.globals.get("FILENAME")
    const file = pyodide.FS.readFile(fileName, { encoding: "utf8" });
    const mimeString = "application/pdf";
    const blob = new Blob([file], { type: mimeString });
    const htmlElement = document.getElementById("download");
    htmlElement.innerText = "Download";
    htmlElement.download = fileName;
    htmlElement.href = window.URL.createObjectURL(blob);
}
main();
</script>
</body>
<a id="download" href="#"></a>
</html>
```

**Comment by Code4SAFrankie** [comment]
https://files.pythonhosted.org/packages/08/69/1fadb986011de190d0a7c7df404e471b5ccd0d3d3df4b9bf095c29c22d21/reportlab-4.2.2-py3-none-any.whl as the wheel url also does not work.

**Comment by agriyakhetarpal** [comment]
While we support all of the dependencies as listed in https://github.com/Distrotech/reportlab/blob/master/setup.py, the repository hasn't been updated in years and I'm not sure it supports an array of stable Python versions. The `reportlab` package has been uploaded to PyPI on June 25, 2024, plus it is pure Python, so I don't think I'm looking at the right repository, because the code seems to build extension modules. Maybe the package was taken over by the means of PEP 541 request or they made the extensions optional through optional dependencies? Could you offer more details on the source code, @Code4SAFrankie?

I think it should be easy to add the package, though. I can take it up soon. On PyPI, versions up to 3.X were the ones that offered compiled wheels, so the latest version makes it easy.

**Comment by Code4SAFrankie** [comment]
This is the project on pypi: https://pypi.org/project/reportlab/
Source code is here: https://files.pythonhosted.org/packages/72/e0/c88e58d38702cff7031dd47c9cdebb8503da5c9887470c2d5407a48dd507/reportlab-4.2.2.tar.gz

It probably has very few stars on github due to it being difficult to find the github for it, but other projects that use it has 1700 stars.

**Comment by Code4SAFrankie** [comment]
Changing my code to use this fixed the issue:

 ```
       import micropip
        await micropip.install("https://files.pythonhosted.org/packages/08/69/1fadb986011de190d0a7c7df404e471b5ccd0d3d3df4b9bf095c29c22d21/reportlab-4.2.2-py3-none-any.whl")


```

**Comment by agriyakhetarpal** [comment]
The wheel isn't very large at ~1.9MB, and we should be able to add it to the Pyodide in-tree list. Should we reopen this?

**Comment by Code4SAFrankie** [comment]
Sure
