### ISSUE TITLE
Micropi cannot find a pure Python 3 wheel fro google-cloud-storage

### ISSUE THREAD

**Issue by ClearSafety** [pyodide/pyodide#4970]
## 🐛 Bug

Trying to run a simple Python project in Flet, but that requires google-cloud-storage package. The app works in browser when running the .py file. But after converted to .html it stops working because micropi cannot find .whl file, even it's been there https://pypi.org/project/google-cloud-storage/#files

### To Reproduce

import flet as ft

def main(page: ft.Page):
    
    # Seu código do app aqui, por exemplo, importações e inicializações

    page.window.always_on_top=True
    page.bgcolor="#2A685A"  # Color grab from Clear Safety website
    page.adaptive=True
    page.title='Clear Safety: Approval Request'
    page.horizontal_alignment=ft.CrossAxisAlignment.CENTER
    page.vertical_alignment=ft.MainAxisAlignment.START
    page.padding=ft.padding.all(0)
    
    header = ft.Text(value='Hello World', size=50, color=ft.colors.WHITE)
    
    
    page.add(header)

ft.app(target=main, assets_dir='assets', upload_dir='assets/uploads')

### Expected behavior

Display a page in web. The example above does not have the usage of functions that requires google-cloud-storage.

### Environment

- Pyodide Version: do not know
- Browser version: Version 127.0.6533.72 (Official Build) (64-bit)
- Any other relevant information: I'm not using Pyodide in my code, but it is automatically called by Google Chome to install the dependencies.

### Additional context

Log in browser console:
Uncaught (in promise) PythonError: Traceback (most recent call last):
  File "/lib/python311.zip/_pyodide/_base.py", line 571, in eval_code_async
    await CodeRunner(
  File "/lib/python311.zip/_pyodide/_base.py", line 396, in run_async
    await coroutine
  File "<exec>", line 11, in <module>
  File "/lib/python3.11/site-packages/micropip/_commands/install.py", line 142, in install
    await transaction.gather_requirements(requirements)
  File "/lib/python3.11/site-packages/micropip/transaction.py", line 204, in gather_requirements
    await asyncio.gather(*requirement_promises)
  File "/lib/python3.11/site-packages/micropip/transaction.py", line 211, in add_requirement
    return await self.add_requirement_inner(Requirement(req))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/micropip/transaction.py", line 300, in add_requirement_inner
    await self._add_requirement_from_package_index(req)
  File "/lib/python3.11/site-packages/micropip/transaction.py", line 347, in _add_requirement_from_package_index
    await self.add_wheel(wheel, req.extras, specifier=str(req.specifier))
  File "/lib/python3.11/site-packages/micropip/transaction.py", line 385, in add_wheel
    await self.gather_requirements(wheel.requires(extras))
  File "/lib/python3.11/site-packages/micropip/transaction.py", line 204, in gather_requirements
    await asyncio.gather(*requirement_promises)
  File "/lib/python3.11/site-packages/micropip/transaction.py", line 208, in add_requirement
    return await self.add_requirement_inner(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/micropip/transaction.py", line 300, in add_requirement_inner
    await self._add_requirement_from_package_index(req)
  File "/lib/python3.11/site-packages/micropip/transaction.py", line 339, in _add_requirement_from_package_index
    wheel = find_wheel(metadata, req)
            ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/micropip/transaction.py", line 431, in find_wheel
    raise ValueError(
ValueError: Can't find a pure Python 3 wheel for 'google-crc32c<2.0dev,>=1.0'.
See: https://pyodide.org/en/stable/usage/faq.html#why-can-t-micropip-find-a-pure-python-wheel-for-a-package
You can use `await micropip.install(..., keep_going=True)` to get a list of all packages with missing wheels.

    at new_error (pyodide.asm.js:9:12519)
    at pyodide.asm.wasm:0x158827
    at pyodide.asm.wasm:0x15fcd5
    at _PyCFunctionWithKeywords_TrampolineCall (pyodide.asm.js:9:123052)
    at pyodide.asm.wasm:0x1a3091
    at pyodide.asm.wasm:0x289e4d
    at pyodide.asm.wasm:0x1e3f77
    at pyodide.asm.wasm:0x1a3579
    at pyodide.asm.wasm:0x1a383a
    at pyodide.asm.wasm:0x1a38dc
    at pyodide.asm.wasm:0x2685c5
    at pyodide.asm.wasm:0x26e3d0
    at pyodide.asm.wasm:0x1a3a04
    at pyodide.asm.wasm:0x1a3694
    at pyodide.asm.wasm:0x15f45e
    at Module.callPyObjectKwargs (pyodide.asm.js:9:81732)
    at Module.callPyObject (pyodide.asm.js:9:82066)
    at wrapper (pyodide.asm.js:9:58562)

**Comment by ryanking13** [comment]
I don't know what flet is or why it worked before, but the error message seems reasonable to me. `google-crc32c` is not a pure python wheel and it cannot be installed through micropip, unless it is prebuilt.

So if your code worked in flet, probably flet devs may have prebuilt the package. I would suggest you open an issue in the Flet issue tracker?

**Comment by agriyakhetarpal** [comment]
It's been a while since this issue has been opened, and I checked https://github.com/flet-dev/flet – they are using Pyodide 0.25.0 internally for their framework. We can't do much about the failure here, because `google-crc32c` has not been packaged in Pyodide yet. Their source is here: https://github.com/googleapis/python-crc32c. We do have the `crc32c` apckage, but both of them are different packages.

For `google-cloud-storage` to work, we need these dependencies, and their dependencies: https://github.com/googleapis/python-storage/blob/0cfddf4ba101ebbcd6a026687a4f1b67f98bdf96/setup.py#L30-L37

I'm closing this for now; please feel free to reopen or open new issues/PRs for adding more dependencies (including the above ones) if you feel this is still relevant, @ClearSafety!
