### ISSUE TITLE
RuntimeError: null function or function signature mismatch in github action

### ISSUE THREAD

**Issue by leandro-benedet-garcia** [pyodide/pyodide#5015]
## 🐛 Bug

In the github action for my repository https://github.com/leandro-benedet-garcia/funengine/tree/nanobind
I am receiving this messages when trying to run pytests. 

the full log follows:
```
 Looking in indexes: https://pypi.org/simple, file:///home/runner/work/funengine/funengine/.pyodide-xbuildenv-0.27.3/0.26.2/xbuildenv/pyodide-root/package_index
Processing ./dist/funengine-0.1.0-cp312-cp312-pyodide_2024_0_wasm32.whl
Collecting pytest
  Using cached pytest-8.3.2-py3-none-any.whl.metadata (7.5 kB)
Collecting iniconfig (from pytest)
  Using cached https://cdn.jsdelivr.net/pyodide/v0.26.2/full/iniconfig-2.0.0-py3-none-any.whl
Requirement already satisfied: packaging in ./.venv-pyodide/lib/python3.12/site-packages (from pytest) (23.2)
Collecting pluggy<2,>=1.5 (from pytest)
  Using cached https://cdn.jsdelivr.net/pyodide/v0.26.2/full/pluggy-1.5.0-py3-none-any.whl
Using cached pytest-8.3.2-py3-none-any.whl (341 kB)
Installing collected packages: pluggy, iniconfig, funengine, pytest
Successfully installed funengine-0.1.0 iniconfig-2.0.0 pluggy-1.5.0 pytest-8.3.2
Notice:  A new release of pip is available: 24.1 -> 24.2
Notice:  To update, run: pip install --upgrade pip
============================= test session starts ==============================
platform emscripten -- Python 3.12.1, pytest-8.3.2, pluggy-1.5.0
rootdir: /home/runner/work/funengine/funengine
configfile: pyproject.toml
collected 2 items
tests/math/test_utils.py .                                               [ 50%]
Pyodide has suffered a fatal error. Please report this to the Pyodide maintainers.
The cause of the fatal error was:
RuntimeError: null function or function signature mismatch
    at wasm://wasm/0267b736:wasm-function[2565]:0x223402
    at _PyEM_TrampolineCall_JS (/home/runner/work/funengine/funengine/.pyodide-xbuildenv-0.27.3/0.26.2/xbuildenv/pyodide-root/dist/pyodide.asm.js:10:124082)
    at wasm://wasm/0267b736:wasm-function[1132]:0x1c2c4c
    at wasm://wasm/0267b736:wasm-function[1141]:0x1c345d
    at wasm://wasm/0267b736:wasm-function[3406]:0x2a0457
    at wasm://wasm/0267b736:wasm-function[3407]:0x2a4cf1
    at wasm://wasm/0267b736:wasm-function[1146]:0x1c3806
    at wasm://wasm/0267b736:wasm-function[1133]:0x1c2d63
    at wasm://wasm/0267b736:wasm-function[1150]:0x1c3a27
    at wasm://wasm/0267b736:wasm-function[2611]:0x228104 {
  pyodide_fatal_error: true
}
RuntimeError: null function or function signature mismatch
    at wasm://wasm/0267b736:wasm-function[2565]:0x223402
    at _PyEM_TrampolineCall_JS (/home/runner/work/funengine/funengine/.pyodide-xbuildenv-0.27.3/0.26.2/xbuildenv/pyodide-root/dist/pyodide.asm.js:10:124082)
    at wasm://wasm/0267b736:wasm-function[1132]:0x1c2c4c
    at wasm://wasm/0267b736:wasm-function[1141]:0x1c345d
    at wasm://wasm/0267b736:wasm-function[3406]:0x2a0457
    at wasm://wasm/0267b736:wasm-function[3407]:0x2a4cf1
    at wasm://wasm/0267b736:wasm-function[1146]:0x1c3806
    at wasm://wasm/0267b736:wasm-function[1133]:0x1c2d63
    at wasm://wasm/0267b736:wasm-function[1150]:0x1c3a27
    at wasm://wasm/0267b736:wasm-function[2611]:0x228104 {
  pyodide_fatal_error: true
}
tests/math/test_vectors.py 
```

### To Reproduce

Execute the emscripten github action, sorry, my skills with C++ are not good enough to figure out a minimun reproduceable project.

### Expected behavior

Tests pass fine just like the other actions from python 3.8 to python 3.12 using CLANG and MSVC

### Environment

- Pyodide Version: venv version that pyodide-build==0.27.3 generates
- Browser version: I am using virtual env, so unrelated

**Comment by hoodmane** [comment]
Can you build the package with debug symbols (pass `-g` to compiler and linker, or in cflags, cxxflags, and ldflags) so we can where it is failing? Would also be convenient if you could provide a wheel and a script that reproduces outside of CI.

**Comment by leandro-benedet-garcia** [comment]
Ah, yes apologies, here is the package built with `pyodide build . cmake.build-type=Debug`
[module.zip](https://github.com/user-attachments/files/16646734/module.zip)

here's a code to reproduce the issue:
```
from funenginepy import math

aprox = math.approximately
Vec3 = math.Vector3

assert aprox(Vec3(10, 10, 10).magnitude(), 17.320508075688775)
assert aprox(Vec3(1, 1, 1).magnitude(), 1.7320508075688772)
assert aprox(Vec3(-1, 1, 1).magnitude(), 1.7320508075688772)
assert aprox(Vec3(1, -1, 1).magnitude(), 1.7320508075688772)
```

But even with `cmake.build-type=Debug` the error does not improve much:
```
Pyodide has suffered a fatal error. Please report this to the Pyodide maintainers.
The cause of the fatal error was:
RuntimeError: null function or function signature mismatch
    at wasm://wasm/0267b736:wasm-function[2565]:0x223402
    at _PyEM_TrampolineCall_JS (/home/leandrobg/Projects/Games/tetris_fun_way/.pyodide-xbuildenv-0.28.0/0.26.2/xbuildenv/pyodide-root/dist/pyodide.asm.js:10:124082)
    at wasm://wasm/0267b736:wasm-function[1132]:0x1c2c4c
    at wasm://wasm/0267b736:wasm-function[1141]:0x1c345d
    at wasm://wasm/0267b736:wasm-function[3406]:0x2a0457
    at wasm://wasm/0267b736:wasm-function[3404]:0x295f35
    at wasm://wasm/0267b736:wasm-function[4209]:0x30a85a
    at wasm://wasm/0267b736:wasm-function[4204]:0x309f8c
    at wasm://wasm/0267b736:wasm-function[4201]:0x3099a5
    at wasm://wasm/0267b736:wasm-function[4563]:0x3276a9 {
  pyodide_fatal_error: true
}
Stack (most recent call first):
  File "/home/leandrobg/Projects/Games/tetris_fun_way/test_run.py", line 6 in <module>
RuntimeError: null function or function signature mismatch
    at wasm://wasm/0267b736:wasm-function[2565]:0x223402
    at _PyEM_TrampolineCall_JS (/home/leandrobg/Projects/Games/tetris_fun_way/.pyodide-xbuildenv-0.28.0/0.26.2/xbuildenv/pyodide-root/dist/pyodide.asm.js:10:124082)
    at wasm://wasm/0267b736:wasm-function[1132]:0x1c2c4c
    at wasm://wasm/0267b736:wasm-function[1141]:0x1c345d
    at wasm://wasm/0267b736:wasm-function[3406]:0x2a0457
    at wasm://wasm/0267b736:wasm-function[3404]:0x295f35
    at wasm://wasm/0267b736:wasm-function[4209]:0x30a85a
    at wasm://wasm/0267b736:wasm-function[4204]:0x309f8c
    at wasm://wasm/0267b736:wasm-function[4201]:0x3099a5
    at wasm://wasm/0267b736:wasm-function[4563]:0x3276a9 {
  pyodide_fatal_error: true
}
```

**Comment by hoodmane** [comment]
Thanks, I can reproduce. It's failing here:
https://github.com/python/cpython/blob/2305ca51448552542b2414186252123a8dc87db7/Objects/typeobject.c?plain=1#L1661
It's because the type has a bad `tp_new` -- it takes only one argument but it should take three arguments.

This looks to me like a nanobind bug. Nanobind sets the `tp_new` of the types it makes to `inst_new_int` here:
https://github.com/wjakob/nanobind/blob/master/src/nb_type.cpp?plain=1#L974

And `inst_new_int` is defined here with the wrong signature:
https://github.com/wjakob/nanobind/blob/master/src/nb_type.cpp?plain=1#L68

**Comment by leandro-benedet-garcia** [comment]
With https://github.com/wjakob/nanobind/pull/687 merged my problem is fixed, thank you very much!
