### ISSUE TITLE
It will meet error when I use edge_tts, which will use asynchronous function

### ISSUE THREAD

**Issue by wa008** [pyodide/pyodide#5045]
## 🐛 Bug

It will meet error when I use edge_tts, which will use asynchronous function

### To Reproduce

code:
```
    <script type="text/javascript">
      async function main(){
        let pyodide = await loadPyodide();
        await pyodide.loadPackage("micropip");
        const micropip = pyodide.pyimport("micropip");
        await micropip.install("edge_tts");
        await micropip.install("ssl");
        let output = pyodide.runPythonAsync(`
            import edge_tts
            import asyncio
            # import numpy
            import sys
            print (sys.platform, 'debug')
            communicate = edge_tts.Communicate('${TEXT}', '${VOICE}')
            output = b''
            async for chunk in communicate.stream():
                if chunk["type"] == "audio":
                    output += chunk["data"]
                    print (type(chunk["data"]))
                elif chunk["type"] == "WordBoundary":
                    print(f"WordBoundary: {chunk}")
            output
        `);
        document.getElementById("output_total").innerHTML = output;
        // let audio_src = document.getElementById("output_total").src
        // fs.writeFile(audio_src, output, function (err) {
        //     if (err) throw err;
        //     console.log('Saved!');
        // });
      }
      let TEXT = 'I like dogs';
      let VOICE = 'en-GB-SoniaNeural';
      let OUTPUT_FILE = 'abc';
      main();
    </script>
```

error:
```
Uncaught (in promise) PythonError: Traceback (most recent call last):
  File "/lib/python312.zip/_pyodide/_base.py", line 596, in eval_code_async
    await CodeRunner(
  File "/lib/python312.zip/_pyodide/_base.py", line 412, in run_async
    await coroutine
  File "<exec>", line 9, in <module>
  File "/lib/python3.12/site-packages/edge_tts/communicate.py", line 506, in stream
    async for message in self.__stream():
  File "/lib/python3.12/site-packages/edge_tts/communicate.py", line 365, in __stream
    async with aiohttp.ClientSession(
  File "/lib/python3.12/site-packages/aiohttp/client.py", line 1197, in __aenter__
    self._resp = await self._coro
                 ^^^^^^^^^^^^^^^^
  File "/lib/python3.12/site-packages/aiohttp/client.py", line 835, in _ws_connect
    resp = await self.request(
           ^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.12/site-packages/aiohttp/client.py", line 581, in _request
    conn = await self._connector.connect(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.12/site-packages/aiohttp/connector.py", line 544, in connect
    proto = await self._create_connection(req, traces, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.12/site-packages/aiohttp/connector.py", line 944, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.12/site-packages/aiohttp/connector.py", line 1203, in _create_direct_connection
    hosts = await self._resolve_host(host, port, traces=traces)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.12/site-packages/aiohttp/connector.py", line 880, in _resolve_host
    return await asyncio.shield(resolved_host_task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.12/site-packages/aiohttp/connector.py", line 917, in _resolve_host_with_throttle
    addrs = await self._resolver.resolve(host, port, family=self._family)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.12/site-packages/aiohttp/resolver.py", line 33, in resolve
    infos = await self._loop.getaddrinfo(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python312.zip/asyncio/events.py", line 299, in getaddrinfo
    raise NotImplementedError
NotImplementedError

    at new_error (pyodide.asm.js:10:9965)
    at pyodide.asm.wasm:0x16dc69
    at pyodide.asm.wasm:0x177492
    at _PyEM_TrampolineCall_JS (pyodide.asm.js:10:124082)
    at pyodide.asm.wasm:0x1c2c4c
    at pyodide.asm.wasm:0x2c79ac
    at pyodide.asm.wasm:0x20a621
    at pyodide.asm.wasm:0x1c3339
    at pyodide.asm.wasm:0x1c3648
    at pyodide.asm.wasm:0x1c36c6
    at pyodide.asm.wasm:0x29e6fa
    at pyodide.asm.wasm:0x2a4cf1
    at pyodide.asm.wasm:0x1c3806
    at pyodide.asm.wasm:0x1c346f
    at pyodide.asm.wasm:0x176af6
    at callPyObjectKwargs (pyodide.asm.js:10:62217)
    at Module.callPyObjectMaybePromising (pyodide.asm.js:10:63465)
    at wrapper (pyodide.asm.js:10:27093)
    at onGlobalMessage (pyodide.asm.js:10:99976)
```

### Expected behavior

Produce binary variable

### Environment

- Pyodide Version: v0.26.2
- Browser version: Chrome Version 128.0.6613.85 (Official Build) (arm64)

**Comment by ryanking13** [comment]
`getaddrinfo` is not implemented in Pyodide as we don't support Socket. So `aiohttp` needs to be patched to support environment without socket.

**Comment by wa008** [comment]
> `getaddrinfo` is not implemented in Pyodide as we don't support Socket. So `aiohttp` needs to be patched to support environment without socket.

Thanks very much, I'm new to open source, are there some recommended solution or projects for this problem? I want to try to solve it If it is possible for me.

**Comment by hoodmane** [comment]
You could try this patch:
https://github.com/aio-libs/aiohttp/pull/7803
