### ISSUE TITLE
fatal error in exception handling when testing z3 over pyodide

### ISSUE THREAD

**Issue by NikolajBjorner** [pyodide/pyodide#5203]
## 🐛 Bug

We are trying to build z3 (https://github.com/z3prover/z3) using pyodide.

### To Reproduce

[Use the build steps from the GitHub action, synchronized to z3 repository](https://github.com/Z3Prover/z3/blob/master/.github/workflows/pyodide.yml)

[The workflow fails](https://github.com/Z3Prover/z3/actions/runs/11851278844/job/33027495365)

### Expected behavior

It should pass the doc and python tests

### Environment

- Pyodide Version per GitHub action

### Additional context

@rhelmot

**Comment by NikolajBjorner** [comment]
This isn't a real bug.
While the error report suggests it is a bug, the first issue is that one has to compile with -fexceptions enabled.
Other flags are needed for handling threads and other functionality used by the C++ code.

The first thing that caught attention was that the pyodide bindings assume inheriting from std::exception. Perhaps too stringent a requirement.

**Comment by hoodmane** [comment]
Good to know it was fixed by `-fexceptions`. Maybe we should pass it by default...

> the pyodide bindings assume inheriting from std::exception. Perhaps too stringent a requirement.

Could you say a bit more about this?

**Comment by ryanking13** [comment]
I am happy to hear you made progress on running z3 in Pyodide! The last time wasn't that successful (https://github.com/pyodide/pyodide/pull/2892), but we improved our build system a lot since then, so it might be better now.

**Comment by NikolajBjorner** [comment]
> Good to know it was fixed by `-fexceptions`. Maybe we should pass it by default...
> 
> > the pyodide bindings assume inheriting from std::exception. Perhaps too stringent a requirement.
> 
> Could you say a bit more about this?

I am referring to this exception handling code on the pyodide side: https://github.com/pyodide/pyodide/blob/b4b9c8ea2aa1293f1cfbc9d69ac3de7eaa2d043b/src/core/error_handling.ts#L47

Z3 shouldn't be throwing exceptions to the top level (at least in non-buggy code paths): the code was triggered before passing the -fexceptions flag and might be unreachable with the current build flags.

**Comment by NikolajBjorner** [comment]
After dealing with other things, notably threads, I get further. But pyodide itself appears to have some issues based on the error messages. For example: 

https://microsoft.github.io/z3guide/programming/Z3%20Python%20-%20Readonly/Introduction/#solvers

(hit Run twice since we have yet to deal with that we don't pre-cache the pyodide runs and therefore show a spurious error message)

F12 provides a stack deep inside of pyodide with a call to contact maintainers.


```
yodide has suffered a fatal error. Please report this to the Pyodide maintainers.
API.fatal_error @ pyodide.asm.js:10
pyodide.asm.js:10  The cause of the fatal error was:
API.fatal_error @ pyodide.asm.js:10
pyodide.asm.js:10  TypeError: getWasmTableEntry(...) is not a function
    at invoke_viii (pyodide.asm.js:10:1222540)
    at 0523fc16:0x46d65a
    at invoke_viiii (pyodide.asm.js:10:1221618)
    at 0523fc16:0x46fc87
    at invoke_viii (pyodide.asm.js:10:1222540)
    at 0523fc16:0x13a4713
    at invoke_iiii (pyodide.asm.js:10:1220528)
    at 0523fc16:0x13a4470
    at ffi_call_js (pyodide.asm.js:10:127268)
    at pyodide.asm.wasm:0x45ebcd
API.fatal_error @ pyodide.asm.js:10
runZ3PYWeb.ts:1  TypeError: getWasmTableEntry(...) is not a function
    at invoke_viii (pyodide.asm.js:10:1222540)
    at 0523fc16:0x46d65a
    at invoke_viiii (pyodide.asm.js:10:1221618)
    at 0523fc16:0x46fc87
    at invoke_viii (pyodide.asm.js:10:1222540)
    at 0523fc16:0x13a4713
    at invoke_iiii (pyodide.asm.js:10:1220528)
    at 0523fc16:0x13a4470
    at ffi_call_js (pyodide.asm.js:10:127268)
    at pyodide.asm.wasm:0x45ebcd
eval @ runZ3PYWeb.ts:1
pyodide.asm.js:10  Recursive call to fatal_error. Inner error was:
API.fatal_error @ pyodide.asm.js:10
pyodide.asm.js:10  NoGilError: Attempted to use PyProxy when Python GIL not held
    at throw_no_gil (pyodide.asm.js:10:24494)
    at pyodide.asm.wasm:0x176227
    at pyodide.asm.js:10:57831
    at FinalizationRegistry.cleanupSome (<anonymous>)
    
 ```

**Comment by NikolajBjorner** [comment]
This is the saga on the z3 side: https://github.com/Z3Prover/z3/issues/7418

**Comment by chadbrewbaker** [comment]
Bump. OpenAI is now deploying pyodide when you load o4 in side by side browser view. Both sympy and z3 need stripped versions to be part of the standard distro. @NikolajBjorner what from the Z3 wasm32 binary can be stripped to keep file size in check? AFAIK anything with threads or fork() might have to be removed for the wasm32 build. On the bright side you get a version of Z3 that runs better on embedded systems for free.

**Comment by chadbrewbaker** [comment]
This is the current error the ChatGPT wasm32 environment is throwing.



ValueError: Can't find a pure Python 3 wheel for 'z3-solver'.
See: https://pyodide.org/en/stable/usage/faq.html#why-can-t-micropip-find-a-pure-python-wheel-for-a-package
You can use `await micropip.install(..., keep_going=True)` to get a list of all packages with missing wheels.
   line 16, in <module>
  File "/lib/python3.12/site-packages/micropip/_commands/install.py", line 142, in install
    await transaction.gather_requirements(requirements)
  File "/lib/python3.12/site-packages/micropip/transaction.py", line 55, in gather_requirements
    await asyncio.gather(*requirement_promises)
  File "/lib/python3.12/site-packages/micropip/transaction.py", line 62, in add_requirement
    return await self.add_requirement_inner(Requirement(req))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.12/site-packages/micropip/transaction.py", line 151, in add_requirement_inner
    await self._add_requirement_from_package_index(req)
  File "/lib/python3.12/site-packages/micropip/transaction.py", line 190, in _add_requirement_from_package_index
    wheel = find_wheel(metadata, req)
            ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.12/site-packages/micropip/transaction.py", line 281, in find_wheel
    raise ValueError(

**Comment by NikolajBjorner** [comment]
there is no pure wheel for z3-solver. Z3 is implemented in C++. This means the pyodide bindings are not hosted on pypi.
I put a wheel on z3guide, link is in the corresponding z3 github issue. I will need help in getting the last mile on stability with respect to this wheel. I got rid of some top-level locks, but there are other wasm specifics that are lurking.

**Comment by chadbrewbaker** [comment]
TIL. Playing with it now. From my port of Ruby to Blue Gene/L I'm guessing mostly getting rid of threads/forks. If you can compile z3 to run in one process as a static binary that should be enough for exotic OS requirements.

```
python3 -m pip install pyodide-build
```

**Comment by NikolajBjorner** [comment]
https://github.com/Z3Prover/z3/actions/workflows/pyodide.yml

**Comment by chadbrewbaker** [comment]
> https://github.com/Z3Prover/z3/actions/workflows/pyodide.yml
> 
> and here https://github.com/Z3Prover/z3/blob/3aacc6222972fb68436beba307fdec431d95c239/src/api/python/setup.py#L40

Looks good to me.  If you need to pin anything specific to what they are hosting in production this seems to be the setup.

@moyix this would be a good Xbow target. This is my janky script. I'm assuming the js module has more environment surface to enumerate. https://gist.github.com/chadbrewbaker/44e8f343473cd310c87cbcb481a15b01

Environment Variables:
USER=web_user
LOGNAME=web_user
PATH=/
PWD=/
HOME=/home/pyodide
LANG=en_US.UTF-8
_=./this.program
PYTHONINSPECT=1
LD_LIBRARY_PATH=/usr/lib:/lib/python3.12/site-packages

Operating System Information:
Unnamed Platform: posix.uname_result(sysname='Emscripten', nodename='emscripten', release='3.1.58', version='#1', machine='wasm32')

Additional Info:
Home Directory: /home/pyodide
Current User: web_user

**Comment by NikolajBjorner** [comment]
> Looks good to me

well, it is not stable. You can quickly get the web version to crash. https://microsoft.github.io/z3guide/programming/Z3%20Python%20-%20Readonly/Introduction

**Comment by chadbrewbaker** [comment]
Sorry, I forgot to add this is the user agent from the js module they are using in production for ChatGPT, so the CI should probably have the Intel Mac runner loaded.

UserAgent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.2 Safari/605.1.15
