### ISSUE TITLE
Building Fortran extension module fails, numpy headers not found

### ISSUE THREAD

**Issue by jmrohwer** [pyodide/pyodide#5231]
## 🐛 Bug

I'm trying to build a Python package https://github.com/PySCeS/pysces that makes use of two Fortran extension modules. The build system is `meson-python`. During the build process the compile fails because the numpy headers are not found:
```meson
FAILED: pysces/nleq2/nleq2.cpython-312-wasm32-emscripten.so.p/meson-generated_.._nleq2-f2pywrappers.f.o 
/tmp/tmp5klrn7m3/gfortran -Ipysces/nleq2/nleq2.cpython-312-wasm32-emscripten.so.p -Ipysces/nleq2 -I../pysces/nleq2 -I/tmp/build-env-5titjs19/lib/python3.12/site-packages/numpy/core/include -I/tmp/build-env-5titjs19/lib/python3.12/site-packages/numpy/f2py/src -I/home/jr/src/git/pysces/.pyodide-xbuildenv-0.29.0/0.27.0a2/xbuildenv/pyodide-root/cpython/installs/python-3.12.1/include/python3.12 -I/usr/include/python3.12 -fvisibility=hidden -fdiagnostics-color=always -DNDEBUG -D_FILE_OFFSET_BITS=64 -Wall -O3 -fPIC -Jpysces/nleq2/nleq2.cpython-312-wasm32-emscripten.so.p -o pysces/nleq2/nleq2.cpython-312-wasm32-emscripten.so.p/meson-generated_.._nleq2-f2pywrappers.f.o -c pysces/nleq2/nleq2-f2pywrappers.f
pysces/nleq2/nleq2-f2pywrappers.c:13:10: fatal error: 'f2c.h' file not found
   13 | #include "f2c.h"
      |          ^~~~~~~
1 error generated.
[8/21] Compiling C object pysces/nleq2/nleq2.cpython-312-wasm32-emscripten.so.p/meson-generated_.._nleq2module.c.o
pysces/nleq2/nleq2module.c:659:9: warning: unused variable 'ifail' [-Wunused-variable]
  659 |     int ifail=(*ifail_cb_capi);
      |         ^~~~~
1 warning generated.
[9/21] Compiling C object pysces/pitcon/pitcon.cpython-312-wasm32-emscripten.so.p/meson-generated_.._pitconmodule.c.o
pysces/pitcon/pitconmodule.c:419:9: warning: unused variable 'ierror' [-Wunused-variable]
  419 |     int ierror=(*ierror_cb_capi);
      |         ^~~~~~
pysces/pitcon/pitconmodule.c:618:9: warning: unused variable 'ierror' [-Wunused-variable]
  618 |     int ierror=(*ierror_cb_capi);
      |         ^~~~~~
2 warnings generated.
[10/21] Compiling Fortran object pysces/nleq2/nleq2.cpython-312-wasm32-emscripten.so.p/nleq2.f.o
FAILED: pysces/nleq2/nleq2.cpython-312-wasm32-emscripten.so.p/nleq2.f.o 
/tmp/tmp5klrn7m3/gfortran -Ipysces/nleq2/nleq2.cpython-312-wasm32-emscripten.so.p -Ipysces/nleq2 -I../pysces/nleq2 -I/tmp/build-env-5titjs19/lib/python3.12/site-packages/numpy/core/include -I/tmp/build-env-5titjs19/lib/python3.12/site-packages/numpy/f2py/src -I/home/jr/src/git/pysces/.pyodide-xbuildenv-0.29.0/0.27.0a2/xbuildenv/pyodide-root/cpython/installs/python-3.12.1/include/python3.12 -I/usr/include/python3.12 -fvisibility=hidden -fdiagnostics-color=always -DNDEBUG -D_FILE_OFFSET_BITS=64 -Wall -O3 -fPIC -Jpysces/nleq2/nleq2.cpython-312-wasm32-emscripten.so.p -o pysces/nleq2/nleq2.cpython-312-wasm32-emscripten.so.p/nleq2.f.o -c ../pysces/nleq2/nleq2.f
   nleq2:
Warning on line 972: local variable chgdat never used
   n2pchk:
   n2int:
   n2scal:
   n2scrf:
   n2fact:
   n2solv:
   n2lvls:
   n2jac:
   n2jcf:
   n2prjn:
   n2prv1:
   n2prv2:
   n2sout:
../pysces/nleq2/nleq2.c:13:10: fatal error: 'f2c.h' file not found
   13 | #include "f2c.h"
      |          ^~~~~~~
1 error generated.
ninja: build stopped: subcommand failed.

ERROR Backend subprocess exited when trying to invoke build_wheel
```

There are four missing header files: 
`f2c.h`
`lapack_lite_names.h`
`npy_cblas.h`
`npy_cblas_base.h`
Copying these into the `nleq2` source directory, the compile does proceed, but then fails with an error as follows:
```meson
FAILED: pysces/nleq2/nleq2.cpython-312-wasm32-emscripten.so.p/nleq2.f.o 
/tmp/tmp8g5dggky/gfortran -Ipysces/nleq2/nleq2.cpython-312-wasm32-emscripten.so.p -Ipysces/nleq2 -I../pysces/nleq2 -I/tmp/build-env-1ib08rg2/lib/python3.12/site-packages/numpy/core/include -I/tmp/build-env-1ib08rg2/lib/python3.12/site-packages/numpy/f2py/src -I/home/jr/src/git/pysces/.pyodide-xbuildenv-0.29.0/0.27.0a2/xbuildenv/pyodide-root/cpython/installs/python-3.12.1/include/python3.12 -I/usr/include/python3.12 -fvisibility=hidden -fdiagnostics-color=always -DNDEBUG -D_FILE_OFFSET_BITS=64 -Wall -O3 -fPIC -Jpysces/nleq2/nleq2.cpython-312-wasm32-emscripten.so.p -o pysces/nleq2/nleq2.cpython-312-wasm32-emscripten.so.p/nleq2.f.o -c ../pysces/nleq2/nleq2.f
   nleq2:
Warning on line 972: local variable chgdat never used
   n2pchk:
   n2int:
   n2scal:
   n2scrf:
   n2fact:
   n2solv:
   n2lvls:
   n2jac:
   n2jcf:
   n2prjn:
   n2prv1:
   n2prv2:
   n2sout:
../pysces/nleq2/nleq2.c:2022:9: error: too many arguments to function call, expected 0, have 4
 2022 |         (*fcn)(n, &x[1], &f[1], &ifail);
      |         ~~~~~~ ^~~~~~~~~~~~~~~~~~~~~~~
../pysces/nleq2/nleq2.c:2142:13: error: too many arguments to function call, expected 0, have 5
 2142 |             (*jac)(n, m1, &x[1], &a[a_offset], &ifail);
      |             ~~~~~~ ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../pysces/nleq2/nleq2.c:2387:50: warning: '&&' within '||' [-Wlogical-op-parentheses]
 2387 |             if (fcdnm > fcnump * fcmin2 || *nonlin == 4 && d__1 * d__1 * 
      |                                         ~~ ~~~~~~~~~~~~~^~~~~~~~~~~~~~~~
 2388 |                     fcnump < fcdnm * 4.) {
      |                     ~~~~~~~~~~~~~~~~~~~
../pysces/nleq2/nleq2.c:2387:50: note: place parentheses around the '&&' expression to silence this warning
 2387 |             if (fcdnm > fcnump * fcmin2 || *nonlin == 4 && d__1 * d__1 * 
      |                                                         ^
      |                                            (
 2388 |                     fcnump < fcdnm * 4.) {
      |                                        
      |                                        )
../pysces/nleq2/nleq2.c:2560:9: error: too many arguments to function call, expected 0, have 4
 2560 |         (*fcn)(n, &x[1], &f[1], &ifail);
      |         ~~~~~~ ^~~~~~~~~~~~~~~~~~~~~~~
../pysces/nleq2/nleq2.c:2785:41: warning: '&&' within '||' [-Wlogical-op-parentheses]
 2785 |             qredu = *fc < *fcmin || *new__ > 0 && nred > 1;
      |                                  ~~ ~~~~~~~~~~~^~~~~~~~~~~
../pysces/nleq2/nleq2.c:2785:41: note: place parentheses around the '&&' expression to silence this warning
 2785 |             qredu = *fc < *fcmin || *new__ > 0 && nred > 1;
      |                                                ^          
      |                                     (                     )
../pysces/nleq2/nleq2.c:3858:9: error: too many arguments to function call, expected 0, have 4
 3858 |         (*fcn)(n, &x[1], &fu[1], ifail);
      |         ~~~~~~ ^~~~~~~~~~~~~~~~~~~~~~~
../pysces/nleq2/nleq2.c:4004:9: error: too many arguments to function call, expected 0, have 4
 4004 |         (*fcn)(n, &x[1], &fu[1], ifail);
      |         ~~~~~~ ^~~~~~~~~~~~~~~~~~~~~~~
2 warnings and 5 errors generated.
[11/21] Compiling Fortran object pysces/nleq2/nleq2.cpython-312-wasm32-emscripten.so.p/zibmon.f.o
   mon:
       entry    monini:
       entry    mondef:
       entry    monstr:
       entry    monon:
       entry    monoff:
       entry    monhlt:
       entry    monprt:
       entry    monget:
[12/21] Compiling Fortran object pysces/nleq2/nleq2.cpython-312-wasm32-emscripten.so.p/linalg_nleq2.f.o
   deccon:
Warning on line 400: local variable d1mach never used
   solcon:
[13/21] Compiling Fortran object pysces/nleq2/nleq2.cpython-312-wasm32-emscripten.so.p/zibsec.f.o
   zibsec:
ninja: build stopped: subcommand failed.

ERROR Backend subprocess exited when trying to invoke build_wheel
```
My knowledge of C and Fortran is insufficient to be able to debug this further.

### To Reproduce
The bug happens (in identical way) whether I use an in-tree build with the following `meta.yaml`
```yaml
package:
  name: pysces
  version: 1.2.3dev0
  top-level:
    - pysces
source:
  url: https://github.com/PySCeS/pysces/archive/refs/heads/pyodide-build.zip
  sha256: e2f356a5aa25f7f7bd0156edc8c13c1b43ca37354e0b103bce199e7f37846486
about:
  home: https://pysces.github.io
  PyPI: https://pypi.org/project/pysces
  summary:
    The Python Simulator for Cellular Systems - simulation and analysis tools
    for modelling biological systems
  license: BSD 3-Clause
extra:
  recipe-maintainers:
    - jmrohwer
```
...or an out-of-tree build according to https://pyodide.org/en/stable/development/building-and-testing-packages.html

### Expected behavior

The compile should complete without error. In a normal Python environment the Fortran modules are built without error, on Linux, Windows and macOS.

### Environment

- Pyodide Version: Pyodide CLI Version: 0.2.3
- Browser version: irrelevant for build

- Commit hash of Pyodide git repository: 7e7cadb9 (tags/0.26.2)
- Build environment: Manjaro Linux (stable)

**Comment by hoodmane** [comment]
You're the first person in my awareness to attempt to build a fortran package that isn't scipy. At least in the four years I've been working on this project I don't _think_ I've seen any bug reports about this. I'll try looking into this a bit but the answer is likely painful. Is the Fortran mostly f90 or do you use newer Fortran features?

@agriyakhetarpal mentioned that the official llvm builds of flang now can target webassembly so that's vaguely hopeful. There's still some questions about whether it will work correctly with the rest of our toolchain but we've been doing okay with using one version of llvm to compile rust and a different version to link rust so maybe we'll be okay.

**Comment by jmrohwer** [comment]
The code is actually f77 :smile: it's rather ancient. The wrapper file (`nleq2.pyf`) for F2PY is f90.

Is there anything to be learnt from how scipy does things or is that such a specific corner case? I was figuring I'd give it a try since scipy is available for pyodide.

**Comment by hoodmane** [comment]
Well that's good news. We should start by trying to fix the header problem I guess.

**Comment by agriyakhetarpal** [comment]
> I was figuring I'd give it a try since scipy is available for pyodide. Is there anything to be learnt from how scipy does things or is that such a specific corner case? If so, I'd appreciate some pointers as to where to look, as the scipy code base is quite unwieldy!

At least for SciPy, the Fortran code is converted to C code first using https://github.com/hoodmane/f2c (you may use the same way SciPy uses to obtain it in its recipe) and then compiled to WASM after applying many patches (eighteen; not all of them are relevant to the build, but some of them fix broken signatures at runtime). Besides those, there are other commands in the `build/script:` field that fix the return types for the calls in some of the Fortran-based SciPy routines.

Though, could you try setting `cflags:` and `ldflags:` to point to `{WASM_LIBRARY_DIR}/lib` and `{WASM_LIBRARY_DIR}/include`, so that you don't need to copy the headers directly?

That said, I think we should also add a basic FORTRAN 77 extension package built with Meson for testing in CI, given that we have some for C++-based packages. I could take a look at it.

I did try what I suggested above locally and I can get the compilation to proceed for a good twenty seconds, after which it fails due to a `[Errno 13] Permission denied` 5/21 object files into the process – quite the unrevealed secret to me, too, as to why that happens.

**Comment by agriyakhetarpal** [comment]
> I was figuring I'd give it a try since scipy is available for pyodide. Is there anything to be learnt from how scipy does things or is that such a specific corner case? If so, I'd appreciate some pointers as to where to look, as the scipy code base is quite unwieldy!

At least for SciPy, the Fortran code is converted to C code first using https://github.com/hoodmane/f2c (you may use the same way SciPy uses to obtain it in its recipe) and then compiled to WASM after applying many patches (eighteen; not all of them are relevant to the build, but some of them fix broken signatures at runtime). Besides those, there are other commands in the `build/script:` field that fix the return types for the calls in some of the Fortran-based SciPy routines.

Though, could you try setting `cflags:` and `ldflags:` to point to `{WASM_LIBRARY_DIR}/lib` and `{WASM_LIBRARY_DIR}/include`, so that you don't need to copy the headers directly?

That said, I think we should also add a basic FORTRAN 77 extension package built with Meson for testing in CI, given that we have some for C++-based packages. I could take a look at it.

I did try what I suggested above locally and I can get the compilation to proceed for a good twenty seconds, after which it fails due to an `[Errno 13] Permission denied` occurring 5/21 object files into the process – quite the unrevealed secret to me, too, as to why that happens.

**Comment by jmrohwer** [comment]
I have managed to get the compile to complete by commenting out the quadmath link in `meson.build`. My `meson.build` now reads:
```meson
nleq2_wrappers = custom_target(
  'nleq2module.c',
  input : ['nleq2.pyf'],
  output : ['nleq2module.c', 'nleq2-f2pywrappers.f'],
  command : [py, '-m', 'numpy.f2py', '@INPUT@', '--build-dir', '@OUTDIR@']
)

py.extension_module(
  'nleq2',
  [
    'nleq2.f',
    'linalg_nleq2.f',
    'zibmon.f',
    'zibsec.f',
    'zibconst.f',
    'wnorm.f',
    nleq2_wrappers,
    fortranobject_c
  ],
  include_directories: inc_np,
  dependencies : [
    py_dep,
#    quadmath_dep,
  ],
  install : true,
  subdir: 'pysces/nleq2'
)

py.install_sources(
  [
    '__init__.py'
  ],
  subdir: 'pysces/nleq2'
)

install_data(
  ['nleq2_readme.txt', 'readme.txt'],
  install_dir: pysces_dir / 'nleq2'
)
```
The module compiles successfully (as does the whole pysces package), and I can import the module in the pyodide console:
```python
>>> from pysces.nleq2 import nleq2
>>> nleq2
<module 'pysces.nleq2.nleq2' from '/lib/python3.12/site-packages/pysces/nleq2/nleq2.cpython-312-wasm32-emscripten.so'>
```
However, trying to execute the module gives an error:
```python
>>> nleq2_res, s_scale, rtol, iopt, ierr = nleq2.nleq2(
    lin3, lin3, initial, initial, rtol, iopt, iwk, rwk
)
Pyodide has suffered a fatal error. Please report this to the Pyodide maintainers.
The cause of the fatal error was:
RuntimeError: indirect call signature mismatch
Look in the browser console for more details.
```
(The variables `lin3`, `initial`, etc. have all been defined previously as required. The function call works in a normal python console).

The browser console output reads as follows:
```
Pyodide has suffered a fatal error. Please report this to the Pyodide maintainers. [pyodide.asm.js:10:48512](http://0.0.0.0:8000/pyodide.asm.js)
The cause of the fatal error was: [pyodide.asm.js:10:48612](http://0.0.0.0:8000/pyodide.asm.js)
RuntimeError: indirect call signature mismatch
    dynCall http://0.0.0.0:8000/pyodide.asm.js:10
    _createPyodideModule http://0.0.0.0:8000/pyodide.asm.js:10
    prop http://0.0.0.0:8000/pyodide.asm.js:10
    _PyEM_TrampolineCall_JS http://0.0.0.0:8000/pyodide.asm.js:10
    _PyEM_TrampolineCall_JS http://0.0.0.0:8000/pyodide.asm.js:10
    qe http://0.0.0.0:8000/pyodide.asm.js:10
    callPyObjectMaybePromising http://0.0.0.0:8000/pyodide.asm.js:10
    wrapper http://0.0.0.0:8000/pyodide.asm.js:10
    t http://0.0.0.0:8000/pyodide.asm.js:10
[pyodide.asm.js:10:48732](http://0.0.0.0:8000/pyodide.asm.js)
    fatal_error http://0.0.0.0:8000/pyodide.asm.js:10
    maybe_fatal_error http://0.0.0.0:8000/pyodide.asm.js:10
    qe http://0.0.0.0:8000/pyodide.asm.js:10
    callPyObjectMaybePromising http://0.0.0.0:8000/pyodide.asm.js:10
    wrapper http://0.0.0.0:8000/pyodide.asm.js:10
    t http://0.0.0.0:8000/pyodide.asm.js:10
Stack (most recent call first): [pyodide.asm.js:10:98326](http://0.0.0.0:8000/pyodide.asm.js)
  File "<console>", line 1 in <module> [pyodide.asm.js:10:98326](http://0.0.0.0:8000/pyodide.asm.js)
  File "/lib/python312.zip/_pyodide/_base.py", line 411 in run_async [pyodide.asm.js:10:98326](http://0.0.0.0:8000/pyodide.asm.js)
  File "/lib/python312.zip/pyodide/console.py", line 419 in runcode [pyodide.asm.js:10:98326](http://0.0.0.0:8000/pyodide.asm.js)
  File "/lib/python312.zip/pyodide/console.py", line 535 in runcode [pyodide.asm.js:10:98326](http://0.0.0.0:8000/pyodide.asm.js)
  File "/lib/python312.zip/pyodide/console.py", line 413 in _runcode_with_lock [pyodide.asm.js:10:98326](http://0.0.0.0:8000/pyodide.asm.js)
  File "/lib/python312.zip/asyncio/events.py", line 88 in _run [pyodide.asm.js:10:98326](http://0.0.0.0:8000/pyodide.asm.js)
  File "/lib/python312.zip/pyodide/webloop.py", line 332 in run_handle [pyodide.asm.js:10:98326](http://0.0.0.0:8000/pyodide.asm.js)
Uncaught (in promise) RuntimeError: indirect call signature mismatch
    dynCall http://0.0.0.0:8000/pyodide.asm.js:10
    _createPyodideModule http://0.0.0.0:8000/pyodide.asm.js:10
    prop http://0.0.0.0:8000/pyodide.asm.js:10
    _PyEM_TrampolineCall_JS http://0.0.0.0:8000/pyodide.asm.js:10
    _PyEM_TrampolineCall_JS http://0.0.0.0:8000/pyodide.asm.js:10
    qe http://0.0.0.0:8000/pyodide.asm.js:10
    callPyObjectMaybePromising http://0.0.0.0:8000/pyodide.asm.js:10
    wrapper http://0.0.0.0:8000/pyodide.asm.js:10
    t http://0.0.0.0:8000/pyodide.asm.js:10
```

Seems to be linked to a call signature mismatch. Unfortunately I have no idea how to pursue this further...

**Comment by agriyakhetarpal** [comment]
Sounds like good progress! I think `libquadmath` should be available as a part of a Fortran compiler's sysroot, but we don't exactly have a Fortran compiler as discussed... Could you build under debug mode (by setting the `PYODIDE_DEBUG` environment variable to `1`) and see if that helps with a better stack trace? We do have a guide on debugging function signature mismatches in signatures at https://pyodide.org/en/stable/development/debugging.html, but I'm not fully sure what the approach for a call signature mismatch would be, it might probably be similar. @hoodmane would be able to help more. I would suggest trying the code under multiple browsers to isolate in case this is an Emscripten bug or something to do with the WebAssembly ABI.

**Comment by agriyakhetarpal** [comment]
I've renamed the issue title since the NumPy headers are now being found as expected.

**Comment by jmrohwer** [comment]
I've opened a new issue (#5241) with a minimal example that reproduces the error. It is a general error for any `f2py`/`meson` compiled module and not restricted to `pysces` or `nleq2` as in this report.

**Comment by jmrohwer** [comment]
There has been some progress, background information is provided in #5241. I've renamed the issue title accordingly. To assist debugging and avoid having to compile the whole `pysces` module every time, I've created a Python module that just wraps the `nleq2` Fortran code [here](https://github.com/jmrohwer/nleq2_for_pyodide). Details are provided in the readme on that site.

Following #5241 I've tried two approaches. First, I manually ran `f2py` to generate `nleq2module.c` and then edited the latter file, mainly replacing `void` with `int` but also changing one or two return values. The complete diff (from the f2py-generated file) reads:
```diff
diff --git a/nleq2/nleq2/nleq2module.c b/nleq2/nleq2/nleq2module.c
index 63ad689..1b6fe84 100644
--- a/nleq2/nleq2/nleq2module.c
+++ b/nleq2/nleq2/nleq2module.c
@@ -32,8 +32,8 @@ static PyObject *nleq2_module;
 typedef signed char signed_char;
 
 /****************** See f2py2e/cfuncs.py: typedefs_generated ******************/
-typedef void(*cb_jac_in_nleq2__user__routines_typedef)(int *,int *,double *,double *,int *);
-typedef void(*cb_fcn_in_nleq2__user__routines_typedef)(int *,double *,double *,int *);
+typedef int(*cb_jac_in_nleq2__user__routines_typedef)(int *,int *,double *,double *,int *);
+typedef int(*cb_fcn_in_nleq2__user__routines_typedef)(int *,double *,double *,int *);
 
 /********************** See f2py2e/cfuncs.py: cppmacros **********************/
 
@@ -401,7 +401,7 @@ double_from_pyobj(double* v, PyObject *obj, const char *errmess)
 
 
 /* See f2py2e/rules.py */
-extern void F_FUNC(nleq2,NLEQ2)(int*,cb_fcn_in_nleq2__user__routines_typedef,cb_jac_in_nleq2__user__routines_typedef,double*,double*,double*,int*,int*,int*,int*,int*,double*);
+extern int F_FUNC(nleq2,NLEQ2)(int*,cb_fcn_in_nleq2__user__routines_typedef,cb_jac_in_nleq2__user__routines_typedef,double*,double*,double*,int*,int*,int*,int*,int*,double*);
 /*eof externroutines*/
 
 /******************** See f2py2e/capi_rules.py: usercode1 ********************/
@@ -427,7 +427,7 @@ static cb_fcn_in_nleq2__user__routines_t *swap_active_cb_fcn_in_nleq2__user__rou
     return prev;
 }
 
-static cb_fcn_in_nleq2__user__routines_t *get_active_cb_fcn_in_nleq2__user__routines(void) {
+static cb_fcn_in_nleq2__user__routines_t *get_active_cb_fcn_in_nleq2__user__routines() {
     return _active_cb_fcn_in_nleq2__user__routines;
 }
 
@@ -438,7 +438,7 @@ static cb_fcn_in_nleq2__user__routines_t *swap_active_cb_fcn_in_nleq2__user__rou
     return (cb_fcn_in_nleq2__user__routines_t *)F2PySwapThreadLocalCallbackPtr(key, ptr);
 }
 
-static cb_fcn_in_nleq2__user__routines_t *get_active_cb_fcn_in_nleq2__user__routines(void) {
+static cb_fcn_in_nleq2__user__routines_t *get_active_cb_fcn_in_nleq2__user__routines() {
     char *key = "__f2py_cb_cb_fcn_in_nleq2__user__routines";
     return (cb_fcn_in_nleq2__user__routines_t *)F2PyGetThreadLocalCallbackPtr(key);
 }
@@ -446,7 +446,7 @@ static cb_fcn_in_nleq2__user__routines_t *get_active_cb_fcn_in_nleq2__user__rout
 #endif
 
 /*typedef void(*cb_fcn_in_nleq2__user__routines_typedef)(int *,double *,double *,int *);*/
-static void cb_fcn_in_nleq2__user__routines (int *n_cb_capi,double *x,double *f,int *ifail_cb_capi) {
+static int cb_fcn_in_nleq2__user__routines (int *n_cb_capi,double *x,double *f,int *ifail_cb_capi) {
     cb_fcn_in_nleq2__user__routines_t cb_local = { NULL, NULL, 0 };
     cb_fcn_in_nleq2__user__routines_t *cb = NULL;
     PyTupleObject *capi_arglist = NULL;
@@ -484,7 +484,7 @@ f2py_cb_start_clock();
     cb_fcn_in_nleq2__user__routines_typedef cb_fcn_in_nleq2__user__routines_cptr;
     cb_fcn_in_nleq2__user__routines_cptr = F2PyCapsule_AsVoidPtr(cb->capi);
     (*cb_fcn_in_nleq2__user__routines_cptr)(n_cb_capi,x,f,ifail_cb_capi);
-    return;
+    return 0;
     }
     if (capi_arglist==NULL) {
         capi_longjmp_ok = 0;
@@ -602,7 +602,7 @@ capi_fail:
     }
 capi_return_pt:
     ;
-return;
+return 0;
 }
 /******************* end of cb_fcn_in_nleq2__user__routines *******************/
 
@@ -625,7 +625,7 @@ static cb_jac_in_nleq2__user__routines_t *swap_active_cb_jac_in_nleq2__user__rou
     return prev;
 }
 
-static cb_jac_in_nleq2__user__routines_t *get_active_cb_jac_in_nleq2__user__routines(void) {
+static cb_jac_in_nleq2__user__routines_t *get_active_cb_jac_in_nleq2__user__routines() {
     return _active_cb_jac_in_nleq2__user__routines;
 }
 
@@ -636,7 +636,7 @@ static cb_jac_in_nleq2__user__routines_t *swap_active_cb_jac_in_nleq2__user__rou
     return (cb_jac_in_nleq2__user__routines_t *)F2PySwapThreadLocalCallbackPtr(key, ptr);
 }
 
-static cb_jac_in_nleq2__user__routines_t *get_active_cb_jac_in_nleq2__user__routines(void) {
+static cb_jac_in_nleq2__user__routines_t *get_active_cb_jac_in_nleq2__user__routines() {
     char *key = "__f2py_cb_cb_jac_in_nleq2__user__routines";
     return (cb_jac_in_nleq2__user__routines_t *)F2PyGetThreadLocalCallbackPtr(key);
 }
@@ -644,7 +644,7 @@ static cb_jac_in_nleq2__user__routines_t *get_active_cb_jac_in_nleq2__user__rout
 #endif
 
 /*typedef void(*cb_jac_in_nleq2__user__routines_typedef)(int *,int *,double *,double *,int *);*/
-static void cb_jac_in_nleq2__user__routines (int *n_cb_capi,int *m1_cb_capi,double *x,double *a,int *ifail_cb_capi) {
+static int cb_jac_in_nleq2__user__routines (int *n_cb_capi,int *m1_cb_capi,double *x,double *a,int *ifail_cb_capi) {
     cb_jac_in_nleq2__user__routines_t cb_local = { NULL, NULL, 0 };
     cb_jac_in_nleq2__user__routines_t *cb = NULL;
     PyTupleObject *capi_arglist = NULL;
@@ -683,7 +683,7 @@ f2py_cb_start_clock();
     cb_jac_in_nleq2__user__routines_typedef cb_jac_in_nleq2__user__routines_cptr;
     cb_jac_in_nleq2__user__routines_cptr = F2PyCapsule_AsVoidPtr(cb->capi);
     (*cb_jac_in_nleq2__user__routines_cptr)(n_cb_capi,m1_cb_capi,x,a,ifail_cb_capi);
-    return;
+    return 0;
     }
     if (capi_arglist==NULL) {
         capi_longjmp_ok = 0;
@@ -799,7 +799,7 @@ capi_fail:
     }
 capi_return_pt:
     ;
-return;
+return 0;
 }
 /******************* end of cb_jac_in_nleq2__user__routines *******************/
 
@@ -852,7 +852,7 @@ x,xscal,rtol,iopt,ierr = nleq2(fcn,jac,x,xscal,rtol,iopt,iwk,rwk,[n,liwk,lrwk,fc
 static PyObject *f2py_rout_nleq2_nleq2(const PyObject *capi_self,
                            PyObject *capi_args,
                            PyObject *capi_keywds,
-                           void (*f2py_func)(int*,cb_fcn_in_nleq2__user__routines_typedef,cb_jac_in_nleq2__user__routines_typedef,double*,double*,double*,int*,int*,int*,int*,int*,double*)) {
+                           int (*f2py_func)(int*,cb_fcn_in_nleq2__user__routines_typedef,cb_jac_in_nleq2__user__routines_typedef,double*,double*,double*,int*,int*,int*,int*,int*,double*)) {
     PyObject * volatile capi_buildvalue = NULL;
     volatile int f2py_success = 1;
 /*decl*/
```
The source is available on the *no_f2py* branch: https://github.com/jmrohwer/nleq2_for_pyodide/tree/no_f2py

After compilation and testing I get an error `cannot resolve symbol d_sign`:
```python
Welcome to the Pyodide 0.27.0.dev0 terminal emulator 🐍
Python 3.12.7 (main, Nov 29 2024 08:11:23) on WebAssembly/Emscripten
Type "help", "copyright", "credits" or "license" for more information.
>>> import nleq2
>>> nleq2.nleq2
<module 'nleq2.nleq2.nleq2' from '/lib/python3.12/site-packages/nleq2/nleq2/nleq2.cpython-312-wasm32-emscripten.so'>
>>> nleq2.test()
Pyodide has suffered a fatal error. Please report this to the Pyodide maintainers.
The cause of the fatal error was:
Error: Dynamic linking error: cannot resolve symbol d_sign
Look in the browser console for more details.
```
The browser console:
![Screenshot_20241217_111849](https://github.com/user-attachments/assets/5b1c8ccb-fd79-4a07-adae-81e788b3e459)

**Comment by jmrohwer** [comment]
**The second approach**

Code is available on the main branch: https://github.com/jmrohwer/nleq2_for_pyodide.

Inspired by https://github.com/pyodide/pyodide/blob/main/packages/scipy/patches/0010-Link-openblas-with-modules-that-require-f2c.patch I've used `f2py` to generate the C wrappers on the fly during compilation (this does not use the hand edited `nleq2module.c` referred to in the previous post), and I've added a dependency to `openblas` in the `meson.build`:
```meson
py.extension_module(
  'nleq2',
  ...,
  ...,
  dependencies: [lapack, fortranobject_dep],
  ...)
```
with 
```meson
lapack = dependency(['openblas', 'OpenBLAS'])
```
(inspired by scipy).

The module compiles fine, but there is the following error on import:
```python
>>> import nleq2
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/lib/python3.12/site-packages/nleq2/__init__.py", line 2, in <module>
    from .nleq2 import nleq2
ImportError: dynamic module does not define module export function (PyInit_nleq2)
```
Again I'm not sure how to proceed here, so any advice would be appreciated.

In general, in the scipy source I've seen manually generated C wrappers, e.g.:
https://github.com/scipy/scipy/blob/main/scipy/integrate/_odepackmodule.c
https://github.com/scipy/scipy/blob/main/scipy/interpolate/src/_fitpackmodule.c

...as well as numerous `*.pyf` files which are compiled by `f2py` on the fly, e.g.:
https://github.com/scipy/scipy/blob/15d6284e5a0f3333394ca4498eb56bce14a6245b/scipy/integrate/meson.build#L82-L84
https://github.com/scipy/scipy/blob/15d6284e5a0f3333394ca4498eb56bce14a6245b/scipy/integrate/meson.build#L93-L95

**Comment by zerothi** [comment]
> You're the first person in my awareness to attempt to build a fortran package that isn't scipy. At least in the four years I've been working on this project I don't _think_ I've seen any bug reports about this. I'll try looking into this a bit but the answer is likely painful. Is the Fortran mostly f90 or do you use newer Fortran features?
> 
> [@agriyakhetarpal](https://github.com/agriyakhetarpal) mentioned that the official llvm builds of flang now can target webassembly so that's vaguely hopeful. There's still some questions about whether it will work correctly with the rest of our toolchain but we've been doing okay with using one version of llvm to compile rust and a different version to link rust so maybe we'll be okay.

Actually, in #4210 sisl also uses fortran, however, functionality can be reduced by not compiling fortran code. But ideally, we would like it in, so I'm following this with interest! :)
