### ISSUE TITLE
Pyodide REPL can break on quotes in comments

### ISSUE THREAD

**Issue by bartbroere** [pyodide/pyodide#5245]
## 🐛 Bug
The Pyodide REPL can get confused by quotes appearing in line comments. It seems the parsing performed by JQuery Terminal causes this issue. I think there probably are other ways to trigger this error (for example single quotes in double-quoted strings etc.).

### To Reproduce
Paste the following two lines in the Pyodide console
```python
# don't work
test = {"Test": 'test'}["Test"]
```

and you'll get a stacktrace similar to this:

```
[USER]: Bad control character in string literal in JSON at position 7 (line 1 column 8)
SyntaxError: Bad control character in string literal in JSON at position 7 (line 1 column 8)
    at JSON.parse (<anonymous>)
    at https://cdn.jsdelivr.net/npm/jquery.terminal@2.35.2/js/jquery.terminal.min.js:46:94091
    at Array.map (<anonymous>)
    at r (https://cdn.jsdelivr.net/npm/jquery.terminal@2.35.2/js/jquery.terminal.min.js:46:93840)
    at Object.e [as parse_argument] (https://cdn.jsdelivr.net/npm/jquery.terminal@2.35.2/js/jquery.terminal.min.js:46:94437)
    at https://cdn.jsdelivr.net/npm/jquery.terminal@2.35.2/js/jquery.terminal.min.js:46:95161
    at https://cdn.jsdelivr.net/npm/jquery.terminal@2.35.2/js/jquery.terminal.min.js:46:78816
    at Function.map (https://cdn.jsdelivr.net/npm/jquery:2:3971)
    at process_command (https://cdn.jsdelivr.net/npm/jquery.terminal@2.35.2/js/jquery.terminal.min.js:46:78670)
    at Object.e [as split_command] (https://cdn.jsdelivr.net/npm/jquery.terminal@2.35.2/js/jquery.terminal.min.js:46:95113)
```

### Expected behavior
Valid Python gets executed by the REPL.

### Environment
- Pyodide Version: current release (0.26.4) and previous releases
- Browser version: occurs irrespective of browser version

### Additional context
The method that introduces the error is located here: https://github.com/jcubic/jquery.terminal/blob/301b0965a1f445323fd9300bffcf7cfdf21bd4a1/js/jquery.terminal.js#L6521-L6580

By setting breakpoints you can see that it splits the code snippet above into the following JSON literals (before it crashes). This is likely due to the regex parsing.
```json
"\"don\""
```

```json
"\"t work\ntest = {\\\"Test\\\": \""
```

I realise the bug is outside of the Pyodide project, but maybe a solution can be created on the Pyodide side nonetheless. There might be a way to bypass the problematic code (maybe avoiding multi-line strings, or feeding them line-by-line?).

**Comment by agriyakhetarpal** [comment]
Hi @bartbroere, I tried your reproducer on both the stable and latest versions of the console, and I wasn't able to reproduce. Could you share more about the browsers you tried it on and the operating system you are using for additional diagnostics?

**Comment by ruizehung** [comment]
I was able to reproduce this easily by pasting 
```py
# don't work
test = {"Test": 'test'}["Test"]
```
into https://pyodide.org/en/stable/console.html

Browser: Arc Version 1.73.0 (56815)
OS: MacOS Sequoia 15.1.1 (24B2091)

<img width="1205" alt="image" src="https://github.com/user-attachments/assets/9f4f9d1b-199c-4532-928d-e6c3b7b20fc5" />

**Comment by ryanking13** [comment]
I cannot reproduce it either

**Comment by agriyakhetarpal** [comment]
Update from my test: I can reproduce it with a local build on macOS on ARM, but not on the stable or latest consoles.

**Comment by hoodmane** [comment]
Weird.
