### ISSUE TITLE
Reduce the number of dynamic libraries

### ISSUE THREAD

**Issue by juntyr** [pyodide/pyodide#5264]
Some Python packages use a large number of shared libraries, e.g. (counts are from globbing the site packages directory in my own Pyodide deployment for *.so files):

- 'scipy': 110,
- 'sklearn': 68,
- 'pandas': 44,
- 'h5py': 24,
- 'numpy': 19,
- 'astropy': 18,
- 'pyarrow': 15,

As far as I understand, dynamically loading each of these shared libraries requires instantiating a new WebAssembly module. The day has finally come where I'm hitting limits in Firefox when importing packages, which fails with
```
WebAssembly module validated with warning: failed to allocate executable memory for module
```

Since the modules themselves aren't that big, I think the problem is with the pre-allocation of virtual memory to eliminate bounds checks in WebAssembly memories, which makes a large number of small modules (or memories) exceed the memory limits even though their combined size is small.

My question now is whether there is anything we can do when building some of the worst offending packages (very few people will get around scipy, sklearn, and pandas) to somehow bundle more shared libraries together to leave space to load other modules as well.

**Comment by ryanking13** [comment]
Thanks for bringing this up, @juntyr! Reducing the number of shared libraries would help reduce loading time and memory usage. However, as you mentioned, this is up to the package maintainers, so there is not much we can do. For instance, pygame builds a single shared library (pygame-static) for WASM, but it is done by pygame maintainers.

In the future, JSPI will help this situation, as after JSPI we will no longer have to pre-load all the shared libraries in the package, but load them on demand instead.

**Comment by juntyr** [comment]
> In the future, JSPI will help this situation, as after JSPI we will no longer have to pre-load all the shared libraries in the package, but load them on demand instead.

Good point! I agree that we can then treat it as a known limitation with the current pre-loading (we need to be conservative and so you might OOM earlier than necessary). #5075 might also be related in generally trying to minimize which Python modules we load and when so that OOMs become less likely and restricted to the user loading loads of really heavy dependencies explicitly.

I'm wondering if lazier loading would be implemented once browsers support JSPI (not just behind feature flags), or if it could already be added earlier switched to if JSPI support is detected at runtime?

**Comment by ryanking13** [comment]
> I'm wondering if lazier loading would be implemented once browsers support JSPI (not just behind feature flags), or if it could already be added earlier switched to if JSPI support is detected at runtime?

We are already pushing features that are only available when JSPI is available (e.g. [run_sync](https://pyodide.org/en/stable/usage/api/python-api/ffi.html#pyodide.ffi.run_sync)). So I think we can start implementing that feature even from now. But because of the limited resources, I am not actively looking into it. For instance, https://github.com/emscripten-core/emscripten/issues/22126 is required to get rid of JS hacks we are using to load shared libraries.

**Comment by hoodmane** [comment]
Yeah it'd be best to first try to add support for `rpath`.

**Comment by juntyr** [comment]
I've been experimenting a bit with what synchronous package loading will look like (not using JSPI but by hacking together a `loadPackageSync` function, see https://github.com/climet-eu/pyodide/compare/climet-lab-0.27.0...climet-eu:pyodide:climate-lab-0.27.0-syncify, everything built on top should still give us the same idea).

## The Great

```python
import importlib
import sys

import pyodide_js


class PyodidePackageFinder(importlib.abc.MetaPathFinder):
    def find_spec(self, fullname, path, target=None):
        # no need to load an already-imported package
        if fullname in sys.modules:
            return None

        # we can only load packages in the Pyodide distribution
        if fullname not in pyodide_js._api._import_name_to_package_name:
            return None

        package_name = pyodide_js._api._import_name_to_package_name[fullname]
        pkg = getattr(pyodide_js._api.lockfile_packages, package_name)

        # no need to load an already-loaded package
        if getattr(pyodide_js.loadedPackages, pkg.name, None) is not None:
            return None

        pyodide_js.loadPackageSync(package_name)

        # the package is now installed and can be loaded as usual
        return None

sys.meta_path.insert(0, PyodidePackageFinder())
```

This just works! Import statements synchronously load the package if Pyodide can provide it. I'm experimenting inside JupyterLite, which automatically preloads imports, so to trigger the sync import I need to use e.g. `exec("import numpy")`.

Previously, I had a nasty hack to also support the import preloading for local Python files (e.g. a utils.py file next to a Jupyter notebook that is imported but has some imports itself, I previously had a hack to pre-pre-load even those imports of imports). Now, it just works.

Many packages do cheap optional dependency checks by trying to import. Previously, I had to add such optional dependencies to the requirement list of the package to ensure they would be available, just in case. Now, when a package checks for availability, we catch it and automatically load the package. Note that this unfortunately increases the dynlib pressure as e.g. pandas now always loads pyarrow. Unfortunately, packages that perform plugin detection still cannot use plugins that are loaded after the main package (e.g. xarray needs custom backends to be loaded before xarray is imported ... sigh).

Over, this brings a significant quality of life improvement. So much so that I wonder whether Pyodide should just add such an import hook right now (if JSPI is available). I think it would make a lot of import edge cases a lot easier to deal with.

## The messy: lazy dependency loading

I also tried hacking around with lazy dependency loading by ... not loading any "package" type dependencies (since later imports should catch them). This will unfortunately open up a very messy tradeoff:

- For performance, we want to load as many packages as possible in one asynchronous load (even if that is syncified at the top-level with JSPI).
- Loading packages lazily that are imported unconditionally makes package imports very slow
- We *do* want to use lazy loading for dependencies that are (a) optional or (b) only accessed when a user imports a submodule or calls a function, as this would give most users a bit more breathing room (with less eager imports)

I think there is no general purpose way of doing this (and I already found one package that breaks because it has a dependency it never imports but whose plugin it expects to always exist ... sigh ... I guess I could always patch in a dummy import). If lazy loading is something we would want (and there are packages like kerchunk which have a lot of dependencies that are only imported if the user explicitly loads a specific submodule with a specific purpose), I think we would need hints in the requirements as to whether a dependency should be loaded eagerly or whether it can be delayed. By default, every runtime requirement would be eager.

## The bad: namespace packages

If you have an `import namespace.sub`, the import hook will first be called on `namespace`, then on `namespace.sub`. If `namespace` is a meta-package that imports everything, this now also loads everything. This again adds module and dynlib pressure, but I don't know how to solve it (other than to use lazy loading and to convince the authors of metapackages to use lazy imports on all subpackages so the user still only pays for the ones they access).

## The blocked: dynamic library dependencies

Still no progress here

**Comment by juntyr** [comment]
If you have ideas for how to hack around with lazy dynamic library loading, (e.g. would only pre-loading the indirect dependencies in the "<PACKAGE>.libs" folder work to hack around the missing rpath?), I'd be delighted to try them out in my fork so that I can gather some usability feedback on how valuable it would be

**Comment by juntyr** [comment]
I found a very hacky way to implement lazy loading of dynlibs. It's basically registering a mapping from dynlib name to path when we'd preload them right now (also recording ambiguous names), and when emscripten is unable to locate a dependent dynlib, I consult the mapping and issue a temporary object URL to load the library. This is very fragile in general but seems to work really well so far (so far only gdal has ambiguous dynlibs as it's included via auditwheel in at least two different wheels, and I'm ok with assuming that both dynlibs here are the same).

So while the implementation is in no way generalisable, you can check our https://lab.climet.eu/main for what sync lazy package imports and lazy dynlib loading might feel like for the end user

**Comment by hoodmane** [comment]
Thanks for looking into this @juntyr! It's definitely about time to think of having a lazier loading mode based on jspi. I think we want to start by just lazily loading the dynamic libraries and keeping the package loading the same but I'd be open to exploring experimental approaches to both. We'll need to keep the current behavior as the default for a long time from now though -- at least until Safari ships jspi support which there is no sign of them doing =(

**Comment by hoodmane** [comment]
> So much so that I wonder whether Pyodide should just add such an import hook right now

I think we can add such an import hook to our public API and give people the option to use it or not. I think switching to deferred dso loading will be transparent to users and can be done whenever automatically whenever jspi is available but this auto installer behavior is a more significant behavior change that needs to be opt in.

**Comment by juntyr** [comment]
I like the idea of exposing the import hook - that way Pyodide can care about implementing it and a lot of other projects will just activate it in their startup.

For lazy dynamic libraries we really need the rpath (and then JSPI can be used so lazy loading also works on the main thread where we need to take the async code path). Since Pyodide already patches Emscripten to get the dynload to work, what about sketching out what the rpath impl in Emscripten would look like? Once the tool convention is adopted this patch could then be upstreamed (it seems like waiting for the adaptation to happen first would leave Pyodide with just eager dynlib loading for quite a while longer).

**Comment by juntyr** [comment]
Should the import hook be conditionally exposed based on if JSPI is available, or always exposed but be a no-op if it’s not?

Either way, I’d be happy to open a PR and contribute my hook.

Tangentially, I also discovered that I’d really like a way to override the default output hooks for package loading (similar to how stdout can be overridden). Would there be interest in having these methods upstreamed as well?

**Comment by ogrisel** [comment]
> you can check our https://lab.climet.eu/main for what sync lazy package imports and lazy dynlib loading might feel like for the end user

Thanks, @juntyr, for moving this forward. I tried running:

```python
import pyarrow, pandas, sklearn
```

Because this 3 package import statement is known to crash chrome (the famous "Aw, Snap!"), for instance on the [pyodide 0.27.2 console](https://pyodide.org/en/0.27.2/console.html).

With https://lab.climet.eu/main, it does not crash chrome itself, but it does crash pyodide ("Pyodide has suffered a fatal error") after printing the following output:

```
[pyodide]: Loaded joblib, lzma, numpy, pandas, pyarrow, pyodide-unix-timezones, python-dateutil, pytz, scikit-learn, scipy, threadpoolctl, tzdata
[pyodide]: Loading cloudpickle
[pyodide]: Loaded cloudpickle
```

I found the following error messages in the JS console:

<details>

```
Pyodide contents will be synced with Jupyter Contents
VM33:3 openssl already loaded from default channel
VM33:3 Loading hashlib
VM33:3 Loaded hashlib
VM33:3 six already loaded from default channel
VM33:3 Loading joblib, lzma, numpy, pandas, pyarrow, pyodide-unix-timezones, python-dateutil, pytz, scikit-learn, scipy, threadpoolctl, tzdata
VM33:3 Loaded joblib, lzma, numpy, pandas, pyarrow, pyodide-unix-timezones, python-dateutil, pytz, scikit-learn, scipy, threadpoolctl, tzdata
VM33:3 Loading cloudpickle
VM33:3 Loaded cloudpickle
pyodide.asm.js:10 Pyodide has suffered a fatal error. Please report this to the Pyodide maintainers.
API.fatal_error @ pyodide.asm.js:10Understand this errorAI
pyodide.asm.js:10 The cause of the fatal error was:
API.fatal_error @ pyodide.asm.js:10Understand this errorAI
pyodide.asm.js:10 SyntaxError: Bad control character in string literal in JSON at position 125 (line 1 column 126)
    at parse (<anonymous>)
    at coincident.worker.js:4:11723
    at Object.then (coincident.worker.js:4:10888)
    at coincident.worker.js:4:11714
    at Object.then (coincident.worker.js:4:10888)
    at Proxy.<anonymous> (coincident.worker.js:4:11598)
    at wt.request (coincident.worker.js:12:4713)
    at wt.getattr (coincident.worker.js:4:4880)
    at Be.getattr (coincident.worker.js:4:1943)
    at stat (pyodide.asm.js:10:242425)
API.fatal_error @ pyodide.asm.js:10Understand this errorAI
pyodide.asm.js:10 Stack (most recent call first):
pyodide.asm.js:10   File "<frozen importlib._bootstrap_external>", line 147 in _path_stat
pyodide.asm.js:10   File "<frozen importlib._bootstrap_external>", line 1601 in find_spec
pyodide.asm.js:10   File "<frozen importlib._bootstrap_external>", line 1502 in _get_spec
pyodide.asm.js:10   File "<frozen importlib._bootstrap_external>", line 1528 in find_spec
pyodide.asm.js:10   File "<frozen importlib._bootstrap>", line 1262 in _find_spec
pyodide.asm.js:10   File "<frozen importlib._bootstrap>", line 1322 in _find_and_load_unlocked
pyodide.asm.js:10   File "<frozen importlib._bootstrap>", line 1360 in _find_and_load
pyodide.asm.js:10   File "/lib/python3.12/site-packages/pandas/__init__.py", line 14 in <module>
pyodide.asm.js:10   File "<frozen importlib._bootstrap>", line 488 in _call_with_frames_removed
pyodide.asm.js:10   File "<frozen importlib._bootstrap_external>", line 995 in exec_module
pyodide.asm.js:10   File "<frozen importlib._bootstrap>", line 935 in _load_unlocked
pyodide.asm.js:10   File "<frozen importlib._bootstrap>", line 1331 in _find_and_load_unlocked
pyodide.asm.js:10   File "<frozen importlib._bootstrap>", line 1360 in _find_and_load
pyodide.asm.js:10   File "<ipython-input-1-bb3306b7ba22>", line 1 in <module>
pyodide.asm.js:10   File "/lib/python3.12/site-packages/IPython/core/interactiveshell.py", line 3580 in run_code
pyodide.asm.js:10   File "/lib/python3.12/site-packages/IPython/core/interactiveshell.py", line 3520 in run_ast_nodes
pyodide.asm.js:10   File "/lib/python3.12/site-packages/IPython/core/interactiveshell.py", line 3337 in run_cell_async
pyodide.asm.js:10   File "/lib/python3.12/site-packages/IPython/core/async_helpers.py", line 128 in _pseudo_sync_runner
pyodide.asm.js:10   File "/lib/python3.12/site-packages/IPython/core/interactiveshell.py", line 3133 in _run_cell
pyodide.asm.js:10   File "/lib/python3.12/site-packages/IPython/core/interactiveshell.py", line 3078 in run_cell
pyodide.asm.js:10   File "/lib/python3.12/site-packages/pyodide_kernel/kernel.py", line 103 in run
pyodide.asm.js:10   File "/lib/python312.zip/asyncio/events.py", line 88 in _run
pyodide.asm.js:10   File "/lib/python312.zip/pyodide/webloop.py", line 332 in run_handle
620.1f7022cb36bb0022…022cb36bb0022cde6:1 Uncaught (in promise) SyntaxError: Bad control character in string literal in JSON at position 125 (line 1 column 126)
    at parse (<anonymous>)
    at coincident.worker.js:4:11723
    at Object.then (coincident.worker.js:4:10888)
    at coincident.worker.js:4:11714
    at Object.then (coincident.worker.js:4:10888)
    at Proxy.<anonymous> (coincident.worker.js:4:11598)
    at wt.request (coincident.worker.js:12:4713)
    at wt.getattr (coincident.worker.js:4:4880)
    at Be.getattr (coincident.worker.js:4:1943)
    at stat (pyodide.asm.js:10:242425)
```

</details>

On firefox and safari it works and prints the following for both browsers:

```
[pyodide]: Loaded joblib, lzma, numpy, pandas, pyarrow, pyodide-unix-timezones, python-dateutil, pytz, scikit-learn, scipy, threadpoolctl, tzdata
[pyodide]: Loading cloudpickle
[pyodide]: Loaded cloudpickle
[pyodide]: Memory usage has grown to 179.0MiB (from 49.9MiB) for this notebook
[pyodide]: Loaded 149 new dynamic libraries (155 total for this notebook)
```

**Comment by juntyr** [comment]
@ogrisel Thanks for the report! I just tried it in Chrome on Windows and it ran successfully. In my Chrome I have experimental JSPI enabled, which takes a slightly different code path, perhaps that had an effect?

**Comment by ogrisel** [comment]
@juntyr actually I cannot reproduce anymore. I did not change anything in the chrome config. I also retried in a new incognito window, and it worked 4 out of 4 times I tried.

**Comment by ogrisel** [comment]
> Since the modules themselves aren't that big, I think the problem is with the pre-allocation of virtual memory to eliminate bounds checks in WebAssembly memories, which makes a large number of small modules (or memories) exceed the memory limits even though their combined size is small.

Isn't there a way to tackle this problem directly, BTW? Is this per-dynlib-file memory overhead browser specific? Or is it something emscripten can control?

**Comment by juntyr** [comment]
> However, it's still easy to trigger the chrome "Aw, Snap!" crash by opening 2 or 3 concurrent notebooks in the same jupyterlite browser tab and running:
> 
> import pyarrow, pandas, sklearn
> in each of them (even sequentially). So the lazy loader only buys a bit more time before the "python package with multiple dynlibs problem" occurs but does not fully fix it (as expected I guess). The real fix would be to change the WASM build of those projects to make sure that they use a single .so file per Python package as pygame does.

 Yes, you’re right. The browser has a limit on the number of Wasm modules that can be opened at the same time (or its memories). Eagerly loading all shared libs makes it trivial to bust the limit, lazy loading buys time in most use cases, but merging shared libs would be the holy grail.

**Comment by hoodmane** [comment]
I don't believe this idea about it being an address space limitation because there's only one webassembly memory shared by all dynamic libraries so you only need 4gb of virtual memory total no matter how many modules you load. But looking at heap snapshots after loading a lot of dynamic libraries shows a lot of memory overhead. With jspi the hope is to switch to only loading dynamic libraries as needed and maybe that would help enough. It depends on whether you actually are using all this stuff in scipy or are just carrying it along.

**Comment by juntyr** [comment]
> I don't believe this idea about it being an address space limitation because there's only one webassembly memory shared by all dynamic libraries so you only need 4gb of virtual memory total no matter how many modules you load. But looking at heap snapshots after loading a lot of dynamic libraries shows a lot of memory overhead. With jspi the hope is to switch to only loading dynamic libraries as needed and maybe that would help enough. It depends on whether you actually are using all this stuff in scipy or are just carrying it along.

Do all the modules share a single memory that’s imported in all dynlibs? I didn’t know. That makes it even more curious as to what is eating up the memory and why it’s worse in Chrome. The size of the wasm code of all dynlibs doesn’t add up to enough to explain it.

**Comment by ogrisel** [comment]
Actually, it appears that enabling JSPI in chrome://flags fixes the "Aw, Snap!" crash observed when importing heavy dynlib packages in concurrent jupyterlite tabs within the same browser tab.

**Comment by hoodmane** [comment]
Yes they all share one memory because they have to share one address space. "Pointers" in wasm are indexes into a memory, if a dynamic library had its own separate memory it wouldn't be able to dereference pointers from the main binary nor would the main binary be able to dereference library pointers.

**Comment by hoodmane** [comment]
> That makes it even more curious as to what is eating up the memory and why it’s worse in Chrome. The size of the wasm code of all dynlibs doesn’t add up to enough to explain it.

I agree it's perplexing and frustrating. I have some documents somewhere where I attempted to understand this I'll see if I can find them and share them here. Not that I got all that far. But they might not be completely useless.

**Comment by ogrisel** [comment]
@juntyr I further experimented with your https://lab.climet.eu/main/lab/index.html deployment with JSPI enabled in chrome and the following causes the call to `fit` to crash with "Pyodide has suffered a fatal error" while it works with a regular jupyterlite deployment (or in the pyodide REPL).

```python
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression


X, y = make_classification(
    n_samples=100_000, class_sep=0.5, random_state=0
)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.5, random_state=0)


model = LogisticRegression()
model.fit(X_train, y_train)
```

Errors in the JS console of chrome:

<details>

```
pyodide.asm.js:10 Pyodide has suffered a fatal error. Please report this to the Pyodide maintainers.

pyodide.asm.js:10 The cause of the fatal error was:
pyodide.asm.js:10 Error: Dynamic linking error: cannot resolve symbol s_cmp
    at stubs.<computed> (pyodide.asm.js:10:169640)
    at 0003cd5e:0x29fd
    at 0003cd5e:0x1cdb
    at 001d3d1a:0x3e701
    at _PyEM_TrampolineCall_JS (pyodide.asm.js:10:146672)
    at pyodide.asm.wasm:0x1c442b
    at pyodide.asm.wasm:0x1c4c3c
    at pyodide.asm.wasm:0x2a2ba3
    at pyodide.asm.wasm:0x2a73f5
    at pyodide.asm.wasm:0x1c4fe5
pyodide.asm.js:10 Stack (most recent call first):
pyodide.asm.js:10   File "/lib/python3.12/site-packages/scipy/optimize/_lbfgsb_py.py", line 398 in _minimize_lbfgsb
pyodide.asm.js:10   File "/lib/python3.12/site-packages/scipy/optimize/_minimize.py", line 731 in minimize
pyodide.asm.js:10   File "/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py", line 451 in _logistic_regression_path
pyodide.asm.js:10   File "/lib/python3.12/site-packages/sklearn/utils/parallel.py", line 139 in __call__
pyodide.asm.js:10   File "/lib/python3.12/site-packages/joblib/parallel.py", line 1847 in _get_sequential_output
pyodide.asm.js:10   File "/lib/python3.12/site-packages/joblib/parallel.py", line 1918 in __call__
pyodide.asm.js:10   File "/lib/python3.12/site-packages/sklearn/utils/parallel.py", line 77 in __call__
pyodide.asm.js:10   File "/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py", line 1350 in fit
pyodide.asm.js:10   File "/lib/python3.12/site-packages/sklearn/base.py", line 1389 in wrapper
pyodide.asm.js:10   File "<ipython-input-1-297fe61e5180>", line 18 in <module>
pyodide.asm.js:10   File "/lib/python3.12/site-packages/IPython/core/interactiveshell.py", line 3580 in run_code
pyodide.asm.js:10   File "/lib/python3.12/site-packages/IPython/core/interactiveshell.py", line 3520 in run_ast_nodes
pyodide.asm.js:10   File "/lib/python3.12/site-packages/IPython/core/interactiveshell.py", line 3337 in run_cell_async
pyodide.asm.js:10   File "/lib/python3.12/site-packages/IPython/core/async_helpers.py", line 128 in _pseudo_sync_runner
pyodide.asm.js:10   File "/lib/python3.12/site-packages/IPython/core/interactiveshell.py", line 3133 in _run_cell
pyodide.asm.js:10   File "/lib/python3.12/site-packages/IPython/core/interactiveshell.py", line 3078 in run_cell
pyodide.asm.js:10   File "/lib/python3.12/site-packages/pyodide_kernel/kernel.py", line 103 in run
pyodide.asm.js:10   File "/lib/python312.zip/asyncio/events.py", line 88 in _run
pyodide.asm.js:10   File "/lib/python312.zip/pyodide/webloop.py", line 332 in run_handle
pyodide.asm.js:10 Uncaught (in promise) Error: Dynamic linking error: cannot resolve symbol s_cmp
    at stubs.<computed> (pyodide.asm.js:10:169640)
    at 0003cd5e:0x29fd
    at 0003cd5e:0x1cdb
    at 001d3d1a:0x3e701
    at _PyEM_TrampolineCall_JS (pyodide.asm.js:10:146672)
    at pyodide.asm.wasm:0x1c442b
    at pyodide.asm.wasm:0x1c4c3c
    at pyodide.asm.wasm:0x2a2ba3
    at pyodide.asm.wasm:0x2a73f5
    at pyodide.asm.wasm:0x1c4fe5
﻿```

</details>

**Comment by juntyr** [comment]
Thanks @ogrisel for providing an example - I can reproduce the issue. This one seems to be independent of JSPI but was introduced by the lazy loading of shared libs (either using JSPI or via my manually syncified codepath).

I unfortunately have no experience with debugging dynamic linking errors. Clearly this is a case where loading a library on demand causes a missing symbol, but why? Perhaps @agriyakhetarpal has an idea?

**Comment by agriyakhetarpal** [comment]
Hi @ogrisel, and thanks @juntyr for the ping. Could you share what version of Pyodide and those for the packages that you're using? Could you please [update to `jupyterlite-pyodide-kernel>=0.4.7`](https://jupyterlite-pyodide-kernel.readthedocs.io/en/stable/#with-pyodide) when you have a chance to grab Pyodide 0.27? I remember that this error used to occur downstream in a few packages that used to rely on SciPy and subsequently OpenBLAS, as the `s_cmp` symbol comes from the latter; see scikit-image/scikit-image#7525 for an example. The fix was mostly around fixing more parts of SciPy and getting it to as up-to-date a version as possible/available at that time, which automatically resolved a few issues and signature mismatches here and there as a part of FORTRAN77-to-C rewrites upstream via https://github.com/scipy/scipy/issues/18566.

Though, in this particular case, the stack trace from the console reveals more information:

```
Stack (most recent call first):
pyodide.asm.js:10   File "/lib/python3.12/site-packages/scipy/optimize/_lbfgsb_py.py", line 398 in _minimize_lbfgsb
pyodide.asm.js:10   File "/lib/python3.12/site-packages/scipy/optimize/_minimize.py", line 731 in minimize
pyodide.asm.js:10   File "/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py", line 451 in _logistic_regression_path
```

where line 398 is as follows

```python
_lbfgsb.setulb(m, x, low_bnd, upper_bnd, nbd, f, g, factr,
                       pgtol, wa, iwa, task, iprint, csave, lsave,
                       isave, dsave, maxls)
```

whereas the Fortran 90 signature in `lbfgsb.pyf` is

```fortran
subroutine setulb(n,m,x,l,u,nbd,f,g,factr,pgtol,wa,iwa,task,iprint,csave,lsave,isave,dsave,maxls)
```

which looks fine to me from a cursory look. I think the current fix would be to patch SciPy and link OpenBLAS at this code fissure in `scipy/optimize/meson.build`, i.e., add LBFGSB to [`patch 10/18`](https://github.com/pyodide/pyodide/blob/71c16894ecca40d2b2e411735340740c8ade031c/packages/scipy/patches/0010-Link-openblas-with-modules-that-require-f2c.patch).


However, the ideal fix—in a similar vein as the above—is to rather incorporate https://github.com/scipy/scipy/pull/21314 instead, which first appeared in SciPy 1.15rc1. I've been trying to update SciPy to version 1.15 in https://github.com/pyodide/pyodide/pull/5297, but it has been a slight while since I last touched it. It is on my radar for this month or early next month, though, albeit not as an immediate priority (feedback/help there is welcome, of course!).

**Comment by hoodmane** [comment]
> Tangentially, I also discovered that I’d really like a way to override the default output hooks for package loading (similar to how stdout can be overridden). Would there be interest in having these methods upstreamed as well?

I think so.

**Comment by juntyr** [comment]
Thanks @agriyakhetarpal so much for your insights!

I'm currently on scipy 1.14.1 and jupyterlite-pyodide-kernel 0.5.2, but with my custom Pyodide version based on a 0.27 pre-release just after your matplotlib update and before the numpy update landed (I'm planning to rebase again soon).

> I think the current fix would be to patch SciPy and link OpenBLAS at this code fissure in `scipy/optimize/meson.build`, i.e., add LBFGSB to [`patch 10/18`](https://github.com/pyodide/pyodide/blob/71c16894ecca40d2b2e411735340740c8ade031c/packages/scipy/patches/0010-Link-openblas-with-modules-that-require-f2c.patch).

I looked at scipy/optimize/meson.build and found the following:
```
py3.extension_module('_lbfgsb',
  [
    'lbfgsb_src/lbfgsb.f',
    'lbfgsb_src/linpack.f',
    'lbfgsb_src/timer.f',
    f2py_gen.process('lbfgsb_src/lbfgsb.pyf'),
  ],
  fortran_args: fortran_ignore_warnings,
  link_args: version_link_args,
  dependencies: [lapack_dep, blas_dep, fortranobject_dep],
  override_options: ['b_lto=false'],
  install: true,
  link_language: 'fortran',
  subdir: 'scipy/optimize'
)
```

This seems to suggest that OpenBLAS should already be linked, or am I wrong?

> However, the ideal fix—in a similar vein as the above—is to rather incorporate [scipy/scipy#21314](https://github.com/scipy/scipy/pull/21314) instead, which first appeared in SciPy 1.15rc1. I've been trying to update SciPy to version 1.15 in #5297, but it has been a slight while since I last touched it. It is on my radar for this month or early next month, though, albeit not as an immediate priority (feedback/help there is welcome, of course!).

That sounds great, I'm looking forward to updating once you've updated the patch (absolutely no rush, for these heavy dependencies I'm happy to update whenever they land in Pyodide)

**Comment by agriyakhetarpal** [comment]
> This seems to suggest that OpenBLAS should already be linked, or am I wrong?

Ah, @juntyr, I think here `lapack_dep` refers to the reference/Netlib CLAPACK (plus a bunch of wrapper libraries and the LAPACK-specific compiler flags SciPy adds), while `lapack` itself means OpenBLAS, due to #3331. So, they are not the same in this case.

Hood might know better and could correct me in case I'm wrong.

**Comment by juntyr** [comment]
@agriyakhetarpal I tried out your suggested patch in https://github.com/climet-eu/pyodide/commit/5b7f4e7d8e6b28ad82c2644f6f9829ab640b10fa but unfortunately the same crash still persists on https://lab.climet.eu/main

**Comment by agriyakhetarpal** [comment]
Thanks for trying it out, @juntyr. I think @ryanking13 had observed how the symbol loading works, so he might know better.

The best fix in that case (if it's not patch-able without much effort) is to proceed with #5297.

**Comment by agriyakhetarpal** [comment]
Also, maybe I spoke too early – the signatures are different in https://github.com/pyodide/pyodide/issues/5264#issuecomment-2669674066. I didn't notice closely enough :D

They are correct with the C rewrite in 1.15. Aligning the Fortran signature (19 arguments with one extra `n` at the start) with the Python one (with 18 arguments) could help. However, I don't see why that would become an unresolved symbol error at runtime like you noticed instead of showing up as a [function signature mismatch](https://pyodide.org/en/stable/development/debugging.html#debugging-runtimeerror-function-signature-mismatch).

**Comment by ogrisel** [comment]
For the record, I tried to reproduce the problem with [jupyterlite-xeus](https://github.com/jupyterlite/xeus) kernel and the emscripten-forge packages instead of Pyodide versions and I can open many jupyterlite tabs with the following imports and all run well without crashing on chrome or safari:

```python
import pyarrow, pandas, sklearn
```

Here is the deployed site if you want to give it a try:

https://ogrisel.github.io/jupyterlite-emscripten-forge-sandbox/lab/index.html

and the build config:

https://github.com/ogrisel/jupyterlite-emscripten-forge-sandbox/

Not sure what the jupyterlite-xeus does differently that would explain the observed difference with pyodide.

I also tried opening the jupyterlite-xeus deployment with firefox, and there I seem to hit a limit after open a few such jupyterlite tabs with the same import statements then I get `ImportError: dynamic module does not define module export function (PyInit_vectorized)` when importing on of those packages.
