### ISSUE TITLE
statsmodels crashes on import

### ISSUE THREAD

**Issue by mdboom** [pyodide/pyodide#537]
```
import statsmodels.api
```

```
Error: Traceback (most recent call last):
  File "/lib/python3.7/site-packages/pyodide.py", line 42, in eval_code
    exec(compile(mod, '<exec>', mode='exec'), ns, ns)
  File "<exec>", line 1, in <module>
  File "/lib/python3.7/site-packages/statsmodels/api.py", line 7, in <module>
    from .regression.recursive_ls import RecursiveLS
  File "/lib/python3.7/site-packages/statsmodels/regression/recursive_ls.py", line 16, in <module>
    from statsmodels.tsa.statespace.mlemodel import (
  File "/lib/python3.7/site-packages/statsmodels/tsa/statespace/mlemodel.py", line 18, in <module>
    from .simulation_smoother import SimulationSmoother
  File "/lib/python3.7/site-packages/statsmodels/tsa/statespace/simulation_smoother.py", line 10, in <module>
    from .kalman_smoother import KalmanSmoother
  File "/lib/python3.7/site-packages/statsmodels/tsa/statespace/kalman_smoother.py", line 11, in <module>
    from statsmodels.tsa.statespace.representation import OptionWrapper
  File "/lib/python3.7/site-packages/statsmodels/tsa/statespace/representation.py", line 10, in <module>
    from .tools import (
  File "/lib/python3.7/site-packages/statsmodels/tsa/statespace/tools.py", line 207, in <module>
    set_mode(compatibility=None)
  File "/lib/python3.7/site-packages/statsmodels/tsa/statespace/tools.py", line 59, in set_mode
    from . import (_representation, _kalman_filter, _kalman_smoother,
ImportError: cannot import name '_representation' from 'statsmodels.tsa.statespace' (/lib/python3.7/site-packages/statsmodels/tsa/statespace/__init__.py)
```

**Comment by marcpabst** [comment]
I can reproduce this with the latest release. Statsmodels would be really nice...

**Comment by machow** [comment]
Hey, I think it's related to how statsmodels v0.9 checks for / builds against scipy on install.

Basically, `setup.py` tries `from scipy.linalg import cython_blas`, and if that fails then excludes certain files. This is normally okay, since on import time, statsmodels tries the same scipy import again. If this fails, then it enters "compatibility" mode and uses pure python implementations.

This importing twice breaks down if you **can't** import scipy at install (so no didn't build what you need), AND **can** import at run time (eg didn't build on install, but try to import at runtime).

https://github.com/statsmodels/statsmodels/blob/a8889192d705e86397acf1473fa3f4336b0b6816/setup.py#L448-L455

https://github.com/statsmodels/statsmodels/blob/a8889192d705e86397acf1473fa3f4336b0b6816/statsmodels/tsa/statespace/tools.py#L49-L54

Since later versions of statsmodels require a scipy update, it seems like a quick workaround could be patching statsmodels? I'm working on it now, and can submit a PR! There's a single multiprocessing import to work around, and then hopefully it should import...

**Comment by rth** [comment]
That would be nice thanks @machow, PR welcome. How to you propose to patch it, but using compat mode or assuming that scipy is always available at build time?

**Comment by marcpabst** [comment]
Seconding @gitkwr's observation. I still see this issue. I'm evaluating solutions for interactive statistical visualisations at the moment and having statsmodels in the browser would be super nice.
