### ISSUE TITLE
Add umbral package

### ISSUE THREAD

**Issue by Himan000** [pyodide/pyodide#681]
My code is :
```
<%--
  Created by IntelliJ IDEA.
  User: Himan
  Date: 2020/6/5
  Time: 12:24
  To change this template use File | Settings | File Templates.
--%>
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<html>
  <head>
    <meta http-equiv="Access-Control-Allow-Origin" content="*" />
    <title>Test Pyodide</title>
    <script type="text/javascript">
      // set the pyodide files URL (packages.json, pyodide.asm.data etc)
      window.languagePluginUrl = 'https://pyodide-cdn2.iodide.io/v0.15.0/full/';
    </script>
    <!-- <script src="https://pyodide-cdn2.iodide.io/v0.15.0/full/pyodide.js"></script> -->
    <script type="text/javascript" src="js/pyodide.js"></script>
  </head>
  <body>
  <!-- $END$ -->
  Pyodide test page <br>
  Open your browser console to see pyodide output
  <script type="text/javascript">
    pythonCode = `
      def do_work(*args):
          from umbral.keys import UmbralPrivateKey, UmbralPublicKey
          private_key = UmbralPrivateKey.gen_key()
          print(private_key.to_bytes())

      import micropip
      micropip.install('umbral').then(do_work)
    `

    languagePluginLoader.then(() => {
      return pyodide.loadPackage(['umbral'])
    }).then(() => {
      pyodide.runPython(pythonCode);
    })
  </script>
  </body>
</html>

```

error detail:
```
pyodide.asm.js:8 Python initialization complete
pyodide.js:146 umbral to be loaded from default channel
pyodide.js:108 Unknown package 'umbral'
_errorCallback @ pyodide.js:108
_loadPackage @ pyodide.js:157
(anonymous) @ pyodide.js:267
Promise.then (async)
loadPackage @ pyodide.js:266
(anonymous) @ (index):30
Promise.then (async)
(anonymous) @ (index):29
pyodide.js:104 Loading umbral
pyodide.js:104 Loading umbral from https://pyodide-cdn2.iodide.io/v0.15.0/full/umbral.js
pyodide.js:85 GET https://pyodide-cdn2.iodide.io/v0.15.0/full/umbral.js net::ERR_ABORTED 404
loadScript @ pyodide.js:85
(anonymous) @ pyodide.js:236
_loadPackage @ pyodide.js:174
(anonymous) @ pyodide.js:267
Promise.then (async)
loadPackage @ pyodide.js:266
(anonymous) @ (index):30
Promise.then (async)
(anonymous) @ (index):29
pyodide.js:108 Couldn't load package from URL https://pyodide-cdn2.iodide.io/v0.15.0/full/umbral.js
_errorCallback @ pyodide.js:108
(anonymous) @ pyodide.js:241
script.onerror @ pyodide.js:84
error (async)
loadScript @ pyodide.js:84
(anonymous) @ pyodide.js:236
_loadPackage @ pyodide.js:174
(anonymous) @ pyodide.js:267
Promise.then (async)
loadPackage @ pyodide.js:266
(anonymous) @ (index):30
Promise.then (async)
(anonymous) @ (index):29
pyodide.js:206 Loaded no packages
pyodide.asm.js:8 Python exception:
pyodide.asm.js:8 Traceback (most recent call last):
pyodide.asm.js:8   File "/lib/python3.7/site-packages/pyodide.py", line 43, in eval_code
pyodide.asm.js:8     exec(compile(mod, '<exec>', mode='exec'), ns, ns)
pyodide.asm.js:8   File "<exec>", line 7, in <module>
pyodide.asm.js:8 ModuleNotFoundError: No module named 'micropip'
pyodide.asm.js:8 
pyodide.asm.js:8 Uncaught (in promise) Error: Traceback (most recent call last):
  File "/lib/python3.7/site-packages/pyodide.py", line 43, in eval_code
    exec(compile(mod, '<exec>', mode='exec'), ns, ns)
  File "<exec>", line 7, in <module>
ModuleNotFoundError: No module named 'micropip'

    at _hiwire_throw_error (pyodide.asm.js:8)
    at :8080/wasm-function[358]:1239
    at :8080/wasm-function[385]:265
    at Object.Module.__runPython (pyodide.asm.js:8)
    at Object.Module._runPythonInternal (pyodide.asm.js:8)
    at Object.Module.runPython (pyodide.asm.js:8)
    at (index):32
```

I seems that I can't install `umbral` . How do I install `umbral`? Thanks.

**Comment by rth** [comment]
You should replace,
```
pyodide.loadPackage(['umbral'])
```
by
```
pyodide.loadPackage(['micropip'])
```
I think.

**Comment by Himan000** [comment]
Hi @rth ,
Thank you for replying so soon. Yes, you'r right. But after I correct it, there is other error.

```
Python initialization complete
pyodide.js:146 micropip to be loaded from default channel
pyodide.js:146 distlib to be loaded from default channel
pyodide.js:104 Loading micropip, distlib
pyodide.js:104 Loading micropip from https://pyodide-cdn2.iodide.io/v0.15.0/full/micropip.js
pyodide.js:104 Loading distlib from https://pyodide-cdn2.iodide.io/v0.15.0/full/distlib.js
pyodide.js:206 Loaded micropip, distlib
pyodide.asm.js:8 [Deprecation] Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.
_hiwire_call_member @ pyodide.asm.js:8
(anonymous) @ wasm-03187532-325:45
(anonymous) @ wasm-03187532-14894:8
(anonymous) @ wasm-03187532-841:710
(anonymous) @ wasm-03187532-2755:559
(anonymous) @ wasm-03187532-2750:20424
(anonymous) @ wasm-03187532-20581:6
(anonymous) @ wasm-03187532-839:124
(anonymous) @ wasm-03187532-842:44
(anonymous) @ wasm-03187532-2755:553
(anonymous) @ wasm-03187532-2750:20471
(anonymous) @ wasm-03187532-20581:6
(anonymous) @ wasm-03187532-839:124
(anonymous) @ wasm-03187532-842:44
(anonymous) @ wasm-03187532-2755:553
(anonymous) @ wasm-03187532-2750:20471
(anonymous) @ wasm-03187532-20581:6
(anonymous) @ wasm-03187532-839:124
(anonymous) @ wasm-03187532-842:44
(anonymous) @ wasm-03187532-2755:553
(anonymous) @ wasm-03187532-2750:20416
(anonymous) @ wasm-03187532-20581:6
(anonymous) @ wasm-03187532-2745:2095
(anonymous) @ wasm-03187532-842:118
(anonymous) @ wasm-03187532-2755:553
(anonymous) @ wasm-03187532-2750:20521
(anonymous) @ wasm-03187532-20581:6
(anonymous) @ wasm-03187532-2745:2095
(anonymous) @ wasm-03187532-835:215
(anonymous) @ wasm-03187532-846:25
(anonymous) @ wasm-03187532-356:42
Module.__pyproxy_apply @ pyodide.asm.js:8
apply @ pyodide.asm.js:8
newCall @ pyodide.asm.js:8
_hiwire_new @ pyodide.asm.js:8
(anonymous) @ wasm-03187532-321:43
(anonymous) @ wasm-03187532-14890:8
(anonymous) @ wasm-03187532-843:515
(anonymous) @ wasm-03187532-844:22
(anonymous) @ wasm-03187532-2755:400
(anonymous) @ wasm-03187532-2750:20424
(anonymous) @ wasm-03187532-20581:6
(anonymous) @ wasm-03187532-2745:2095
(anonymous) @ wasm-03187532-842:118
(anonymous) @ wasm-03187532-2755:553
(anonymous) @ wasm-03187532-2750:20424
(anonymous) @ wasm-03187532-20581:6
(anonymous) @ wasm-03187532-2745:2095
(anonymous) @ wasm-03187532-2744:17
(anonymous) @ wasm-03187532-2691:313
(anonymous) @ wasm-03187532-15964:8
(anonymous) @ wasm-03187532-843:343
(anonymous) @ wasm-03187532-844:22
(anonymous) @ wasm-03187532-2755:400
(anonymous) @ wasm-03187532-2750:20471
(anonymous) @ wasm-03187532-20581:6
(anonymous) @ wasm-03187532-839:124
(anonymous) @ wasm-03187532-835:51
(anonymous) @ wasm-03187532-834:22
(anonymous) @ wasm-03187532-860:235
(anonymous) @ wasm-03187532-862:14
(anonymous) @ wasm-03187532-385:38
Module.__runPython @ pyodide.asm.js:8
Module._runPythonInternal @ pyodide.asm.js:8
Module.runPython @ pyodide.asm.js:8
(anonymous) @ (index):32
Promise.then (async)
(anonymous) @ (index):31
Show 36 more frames
pyodide.js:146 setuptools to be loaded from default channel
pyodide.js:146 pyparsing to be loaded from default channel
pyodide.js:104 Loading setuptools, pyparsing
pyodide.js:104 Loading setuptools from https://pyodide-cdn2.iodide.io/v0.15.0/full/setuptools.js
pyodide.js:104 Loading pyparsing from https://pyodide-cdn2.iodide.io/v0.15.0/full/pyparsing.js
(index):1 Uncaught (in promise) Couldn't find a pure Python 3 wheel for 'cryptography >= 2.3'
Promise.then (async)
_hiwire_call_member @ pyodide.asm.js:8
(anonymous) @ wasm-03187532-325:45
(anonymous) @ wasm-03187532-14894:8
(anonymous) @ wasm-03187532-841:710
(anonymous) @ wasm-03187532-2755:559
(anonymous) @ wasm-03187532-2750:20424
(anonymous) @ wasm-03187532-20581:6
(anonymous) @ wasm-03187532-2745:2095
(anonymous) @ wasm-03187532-2744:17
(anonymous) @ wasm-03187532-2691:313
(anonymous) @ wasm-03187532-15964:8
(anonymous) @ wasm-03187532-843:343
(anonymous) @ wasm-03187532-844:22
(anonymous) @ wasm-03187532-2755:400
(anonymous) @ wasm-03187532-2750:20471
(anonymous) @ wasm-03187532-20581:6
(anonymous) @ wasm-03187532-839:124
(anonymous) @ wasm-03187532-835:51
(anonymous) @ wasm-03187532-834:22
(anonymous) @ wasm-03187532-860:235
(anonymous) @ wasm-03187532-862:14
(anonymous) @ wasm-03187532-385:38
Module.__runPython @ pyodide.asm.js:8
Module._runPythonInternal @ pyodide.asm.js:8
Module.runPython @ pyodide.asm.js:8
(anonymous) @ (index):32
Promise.then (async)
(anonymous) @ (index):31
pyodide.js:206 Loaded setuptools, pyparsing
```

**Comment by Himan000** [comment]
Uncaught (in promise) Couldn't find a pure Python 3 wheel for 'cryptography >= 2.3'

**Comment by rth** [comment]
Yes, looks like `cryptography` is a dependency and we would need to build it in pyodide as it uses C-extensions. Would you be interested in making a PR ? https://pyodide.readthedocs.io/en/latest/new_packages.html#mkpkg

**Comment by Himan000** [comment]
Do you mean `cryptography` doesn't work in pyodide? If so, how to solve it?

**Comment by Himan000** [comment]
Sorry I don't know how to make a PR despite I readed your link https://pyodide.readthedocs.io/en/latest/new_packages.html#mkpkg.

**Comment by rth** [comment]
Generally to make a package one would add a folder e.g. `cryptography` with `meta.yaml` to https://github.com/iodide-project/pyodide/tree/master/packages (see how it's done for other packages there)

> Do you mean cryptography doesn't work in pyodide? If so, how to solve it?

We could try to build it and see what happens but I don't think that it would work, because a
 - we don't actually have the openssl dynamic library in the wasm environment which we could open with CFFI as done in `cryptography` as far as I understand. [Creating DLLs should be possible](https://github.com/emscripten-core/emscripten/wiki/Linking) but my attempts to do so, at least for BLAS https://github.com/iodide-project/pyodide/issues/240 were not very successful.
 - ctypes (and I imagine CFFI) currently don't work. At least the corresponding tests are marked as a known failure in CPython. I have not investigated in detail what is the blocker there (or if it might be possible to make it work eventually).

**Comment by Himan000** [comment]
OK,I understand.It seems a big issue,looking forward to your good news.Thanks.

**Comment by agriyakhetarpal** [comment]
Hi @Himan000, `cryptography` has been available with Pyodide for quite a few releases by now. Could you check if this request is still relevant? I noticed that `umbral` is a pure Python package, so you should be able to use it in Pyodide by now without having to add a recipe for it. I'll close this issue for now; please don't hesitate to let us know in case you face more problems with Pyodide or with `umbral` in specific! :)

**Comment by agriyakhetarpal** [comment]
Hi @Himan000, `cryptography` has been available with Pyodide for quite a few releases by now. Could you check if this request is still relevant? I noticed that `umbral` is a pure Python package, so you should be able to use it in Pyodide by now without having to add a recipe for it. I'll close this issue for now; please don't hesitate to let us know in case you face more problems with Pyodide, or with `umbral` in particular! :)
