### ISSUE TITLE
statsmodules and scikit-learn cause a 'Could not load dynamic lib' error when importing numpy

### ISSUE THREAD

**Issue by IOThomas** [pyodide/pyodide#752]
Hi,

I'm using Google Chrome version 84.04147.135.  If I load the pyodide packages `statsmodules` and/or `scikit-learn` using `pyodide.loadPackage`, which means that `numpy` is loaded automatically as a dependency, and then run a python script containing `import numpy as np`, I get the following error in my console (and naturally, if the python script wants to do anything else, it can't):

```Python exception:
pyodide.asm.js:8 Traceback (most recent call last):
pyodide.asm.js:8   File "/lib/python3.7/site-packages/numpy/core/__init__.py", line 16, in <module>
pyodide.asm.js:8     from . import multiarray
pyodide.asm.js:8 ImportError: Could not load dynamic lib: /lib/python3.7/site-packages/numpy/core/multiarray.so
pyodide.asm.js:8 RangeError: WebAssembly.Compile is disallowed on the main thread, if the buffer size is larger than 4KB. Use WebAssembly.compile, or compile on a worker thread.
pyodide.asm.js:8 
pyodide.asm.js:8 During handling of the above exception, another exception occurred:
pyodide.asm.js:8 
pyodide.asm.js:8 Traceback (most recent call last):
pyodide.asm.js:8   File "/lib/python3.7/site-packages/pyodide.py", line 43, in eval_code
pyodide.asm.js:8     exec(compile(mod, '<exec>', mode='exec'), ns, ns)
pyodide.asm.js:8   File "<exec>", line 6, in <module>
pyodide.asm.js:8   File "/lib/python3.7/site-packages/numpy/__init__.py", line 142, in <module>
pyodide.asm.js:8     from . import add_newdocs
pyodide.asm.js:8   File "/lib/python3.7/site-packages/numpy/add_newdocs.py", line 13, in <module>
pyodide.asm.js:8     from numpy.lib import add_newdoc
pyodide.asm.js:8   File "/lib/python3.7/site-packages/numpy/lib/__init__.py", line 8, in <module>
pyodide.asm.js:8     from .type_check import *
pyodide.asm.js:8   File "/lib/python3.7/site-packages/numpy/lib/type_check.py", line 11, in <module>
pyodide.asm.js:8     import numpy.core.numeric as _nx
pyodide.asm.js:8   File "/lib/python3.7/site-packages/numpy/core/__init__.py", line 26, in <module>
pyodide.asm.js:8     raise ImportError(msg)
pyodide.asm.js:8 ImportError: 
pyodide.asm.js:8 Importing the multiarray numpy extension module failed.  Most
pyodide.asm.js:8 likely you are trying to import a failed build of numpy.
pyodide.asm.js:8 If you're working with a numpy git repo, try `git clean -xdf` (removes all
pyodide.asm.js:8 files not under version control).  Otherwise reinstall numpy.
pyodide.asm.js:8 
pyodide.asm.js:8 Original error was: Could not load dynamic lib: /lib/python3.7/site-packages/numpy/core/multiarray.so
pyodide.asm.js:8 RangeError: WebAssembly.Compile is disallowed on the main thread, if the buffer size is larger than 4KB. Use WebAssembly.compile, or compile on a worker thread.
```

Note that if I do the same with `pandas` or `numpy` on their own, there's no such problem.  If this isn't me making a daft mistake I guess this might be worth looking into, as it does seem to limit the utility of these packages a little!

**Comment by rth** [comment]
There have been a lot of changes on the `main` branch since. For scikit-learn this would work. For statsmodules, there is still an issue due to #537
