### ISSUE TITLE
Failed to import skimage in a web-worker

### ISSUE THREAD

**Issue by oeway** [pyodide/pyodide#917]
After closing https://github.com/iodide-project/pyodide/issues/253 with https://github.com/iodide-project/pyodide/pull/866, we should be able to use scikit-image, however, when I try to import it (from cdn.jsdelivr.net/pyodide/dev/full/) it fails. 

Specifically, I can use micropip to install the pacakge:
```
Loaded pytest, setuptools, pyparsing, py, pluggy, more-itertools, attrs, atomicwrites, scikit-image, pywavelets, scipy, numpy, matplotlib, pytz, python-dateutil, pillow, kiwisolver, cycler, networkx, decorator
```
But importing the module in Python results the following error:
```bash
pyodide.asm.js:8 Uncaught (in promise) Error: Traceback (most recent call last):
  File "<exec>", line 5, in try_import_skimage
  File "/lib/python3.8/site-packages/skimage/__init__.py", line 127, in <module>
    from .util.dtype import (img_as_float32,
  File "/lib/python3.8/site-packages/skimage/util/__init__.py", line 1, in <module>
    from .dtype import (img_as_float32, img_as_float64, img_as_float,
  File "/lib/python3.8/site-packages/skimage/util/dtype.py", line 1, in <module>
    import numpy as np
  File "/lib/python3.8/site-packages/numpy/__init__.py", line 142, in <module>
    from . import add_newdocs
  File "/lib/python3.8/site-packages/numpy/add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "/lib/python3.8/site-packages/numpy/lib/__init__.py", line 8, in <module>
    from .type_check import *
  File "/lib/python3.8/site-packages/numpy/lib/type_check.py", line 11, in <module>
    import numpy.core.numeric as _nx
  File "/lib/python3.8/site-packages/numpy/core/__init__.py", line 103, in <module>
    from numpy.testing._private.pytesttester import PytestTester
  File "/lib/python3.8/site-packages/numpy/testing/__init__.py", line 10, in <module>
    from unittest import TestCase
  File "/lib/python3.8/unittest/__init__.py", line 60, in <module>
    from .async_case import IsolatedAsyncioTestCase
  File "/lib/python3.8/unittest/async_case.py", line 1, in <module>
    import asyncio
  File "/lib/python3.8/asyncio/__init__.py", line 8, in <module>
    from .base_events import *
  File "/lib/python3.8/asyncio/base_events.py", line 39, in <module>
    from . import coroutines
  File "/lib/python3.8/asyncio/coroutines.py", line 5, in <module>
    import inspect
  File "/lib/python3.8/inspect.py", line 35, in <module>
    import dis
RecursionError: maximum recursion depth exceeded during compilation

    at _hiwire_throw_error (pyodide.asm.js:8)
    at _pythonexc2js (cdn.jsdelivr.net/pyodide/dev/full/pyodide.asm.wasm:wasm-function[372]:0x1078d8)
    at __pyproxy_apply (cdn.jsdelivr.net/pyodide/dev/full/pyodide.asm.wasm:wasm-function[370]:0x1075d1)
    at Module.__pyproxy_apply (pyodide.asm.js:8)
    at Object.apply (pyodide.asm.js:8)
```

I am running this in a webworker:
```js
self.languagePluginUrl = "https://cdn.jsdelivr.net/pyodide/dev/full/";
importScripts("https://cdn.jsdelivr.net/pyodide/dev/full/pyodide.js");

const startupScript = `
import micropip

def try_import_skimage(_):
    import skimage

micropip.install(["imjoy-rpc>=0.2.59", "scikit-image"]).then(try_import_skimage)
`;

languagePluginLoader.then(() => {
  self.pyodide.loadPackage(["micropip"]).then(async () => {
    self.pyodide.runPython(startupScript);
  });
});
```

@rth @nopid Could you please take a look?

**Comment by rth** [comment]
Did it happen in Chrome? If so it's possibly related to https://github.com/iodide-project/pyodide/issues/821 Could you try with Firefox?

Does it also happen outside of a web-worker? I'm not sure if webworkers have access to a smaller stack size than the main thread in browsers.. Otherwise could you try setting `sys.setrecursionlimit` to a larger value than the current `sys.getrecursionlimit()` ?

**Comment by oeway** [comment]
I just tried both Chrome and Firefox, inside and outside web-worker, got the same error.

Maybe due to the new merged PRs,  the error has been changed to the follow two errors:
```
Uncaught abort(Assertion failed: undefined). Build with -s ASSERTIONS=1 for more info. pyodide.asm.js:8:3328193
    abort https://cdn.jsdelivr.net/pyodide/dev/full/pyodide.asm.js:8
    assert https://cdn.jsdelivr.net/pyodide/dev/full/pyodide.asm.js:8
    loadPackage https://cdn.jsdelivr.net/pyodide/dev/full/pyodide.asm.js:8
    processPackageData https://cdn.jsdelivr.net/pyodide/dev/full/scipy.js:1
    loadPackage https://cdn.jsdelivr.net/pyodide/dev/full/scipy.js:1
    onload https://cdn.jsdelivr.net/pyodide/dev/full/scipy.js:1
    (Async: EventHandlerNonNull)
    fetchRemotePackage https://cdn.jsdelivr.net/pyodide/dev/full/scipy.js:1
    loadPackage https://cdn.jsdelivr.net/pyodide/dev/full/scipy.js:1
    <anonymous> https://cdn.jsdelivr.net/pyodide/dev/full/scipy.js:1
    <anonymous> https://cdn.jsdelivr.net/pyodide/dev/full/scipy.js:1
```
```
Uncaught (in promise) Script error.
  | Promise.then (async) |   |  
-- | -- | -- | --
  | _hiwire_call_member | @ | pyodide.asm.js:8
  | _JsBoundMethod_Call | @ | pyodide.asm.wasm:0x106eb1
  | (anonymous) | @ | pyodide.asm.wasm:0x99229b
  | __PyObject_MakeTpCall | @ | pyodide.asm.wasm:0x12efdf
  | _call_function | @ | pyodide.asm.wasm:0x24ffb2
  | __PyEval_EvalFrameDefault | @ | pyodide.asm.wasm:0x24b3d7
  | (anonymous) | @ | pyodide.asm.wasm:0x9a652e
  | __PyEval_EvalCodeWithName | @ | pyodide.asm.wasm:0x244297
  | __PyFunction_Vectorcall | @ | pyodide.asm.wasm:0x12fd66
  | (anonymous) | @ | pyodide.asm.wasm:0x9a3911
  | _method_vectorcall | @ | pyodide.asm.wasm:0x13352a
  | (anonymous) | @ | pyodide.asm.wasm:0x9a3ae9
  | _call_function | @ | pyodide.asm.wasm:0x24ff93
  | __PyEval_EvalFrameDefault | @ | pyodide.asm.wasm:0x24b488
  | (anonymous) | @ | pyodide.asm.wasm:0x9a652e
  | __PyEval_EvalCodeWithName | @ | pyodide.asm.wasm:0x244297
  | __PyFunction_Vectorcall | @ | pyodide.asm.wasm:0x12fd66
  | (anonymous) | @ | pyodide.asm.wasm:0x9a3911
  | _PyVectorcall_Call | @ | pyodide.asm.wasm:0x12f3dc
  | _PyObject_Call | @ | pyodide.asm.wasm:0x12f4a4
  | __pyproxy_apply | @ | pyodide.asm.wasm:0x107606
  | Module.__pyproxy_apply | @ | pyodide.asm.js:8
  | apply | @ | pyodide.asm.js:8
  | newCall | @ | pyodide.asm.js:8
  | _hiwire_new | @ | pyodide.asm.js:8
  | _JsProxy_New | @ | pyodide.asm.wasm:0x106cfd
  | (anonymous) | @ | pyodide.asm.wasm:0x99226c
  | _cfunction_call_varargs | @ | pyodide.asm.wasm:0x12f757
  | _PyCFunction_Call | @ | pyodide.asm.wasm:0x130bb2
  | (anonymous) | @ | pyodide.asm.wasm:0x9943e8
  | Promise.then (async) |   |  
  | eval | @ | VM13:17
  | Promise.then (async) |   |  
  | eval | @ | VM13:16
  | execute | @ | plugin.webworker.js:117
  | (anonymous) | @ | rpc.js:180
  | _fire | @ | utils.js:187
  | (anonymous) | @ | plugin.webworker.js:33
  | Show 30 more frames
```

**Comment by nopid** [comment]
With Firefox inside a pyodide console pointing to `cdn.jsdelivr.net/pyodide/dev/full/`, the packages load without trouble:
```
>>> import micropip
>>> micropip.install(["imjoy-rpc>=0.2.59", "scikit-image"])
Installed scikit-image, numpy, pytest, werkzeug, imjoy-rpc
>>> import skimage
>>> 
>>> dir(skimage)
_INPLACE_MSG,_STANDARD_MSG,__SKIMAGE_SETUP__,__builtins__,__cached__,__doc__,__file__,__loader__,__name__,__package__,__path__,__spec__,__version__,_raise_build_error,_shared,color,data,data_dir,dr
aw,dtype_limits,ensure_python_version,exposure,external,filters,img_as_bool,img_as_float,img_as_float32,img_as_float64,img_as_int,img_as_ubyte,img_as_uint,io,lookfor,measure,restoration,transform,u
til
>>> import imjoy_rpc
>>> dir(imjoy_rpc)
ApiWrapper,ContextLocal,Local,LocalProxy,__all__,__builtins__,__cached__,__doc__,__file__,__loader__,__name__,__package__,__path__,__spec__,_rpc_context,api,default_config,dotdict,logger,logging,os
,register_default_codecs,setup_connection,sys,type_of_script,utils
```

**Comment by oeway** [comment]
I just noticed that the error only occured when I first enable a custom asyncio loop then import skimage, see here: https://github.com/iodide-project/pyodide/issues/821#issuecomment-750310984

**Comment by oeway** [comment]
Found a workaround to this issue:
```python
import sys
import js

sys.setrecursionlimit(1500)

js.eval("""
try{
    pyodide.runPython(`import skimage`);
} catch(e) {
    if(e instanceof RangeError){
        console.log('Trying again due to recursion error...')
        pyodide.runPython(`import skimage`);
    }
    else{
        throw e
    }
}
""")
```
Note: I had to go back to js because that's the only way I can capture the recursion error, also see: https://github.com/iodide-project/pyodide/issues/951

**Comment by hoodmane** [comment]
> `sys.setrecursionlimit(1500)`

^^ Probably a really bad idea, recursion limit shouldn't be set above 400 in firefox nor above ~140 in chrome. If you need more recursion for some reason, then this is a blocking issue unless the browsers are changed... =(

**Comment by oeway** [comment]
Hi @hoodmane Thanks for the explanation, do you have any suggestion in resolving this issue? Apparently, importing skimage somehow hit the the recursion limit. It might not even related to skimage, I suspect that it just because it has a deep dependency tree during importing.

Do you have any idea on why the `import` statement would do recursion? Is it related to the use of `eval` somewhere for importing? The following error seems complaining the line with `eval`:
```js
>>> import js
>>> js.eval('try{pyodide.runPython("def f(): return 1 + f()\\nf()")}catch(e){console.error("error!")}')
>>> js.pyodide.runPython('import random')
Error: Traceback (most recent call last):
  File "/lib/python3.8/site-packages/pyodide/_base.py", line 70, in eval_code
    eval(compile(mod, "<exec>", mode="exec"), ns, ns)
  File "<exec>", line 1, in <module>
RecursionError: maximum recursion depth exceeded during compilation
```

**Comment by hoodmane** [comment]
> do you have any suggestion in resolving this issue?

I will spend some time thinking about it, though I'll probably have to checkout your branch and actually test it to learn about this specific case. As I said above, I think that it is more likely than not that this has to be fixed by changing the browser.

> `js.eval('try{pyodide.runPython("def f(): return 1 + f()\\nf()")}catch(e){console.error("error!")}')`

I assume that triggers a `RangeError`. As I said before, anything that happens after this range error is [undefined behavior](https://en.wikipedia.org/wiki/Undefined_behavior). You cannot assume that it will work the same from browser to browser, from computer to computer, from test to retest. I cannot replicate the `maximum recursion depth exceeded during compilation` error you gave above, for me `import random` works fine and everything seems superficially okay. But:
```python
>>> import sys
>>> sys.setrecursionlimit(5)
RecursionError: cannot set the recursion limit to 5 at the recursion depth 421: the limit is too low
```
It should say "cannot set the recursion limit to 5 at the recursion depth 8". So there are hundreds of orphaned stack frames which will never be cleaned up.

Anyways the fix for this `maximum recursion depth exceeded during compilation` is to catch the `RangeError` and raise a fatal error, then throw an exception on further calls to `pyodide.runPython()` saying that the pyodide runtime died. Then you wouldn't be able to find out what inconsistent and strange stuff happens after the fatal error.

**Comment by oeway** [comment]
>  I cannot replicate the maximum recursion depth exceeded during compilation error you gave above, for me import random works fine and everything seems superficially okay. 

Try the following code at https://pyodide-cdn2.iodide.io/v0.16.1/full/console.html

```py
Welcome to the Pyodide terminal emulator 🐍
>>> import js
>>> js.eval('try{pyodide.runPython("def f(): return 1 + f()\\nf()")}catch(e){console.error("error!")}')
>>> import micropip
Error: Traceback (most recent call last):
  File "<frozen importlib._bootstrap_external>", line 1281, in _path_importer_cache
KeyError: '/lib/python3.8/json'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/lib/python3.8/site-packages/pyodide/_base.py", line 70, in eval_code
    eval(compile(mod, "<exec>", mode="exec"), ns, ns)
  File "<exec>", line 1, in <module>
  File "/lib/python3.8/site-packages/micropip.py", line 21, in <module>
    import json
  File "/lib/python3.8/json/__init__.py", line 106, in <module>
    from .decoder import JSONDecoder, JSONDecodeError
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 914, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1342, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1311, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1283, in _path_importer_cache
  File "<frozen importlib._bootstrap_external>", line 1259, in _path_hooks
  File "<frozen zipimport>", line 64, in __init__
RecursionError: maximum recursion depth exceeded while calling a Python object
>>> js.pyodide.runPython('123')
123
>>> import numpy
Error: Traceback (most recent call last):
  File "/lib/python3.8/site-packages/pyodide/_base.py", line 70, in eval_code
    eval(compile(mod, "<exec>", mode="exec"), ns, ns)
  File "<exec>", line 1, in <module>
  File "/lib/python3.8/site-packages/numpy/__init__.py", line 142, in <module>
    from . import add_newdocs
  File "/lib/python3.8/site-packages/numpy/add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
RecursionError: maximum recursion depth exceeded during compilation
```
Indeed, it shows "undefined behavior" after hitting the `RangeError`.


However, if you restart the console and try the code below, simply by not running `import micropip` after hitting the `RangeError` everything seems to be ok (I guess this is why my workaround for scikit-image above works):
```
Welcome to the Pyodide terminal emulator 🐍
>>> import js
>>> js.eval('try{pyodide.runPython("def f(): return 1 + f()\\nf()")}catch(e){console.error("error!")}')
>>> js.pyodide.runPython('123')
123
>>> import numpy
>>> numpy.zeros(10)+10
10,10,10,10,10,10,10,10,10,10
>>> js.pyodide.runPython('import random')
>>> import micropip
>>>
```

**Comment by hoodmane** [comment]
> everything seems to be ok

That's what I'm saying, it **SEEMS** okay, but it is **NOT** okay. It may work on your computer and break on my computer. The behavior may completely change any time your browser updates. It's behavior will depend on exactly what python and js code you've executed beforehand in completely incomprehensible ways.

**Comment by oeway** [comment]
Yes, you are right, I cannot even reproduce it if I try it again.

**Comment by oeway** [comment]
If you want to reproduce the issue, try the following script in a web-worker (it seems ok for a normal window):
```js
self.languagePluginUrl = "https://cdn.jsdelivr.net/pyodide/v0.16.1/full/";
importScripts("https://cdn.jsdelivr.net/pyodide/v0.16.1/full/pyodide.js");
const startupScript = `
import micropip

def try_import_skimage(_):
    import skimage
    print('=====skimage imported=====')

micropip.install(["scikit-image"]).then(try_import_skimage)
`;

languagePluginLoader.then(() => {
  self.pyodide.loadPackage(["micropip"]).then(async () => {
    self.pyodide.runPython(startupScript);
  });
});
```

And you should see the recursion error in the console.

**Comment by hoodmane** [comment]
I went to https://pyodide-cdn2.iodide.io/v0.16.1/full/console.html and typed into the browser console:
```javascript
await languagePluginLoader;
await pyodide.runPythonAsync("import micropip\nimport skimage"); 
pyodide.runPython("skimage.__version__)
```
Returns `0.15.0`, no errors.

**Comment by hoodmane** [comment]
My browser logs from the sessions:
[firefox-import-skimage.log](https://github.com/iodide-project/pyodide/files/5742645/firefox-import-skimage.log)
[chrome-import-skimage.log](https://github.com/iodide-project/pyodide/files/5742646/chrome-import-skimage.log)

**Comment by oeway** [comment]
Works for me as well if I run it in the web page, could you try it in a web worker? See my comment above.

**Comment by hoodmane** [comment]
Apologies for my poor reading comprehension.

**Comment by oeway** [comment]
I think this issue might be similar or the same as https://github.com/iodide-project/pyodide/issues/373

**Comment by oeway** [comment]
@hoodmane  @rth I made a jsfiddle to reproduce this issue: https://jsfiddle.net/wrjom5h9/4/ you should be able to see an error in the browser console for both Chrome and Firefox. Please take a look when you get a chance.

**Comment by hoodmane** [comment]
@oeway I don't get a recursion error in firefox.
[firefox-import-skimage-webworker.log](https://github.com/iodide-project/pyodide/files/5752653/firefox-import-skimage-webworker.log)

**Comment by hoodmane** [comment]
On Chrome I get a bunch of network errors like:
```
scikit-image.js:1 Uncaught Error: NetworkError for: https://cdn.jsdelivr.net/pyodide/v0.16.1/full/scikit-image.data
    at XMLHttpRequest.xhr.onerror (scikit-image.js:1)
```

**Comment by oeway** [comment]
Hi @hoodmane Thanks for looking into this!

I just tried a few times again in FireFox (84.0.1, 64-bit on MacOS 10.14.6) and I see the same output as you have for twice, if I refresh the page, sometimes I got the recursion error: [console-export-2020-12-30_2-52-58.txt](https://github.com/iodide-project/pyodide/files/5752733/console-export-2020-12-30_2-52-58.txt), so maybe you just need to refresh the page.

It's wired that you get network error in chrome, could you also try to refresh the page?  here is the log I got: [jsfiddle.net-1609292948492.log](https://github.com/iodide-project/pyodide/files/5752734/jsfiddle.net-1609292948492.log).

**Comment by oeway** [comment]
BTW, how do you debug this type of error? I can see the stack trace, but I have no idea about the wasm error. It would be great to see a bit more code in C, or ideally in Python, just came across this: https://developers.google.com/web/updates/2020/12/webassembly

**Comment by hoodmane** [comment]
Thanks for the link! The main way I debug things is by using `console.log`, `printf`, etc. Put lots of these into the code and then you can narrow down what code paths are getting executed and where the error occurred. Once you've located the region where the error happens, you can start printing out program state.

I will try again.

**Comment by hoodmane** [comment]
I can tell you what the stuff in that stack trace is, but it's not very helpful.
```
__PyObject_CallMethodIdObjArgs // This is calling "pyodide.eval_code"
_object_vacall  // A python internal: "variable arguments call"
(anonymous) 
__PyFunction_Vectorcall // this is the new python fast dispatch method added in 3.8
_function_code_fastcall 
_PyEval_EvalFrameEx // This is a hook for JITs that gets called by eval every frame.
(anonymous) 
__PyEval_EvalFrameDefault // This is the ordinary non-git value for the FrameEx hook.
_call_function // This is calling eval (_base.py line 88)
(anonymous)  
_cfunction_vectorcall_FASTCALL 
(anonymous) 
_builtin_eval // finally got to eval's body
_PyEval_EvalCode 
__PyEval_EvalCodeWithName 
(anonymous) 
__PyEval_EvalFrameDefault // Okay now we finally made it to executing the evaled code. Apparently eval skips the JIT hook.
_call_function 
__PyObject_MakeTpCall  // Someone called a callable object
(anonymous) 
_JsBoundMethod_Call // that callable object was a `JsBoundMethod`. Now it's in our pyodide code
_hiwire_call_member // hiwire is a transfer layer between C and js, it's going to call the actual js object for us
Promise.then (async) // Okay we were calling Promise.then.
apply // Called `.then` with a pyproxy, so we're heading back into pyodide
Module.__pyproxy_apply // Call a py proxy, the js wrapper
__pyproxy_apply // Call a py proxy the C code
_pythonexc2js // `PyObject_Call` raised an error, now pyodide is formatting the error method. 
_hiwire_throw_error // tell javascript to throw an error.

```
So the error was raised in [`PyProxy_Call`](https://github.com/iodide-project/pyodide/blob/3b534c3f85ea207ee63e6e43b41c7b0884750e1e/src/type_conversion/pyproxy.c#L108), reported back to us three lines down on line 111.

**Comment by hoodmane** [comment]
Note that the useful part of the stack trace would be the part inside of `PyObject_Call`, but that's unfortunately missing.

**Comment by oeway** [comment]
> I can tell you what the stuff in that stack trace is, but it's not very helpful.

Thanks a lot for the explanation and tips for debugging!

**Comment by hoodmane** [comment]
Another useful tip: using `console.error("some message", an_object)` gives a stack trace but doesn't throw an error. This is very helpful.

**Comment by nopid** [comment]
Ran the [jsfiddle exemple](https://jsfiddle.net/ye05v4ok/) serveral times in Firefox 84.0.1 on macOS, displaying `sys.getrecursionlimit()` value. The value varies from run to run, always quite low (as we know):
 - 287 is enough for the import
 - 189 is enough for the import
 -  133 get you recursionerror
 
I understand that recursionlimit is lower is pyodide than in classical Python (typically 1000), but why does it vary on browser reload?

**Comment by hoodmane** [comment]
`why does it vary on browser reload?`

I think it has to do with `setRecursionLimit` in `pyodide.js`. `setRecursionLimit` is measuring the amount of stuff on the browser stack, which is quite variable and depends on things beyond our control. The browser is likely adjusting how many resources a new tab gets based on system resource availability / behavior of other tabs. 

To check this, add a `console.log("Available stack depth:", depth)` or something here: https://github.com/iodide-project/pyodide/blob/860974b64683f622cc8916c9a48ac240a7117444/src/pyodide.js#L290

**Comment by hoodmane** [comment]
The wasm browser VM is still an immature technology and the unfortunate state of things is that packages like `skimage` and `jedi` cannot work correctly without changes to the browsers.

**Comment by nopid** [comment]
Thanks @hoodmane for the explanations. Classical terminal Python cannot import `skimage` with recursion limit of 100. In the browser with pyodide, Firefox gives me a recursion limit of 400 inside the console (more than enough to load `skimage` or `matplotlib`). Inside the web-worker example, when the limit gets too low it blocks importing both `skimage` and `matplotlib`.

How precise is the heuristic of dividing by 50? Maybe this can be improved? https://github.com/iodide-project/pyodide/blob/860974b64683f622cc8916c9a48ac240a7117444/src/pyodide.js#L291

**Comment by hoodmane** [comment]
Unfortunately I think dividing by 50 isn't conservative enough. The right thing is more like dividing by 70 or 80.

One issue here is that the browser javascript VM is throwing a `RangeError` when it runs out of stack space which it is actually measuring, but Python does not measure stack space used, it only counts call frames. Some call frames are much bigger than others.

**Comment by hoodmane** [comment]
Recursion errors seem mysteriously improved in v0.17.0, see #821.
